### ISSUE TITLE
关于docker时区问题

### ISSUE THREAD

**Issue by vay1314** [EvineDeng/jd-base#1]
## 但因为Github Action定时任务采用的是UTC时间，比北京时间晚8小时，所以会导致本地任务无法真正地在准确设定的时间运行，需要手动修改crontab

这个不能把容器时区默认设置UTC吗？这样跟随更新后就不用手动设置时间。

**Comment by EvineDeng** [comment]
我本意是为了让人能够更容易理解运行时间的，所以改成北京时间了，不过一年到头也不会有几条新任务的。

**Comment by EvineDeng** [comment]
> ################################## 定义是否自动增加新的本地定时任务 ##################################
> 
> ## lxk0301 大佬会在有需要的时候，增加Github Action定时任务，但如果是本地的定时任务，则不会自动增加
> ## 如需要自动增加新的本地定时任务，则设置为 true ，否则请设置为 false
> ## 请注意：如果你设置为 true，本脚本将会自动从 scripts/.github/workflows 文件夹新增加的 .yml 文件中读取 cron 这一行的任务时间
> ## 但因为Github Action定时任务采用的是UTC时间，比北京时间晚8小时，所以会导致本地任务无法真正地在准确设定的时间运行，需要手动修改crontab
> 这个不能把容器时区默认设置UTC吗？这样跟随更新后就不用手动设置时间。

过两天和另外一个大佬的docker糅合一下，顺便加上自定义docker内部的时区的功能，让大家自由选择吧。

**Comment by landcruser** [comment]
大佬威武 ，受教很多

**Comment by EvineDeng** [comment]
> ################################## 定义是否自动增加新的本地定时任务 ##################################
> 
> ## lxk0301 大佬会在有需要的时候，增加Github Action定时任务，但如果是本地的定时任务，则不会自动增加
> ## 如需要自动增加新的本地定时任务，则设置为 true ，否则请设置为 false
> ## 请注意：如果你设置为 true，本脚本将会自动从 scripts/.github/workflows 文件夹新增加的 .yml 文件中读取 cron 这一行的任务时间
> ## 但因为Github Action定时任务采用的是UTC时间，比北京时间晚8小时，所以会导致本地任务无法真正地在准确设定的时间运行，需要手动修改crontab
> 这个不能把容器时区默认设置UTC吗？这样跟随更新后就不用手动设置时间。

现在我觉定暂时不想改了，你如果想用UTC时间的话，在创建容器时增加一个环境变量`TZ=UTC`，就可以实现使用UTC时间了，不过记得里面的crontab的时间也要改成UTC时间：
```
docker run -dit \
  -v /Host主机上的目录/:/root `#冒号左边请替换为Host主机上的目录` \
  -e TZ=UTC \
  --name jd \
  --restart unless-stopped \
  evinedeng/jd-base:latest
```

**Comment by vay1314** [comment]
> > ################################## 定义是否自动增加新的本地定时任务 ##################################
> > ## lxk0301 大佬会在有需要的时候，增加Github Action定时任务，但如果是本地的定时任务，则不会自动增加
> > ## 如需要自动增加新的本地定时任务，则设置为 true ，否则请设置为 false
> > ## 请注意：如果你设置为 true，本脚本将会自动从 scripts/.github/workflows 文件夹新增加的 .yml 文件中读取 cron 这一行的任务时间
> > ## 但因为Github Action定时任务采用的是UTC时间，比北京时间晚8小时，所以会导致本地任务无法真正地在准确设定的时间运行，需要手动修改crontab
> > 这个不能把容器时区默认设置UTC吗？这样跟随更新后就不用手动设置时间。
> 
> 现在我觉定暂时不想改了，你如果想用UTC时间的话，在创建容器时增加一个环境变量`TZ=UTC`，就可以实现使用UTC时间了，不过记得里面的crontab的时间也要改成UTC时间：
> 
> ```
> docker run -dit \
>   -v /Host主机上的目录/:/root `#冒号左边请替换为Host主机上的目录` \
>   -e TZ=UTC \
>   --name jd \
>   --restart unless-stopped \
>   evinedeng/jd-base:latest
> ```

我是这样修改的，但这样之后自动更新js脚本和shell脚本，之前修改的crontab会被覆盖吗

**Comment by EvineDeng** [comment]
> > > ################################## 定义是否自动增加新的本地定时任务 ##################################
> > > ## lxk0301 大佬会在有需要的时候，增加Github Action定时任务，但如果是本地的定时任务，则不会自动增加
> > > ## 如需要自动增加新的本地定时任务，则设置为 true ，否则请设置为 false
> > > ## 请注意：如果你设置为 true，本脚本将会自动从 scripts/.github/workflows 文件夹新增加的 .yml 文件中读取 cron 这一行的任务时间
> > > ## 但因为Github Action定时任务采用的是UTC时间，比北京时间晚8小时，所以会导致本地任务无法真正地在准确设定的时间运行，需要手动修改crontab
> > > 这个不能把容器时区默认设置UTC吗？这样跟随更新后就不用手动设置时间。
> > 
> > 现在我觉定暂时不想改了，你如果想用UTC时间的话，在创建容器时增加一个环境变量`TZ=UTC`，就可以实现使用UTC时间了，不过记得里面的crontab的时间也要改成UTC时间：
> > 
> > ```
> > docker run -dit \
> >   -v /Host主机上的目录/:/root `#冒号左边请替换为Host主机上的目录` \
> >   -e TZ=UTC \
> >   --name jd \
> >   --restart unless-stopped \
> >   evinedeng/jd-base:latest
> > ```
> 
> 我是这样修改的，但这样修改后 ，自动更新js脚本和shell脚本时修改的crontab会被覆盖吗？

不会，crontab完全由你自己控制，shell脚本只会增删条目不会修改已有条目。
