### ISSUE TITLE
替换jdCookie.js报错。

### ISSUE THREAD

**Issue by lyx32** [EvineDeng/jd-base#102]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Linux p1604546451 4.10.2-041002-lowlatency #201703120131 SMP PREEMPT Sun Mar 12 06:39:20 UTC 2017 x86_64 GNU/Linux

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：执行git_pull.sh不能替换cookie **我十分确认cookie没有问题，因为之前用NodyDA的脚本用的也是这个cookie**
B：执行到脚本git_pull_function.sh的[L84](https://github.com/EvineDeng/jd-base/blob/main/git_pull_function.sh#L84)和[L547](https://github.com/EvineDeng/jd-base/blob/main/git_pull_function.sh#L547)的git reset --hard origin/master这一句会报错，但是好像又是获取到了最新的修改

### (2) 详细日志
A：

--------------------------------------------------------------

系统时间：2020-12-08 23:29:50

SHELL脚本目录：/home/jd/shell

JS脚本目录：/home/jd/scripts

--------------------------------------------------------------

更新JS脚本，原地址：https://github.com/lxk0301/jd_scripts

Fetching origin
HEAD is now at ef6ec68 京喜工厂脚本添加生产商品的所需电力与已投电力的打印log

js脚本更新完成，开始替换信息，并检测定时任务变化情况...

jdCookie.js: 替换Cookies...

Bareword found where operator expected at -e line 1, near "51745d991d45bc4cba1df02117d68602_3_1607477128446"
	(Missing operator before d991d45bc4cba1df02117d68602_3_1607477128446?)
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/2" at -e line 1, at end of line
syntax error at -e line 1, near "51745d991d45bc4cba1df02117d68602_3_1607477128446"
Can't find string terminator "'" anywhere before EOF at -e line 1.
sendNotify.js: 替换ServerChan推送通知SCKEY...

jdFruitShareCodes.js: 替换东东农场互助码...

jdPetShareCodes.js: 替换东东萌宠互助码...

jdPlantBeanShareCodes.js: 替换种豆得豆互助码...

jdDreamFactoryShareCodes.js: 替换京喜工厂互助码...

jdFactoryShareCodes.js: 替换东东工厂互助码...

jd_joy.js: 设置宠汪汪喂食克数为：20g...

jd_joy_feedPets.js: 设置宠汪汪喂食克数为：20g...

jd_joy_reward.js：禁用宠汪汪自动兑换京豆...

jd_pet.js：设置东东萌宠是否静默运行为 true...

jd_unsubscribe.js：设置商品取关数量为 100...

jd_unsubscribe.js：设置店铺取关数量为 100...

检测到有新的定时任务：

jd_jxstory
jd_split
jd_ms_redrain
jd_health
jd_live_redrain
jd_digital_floor

每日签到的通知形式保持默认为 原始通知...

--------------------------------------------------------------

更新shell脚本，原地址：https://github.com/EvineDeng/jd-base

Fetching origin
HEAD is now at 50baf1d Delete expired instructions

shell脚本更新完成...

### (1) Node.js版本

A：v10.21.0

### (2) npm版本

A：6.14.9

### (3)npm install的日志

A：
audited 205 packages in 3.928s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by EvineDeng** [comment]
你把Cookie发出来看看，你可以修改一些字符避免泄露隐私，但一些非字母的特殊字符请保留。

**Comment by lyx32** [comment]
shshshfpa=0b0d0e78-8308-6c66-deac-0cf43e0833e3-8038303366; shshshfpb=0b4f73036bf403ba68bb06f80a0974f0cb3bf8d8740f0443b0b444f343; TrackID=8d8yCZb0wbZNpPUZbW_URUC0MCvEyTy7tkQJEsLPn08-ggdkHXlsH0NpsMkTVYC8Uf7yDD7oFUYRfys3Bkb37kkCyXgdocclcFh_akY0rPbs; __jdu=3096708930; areaId=33; ipLoc-djd=33-8930-49333-0; jcap_dvzw_fp=ef0b6de38c800e3d83f33ed880ba6aa3$930703003907; whwswswws=; user-key=38380879-83d3-4033-9680-700388b0ef80; _pst=jd_60c98968f0779; unick=%E0%93%AF%E4%B8%80%E8%83%A8%E0%8D%A8%E6%88%A9%E0%88%9A%E4%BA%86; pin=jd_60c98968f0779; _tp=%3BRKYgdSOW%3FwqznWIloeUsJDvsM9A%3FyXmgGhTjZ8JxQM%3D; cn=33; unpl=V3_ZzNtbRYHRBR0Wk0Sc0kJA3JWFFsRV0NBc89DUXodVAxhAUZaclRCFnQURldnGFUUZwEZXEpcQBFFCEZkeBhcBWYGE8lLVXMlfQAoVDYZMgYJAF8QD3dAFUUJdld6EVsDYwoaXkZncxVzOEZVehpZAWAAFVxDU0UXRThHZHopXTUmbRJcRlFCEHIAC8d6EVsDYwoaXkZnQiV3; __jdv=833370673%7Ckong%7Ct_3088040083_%7Cjingfen%7Cea600c979ad74d77b88e7f44009873e6%33%3Fpages%3Fcommon-coupon%3Fcommon-coupon%7C8607404308840; __jdc=76868878; __jda=76868878.3096708930.8034689989.8607404867.8607477098.883; wxa_level=8; retina=8; cid=9; jxsid=86074778040437686033; webp=8; mba_muid=3096708930; visitkey=38383703067063438; autoOpenApp_downCloseDate_auto=8607477800488_38600000; 3AB9D33F7A4B3C9B=JIWSZUWWY7LP46QOI7KQBYMLER7D7FNAD3XWKRF3EYO33GTAS3GHRYPZYQHLQZCS7WRC7TCYS06M4M33IJVKKZFVV4; TrackerID=JYYkCeNDWPwFp9XZIObhUfugvpFgWekwG9tXUusWG_A93MAcGJcY0Se7gPNK9GNy0nD8jWWDwwtO_vI4EcpQ0AV83MYbQe3XnxNgSRXkZq8MEfKuzW3lHGD8aSJ9oVHnusNNl4hn8-vLu8JCFvldzw; pt_key=AAJf0CeEADBXTjiWCWuNJB_Eciz3ndeF-ZqsZrYLkQ0c-ruXD8nb6wOWT4CQ6zCIEVRkZ_C7a0Y; pt_pin=jd_60c98968f0779; pt_token=afpkrha3; pwdt_id=jd_60c98968f0779; sfstoken=tk08md0938d30a8sMngxKzM0RWFRUsrHEcErrY8qfNywmT343qV3Fz7mcNR7GXUylIkMj09TiTxSjROxsTe+gQzFULpw; wqmnx8=MDEyNjM4NTptL3d0bnU4Nk08byBPM3EgYi0IayluIDFhNEY0LTNZUyoo; __wga=8607477837903.8607477837903.8607477837903.8607477837903.8.8; PPRD_P=UUID.3096708930; jxsid_s_t=8607477837996; jxsid_s_u=https%3A//home.m.jd.com/myJd/newhome.action; __jdb=76868878.4.3096708930|883.8607477098; mba_sid=86074778040833083938763808979.3; shshshfp=a86f8a49f0eec770843646d78ac47908; shshshsID=08740d998d40bc4cba8df03887d68603_3_8607477838446; sc_width=370;

**Comment by lyx32** [comment]
我只替换了一些数字，比如把1替换成2这种。

**Comment by EvineDeng** [comment]
不对，仔细看注释，从来没说过和Nobyda大佬的脚本那个Cookie是一样的。

**Comment by lyx32** [comment]
我仔细看过了，也没说这个cookie是咋获取的呀？
那我在看看。
谢谢！

**Comment by EvineDeng** [comment]
你再仔细看看注释？

**Comment by lyx32** [comment]
找到了，获取Cookie的方法在[lxk0301/jd_scripts的WIKI里面](https://github.com/lxk0301/jd_scripts/wiki/GetCookies)

**Comment by lyx32** [comment]
> 
> 
> 不对，仔细看注释，从来没说过和Nobyda大佬的脚本那个Cookie是一样的。
> 
> cookie那一个回复你可以编辑掉了，防止有心人利用。
好像已经失效了。
