### ISSUE TITLE
first_run.sh 文件无法下载

### ISSUE THREAD

**Issue by 5axf** [EvineDeng/jd-base#105]
https://raw.githubusercontent.com/EvineDeng/jd-base/main/first_run.sh
这个链接不管翻不翻墙都没办法打开

**Comment by EvineDeng** [comment]
我不翻墙在网页上都能打开，自己想办法解决。

**Comment by EvineDeng** [comment]
自己想办法。

**Comment by 5axf** [comment]
我网络的问题？
