### ISSUE TITLE
博主你好

### ISSUE THREAD

**Issue by jinyusme** [EvineDeng/jd-base#11]
可否加一个自动检查GITHUB上文件更新然后替换的脚本，目前自己写了crontab 删除scripts文件夹然后从新拉，感觉有点傻

**Comment by QCEnjoyLL** [comment]
> 可否加一个自动检查GITHUB上文件更新然后替换的脚本，目前自己写了crontab 删除scripts文件夹然后从新拉，感觉有点傻

crontab.list的第一个定时任务不就是自动更新脚本吗。。。。

**Comment by jinyusme** [comment]
啊。。眼瞎了，不好意思
