### ISSUE TITLE
运行git_pull.sh，替换Cookies 时出错

### ISSUE THREAD

**Issue by tanhao** [EvineDeng/jd-base#110]
运行环境：斐讯N1
系       统：Armbian buster with Linux 5.5.0-rc6-aml-s9xxx
Perl 版本：5.28.1

运行git_pull.sh，只有替换Cookies出错，
错误信息如下：

`
jdCookie.js: 替换Cookies...

Backslash found where operator expected at -e line 1, near "1\"
        (Missing operator before \?)
Unknown regexp modifier "/t" at -e line 1, at end of line
syntax error at -e line 1, near "1\"
Can't find string terminator "'" anywhere before EOF at -e line 1.
sendNotify.js: 替换ServerChan推送通知SCKEY...

jdFruitShareCodes.js: 替换东东农场互助码...

jdPetShareCodes.js: 替换东东萌宠互助码...

jdPlantBeanShareCodes.js: 替换种豆得豆互助码...
`

**Comment by EvineDeng** [comment]
仔细读完Cookie的注释再按模板提问。
