### ISSUE TITLE
配置文件 /config.sh 不存在，请先按教程配置好该文件...

### ISSUE THREAD

**Issue by 68cs** [EvineDeng/jd-base#117]
![Xnip2020-12-19_22-33-54](https://user-images.githubusercontent.com/25496213/102691857-8fa68480-424a-11eb-994f-e94ac1255b46.png)

**Comment by EvineDeng** [comment]
你映射错误，现在我还在调整，建议继续使用v2版脚本，明天起来再重新部署v3

**Comment by hacken156026692** [comment]
检测到有新的定时任务：

jd_health
jd_jdh
jd_ms_redrain
jr_sign

运行npm install...


npm install 运行不成功，自动删除 /data/data/com.termux/files/home/jd/scripts/node_modules...

请进入 /data/data/com.termux/files/home/jd/scripts 目录后手动运行 npm install...

大神，我运行了好几次npm install
但返回jd根目录后bash git_pull.sh，还是不成功

**Comment by EvineDeng** [comment]
> 检测到有新的定时任务：
> 
> jd_health
> jd_jdh
> jd_ms_redrain
> jr_sign
> 
> 运行npm install...
> 
> npm install 运行不成功，自动删除 /data/data/com.termux/files/home/jd/scripts/node_modules...
> 
> 请进入 /data/data/com.termux/files/home/jd/scripts 目录后手动运行 npm install...
> 
> 大神，我运行了好几次npm install
> 但返回jd根目录后bash git_pull.sh，还是不成功

你要按教程做。教程告诉你可以切换为淘宝的npm源。

**Comment by hacken156026692** [comment]
我就是按教程做的啊，V2就是这么做的。

cd /home/myid/jd/scripts
npm install || npm install --registry=https://registry.npm.taobao.org

你有个笔误，多了个myid的目录。

我就是npm install || npm install --registry=https://registry.npm.taobao.org
这样运行了十几次，然后再返回jd目录，不成功。

**Comment by EvineDeng** [comment]
> 我就是按教程做的啊，V2就是这么做的。
> 
> cd /home/myid/jd/scripts
> npm install || npm install --registry=https://registry.npm.taobao.org
> 
> 你有个笔误，多了个myid的目录。
> 
> 我就是npm install || npm install --registry=https://registry.npm.taobao.org
> 这样运行了十几次，然后再返回jd目录，不成功。

你是安卓。。。请看安卓的教程。

**Comment by hacken156026692** [comment]
还有2个问题

1、我运行bash git_pull.sh
显示
~/jd $ bash git_pull.sh
cat: /proc/1/cgroup: No such file or directory

这是什么文件？提示我没有

2、定时里设置，您还有个笔误，这次V3已经没有shell文件夹了，所以cd shell crontab不行了。

**Comment by binge8** [comment]
和楼主遇到同样的问题

**Comment by hacken156026692** [comment]
还发现一个问题，我设置好了nano config.sh，cookie1=啥啥啥，cookie2=啥啥啥，设置好了自动任务，但进log文件夹看，显示的是如下信息

🔔京喜工厂, 开始!
您的cookie选择的是用&隔开


====================共有3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：12/20/2020, 8:20:05 AM=====================

开始获取京喜工厂配置文件

共3个京东账号

您提供了2个账号的京喜工厂助力码

**Comment by EvineDeng** [comment]
> 还发现一个问题，我设置好了nano config.sh，cookie1=啥啥啥，cookie2=啥啥啥，设置好了自动任务，但进log文件夹看，显示的是如下信息
> 
> 🔔京喜工厂, 开始!
> 您的cookie选择的是用&隔开
> 
> ====================共有3个京东账号Cookie=========
> 
> ==================脚本执行- 北京时间(UTC+8)：12/20/2020, 8:20:05 AM=====================
> 
> 开始获取京喜工厂配置文件
> 
> 共3个京东账号
> 
> 您提供了2个账号的京喜工厂助力码

那实际日志显示第3个账号的输出是啥？

**Comment by hacken156026692** [comment]
以jd_jdh的log为例，文件名2020-12-20-08-14-28.log，打开的全文如下
🔔京东健康, 开始!
您的cookie选择的是用&隔开


====================共有3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：12/20/2020, 8:14:31 AM=====================

刚刚发的京喜工厂的全文就是上一个评论里的内容。

**Comment by EvineDeng** [comment]
@68cs @binge8 现在你们重新克隆本仓库重新部署看看还有没有这个错误？

@hacken156026692 你可能是访问不了取互助码的api，然后卡住了，你尝试手动运行一下看看？

**Comment by binge8** [comment]
> @68cs @binge8 现在你们重新克隆本仓库重新部署看看还有没有这个错误？
> 
> @hacken156026692 你可能是访问不了取互助码的api，然后卡住了，你尝试手动运行一下看看？

刚试了，还是一样不行

**Comment by EvineDeng** [comment]
> > @68cs @binge8 现在你们重新克隆本仓库重新部署看看还有没有这个错误？
> > @hacken156026692 你可能是访问不了取互助码的api，然后卡住了，你尝试手动运行一下看看？
> 
> 刚试了，还是一样不行

那应该确实是你们那个环境不行了。。。我自己试了物理机、安卓termux、Docker全部正常。

**Comment by fjqken** [comment]
/home/myid/jd/scripts/jd_bean_sign.js:28
!(async() => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

大佬手动跑报错了

**Comment by EvineDeng** [comment]
> /home/myid/jd/scripts/jd_bean_sign.js:28
> !(async() => {
> ^
> 
> SyntaxError: Unexpected token (
> at createScript (vm.js:56:10)
> at Object.runInThisContext (vm.js:97:10)
> at Module._compile (module.js:549:28)
> at Object.Module._extensions..js (module.js:586:10)
> at Module.load (module.js:494:32)
> at tryModuleLoad (module.js:453:12)
> at Function.Module._load (module.js:445:3)
> at Module.runMain (module.js:611:10)
> at run (bootstrap_node.js:394:7)
> at startup (bootstrap_node.js:160:9)
> 
> 大佬手动跑报错了

估计是WIKI常见问题中的那个错误。

**Comment by hacken156026692** [comment]
我手动也错了。

🔔京东直播, 开始!
(node:29726) UnhandledPromiseRejectionWarning: Error: Cannot find module 'got'
Require stack:
- /data/data/com.termux/files/home/jd/scripts/jd_live.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.initGotEnv (/data/data/com.termux/files/home/jd/scripts/jd_live.js:312:3667)
    at Object.post (/data/data/com.termux/files/home/jd/scripts/jd_live.js:312:5580)
    at /data/data/com.termux/files/home/jd/scripts/jd_live.js:264:7
    at new Promise (<anonymous>)
    at TotalBean (/data/data/com.termux/files/home/jd/scripts/jd_live.js:250:10)
    at /data/data/com.termux/files/home/jd/scripts/jd_live.js:57:13
(node:29726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fjqken** [comment]
> > /home/myid/jd/scripts/jd_bean_sign.js:28
> > !(async() => {
> > ^
> > SyntaxError: Unexpected token (
> > at createScript (vm.js:56:10)
> > at Object.runInThisContext (vm.js:97:10)
> > at Module._compile (module.js:549:28)
> > at Object.Module._extensions..js (module.js:586:10)
> > at Module.load (module.js:494:32)
> > at tryModuleLoad (module.js:453:12)
> > at Function.Module._load (module.js:445:3)
> > at Module.runMain (module.js:611:10)
> > at run (bootstrap_node.js:394:7)
> > at startup (bootstrap_node.js:160:9)
> > 大佬手动跑报错了
> 
> 估计是WIKI常见问题中的那个错误。

感谢大佬，升级node版本解决了

附上命令：sudo npm cache clean -f
sudo n stable

**Comment by EvineDeng** [comment]
> Cannot find module 'got'

Cannot find module 'got'

你有没有注意到你git_pull时也报错npm install不对了。。。自己看教程解决

**Comment by hacken156026692** [comment]
明白，我把文件夹删了重新来一次

**Comment by bsdcpp** [comment]
我也是主机部署（非docker），就是JD_DIR没有定义，直接按docker的路径来也可以的。

**Comment by hacken156026692** [comment]
大神，还是老问题。我nano两个文件编辑好了，运行bash git_pull.sh，始终是如下

jd_health
jd_jdh
jd_live_redrain
jd_ms_redrain
jr_sign

运行 npm install...

npm install 运行不成功，自动删除 /data/data/com.termux/files/home/jd/scripts/node_modules 后再次尝试一遍...

运行 npm install...

npm install 运行不成功，自动删除 /data/data/com.termux/files/home/jd/scripts/node_modules...

请进入 /data/data/com.termux/files/home/jd/scripts 目录后按照wiki教程手动运行 npm install...

然后我进了scripts文件夹后，运行npm install || npm install --registry=https://registry.npm.taobao.org，等了几秒钟后，再反复运行这个npm install || npm install --registry=https://registry.npm.taobao.org命令。但始终没有任何显示。
我再回jd文件夹运行bash git_pull.sh，还是不成功的显示。我真的很认真很仔细看了教程了，请问npm install不成功，有没有啥解决办法？谢谢！

**Comment by EvineDeng** [comment]
> 我也是主机部署（非docker），就是JD_DIR没有定义，直接按docker的路径来也可以的。

主机部署应该不影响，只有docker才有JD_DIR，主机没有的，脚本会识别的。如果报错则请重头部署一下。

**Comment by EvineDeng** [comment]
> npm install --registry=[https://registry.npm.taobao.org](https://registry.npm.taobao.org%EF%BC%8C%E7%AD%89%E4%BA%86%E5%87%A0%E7%A7%92%E9%92%9F%E5%90%8E%EF%BC%8C%E5%86%8D%E5%8F%8D%E5%A4%8D%E8%BF%90%E8%A1%8C%E8%BF%99%E4%B8%AAnpm)

这个原因我也不是很清楚，要不你只运行`npm install --registry=https://registry.npm.taobao.org`看看？

**Comment by bsdcpp** [comment]
> > 我也是主机部署（非docker），就是JD_DIR没有定义，直接按docker的路径来也可以的。
> 
> 主机部署应该不影响，只有docker才有JD_DIR，主机没有的，脚本会识别的。如果报错则请重头部署一下。

我明白了，我也属于docker，我是部署在自己使用的docker上面，不想单独开个docker，所以也会有这个问题。尴尬了，我这不属于主机了，希望开发者可以加个判断。

**Comment by EvineDeng** [comment]
> > > 我也是主机部署（非docker），就是JD_DIR没有定义，直接按docker的路径来也可以的。
> > 
> > 
> > 主机部署应该不影响，只有docker才有JD_DIR，主机没有的，脚本会识别的。如果报错则请重头部署一下。
> 
> 我明白了，我也属于docker，我是部署在自己使用的docker上面，不想单独开个docker，所以也会有这个问题。尴尬了，我这不属于主机了，希望开发者可以加个判断。

那不行，必须用我的docker。

**Comment by bsdcpp** [comment]
> > > > 我也是主机部署（非docker），就是JD_DIR没有定义，直接按docker的路径来也可以的。
> > > 
> > > 
> > > 主机部署应该不影响，只有docker才有JD_DIR，主机没有的，脚本会识别的。如果报错则请重头部署一下。
> > 
> > 
> > 我明白了，我也属于docker，我是部署在自己使用的docker上面，不想单独开个docker，所以也会有这个问题。尴尬了，我这不属于主机了，希望开发者可以加个判断。
> 
> 那不行，必须用我的docker。

好吧，这属于强行推销啊😂

**Comment by EvineDeng** [comment]
> > > > > 我也是主机部署（非docker），就是JD_DIR没有定义，直接按docker的路径来也可以的。
> > > > 
> > > > 
> > > > 主机部署应该不影响，只有docker才有JD_DIR，主机没有的，脚本会识别的。如果报错则请重头部署一下。
> > > 
> > > 
> > > 我明白了，我也属于docker，我是部署在自己使用的docker上面，不想单独开个docker，所以也会有这个问题。尴尬了，我这不属于主机了，希望开发者可以加个判断。
> > 
> > 
> > 那不行，必须用我的docker。
> 
> 好吧，这属于强行推销啊😂

要不然越改越复杂，太麻烦了。

**Comment by bsdcpp** [comment]
> > > > > > 我也是主机部署（非docker），就是JD_DIR没有定义，直接按docker的路径来也可以的。
> > > > > 
> > > > > 
> > > > > 主机部署应该不影响，只有docker才有JD_DIR，主机没有的，脚本会识别的。如果报错则请重头部署一下。
> > > > 
> > > > 
> > > > 我明白了，我也属于docker，我是部署在自己使用的docker上面，不想单独开个docker，所以也会有这个问题。尴尬了，我这不属于主机了，希望开发者可以加个判断。
> > > 
> > > 
> > > 那不行，必须用我的docker。
> > 
> > 
> > 好吧，这属于强行推销啊😂
> 
> 要不然越改越复杂，太麻烦了。自己的环境好控制。

嗯，开个玩笑，复杂的话还是不要改。感谢大佬的奉献。

**Comment by hacken156026692** [comment]
还是不行，然后我尝试了在scripts文件里新建一个“node_modules”空的文件夹，然后再运行bash git_pull.sh，这回那个npm install不成功没了。显示的末尾如下

Fetching origin
HEAD is now at 0f36149 如果是docker，自动把sample/config.sh.sample复制到config目录下

shell脚本更新完成...
然后我切换到scripts想手动试一下，
~/jd/scripts $ node jd_live

🔔京东直播, 开始!
==============📣系统通知📣==============
京东直播
【提示】请先获取京东账号一cookie直接使用NobyDa的京东签到获取
https://bean.m.jd.com/

🔔京东直播, 结束! 🕛 0.035 秒
感觉我的cookie还是没被替换掉。不知为何了

**Comment by EvineDeng** [comment]
> 还是不行，然后我尝试了在scripts文件里新建一个“node_modules”空的文件夹，然后再运行bash git_pull.sh，这回那个npm install不成功没了。显示的末尾如下
> 
> Fetching origin
> HEAD is now at [0f36149](https://github.com/EvineDeng/jd-base/commit/0f36149bf7e39945787f6c9b4d0f9cb2a40bc9fb) 如果是docker，自动把sample/config.sh.sample复制到config目录下
> 
> shell脚本更新完成...
> 然后我切换到scripts想手动试一下，
> ~/jd/scripts $ node jd_live
> 
> 🔔京东直播, 开始!
> ==============📣系统通知📣==============
> 京东直播
> 【提示】请先获取京东账号一cookie直接使用NobyDa的京东签到获取
> https://bean.m.jd.com/
> 
> 🔔京东直播, 结束! 🕛 0.035 秒
> 感觉我的cookie还是没被替换掉。不知为何了

我教程中已经说得很明确，不能再直接node xxx.js了，请按教程手动执行任务。

**Comment by codingwjl** [comment]
![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
一样的问题, 明明有config/config.sh

**Comment by EvineDeng** [comment]
> ![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
> 一样的问题, 明明有config/config.sh

如果是docker，必须用我的docker，在其他docker里面不能用。

**Comment by EvineDeng** [comment]
@bsdcpp @68cs @fjqken @codingwjl 如果是docker环境，必须用我的docker，在其他docker里面不能用。

**Comment by codingwjl** [comment]
> > ![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
> > 一样的问题, 明明有config/config.sh
> 
> 如果是docker，必须用我的docker，在其他docker里面不能用。

docker里安装的centos呢

**Comment by binge8** [comment]
> > > ![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
> > > 一样的问题, 明明有config/config.sh
> > 
> > 
> > 如果是docker，必须用我的docker，在其他docker里面不能用。
> 
> docker里安装的centos呢

看来是docker里部署linux当物理机的都是这个问题

**Comment by EvineDeng** [comment]
> > > ![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
> > > 一样的问题, 明明有config/config.sh
> > 
> > 
> > 如果是docker，必须用我的docker，在其他docker里面不能用。
> 
> docker里安装的centos呢

一样也不行。

**Comment by EvineDeng** [comment]
> > > > ![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
> > > > 一样的问题, 明明有config/config.sh
> > > 
> > > 
> > > 如果是docker，必须用我的docker，在其他docker里面不能用。
> > 
> > 
> > docker里安装的centos呢
> 
> 看来是docker里部署linux当物理机的都是这个问题

一样也不行。

**Comment by binge8** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
> > > > > 一样的问题, 明明有config/config.sh
> > > > 
> > > > 
> > > > 如果是docker，必须用我的docker，在其他docker里面不能用。
> > > 
> > > 
> > > docker里安装的centos呢
> > 
> > 
> > 看来是docker里部署linux当物理机的都是这个问题
> 
> 一样也不行。

关键是v2版本没问题啊，所以我觉得还是目录判断出问题了，相信大佬应该可以解决

**Comment by codingwjl** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
> > > > > 一样的问题, 明明有config/config.sh
> > > > 
> > > > 
> > > > 如果是docker，必须用我的docker，在其他docker里面不能用。
> > > 
> > > 
> > > docker里安装的centos呢
> > 
> > 
> > 看来是docker里部署linux当物理机的都是这个问题
> 
> 一样也不行。

之前v2是可以的 烦请大佬看下是不是目录判断的问题呢

**Comment by EvineDeng** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/37137174/102707953-53bb0000-42da-11eb-86a2-425f3d76c67a.png)
> > > > > > 一样的问题, 明明有config/config.sh
> > > > > 
> > > > > 
> > > > > 如果是docker，必须用我的docker，在其他docker里面不能用。
> > > > 
> > > > 
> > > > docker里安装的centos呢
> > > 
> > > 
> > > 看来是docker里部署linux当物理机的都是这个问题
> > 
> > 
> > 一样也不行。
> 
> 之前v2是可以的 烦请大佬看下是不是目录判断的问题呢

不，因为我的docker才定义了JD_DIR的这个变量。

**Comment by 68cs** [comment]
> > > @68cs @binge8 现在你们重新克隆本仓库重新部署看看还有没有这个错误？
> > > @hacken156026692 你可能是访问不了取互助码的api，然后卡住了，你尝试手动运行一下看看？
> > 
> > 
> > 刚试了，还是一样不行
> 
> 那应该确实是你们那个环境不行了。。。我自己试了物理机、安卓termux、Docker全部正常。

我放弃物理机了，改跑Docker一切正常，谢谢老大

**Comment by hacken156026692** [comment]
谢谢大神，一个yarn命令，轻轻松松的解决了困扰我N天的npm install 运行不成功的窘境！谢谢！！

**Comment by EvineDeng** [comment]
> 谢谢大神，一个yarn命令，轻轻松松的解决了困扰我N天的npm install 运行不成功的窘境！谢谢！！

是更新git_pull.sh脚本后增加了yarn解决的??

**Comment by hacken156026692** [comment]
不是，我重新删掉jd文件夹，clone重新下载jd文件夹，config我备份好了。然后再次npm失败，根据提示进去scripts文件夹进行yarn，提示要安装yarn，安装完，执行了yarn后，再回jd运行git-pull就完全恢复正常了！！！谢谢！

**Comment by hacken156026692** [comment]
另外，大神，有啥其他非京东的撸羊毛脚本推荐吗？从你这边我学到很多很多，node和termux相当于从你这边学到的皮毛，已经够我受用了！！哈哈哈，谢谢！

**Comment by EvineDeng** [comment]
> 另外，大神，有啥其他非京东的撸羊毛脚本推荐吗？从你这边我学到很多很多，node和termux相当于从你这边学到的皮毛，已经够我受用了！！哈哈哈，谢谢！

我也不是很清楚。

**Comment by sofs2005** [comment]
最近种豆子总是互助不满了，不知道大家怎么样？

**Comment by ChadDongDongChen** [comment]
> > > /home/myid/jd/scripts/jd_bean_sign.js:28
> > > !(async() => {
> > > ^
> > > SyntaxError: Unexpected token (
> > > at createScript (vm.js:56:10)
> > > at Object.runInThisContext (vm.js:97:10)
> > > at Module._compile (module.js:549:28)
> > > at Object.Module._extensions..js (module.js:586:10)
> > > at Module.load (module.js:494:32)
> > > at tryModuleLoad (module.js:453:12)
> > > at Function.Module._load (module.js:445:3)
> > > at Module.runMain (module.js:611:10)
> > > at run (bootstrap_node.js:394:7)
> > > at startup (bootstrap_node.js:160:9)
> > > 大佬手动跑报错了
> > 
> > 
> > 估计是WIKI常见问题中的那个错误。
> 
> 感谢大佬，升级node版本解决了
> 
> 附上命令：sudo npm cache clean -f
> sudo n stable

感谢小姐姐，这个报错卡了很久

**Comment by EvineDeng** [comment]
> /scripts目录是不是不能映射到宿主机？试了试发现目录里没脚本了

不能，你一映射就覆盖了，不过你可以尝映射以后重新运行几次git_pull
