### ISSUE TITLE
config.sh.sample 为他人互助部分 疑似笔误

### ISSUE THREAD

**Issue by wsfy15** [EvineDeng/jd-base#119]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker V3

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：为他人互助疑似存在笔误

### (2) 详细日志
A：[东东农场为他人助力的配置说明](https://github.com/EvineDeng/jd-base/blob/v3/sample/config.sh.sample#L106) ：`ForOtherFruit1="${MyFruit2}@{MyFruit3}@{MyFruit5}@{MyFruitA}"`

[种豆得豆为他人助力的配置说明](https://github.com/EvineDeng/jd-base/blob/v3/sample/config.sh.sample#L162) ：`ForOtherBean1="${MyBean2}@${MyBean6}@${MyBeanB}`

是否前者少打了个`$`？

### (1) Node.js版本

A：none

### (2) npm版本

A：none

### (3)npm install的日志

A：none

**Comment by EvineDeng** [comment]
啊，应该全带有$的，我更新一下

**Comment by EvineDeng** [comment]
已更新注释。

**Comment by wsfy15** [comment]
辛苦大佬了
