### ISSUE TITLE
物理机安装,运行定时任务没有反应

### ISSUE THREAD

**Issue by Yaeger7** [EvineDeng/jd-base#12]
Ubuntu 物理机安装,运行定时任务没反应,没有cron.log 文件
每次定时任务的脚本日志文件正常生成,例如"020-11-05-02-40-01.log",但是log文件内容什么都没有.
单独执行脚本文件报错,例如执行,`jd_bean_sign.sh`, 报错如下:

`/root/jd/scripts/jd_bean_sign.js:100
    .finally(() => $.done())
            ^

TypeError: (intermediate value)(...).catch(...).finally is not a function
    at Object.<anonymous> (/root/jd/scripts/jd_bean_sign.js:100:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

**已配置Cookie,和用户数以及tg token**

**Comment by Yaeger7** [comment]
希望大神帮忙看看

**Comment by EvineDeng** [comment]
[修改信息](https://github.com/EvineDeng/jd-base#%E4%BF%AE%E6%94%B9%E4%BF%A1%E6%81%AF)
[定时任务](https://github.com/EvineDeng/jd-base#%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1)

**Comment by Yaeger7** [comment]
git diff ,cookie 显示已经替换成功了.

**Comment by EvineDeng** [comment]
那是好了？

**Comment by rayliu768** [comment]
你这个错误应该是没安装好nodejs吧

**Comment by kissfast** [comment]
先执行命令：node jd_xx.js
如果报错，说明nodejs没有安装好相应模块
注：如果使用Node.js, 需自行安装'crypto-js,got,http-server,tough-cookie'模块. 例: npm install crypto-js http-server tough-cookie got --save

**Comment by EvineDeng** [comment]
> 先执行命令：node jd_xx.js
> 如果报错，说明nodejs没有安装好相应模块
> 注：如果使用Node.js, 需自行安装'crypto-js,got,http-server,tough-cookie'模块. 例: npm install crypto-js http-server tough-cookie got --save

如果他有按我流程做，这些都会安装好的。
