### ISSUE TITLE
docker的启动配置文件好像写错了

### ISSUE THREAD

**Issue by caitaohjj** [EvineDeng/jd-base#121]
docker run -dit \
-v /appdata/jd/config:/jd/config `# 冒号左边是刚刚下载的两个文件存放的目录` \
-v /appdata/jd/log:/jd/log `# 日志保存目录` \
--name jd \
--hostname jd \
--restart always \
--network host `#如果是旁路由OpenWrt的Docker，建议添加上此行` \
evinedeng/jd

第二行，应该是   -v /appdata/jd/config/config:/jd/config

**Comment by EvineDeng** [comment]
> docker run -dit
> -v /appdata/jd/config:/jd/config `# 冒号左边是刚刚下载的两个文件存放的目录`
> -v /appdata/jd/log:/jd/log `# 日志保存目录`
> --name jd
> --hostname jd
> --restart always
> --network host `#如果是旁路由OpenWrt的Docker，建议添加上此行`
> evinedeng/jd
> 
> 第二行，应该是 -v /appdata/jd/config/config:/jd/config

没错，就是映射文件夹过去。这个config文件夹必须存在config.sh和crontab.list两个文件

**Comment by xie0027** [comment]
问一下 那短期任务是在docker内进行合并还是？

**Comment by EvineDeng** [comment]
> 问一下 那短期任务是在docker内进行合并还是？

crontab.list中说得很清楚了，AutoAddCron=true时自动合并，如果你非要设置false，那就只能手动加了。

**Comment by xie0027** [comment]
> > 问一下 那短期任务是在docker内进行合并还是？
> 
> crontab.list中说得很清楚了，AutoAddCron=true时自动合并，如果你非要设置false，那就只能手动加了。

不好意思 大佬 第一次用docker  刚手动运行了一下git pull 列表就更新好了
