### ISSUE TITLE
docker里git_pull的定时更新没有输出日志

### ISSUE THREAD

**Issue by smiking** [EvineDeng/jd-base#122]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：docker里git_pull的定时更新没有输出日志，输出日志是成功更新才会输出嘛，因为我之前手动git_pull了一下

### (2) 详细日志
A：没出现git_pull的日志

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
只有定时任务才会写入日志，手动运行直接在终端输出，不写入日志。

**Comment by smiking** [comment]
但是跑了一天了也每这个的日志

**Comment by EvineDeng** [comment]
> 但是跑了一天了也没有这个的日志，文件也没有

你看看你的crontab.list和sample下相应的list一样不一样

**Comment by smiking** [comment]
一样的，之前没动过这一行

**Comment by EvineDeng** [comment]
不会呀，要不你重新部署一下容器。我昨天深夜过容器，教程也更新了，部署方法也更新了。

**Comment by smiking** [comment]
好的，谢谢

**Comment by smiking** [comment]
还是不行，是不是这里面
`55 5-23 * * * bash git_pull >> {JD_DIR}/log/git_pull.log 2>&1`
得换成成`${JD_DIR}`
或者我系统的问题，可能不支持这么写

**Comment by EvineDeng** [comment]
哦哦，是的是的，我写错了&nbsp;

邓文星/Evine Deng
上海飞机制造有限公司
Shanghai Aircraft Manufacturing Co.,Ltd
CELL:177 2113 8711

&nbsp;TEL:021 2085 8201




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Quinn"<notifications@github.com&gt;; 
发送时间: 2020年12月20日(星期天) 下午3:29
收件人: "EvineDeng/jd-base"<jd-base@noreply.github.com&gt;; 
抄送: "EvineDeng"<evinedeng@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [EvineDeng/jd-base] docker里git_pull的定时更新没有输出日志 (#122)





 
还是不行，是不是这里面
 55 5-23 * * * bash git_pull &gt;&gt; {JD_DIR}/log/git_pull.log 2&gt;&amp;1
 得换成成${JD_DIR}
 或者我系统的问题，可能不支持这么写

**Comment by smiking** [comment]
emmmm 好的

**Comment by smiking** [comment]
还有wiki里面

手动 git pull 更新脚本

`docker exec -it bash git_pull`
手动删除指定时间以前的旧日志

`docker exec -it bash rm_log`

这里少了少了容器名，也改一下吧

**Comment by EvineDeng** [comment]
> 还有wiki里面
> 
> 手动 git pull 更新脚本
> 
> `docker exec -it bash git_pull`
> 手动删除指定时间以前的旧日志
> 
> `docker exec -it bash rm_log`
> 
> 这里少了少了容器名，也改一下吧

你可以帮忙编辑一下那个页面。

**Comment by smiking** [comment]
好的

**Comment by xie0027** [comment]
我cronlist gitpull那一行把$加进去了  然后又会自动更新没掉  咋整啊？

**Comment by EvineDeng** [comment]
> 我cronlist gitpull那一行把$加进去了  然后又会自动更新没掉  咋整啊？

啥？

**Comment by xie0027** [comment]
就是cronlist git_pull的任务{JD_DIR} 你引用这个全局变量 不是少了一个$  然后我自己手动加上  gitpull一运行 又改回去了

**Comment by EvineDeng** [comment]
你只能改你自己config文件夹下的crontab.list。

**Comment by xie0027** [comment]
对的 我改的就是我自己的本地的cronlist 我昨天改的  今天起来一看 又给我改回去了  就是那个$没了  你看下你远程simple文件是不是忘记改了

**Comment by EvineDeng** [comment]
> 对的 我改的就是我自己的本地的cronlist 我昨天改的  今天起来一看 又给我改回去了  就是那个$没了  你看下你远程simple文件是不是忘记改了

估计哪里操作不对。。。。

**Comment by xie0027** [comment]
那我自己研究研究 顺带问下就是新增加的任务不会自动换行  直接在最后一条任务的尾巴加进去的  这个要怎么处理  我现在都是加了任务手动加换行   底部也留了个空行

**Comment by EvineDeng** [comment]
> 那我自己研究研究 顺带问下就是新增加的任务不会自动换行  直接在最后一条任务的尾巴加进去的  这个要怎么处理  我现在都是加了任务手动加换行   底部也留了个空行

你不要删除最后原本多的一个回车

**Comment by EvineDeng** [comment]
> > 那我自己研究研究 顺带问下就是新增加的任务不会自动换行  直接在最后一条任务的尾巴加进去的  这个要怎么处理  我现在都是加了任务手动加换行   底部也留了个空行
> 
> 你不要删除最后原本多的一个回车

最后珩应该是个空行

**Comment by xie0027** [comment]
对啊 我最后一行就是留了个空行  但是还是会加到尾部

**Comment by bingyang519** [comment]
我macos中的定时任务一直没输出日志，也不知道有没有再运行。
挂机脚本一直在输出日志。
crontab -l    也都能打印到控制台。

大佬帮助一下
@EvineDeng
