### ISSUE TITLE
群晖V3版本运行报错自动停止（2020.12.20 中午镜像）

### ISSUE THREAD

**Issue by 1354961639** [EvineDeng/jd-base#124]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：群晖docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：群晖docker运行报错自动停止

### (2) 详细日志
A：crond[8]: crond (busybox 1.31.1) started, log level 8
      cp: cannot create regular file '/jd/config/crontab.list': No such file or directory

### (1) Node.js版本

A：群晖 Docker

### (2) npm版本

A：群晖 Docker

### (3)npm install的日志

A：群晖 Docker

**Comment by EvineDeng** [comment]
你没有映射正确的目录给容器，群晖的目录建议要命令行中获取完整路径，在webui中看到的不一定对。
&nbsp;

邓文星/Evine Deng
上海飞机制造有限公司
Shanghai Aircraft Manufacturing Co.,Ltd
CELL:177 2113 8711

&nbsp;TEL:021 2085 8201




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Juuice"<notifications@github.com&gt;; 
发送时间: 2020年12月20日(星期天) 下午2:06
收件人: "EvineDeng/jd-base"<jd-base@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [EvineDeng/jd-base] 群晖运行报错自动停止 (#124)





 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程
  
2. 使用什么平台，精确到版本
 
A：群晖docker
 
3. 按照以下哪个教程做的
  
 Linux
 
 Android
 
 MacOS
 
 Docker
  
4. 详细叙述
 
(1) 具体问题
 
A：群晖docker运行报错自动停止
 
(2) 详细日志
 
A：crond[8]: crond (busybox 1.31.1) started, log level 8
 cp: cannot create regular file '/jd/config/crontab.list': No such file or directory
 
5.软件版本和npm install
 
(1) Node.js版本
 
A：群晖 Docker
 
(2) npm版本
 
A：群晖 Docker
 
(3)npm install的日志
 
A：群晖 Docker
