### ISSUE TITLE
自定义js文件无法在定时任务执行

### ISSUE THREAD

**Issue by braless** [EvineDeng/jd-base#126]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Centos 7

## 3. 按照以下哪个教程做的

- [ x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：自定义js文件无法在定时任务执行 我调整了执行频率为每分钟 始终没有执行结果，直接在终端li执行是可以的

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
不太明白你说的是什么

**Comment by braless** [comment]
比如说我在 home/myid/jd的目录下新建了一个myscripts/里面有我自己的js文件, 然后我在远程终端输入 node home/myid/jd/myscripts/myxxx.js  可以执行,就是添加到 crontab.list 里面 不会去执行这个js文件,

**Comment by EvineDeng** [comment]
目前还没这个功能，过两天再加。

**Comment by braless** [comment]
我还以为我哪里出问题了呢,一切都按教程来的,我从docker换成linux的版本都不行,那就只能等待大佬更新了.,还有docker 里面的一些小细节, 可以先进入docker 再执行命令,比如手动执行 某个任务 就要docker exec *****  然后可以按tab提示补全jd_后面的吗,都要手动敲

**Comment by EvineDeng** [comment]
不能自动补全，但输错了会提示你有哪些脚本可以执行。

**Comment by EvineDeng** [comment]
自动实例功能，我后面过段时间，看看能不能实现，如果能实现，我后续会加上。

当然，直接宿主机上bash jd xxx肯定是不能自动补全的，要进入容器后。

**Comment by braless** [comment]
这个问题不大,有没有都可以,主要是想要执行自定义js ,因为 之前用v2的时候,我单独创建了一个shell2,scripts2 目录,重写了一下sendNotify.js 然后把一些jd_bean_change.sh执行结果发到我的qq群了,现在在v3的docker/linux 我把那v2俩目录和文件移动过去, 加入定时任务后不能执行sh文件,和js ,终端 里面 二者(直接执行sh,sh去找目录下的js或者直接执行js )都可以(Docker/linux)通过直接敲命令完成,

**Comment by EvineDeng** [comment]
现在自定义脚本功能支持已经和京东脚本一模一样了，详见wiki。

**Comment by braless** [comment]
Got it!
