### ISSUE TITLE
mac版本删除定时任务 Search pattern not terminated at -e line 1.

### ISSUE THREAD

**Issue by GoToBoy** [EvineDeng/jd-base#128]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：mac nodejs

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：执行 bash git_pull.sh

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/2384105/102714226-369d2600-4308-11eb-98d8-920d0678cf06.png)

### (1) Node.js版本

A：v12.13.0

### (2) npm版本

A：7.0.14

### (3)npm install的日志

A：ok

**Comment by EvineDeng** [comment]
已修改，请连续运行两次git_pull.sh，看第二次的结果（第一次仍然会报错的）。

**Comment by GoToBoy** [comment]
不会报错了，but
![image](https://user-images.githubusercontent.com/2384105/102714616-d52a8680-430a-11eb-96d9-77e0348d1f8d.png)

**Comment by EvineDeng** [comment]
> 不会报错了，but
> ![image](https://user-images.githubusercontent.com/2384105/102714616-d52a8680-430a-11eb-96d9-77e0348d1f8d.png)

第2次也删不掉吗？

**Comment by GoToBoy** [comment]
第三遍刚可以了～我再测试几下「thanks」

**Comment by GoToBoy** [comment]
jd_joy_run.js的替换有问题
![image](https://user-images.githubusercontent.com/2384105/102714687-5255fb80-430b-11eb-813e-44e0059f1dff.png)

run_pins 和 friendsArr 没有删掉原来的
![image](https://user-images.githubusercontent.com/2384105/102714715-71ed2400-430b-11eb-8974-b2b83212d8aa.png)

**Comment by EvineDeng** [comment]
> jd_joy_run.js的替换有问题
> ![image](https://user-images.githubusercontent.com/2384105/102714687-5255fb80-430b-11eb-813e-44e0059f1dff.png)
> 
> run_pins 和 friendsArr 没有删掉原来的

我本来就只是增加而已，没有删除，放前面的优先，先是你的，再是我的，最后是脚本自带的。

**Comment by EvineDeng** [comment]
> jd_joy_run.js的替换有问题
> ![image](https://user-images.githubusercontent.com/2384105/102714687-5255fb80-430b-11eb-813e-44e0059f1dff.png)
> 
> run_pins 和 friendsArr 没有删掉原来的

PIN和friendsArr本来就不会删除自带的，PIN的话，先是你的，再是我的，最后是脚本自带的，按顺序助力。没有助力次数了自动跳出。

**Comment by GoToBoy** [comment]
> > jd_joy_run.js的替换有问题
> > ![image](https://user-images.githubusercontent.com/2384105/102714687-5255fb80-430b-11eb-813e-44e0059f1dff.png)
> > run_pins 和 friendsArr 没有删掉原来的
> 
> 我本来就只是增加而已，没有删除，放前面的优先，PIN先是你的，再是我的，最后是脚本自带的。

明白了，我close掉这个吧～ 跪谢大佬
