### ISSUE TITLE
源码贡献 & script reset --hard 设置问题

### ISSUE THREAD

**Issue by GoToBoy** [EvineDeng/jd-base#129]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：v2版本的消息bot v3版本没有实现「git_pull代码中没有找到」
B：我可以贡献代码吗？fork之后改完 commit给主分支？
C：scripts文件夹的reset 问题，比如我增加了一个其他的任务（京喜农场）在源代码中没有的，如果执行了reset，我这个代码也会不见的...这个设置不太好

**Comment by GoToBoy** [comment]
补充具体问题A，我在本地代码增加了，所以会有问题B贡献代码的问题

**Comment by GoToBoy** [comment]
补充问题二:
![image](https://user-images.githubusercontent.com/2384105/102715197-b1693f80-430e-11eb-85ee-01da41bc8a80.png)
![image](https://user-images.githubusercontent.com/2384105/102715201-ba5a1100-430e-11eb-8b3c-98ff3b30f514.png)
都是一样的东西，这来回添加有点奇怪？

**Comment by EvineDeng** [comment]
reset不会删除你加进去的文件，你是其他原因吧？

v2没有消息bot啊？现在v3我今天坐到是刚刚加了消息bot。

你刚刚反馈的又删又加有点奇怪，我研究一下。

**Comment by EvineDeng** [comment]
你可以贡献代码啊，本来就是开源的。

**Comment by GoToBoy** [comment]
> reset不会删除你加进去的文件，你是其他原因吧？
> 
> v2没有消息bot啊？现在v3我今天倒到是刚刚加了消息bot。
> 
> 你刚刚反馈的又删又加有点奇怪，我研究一下。

我表达错了，是推送消息的token secret这些值的替换。如果你加了就没这跟题了

![image](https://user-images.githubusercontent.com/2384105/102715290-5be16280-430f-11eb-8dfc-373b24371153.png)

**Comment by EvineDeng** [comment]
> > reset不会删除你加进去的文件，你是其他原因吧？
> > v2没有消息bot啊？现在v3我今天倒到是刚刚加了消息bot。
> > 你刚刚反馈的又删又加有点奇怪，我研究一下。
> 
> 我表达错了，是推送消息的token secret这些值的替换。如果你加了就没这跟题了
> 
> ![image](https://user-images.githubusercontent.com/2384105/102715290-5be16280-430f-11eb-8dfc-373b24371153.png)

哦，现在不修改js了，直接用环境变量。你在config.sh中配置好就行，脚本会知道的。

**Comment by GoToBoy** [comment]
> > > reset不会删除你加进去的文件，你是其他原因吧？
> > > v2没有消息bot啊？现在v3我今天倒到是刚刚加了消息bot。
> > > 你刚刚反馈的又删又加有点奇怪，我研究一下。
> > 
> > 
> > 我表达错了，是推送消息的token secret这些值的替换。如果你加了就没这跟题了
> > ![image](https://user-images.githubusercontent.com/2384105/102715290-5be16280-430f-11eb-8dfc-373b24371153.png)
> 
> 哦，现在不修改js了，直接用环境变量。你在config.sh中配置好就行，脚本会知道的。

好的～

**Comment by EvineDeng** [comment]
那个又删任务又加任务的bug，我也暂时无法复现，你可以等下次自动执行git_pull再看看正常不正常，或者手动执行看看正常不正常。

**Comment by EvineDeng** [comment]
建议阅读一下v3的教程，有很多不一样的地方。

**Comment by GoToBoy** [comment]
> 建议阅读一下v3的教程，有很多不一样的地方。

了解，刚试了下，reset --hard 会把我添加到scripts里面的其他任务文件删除掉的 ，相当于还原git版本

**Comment by EvineDeng** [comment]
> > 建议阅读一下v3的教程，有很多不一样的地方。
> 
> 了解，刚试了下，reset --hard 会把我添加到scripts里面的其他任务文件删除掉的 ，相当于还原git版本

咋我的正常啊，并且无论是v2还是v3我这里都正常啊。我看git帮助说明，应该reset不会删除其他加进去的文件。

**Comment by GoToBoy** [comment]
= =重新新建一个空文件，竟然没有被删除，我研究下～
