### ISSUE TITLE
京东签到执行出错

### ISSUE THREAD

**Issue by GoToBoy** [EvineDeng/jd-base#131]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Mac

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：之前脚本没问题，v3升级之后有这个，我推测是bash脚本上的哪里出了问题，看了下js代码和之前一样

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/2384105/102732053-97624800-4374-11eb-886b-6ec8d44c1e58.png)

### (1) Node.js版本

A：v12.13.0

### (2) npm版本

A：7.0.14

### (3)npm install的日志

A：up to date in 782ms

**Comment by EvineDeng** [comment]
bean_sign要下载nobyda的签到脚本，就是你错误中的那个。

你把你输入的完整命令发来看看

**Comment by GoToBoy** [comment]
`
bash /dev/jd-base/jd.sh jd_bean_sign now
`

**Comment by EvineDeng** [comment]
机器上存在/tmp目录吗

**Comment by EvineDeng** [comment]
你试一下先cd到jd.sh脚本目录后，再执行bash jd.sh bean_sign now看看报错不报错？

**Comment by GoToBoy** [comment]
> 你试一下先cd到jd.sh脚本目录后，再执行bash jd.sh bean_sign now看看报错不报错？

嗯 我试试

**Comment by GoToBoy** [comment]
`
bash jd.sh jd_bean_sign now
文件下载异常:TypeError: Cannot convert undefined or null to object
`

**Comment by GoToBoy** [comment]
我看了下原来js的代码，疑惑之前是怎么执行成功的？在readfile前没有看到有写入JD_DailyBouns.js文件

**Comment by EvineDeng** [comment]
看起来程序是正常运行的，只是无法下载文件，你到lxk0301那边提个不issue问下确定一下具体原因，再看看是不是shell的问题。

**Comment by GoToBoy** [comment]
> 看起来程序是正常运行的，只是无法下载文件，你到lxk0301那边提个不issue问下确定一下具体原因，再看看是不是shell的问题。

文件是可以读到的，只是没看到代码执行写入到File
 我试试删掉node_modules，手动下载再试一次

**Comment by GoToBoy** [comment]
> > 看起来程序是正常运行的，只是无法下载文件，你到lxk0301那边提个不issue问下确定一下具体原因，再看看是不是shell的问题。
> 
> 文件是可以读到的，只是没看到代码执行写入到File
> 我试试删掉node_modules，手动下载再试一次

可以了，我删掉node_modules，然后用 yarn 来执行

**Comment by GoToBoy** [comment]
downFile 在npm 和 yarn下可能有差别

**Comment by EvineDeng** [comment]
行吧，js的我不太懂，既然你懂那就好说了

**Comment by GoToBoy** [comment]
补充一个，yarn 比npm 好一些，要不要检测到yarn时候执行yarn，没有再执行npm

**Comment by EvineDeng** [comment]
> 补充一个，yarn 比npm 好一些，要不要检测到yarn时候执行yarn，没有再执行npm

那我先学习一下，看看怎么用yarn。

**Comment by EvineDeng** [comment]
你要是会shell，也可以直接发pr。

**Comment by GoToBoy** [comment]
> 你要是会shell，也可以直接发pr。

一样的，npm install == yarn （语法更简洁）

我可以试着改一下
