### ISSUE TITLE
grep -vwf 匹配的问题

### ISSUE THREAD

**Issue by GoToBoy** [EvineDeng/jd-base#133]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Mac BigSur

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：
[js.txt](https://github.com/EvineDeng/jd-base/files/5724918/js.txt)
[task.txt](https://github.com/EvineDeng/jd-base/files/5724920/task.txt)

两个文件只是顺序不一样，内容是一样的，但是在mac，grep匹配不出来

`
grep -vwf js.txt task.txt
jd_joy_feedPets
jd_joy_reward
jd_joy_run
jd_joy_steal
jd_live_redrain

`
![image](https://user-images.githubusercontent.com/2384105/102789519-39b71580-43df-11eb-9043-50144884b1ea.png)

### (2) 详细日志
A：

**Comment by EvineDeng** [comment]
mac下问题怎么这么多？那如何要全字匹配，mac下应该是什么命令？

**Comment by GoToBoy** [comment]
> mac下问题怎么这么多？那如何要全字匹配，mac下应该是什么命令？

我明天找找mac下的相似命令～这几次遇到的sh兼容问题，感觉用shell还是在linux下舒服点

**Comment by EvineDeng** [comment]
嗯，到时候你研究好了可以pr过来。

**Comment by EvineDeng** [comment]
要不装个GNU的grep试试，抛弃BSD的grep？

**Comment by GoToBoy** [comment]
> grep

我抛弃mac跑定时任务了，买了台99的腾讯服务器跑任务。
