### ISSUE TITLE
[功能建议]建议增加 config.sh 自动更新功能，希望大佬能添加一下，谢谢

### ISSUE THREAD

**Issue by FanchangWang** [EvineDeng/jd-base#135]
建议增加 config.sh 自动更新功能，希望大佬能添加一下，谢谢

实现方式：
1、自动读取原 config.sh 已配置项的值，对比新的 config.sh.smaple 同配置项值，值不相同时自动覆盖 config.sh.smaple 配置项。（同时 config.sh 中手动添加的配置项也自动添加到 config.sh.smaple 中）
2、将处理完毕的 config.sh.smaple 重命名为 config.sh。（原 config.sh 文件可以创建个 bak 目录用于备份）

**Comment by EvineDeng** [comment]
你可以提交pr。

**Comment by FanchangWang** [comment]
> 你可以提交pr。

我写写试试吧，shell 的语法不太会，不知道好不好搞

**Comment by EvineDeng** [comment]
还有，为了兼容多平台，不要使用sed，崦用perl。

**Comment by 68cs** [comment]
好提议，好提议，赞

**Comment by hacken156026692** [comment]
大神，jd_unbind这新功能太牛掰了。我一下子注销了121个
==============📣系统通知📣==============
注销京东会员卡
【京东账号1】
【已注销会员卡】121个
【还剩会员卡】7个

好奇问一下，这些新功能，也是lxk0301开发出来的吗？有没有点亮心愿单啊？每天也有20豆。^_^

**Comment by EvineDeng** [comment]
> 大神，jd_unbind这新功能太牛掰了。我一下子注销了121个
> ==============📣系统通知📣==============
> 注销京东会员卡
> 【京东账号1】
> 【已注销会员卡】121个
> 【还剩会员卡】7个
> 
> 好奇问一下，这些新功能，也是lxk0301开发出来的吗？有没有点亮心愿单啊？每天也有20豆。^_^

别人pr到他仓库的。心愿点做不了。

**Comment by FanchangWang** [comment]
`config.sh` 里面还有 `shell` 语句，这种的不好跟 `config.sh.smaple` 对比是否发生变更，有什么好点的解决方案吗？


比如下面这段

```bash

################################## 定义东东萌宠是否静默运行（选填） ##################################
## 默认 "false"（不静默，发送推送通知消息），如想静默请修改为 true
## 每次执行脚本通知太频繁了，改成只在周三和周六中午那一次运行时发送通知提醒
## 除掉上述提及时间之外，均设置为 true，静默不发通知
## 特别说明：针对北京时间有效。
if [ $(date "+%w") -eq 6 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
  export PET_NOTIFY_CONTROL="false"
elif [ $(date "+%w") -eq 3 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
  export PET_NOTIFY_CONTROL="false"
else
  export PET_NOTIFY_CONTROL="true"
fi
```

**Comment by EvineDeng** [comment]
> 
> 
> `config.sh` 里面还有 `shell` 语句，这种的不好跟 `config.sh.smaple` 对比是否发生变更，有什么好点的解决方案吗？
> 
> 
> 比如下面这段
> 
> ```bash
> 
> ################################## 定义东东萌宠是否静默运行（选填） ##################################
> ## 默认 "false"（不静默，发送推送通知消息），如想静默请修改为 true
> ## 每次执行脚本通知太频繁了，改成只在周三和周六中午那一次运行时发送通知提醒
> ## 除掉上述提及时间之外，均设置为 true，静默不发通知
> ## 特别说明：针对北京时间有效。
> if [ $(date "+%w") -eq 6 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
>   export PET_NOTIFY_CONTROL="false"
> elif [ $(date "+%w") -eq 3 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
>   export PET_NOTIFY_CONTROL="false"
> else
>   export PET_NOTIFY_CONTROL="true"
> fi
> ```

一般系统默认带diff命令，可以参考。

**Comment by EvineDeng** [comment]
> 
> 
> `config.sh` 里面还有 `shell` 语句，这种的不好跟 `config.sh.smaple` 对比是否发生变更，有什么好点的解决方案吗？
> 
> 
> 比如下面这段
> 
> ```bash
> 
> ################################## 定义东东萌宠是否静默运行（选填） ##################################
> ## 默认 "false"（不静默，发送推送通知消息），如想静默请修改为 true
> ## 每次执行脚本通知太频繁了，改成只在周三和周六中午那一次运行时发送通知提醒
> ## 除掉上述提及时间之外，均设置为 true，静默不发通知
> ## 特别说明：针对北京时间有效。
> if [ $(date "+%w") -eq 6 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
>   export PET_NOTIFY_CONTROL="false"
> elif [ $(date "+%w") -eq 3 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
>   export PET_NOTIFY_CONTROL="false"
> else
>   export PET_NOTIFY_CONTROL="true"
> fi
> ```

一般系统默认带diff命令，可以参考。

**Comment by 68cs** [comment]
> `config.sh`里面还有`shell`语句，这种的不好跟`config.sh.smaple`对比是否发生变更，有什么好点的解决方案吗？
> 
> 例如下面这段
> 
> ```shell
> ＃ #################################定义东东萌宠是否静默运行（选填）#### ############################## 
> ＃＃默认“假”（不静默，发送推送通知消息），如想静默请修改为真
> ＃＃每次执行脚本通知太频繁了，改成只在周三和周六中午那一次运行时发送通知提醒
> ＃＃除掉上述提及时间之外，均设置为真，静默不发通知
> ＃＃特别说明：针对北京时间有效
> 如果[ $（日期“ +％（重量）”）  -eq 6] && [ $（日期“ +％H ”）  -ge 9] && [ $（日期“ +％H ”）  -lt 14] ;  然后
>   export PET_NOTIFY_CONTROL = “ false ”
>  elif [ $（日期“ +％w ”）-  eq 3] && [ $（日期“ +％H ”）-  ge 9] && [ $（日期“ +％H ”）  -lt 14 ] ； 然后
>   导出PET_NOTIFY_CONTROL = “ false ”，
> 否则
>   导出PET_NOTIFY_CONTROL = “ true ”
>  fi
> ```

“老王”加油，频繁手动更新config，真重复的心烦呀，哈哈

**Comment by EvineDeng** [comment]
> > `config.sh`里面还有`shell`语句，这种的不好跟`config.sh.smaple`对比是否发生变更，有什么好点的解决方案吗？
> > 
> > 例如下面这段
> > 
> > ```shell
> > ＃ #################################定义东东萌宠是否静默运行（选填）#### ############################## 
> > ＃＃默认“假”（不静默，发送推送通知消息），如想静默请修改为真
> > ＃＃每次执行脚本通知太频繁了，改成只在周三和周六中午那一次运行时发送通知提醒
> > ＃＃除掉上述提及时间之外，均设置为真，静默不发通知
> > ＃＃特别说明：针对北京时间有效
> > 如果[ $（日期“ +％（重量）”）  -eq 6] && [ $（日期“ +％H ”）  -ge 9] && [ $（日期“ +％H ”）  -lt 14] ;  然后
> >   export PET_NOTIFY_CONTROL = “ false ”
> >  elif [ $（日期“ +％w ”）-  eq 3] && [ $（日期“ +％H ”）-  ge 9] && [ $（日期“ +％H ”）  -lt 14 ] ； 然后
> >   导出PET_NOTIFY_CONTROL = “ false ”，
> > 否则
> >   导出PET_NOTIFY_CONTROL = “ true ”
> >  fi
> > ```
> 
> “老王”加油，频繁手动更新config，真重复的心烦呀，哈哈

用不着可以不管的，如果大家嫌通知烦，我干脆不通知了，有需要的自己到lxk0301大佬仓库去看新增加的功能。

**Comment by 68cs** [comment]
> > > `config.sh`里面还有`shell`语句，这种的不好跟`config.sh.smaple`对比是否发生变更，有什么好点的解决方案吗？
> > > 例如下面这段
> > > ```shell
> > > ＃ #################################定义东东萌宠是否静默运行（选填）#### ############################## 
> > > ＃＃默认“假”（不静默，发送推送通知消息），如想静默请修改为真
> > > ＃＃每次执行脚本通知太频繁了，改成只在周三和周六中午那一次运行时发送通知提醒
> > > ＃＃除掉上述提及时间之外，均设置为真，静默不发通知
> > > ＃＃特别说明：针对北京时间有效
> > > 如果[ $（日期“ +％（重量）”）  -eq 6] && [ $（日期“ +％H ”）  -ge 9] && [ $（日期“ +％H ”）  -lt 14] ;  然后
> > >   export PET_NOTIFY_CONTROL = “ false ”
> > >  elif [ $（日期“ +％w ”）-  eq 3] && [ $（日期“ +％H ”）-  ge 9] && [ $（日期“ +％H ”）  -lt 14 ] ； 然后
> > >   导出PET_NOTIFY_CONTROL = “ false ”，
> > > 否则
> > >   导出PET_NOTIFY_CONTROL = “ true ”
> > >  fi
> > > ```
> > 
> > 
> > “老王”加油，频繁手动更新config，真重复的心烦呀，哈哈
> 
> 用不着可以不管的，如果大家嫌通知烦，我干脆不通知了，有需要的自己到lxk0301大佬仓库去看新增加的功能。

别呀，老大，该通知还通知呀

**Comment by 68cs** [comment]
发现用Beyond Compare这个软件的“文本合并”功能，可以快速更新替换config.sh，大家不妨试试

**Comment by FanchangWang** [comment]
> > `config.sh` 里面还有 `shell` 语句，这种的不好跟 `config.sh.smaple` 对比是否发生变更，有什么好点的解决方案吗？
> > 比如下面这段
> > ```shell
> > ################################## 定义东东萌宠是否静默运行（选填） ##################################
> > ## 默认 "false"（不静默，发送推送通知消息），如想静默请修改为 true
> > ## 每次执行脚本通知太频繁了，改成只在周三和周六中午那一次运行时发送通知提醒
> > ## 除掉上述提及时间之外，均设置为 true，静默不发通知
> > ## 特别说明：针对北京时间有效。
> > if [ $(date "+%w") -eq 6 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
> >   export PET_NOTIFY_CONTROL="false"
> > elif [ $(date "+%w") -eq 3 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
> >   export PET_NOTIFY_CONTROL="false"
> > else
> >   export PET_NOTIFY_CONTROL="true"
> > fi
> > ```
> 
> 一般系统默认带diff命令，可以参考。

确定用 diff  做功能了，流程如下

- `diff config.sh config.sh.sample`
- 根据 `diff` 结果确定变更行，格式有
  + `460a456` 单行变单行
  + `391c377,378` 单行变多行
  + `236,247c234` 多行变单行
  + `257,263c249,254` 多行变多行
- 过滤变更行内容，排除『# 开头的注释行』、『空行』
  + 注意事项如下
  + 对比结果左右两侧都需要过滤
  + 当左右两侧过滤的行数不一致时，注意行数进行相应累加或减少
- 定位其余变更内容，将『> 』`config.sh.sample` 所在行删除，将『< 』`config.sh` 所在行插入 `config.sh.sample` 删除行位置
  + 注意事项如下
  + 如果 『< 』行内容非最后一行，且无 `\n` 换行符，需增加 `\n` 换行符
  + 当 `删除行` 与 `插入行` 数量不一致时，注意行数进行相应累加或减少
- 备份 `config.sh` 文件 
  + `[ ! -d config_bak ] && mkdir config_bak`
  + `mv config.sh config_bak/config.sh_$(date "+%Y-%m-%d-%H-%M-%S")`
- 重命名 `config.sh.sample` 文件 `mv config.sh.sample config.sh`

**Comment by EvineDeng** [comment]
@FanchangWang ，好了之后先pr到dev分支，我测试完全没问题再merge到v3分支。

**Comment by di7gan** [comment]
如果为了省事，其实可以直接新建一个版本更新内容简介，例如3.7.0版本相对于3.6.x版本哪里有变换，哪里有新增，这样大家直接可以根据这个更新内容去手动更新。

**Comment by EvineDeng** [comment]
> 如果为了省事，其实可以直接新建一个版本更新内容简介，例如3.7.0版本相对于3.6.x版本哪里有变换，哪里有新增，这样大家直接可以根据这个更新内容去手动更新。

这个内容你们直接看github上config.sh.sample的commit一眼就看到了。

**Comment by sofs2005** [comment]
那个新加的导出互助码怎么用？没看懂

**Comment by lonee6** [comment]
> 发现用Beyond Compare这个软件的“文本合并”功能，可以快速更新替换config.sh，大家不妨试试

这个办法好，选几下左右就搞定。

**Comment by sofs2005** [comment]
> 那个新加的导出互助码怎么用？没看懂

跑完发现东东小窝没有对应日志，健康抽奖机（短期）和京东健康（短期）这两个配置文件里面也没有地方填，这个怎么玩呢？

**Comment by EvineDeng** [comment]
> > 那个新加的导出互助码怎么用？没看懂
> 
> 跑完发现东东小窝没有对应日志，健康抽奖机（短期）和京东健康（短期）这两个配置文件里面也没有地方填，这个怎么玩呢？

没地方填就是不提供此功能。

**Comment by FanchangWang** [comment]
每次收到这个 issue 的邮件提醒我都以为有谁提供好的代码方案了 🤣

这代码真难写，`diff` 命令在不同系统下的输出结果不同，折腾半天放弃了这个方案。
改用 [node jsdiff（npm 模块）](https://github.com/kpdecker/jsdiff) 写，但是新旧对比的时候依然会有错误的情况，头大的很。
忽略 # 注释的话，可能会导致跟后续任何一个版本的 `config.sh.sample` 注释对比都不一致，也可能导致手动添加的 # 注释丢失，反之也是一样的情况。
`jsdiff` 对比是顺序逐行的，手动进行代码块调整的时候，不一致的情况太多，都是 `配置项="值"` 的情况下大不了枚举所有 `配置项` 但是 `sh` 文件还能写 `shell` 代码，惆怅。。。
即便忽略掉 `config.sh` 手动添加 `shell` 代码的可能性，也不排除官方脚本后续进行代码块顺序调整或主动添加更多 `shell` 代码，甚至变更某个 `配置项` 的名称，想死的节奏。。。

再想要不要做个人工介入的方案，手动执行某个命令，比如  `bash config_diff.sh`  或 `node config_diff.js` 命令，然后对冲突的行内容进行人工提示，删除 or 保留 or 覆盖，虽然不能自动合并，但总比拉下来用各种文本对比工具弄完再上传方便点

**Comment by EvineDeng** [comment]
> 每次收到这个 issue 的邮件提醒我都以为有谁提供好的代码方案了 🤣
> 
> 这代码真难写，`diff` 命令在不同系统下的输出结果不同，折腾半天放弃了这个方案。
> 改用 [node jsdiff（npm 模块）](https://github.com/kpdecker/jsdiff) 写，但是新旧对比的时候依然会有错误的情况，头大的很。
> 忽略 # 注释的话，可能会导致跟后续任何一个版本的 `config.sh.sample` 注释对比都不一致，也可能导致手动添加的 # 注释丢失，反之也是一样的情况。
> `jsdiff` 对比是顺序逐行的，手动进行代码块调整的时候，不一致的情况太多，都是 `配置项="值"` 的情况下大不了枚举所有 `配置项` 但是 `sh` 文件还能写 `shell` 代码，惆怅。。。
> 即便忽略掉 `config.sh` 手动添加 `shell` 代码的可能性，也不排除官方脚本后续进行代码块顺序调整或主动添加更多 `shell` 代码，甚至变更某个 `配置项` 的名称，想死的节奏。。。
> 
> 再想要不要做个人工介入的方案，手动执行某个命令，比如 `bash config_diff.sh` 或 `node config_diff.js` 命令，然后对冲突的行内容进行人工提示，删除 or 保留 or 覆盖，虽然不能自动合并，但总比拉下来用各种文本对比工具弄完再上传方便点

这也是我不愿意写这功能的原因。。。。在大量注释存在的前提下，这个功能难度非常高。

**Comment by hacken156026692** [comment]
大神，不好意思又要问您个问题：

我cookies满一个月失效了，重新抓包获取了新cookie后，在config.sh配置保存好了，再bash git_pull.sh，但service酱还是一直在发cookie失效。但我在termux里手动运行bash jd.sh XXX.sh，输出的显示是正常的。

请问一下，能否判断一下，是哪里出错了？？

**Comment by EvineDeng** [comment]
> 大神，不好意思又要问您个问题：
> 
> 我cookies满一个月失效了，重新抓包获取了新cookie后，在config.sh配置保存好了，再bash git_pull.sh，但service酱还是一直在发cookie失效。但我在termux里手动运行bash jd.sh XXX.sh，输出的显示是正常的。
> 
> 请问一下，能否判断一下，是哪里出问题了？？
> 

你大概是部署了两套脚本吧。

**Comment by hacken156026692** [comment]
我就是因为cookie到期了，重新设置了。结果还是service酱失效

**Comment by hacken156026692** [comment]
我只有一个脚本，~/jd文件夹。特地把这个文件夹删除了，clone重新下载、配置config、包括用抓包工具重新弄cookie，配置成功后，git pull后，还用yarn install后，手动成功了，crontab自动也实现正常，但就是接二连三收到service酱的cookie失效通知。

**Comment by EvineDeng** [comment]
> 我只有一个脚本，~/jd文件夹。特地把这个文件夹删除了，clone重新下载、配置config、包括用抓包工具重新弄cookie，配置成功后，git pull后，还用yarn install后，手动成功了，crontab自动也实现正常，但就是接二连三收到service酱的cookie失效通知。

一，存在随机延迟，这个要考虑进去，二，serverchan是不是会滞后发消息，也要考虑进去。这个与我脚本是没啥关系的。

**Comment by hacken156026692** [comment]
好的，我只是反映这个现象罢了。不影响实际使用。谢谢大佬的回复！

**Comment by FanchangWang** [comment]
> > 每次收到这个 issue 的邮件提醒我都以为有谁提供好的代码方案了 🤣
> > 这代码真难写，`diff` 命令在不同系统下的输出结果不同，折腾半天放弃了这个方案。
> > 改用 [node jsdiff（npm 模块）](https://github.com/kpdecker/jsdiff) 写，但是新旧对比的时候依然会有错误的情况，头大的很。
> > 忽略 # 注释的话，可能会导致跟后续任何一个版本的 `config.sh.sample` 注释对比都不一致，也可能导致手动添加的 # 注释丢失，反之也是一样的情况。
> > `jsdiff` 对比是顺序逐行的，手动进行代码块调整的时候，不一致的情况太多，都是 `配置项="值"` 的情况下大不了枚举所有 `配置项` 但是 `sh` 文件还能写 `shell` 代码，惆怅。。。
> > 即便忽略掉 `config.sh` 手动添加 `shell` 代码的可能性，也不排除官方脚本后续进行代码块顺序调整或主动添加更多 `shell` 代码，甚至变更某个 `配置项` 的名称，想死的节奏。。。
> > 再想要不要做个人工介入的方案，手动执行某个命令，比如 `bash config_diff.sh` 或 `node config_diff.js` 命令，然后对冲突的行内容进行人工提示，删除 or 保留 or 覆盖，虽然不能自动合并，但总比拉下来用各种文本对比工具弄完再上传方便点
> 
> 这也是我不愿意写这功能的原因。。。。在大量注释存在的前提下，这个功能难度非常高。
> 
> 并且，这个文件本来就允许用户自行按注释添加shell语句，改成适合自己的样子，达到不同时间赋值不一样的效果。这也就造成了每个人的配置文件差别实在太大了。哪些地方以新版覆盖旧版，哪些以旧版覆盖新版，行数对应关系是什么，哪里多了，哪里少了，难度还是很高的。毕竟这个配件文件是一个自定义程度非常高的文件，一百个人有一千种可能。
> 
> 综上，我不会提供此功能，仅提供通知，如果谁有能力的话，欢迎PR。

实在想不出什么方法，只能折腾一个在线对比工具，已提 pr [#155 ](https://github.com/EvineDeng/jd-base/pull/155)

**Comment by avsba001** [comment]
> > > `config.sh` 里面还有 `shell` 语句，这种的不好跟 `config.sh.smaple` 对比是否发生变更，有什么好点的解决方案吗？
> > > 比如下面这段
> > > ```shell
> > > ################################## 定义东东萌宠是否静默运行（选填） ##################################
> > > ## 默认 "false"（不静默，发送推送通知消息），如想静默请修改为 true
> > > ## 每次执行脚本通知太频繁了，改成只在周三和周六中午那一次运行时发送通知提醒
> > > ## 除掉上述提及时间之外，均设置为 true，静默不发通知
> > > ## 特别说明：针对北京时间有效。
> > > if [ $(date "+%w") -eq 6 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
> > >   export PET_NOTIFY_CONTROL="false"
> > > elif [ $(date "+%w") -eq 3 ] && [ $(date "+%H") -ge 9 ] && [ $(date "+%H") -lt 14 ]; then
> > >   export PET_NOTIFY_CONTROL="false"
> > > else
> > >   export PET_NOTIFY_CONTROL="true"
> > > fi
> > > ```
> > 
> > 
> > 一般系统默认带diff命令，可以参考。
> 
> 确定用 diff 做功能了，流程如下
> 
> * `diff config.sh config.sh.sample`
> * 根据 `diff` 结果确定变更行，格式有
>   
>   * `460a456` 单行变单行
>   * `391c377,378` 单行变多行
>   * `236,247c234` 多行变单行
>   * `257,263c249,254` 多行变多行
> * 过滤变更行内容，排除『# 开头的注释行』、『空行』
>   
>   * 注意事项如下
>   * 对比结果左右两侧都需要过滤
>   * 当左右两侧过滤的行数不一致时，注意行数进行相应累加或减少
> * 定位其余变更内容，将『> 』`config.sh.sample` 所在行删除，将『< 』`config.sh` 所在行插入 `config.sh.sample` 删除行位置
>   
>   * 注意事项如下
>   * 如果 『< 』行内容非最后一行，且无 `\n` 换行符，需增加 `\n` 换行符
>   * 当 `删除行` 与 `插入行` 数量不一致时，注意行数进行相应累加或减少
> * 备份 `config.sh` 文件
>   
>   * `[ ! -d config_bak ] && mkdir config_bak`
>   * `mv config.sh config_bak/config.sh_$(date "+%Y-%m-%d-%H-%M-%S")`
> * 重命名 `config.sh.sample` 文件 `mv config.sh.sample config.sh`

本人不会写代码，但是想提供一个思路，不知道是否可行

**Comment by avsba001** [comment]
> > > 每次收到这个 issue 的邮件提醒我都以为有谁提供好的代码方案了 🤣
> > > 这代码真难写，`diff` 命令在不同系统下的输出结果不同，折腾半天放弃了这个方案。
> > > 改用 [node jsdiff（npm 模块）](https://github.com/kpdecker/jsdiff) 写，但是新旧对比的时候依然会有错误的情况，头大的很。
> > > 忽略 # 注释的话，可能会导致跟后续任何一个版本的 `config.sh.sample` 注释对比都不一致，也可能导致手动添加的 # 注释丢失，反之也是一样的情况。
> > > `jsdiff` 对比是顺序逐行的，手动进行代码块调整的时候，不一致的情况太多，都是 `配置项="值"` 的情况下大不了枚举所有 `配置项` 但是 `sh` 文件还能写 `shell` 代码，惆怅。。。
> > > 即便忽略掉 `config.sh` 手动添加 `shell` 代码的可能性，也不排除官方脚本后续进行代码块顺序调整或主动添加更多 `shell` 代码，甚至变更某个 `配置项` 的名称，想死的节奏。。。
> > > 再想要不要做个人工介入的方案，手动执行某个命令，比如 `bash config_diff.sh` 或 `node config_diff.js` 命令，然后对冲突的行内容进行人工提示，删除 or 保留 or 覆盖，虽然不能自动合并，但总比拉下来用各种文本对比工具弄完再上传方便点
> > 
> > 
> > 这也是我不愿意写这功能的原因。。。。在大量注释存在的前提下，这个功能难度非常高。
> > 并且，这个文件本来就允许用户自行按注释添加shell语句，改成适合自己的样子，达到不同时间赋值不一样的效果。这也就造成了每个人的配置文件差别实在太大了。哪些地方以新版覆盖旧版，哪些以旧版覆盖新版，行数对应关系是什么，哪里多了，哪里少了，难度还是很高的。毕竟这个配件文件是一个自定义程度非常高的文件，一百个人有一千种可能。
> > 综上，我不会提供此功能，仅提供通知，如果谁有能力的话，欢迎PR。
> 
> 实在想不出什么方法，只能折腾一个在线对比工具，已提 pr [#155 ](https://github.com/EvineDeng/jd-base/pull/155)

本人不太懂代码，但是根据脚本思路，可不可以再外挂一个账户cookies配置文件呢，config.sh内置好引用，没有填写的返回空值，这样就不涉及对比问题了，cookies和互助码只有在新活动和过期才会去修改

**Comment by FanchangWang** [comment]
> > > > 每次收到这个 issue 的邮件提醒我都以为有谁提供好的代码方案了 🤣
> > > > 这代码真难写，`diff` 命令在不同系统下的输出结果不同，折腾半天放弃了这个方案。
> > > > 改用 [node jsdiff（npm 模块）](https://github.com/kpdecker/jsdiff) 写，但是新旧对比的时候依然会有错误的情况，头大的很。
> > > > 忽略 # 注释的话，可能会导致跟后续任何一个版本的 `config.sh.sample` 注释对比都不一致，也可能导致手动添加的 # 注释丢失，反之也是一样的情况。
> > > > `jsdiff` 对比是顺序逐行的，手动进行代码块调整的时候，不一致的情况太多，都是 `配置项="值"` 的情况下大不了枚举所有 `配置项` 但是 `sh` 文件还能写 `shell` 代码，惆怅。。。
> > > > 即便忽略掉 `config.sh` 手动添加 `shell` 代码的可能性，也不排除官方脚本后续进行代码块顺序调整或主动添加更多 `shell` 代码，甚至变更某个 `配置项` 的名称，想死的节奏。。。
> > > > 再想要不要做个人工介入的方案，手动执行某个命令，比如 `bash config_diff.sh` 或 `node config_diff.js` 命令，然后对冲突的行内容进行人工提示，删除 or 保留 or 覆盖，虽然不能自动合并，但总比拉下来用各种文本对比工具弄完再上传方便点
> > > 
> > > 
> > > 这也是我不愿意写这功能的原因。。。。在大量注释存在的前提下，这个功能难度非常高。
> > > 并且，这个文件本来就允许用户自行按注释添加shell语句，改成适合自己的样子，达到不同时间赋值不一样的效果。这也就造成了每个人的配置文件差别实在太大了。哪些地方以新版覆盖旧版，哪些以旧版覆盖新版，行数对应关系是什么，哪里多了，哪里少了，难度还是很高的。毕竟这个配件文件是一个自定义程度非常高的文件，一百个人有一千种可能。
> > > 综上，我不会提供此功能，仅提供通知，如果谁有能力的话，欢迎PR。
> > 
> > 
> > 实在想不出什么方法，只能折腾一个在线对比工具，已提 pr [#155 ](https://github.com/EvineDeng/jd-base/pull/155)
> 
> 本人不太懂代码，但是根据脚本思路，可不可以再外挂一个账户cookies配置文件呢，config.sh内置好引用，没有填写的返回空值，这样就不涉及对比问题了，cookies和互助码只有在新活动和过期才会去修改

没啥区别，config.sh 除了 cookie 跟 互助码还有其他配置参数要改，这种方式解决不了问题

**Comment by EvineDeng** [comment]
我晚上测试好再merge代码。

**Comment by hacken156026692** [comment]
看到新功能，试了下，不行。确认一下，请问，安卓termux是否不支持挂机？

~/jd $ bash jd.sh hangup
~/jd $ nohup: redirecting stderr to stdout

谢谢大神！

**Comment by EvineDeng** [comment]
> 看到新功能，试了下，不行。确认一下，请问，安卓termux是否不支持挂机？
> 
> ~/jd $ bash jd.sh hangup
> ~/jd $ nohup: redirecting stderr to stdout
> 
> 谢谢大神！

行不行，你要看过jd_crazy_joy_coin的日志再说话。

**Comment by shange1993** [comment]
@EvineDeng 大佬，对比工具能否一直设置一直在线呢，反正用不了几兆内存

**Comment by EvineDeng** [comment]
> @EvineDeng 大佬，对比工具能否一直设置一直在线呢，反正用不了几兆内存

不知道常驻是否会自动刷新文件内容，还是一直是打开那一刻的文件的内容。

**Comment by shange1993** [comment]
> > @EvineDeng 大佬，对比工具能否一直设置一直在线呢，反正用不了几兆内存
> 
> 不知道常驻是否会自动刷新文件内容，还是一直是打开那一刻的文件的内容。

能做下实验测试吗，能自动刷新文件内容的话，就可以不用关闭了

**Comment by FanchangWang** [comment]
> > @EvineDeng 大佬，对比工具能否一直设置一直在线呢，反正用不了几兆内存
> 
> 不知道常驻是否会自动刷新文件内容，还是一直是打开那一刻的文件的内容。

常驻不会自动刷新文件内容，一直都是打开页面的那个，如果想看新的内容，需要手动刷新一下请求。

**Comment by FanchangWang** [comment]
http://ip:5678/diff  这个页面不需要一直打开，有需要的时候再浏览器打开就行，不需要加自动刷新的机制。

node diff.js 这个服务如果想一直跑的话，diy.sh 中自己启动一下然后不关闭就行了，这样随时都可以访问 http://ip:5678/diff  进行对比修改

**Comment by shange1993** [comment]
> > > @EvineDeng 大佬，对比工具能否一直设置一直在线呢，反正用不了几兆内存
> > 
> > 
> > 不知道常驻是否会自动刷新文件内容，还是一直是打开那一刻的文件的内容。
> 
> 常驻不会自动刷新文件内容，一直都是打开页面的那个，如果想看新的内容，需要手动刷新一下请求。
主要是每次要用的话，需要去docker里，设置node diff.js启动，我现在命令都复制保持下来了

**Comment by shange1993** [comment]
> http://ip:5678/diff 这个页面不需要一直打开，有需要的时候再浏览器打开就行，不需要加自动刷新的机制。
> 
> node diff.js 这个服务如果想一直跑的话，diy.sh 中自己启动一下然后不关闭就行了，这样随时都可以访问 http://ip:5678/diff 进行对比修改

对了，我要的就是这种效果

**Comment by EvineDeng** [comment]
> > http://ip:5678/diff 这个页面不需要一直打开，有需要的时候再浏览器打开就行，不需要加自动刷新的机制。
> > node diff.js 这个服务如果想一直跑的话，diy.sh 中自己启动一下然后不关闭就行了，这样随时都可以访问 http://ip:5678/diff 进行对比修改
> 
> 对了，我要的就是这种效果，就是需要这个服务一直启动，不是自动刷新，因为也不可能一直开这个页面，主要是如果每次要用的话，老是进后台用这个node diff.js 命令比较麻烦

你可以百度下screen或者nohup命令的用法，可以实现你的想法，目前暂时先不考虑随容器自动启用并常驻后台，后续再说吧。

**Comment by FanchangWang** [comment]
水平有限自动化合并工具搞不出来了，目前网页版的对比合并工具已上线，这个 issue 我就关闭了
