### ISSUE TITLE
WIN10 子系统 定时任务不生效

### ISSUE THREAD

**Issue by leave668** [EvineDeng/jd-base#137]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [Yes ] 没有类似的issue 

Q：是否阅读了常见问题
- [Yes ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [Yes ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：win10 子系统ubuntu 2004.2020.812.0

## 3. 按照以下哪个教程做的

- [Yes ] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：win10 子系统ubuntu无法定时运行脚本
 手动运行任何一个脚本都正常，就是定时的不生效。
本地环境用echo $PATH  查出来是/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
用which node 查出来是/usr/bin/node

在crontab.list 文件里面 修改了路径为  PATH=/usr/local/node/node-v12.8.1-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

或者/usr/bin/node:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

定时都不生效..

### (2) 详细日志
A：定时脚本不生效，无相关日志，其他情况正常

### (1) Node.js版本

A：v10.19.0

### (2) npm版本

A：6.14.4

### (3)npm install的日志

A：audited 205 packages in 2.371s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by EvineDeng** [comment]
权限问题，解决不了，不要使用Linux子系统。

**Comment by leave668** [comment]
> 权限问题，解决不了，不要使用Linux操作系统。
> 
> 你可以尝试在win10定时任务中添加定时任务，看看有用不有用。
-------------------------
好像可以了。默认的子系统**没有启用crontab**。

开启 cron.log 
sudo vim /etc/rsyslog.d/50-default.conf

将 cron 前面的注释符去掉

重启相关服务
sudo service rsyslog restart

sudo service cron restart

重启后发现 /var/log 下面有日志文件，然后 crontab 已经启动。

再设置定时，已经开始跑了。非常感谢大佬的帮助。现在用起来很方便了
