### ISSUE TITLE
git_pull.sh line:597 语法错误 '}'

### ISSUE THREAD

**Issue by Noo13-man** [EvineDeng/jd-base#14]
程序试运行报错为以下代码片段。

在docker下运行。

################################## 修改宠汪汪兑换京豆数量 ##################################
function Change_joyRewardName {
  case ${joyRewardName} in
    0)
      echo "${FileJoyReward}：禁用宠汪汪自动兑换京豆..."
      sed -i "s|let joyRewardName = 20;|let joyRewardName = ${joyRewardName};|g" ${FileJoyReward};;
    500 | 1000)
      echo "${FileJoyReward}：修改宠汪汪兑换京豆数量为：${joyRewardName}..."
      sed -i "s|let joyRewardName = 20;|let joyRewardName = ${joyRewardName};|g" ${FileJoyReward};;
    20)
      echo "${FileJoyReward}：宠汪汪兑换京豆数量保持默认值：20...";;
    *)
      echo "joyRewardName输入了错误值，宠汪汪兑换京豆数量保持默认值：20...";;
}
###########################################################################################

**Comment by EvineDeng** [comment]
已修复。

**Comment by Noo13-man** [comment]
> 已修复。

感谢开发者的辛苦付出
