### ISSUE TITLE
12月23日晚20点多更新错误造成bug，以致后面无法再继续更新脚本，解决办法附下

### ISSUE THREAD

**Issue by EvineDeng** [EvineDeng/jd-base#140]
12月23日晚20点多更新错误造成bug，有可能造成后面无法再自动更新脚本，如果发现存在此问题（现象是git_pull.log中没有新的日志内容了），解决办法附下：

如果是docker，在docker宿主机运行一下：`docker exec -it jd git pull`， 即可解决此问题。不过也因此建议docker用户一定要安装watchtower来自动更新，这样我会在出错后重新更新容器才让大家直接自动完成容器更新。

如果是物理机或手机termux，cd到脚本存放目录后运行一次：`git pull`， 即可解决此问题。

下次我一定先测试好没问题再发布，以避免类似问题发生。

**Comment by 1Shaun** [comment]
还是出现错误
/home/myid/jd/update.js:42
function Env(t,e){class s{constructor(t){this.env=t}send(t,e="GET"){t="string"==typeof t?{url:t}:t;let s=this.get;return"POST"===e&&(s=this.post),new Promise((e,i)=>{s.call(this,t,(t,s,r)=>{t?i(t):e(s)})})}get(t){return this.send.call(this.env,t)}post(t){return this.send.call(this.env,t,"POST")}}return new class{constructor(t,e){this.name=t,this.http=new s(this),this.data=null,this.dataFile="box.dat",this.logs=[],this.isMute=!1,this.isNeedRewrite=!1,this.logSeparator="\n",this.startTime=(new Date).getTime(),Object.assign(this,e),this.log("",`\ud83d\udd14${this.name}, \u5f00\u59cb!`)}isNode(){return"undefined"!=typeof module&&!!module.exports}isQuanX(){return"undefined"!=typeof $task}isSurge(){return"undefined"!=typeof $httpClient&&"undefined"==typeof $loon}isLoon(){return"undefined"!=typeof $loon}toObj(t,e=null){try{return JSON.parse(t)}catch{return e}}toStr(t,e=null){try{return JSON.stringify(t)}catch{return e}}getjson(t,e){let s=e;const i=this.getdata(t);if(i)try{s=JSON.parse(th

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by lonee6** [comment]
提示
Already up to date.
就是没影响吧？

**Comment by EvineDeng** [comment]
> 提示
> Already up to date.
> 就是没影响吧？

对。只是影响部分人了。

**Comment by yenping08** [comment]
辛苦了  建议可以出个自动更新配置

**Comment by EvineDeng** [comment]
> 辛苦了  建议可以出个自动更新配置

这个难度非常高，除非完全不要注释，那就很简单。

**Comment by zhongqiujie13** [comment]
输入这个命令修复后手动执行任何一个脚本都提示没有文件了
docker exec jd bash jd_bean_change now                          bash: jd_bean_change: No such file or directory

**Comment by zhugecheng** [comment]
辛苦了

**Comment by EvineDeng** [comment]
> 输入这个命令修复后手动执行任何一个脚本都提示没有文件了
> docker exec jd bash jd_bean_change now                          bash: jd_bean_change: No such file or directory
你这不对，应该是别的问题，jd.sh我压根就没动。你再提供详细的问题描述看看吧。

**Comment by zhongqiujie13** [comment]
> > 输入这个命令修复后手动执行任何一个脚本都提示没有文件了
> > docker exec jd bash jd_bean_change now                          bash: jd_bean_change: No such file or directory
> 
> 你这不对，应该是别的问题，jd.sh我压根就没动。你再提供详细的问题描述看看吧。

不能啊，更新前我手动还运行了一次没问题，更新后再运行就这样了

**Comment by EvineDeng** [comment]
> > > 输入这个命令修复后手动执行任何一个脚本都提示没有文件了
> > > docker exec jd bash jd_bean_change now                          bash: jd_bean_change: No such file or directory
> > 
> > 你这不对，应该是别的问题，jd.sh我压根就没动。你再提供详细的问题描述看看吧。
> 
> 不能啊，更新前我手动还运行了一次没问题，更新后再运行就这样了

报平台，或者再次运行git_pull.sh一次。

**Comment by zhongqiujie13** [comment]
> > > > 输入这个命令修复后手动执行任何一个脚本都提示没有文件了
> > > > docker exec jd bash jd_bean_change now                          bash: jd_bean_change: No such file or directory
> > > 
> > > 
> > > 你这不对，应该是别的问题，jd.sh我压根就没动。你再提供详细的问题描述看看吧。
> > 
> > 
> > 不能啊，更新前我手动还运行了一次没问题，更新后再运行就这样了
> 
> 你少输了jd。应该是docker exec -it jd bash jd xxx now

卧槽 是我傻了 我把容器都重新部署了还是不行 原来问题在这 我他妈了。。。。。。 怪不得更新前还好好的更新后就不行了 鼓捣了看半天。。。。谢谢大佬了

**Comment by cnfind** [comment]
大佬，容器里边的JS文件能编辑吗，比如JOY加助力码。

**Comment by infisz** [comment]
物理机 
git pull后最后这样，算正常了吗？

Fetching origin
HEAD is now at a280102 Merge pull request #428 from shylocks/master

js脚本更新完成...

**Comment by EvineDeng** [comment]
> 物理机 
> git pull后最后这样，算正常了吗？
> 
> Fetching origin
> HEAD is now at a280102 Merge pull request #428 from shylocks/master
> 
> js脚本更新完成...
> 

正常了

**Comment by EvineDeng** [comment]
> 大佬，容器里边的JS文件能编辑吗？比如JOY加助力码。编辑了会有影响不？
> 
> 

要更新必然会重置。建议启用EnbaleExtraShell。

**Comment by yangyangxing** [comment]
种豆得豆提供了互助码，也log显示获取到了互助码，但是互助的对象是代码里的互助码，是哪里有问题么？

**Comment by EvineDeng** [comment]
> 种豆得豆提供了互助码，也log显示获取到了互助码，但是互助的对象是代码里的互助码，是哪里有问题么？

MyBean和ForOtherBean两处都要填才有效，建议仔细阅读注释。

**Comment by yangyangxing** [comment]
> > 种豆得豆提供了互助码，也日志显示获取到了互助码，但是互助的对象是代码里的互助码，是哪里有问题么？
> 
> MyBean和ForOtherBean两处都要填才有效，建议仔细阅读注释。

我都填了，v2版本运行的很好，升级了v3后把隔离的“\@”调换为了@，像农场、工厂都可以，但是种豆得豆log中显示获取到了对应数量的互助码，但是互助对象不对

**Comment by EvineDeng** [comment]
> > > 种豆得豆提供了互助码，也日志显示获取到了互助码，但是互助的对象是代码里的互助码，是哪里有问题么？
> > 
> > MyBean和ForOtherBean两处都要填才有效，建议仔细阅读注释。
> 
> 我都填了，v2版本运行的很好，升级了v3后把隔离的“\@”调换为了@，像农场、工厂都可以，但是种豆得豆log中显示获取到了对应数量的互助码，但是互助对象不对

你可以把你这两个变量贴出来看看，另外，其实如果你助力完成你提供的账号以后机会还有的话，会给我助力。

**Comment by yangyangxing** [comment]
> > > > 种豆得豆提供了互助码，也日志显示获取到了互助码，但是互助的对象是代码里的互助码，是哪里有问题么？
> > > 
> > > 
> > > MyBean和ForOtherBean两处都要填才有效，建议仔细阅读注释。
> > 
> > 
> > 我都填了，v2版本运行的很好，升级了v3后把隔离的“ @”调换为了@，像农场，工厂都可以，但是种豆得豆log中显示获取到了对应数量的互助码，但是互助对象不对
> 
> 你可以把你这两个变量贴出来看看，另外，其实如果你助力完成你提供的账号以后机会还有的话，会给我助力。

################################## 定义种豆得豆每个人自己的互助码（选填） ##################################
## 种豆得豆每个Cookie自己的互助码，可以在运行一次种豆得豆脚本（jd_plantBean）后从日志中查看
## 约定：MyBean后面的编号为数字的是提供了Cookie的账号所对应的互助码，编号与Cookie编号一一对应，如MyBean1、MyBean2
## 约定：MyBean后面的编号为大写字母的是未提供Cookie的账号所对应的互助码（比如你和其他人交换助力时或者多容器之间相互助力时），如MyBeanA、MyBeanB
## 这里的码只是为了下面“定义种豆得豆要为哪些人助力”服务的
MyPlantBean1="mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea"
MyPlantBean2="mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa"
MyPlantBean3="olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq"
MyPlantBean4="4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa"
MyPlantBean5="olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy"
MyPlantBean6="e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy"
MyBeanA=""
MyBeanB=""


################################## 定义种豆得豆要为哪些人助力（选填） ##################################
## 1.每个Cookie要为谁助力，填入对应MyBean系列变量名即可，用 @ 分隔每个变量名
## 2.比如：ForOtherBean1="${MyBean2}@${MyBean6}@${MyBeanB}"，含义是Cookie1的账户将为Cookie2、Cookie6的账户以及没有提供Cookie只提供了互助码的B用户提供助力
## 3.Cookie定义了多少个，ForOtherBean系列变量就多少个有效（从编号1开始计）
## 4.可以不赋值，这种情况下，将自动随机给他人助力
ForOtherPlantBean1=mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
ForOtherPlantBean2=mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
ForOtherPlantBean3=mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
ForOtherPlantBean4=mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
ForOtherPlantBean5=mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
ForOtherPlantBean6=mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy

**Comment by EvineDeng** [comment]
> > > > > 种豆得豆提供了互助码，也日志显示获取到了互助码，但是互助的对象是代码里的互助码，是哪里有问题么？
> > > > 
> > > > 
> > > > MyBean和ForOtherBean两处都要填才有效，建议仔细阅读注释。
> > > 
> > > 
> > > 我都填了，v2版本运行的很好，升级了v3后把隔离的“ @”调换为了@，像农场，工厂都可以，但是种豆得豆log中显示获取到了对应数量的互助码，但是互助对象不对
> > 
> > 你可以把你这两个变量贴出来看看，另外，其实如果你助力完成你提供的账号以后机会还有的话，会给我助力。
> 
> ################################## 定义种豆得豆每个人自己的互助码（选填） ##################################
> ## 种豆得豆每个Cookie自己的互助码，可以在运行一次种豆得豆脚本（jd_plantBean）后从日志中查看
> ## 约定：MyBean后面的编号为数字的是提供了Cookie的账号所对应的互助码，编号与Cookie编号一一对应，如MyBean1、MyBean2
> ## 约定：MyBean后面的编号为大写字母的是未提供Cookie的账号所对应的互助码（比如你和其他人交换助力时或者多容器之间相互助力时），如MyBeanA、MyBeanB
> ## 这里的码只是为了下面“定义种豆得豆要为哪些人助力”服务的
> MyPlantBean1="mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea"
> MyPlantBean2="mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa"
> MyPlantBean3="olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq"
> MyPlantBean4="4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa"
> MyPlantBean5="olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy"
> MyPlantBean6="e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy"
> MyBeanA=""
> MyBeanB=""
> 
> 
> ################################## 定义种豆得豆要为哪些人助力（选填） ##################################
> ## 1.每个Cookie要为谁助力，填入对应MyBean系列变量名即可，用 @ 分隔每个变量名
> ## 2.比如：ForOtherBean1="${MyBean2}@${MyBean6}@${MyBeanB}"，含义是Cookie1的账户将为Cookie2、Cookie6的账户以及没有提供Cookie只提供了互助码的B用户提供助力
> ## 3.Cookie定义了多少个，ForOtherBean系列变量就多少个有效（从编号1开始计）
> ## 4.可以不赋值，这种情况下，将自动随机给他人助力
> ForOtherPlantBean1=mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
> ForOtherPlantBean2=mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
> ForOtherPlantBean3=mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
> ForOtherPlantBean4=mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
> ForOtherPlantBean5=mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
> ForOtherPlantBean6=mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea@mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa@olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq@4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa@olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy
> 

填得不对，建议仔细阅读注释。

**Comment by yangyangxing** [comment]
> > > > > > 种豆得豆提供了互助码，也日志显示获取到了互助码，但是互助的对象是代码里的互助码，是哪里有问题么？
> > > > > 
> > > > > 
> > > > > MyBean和ForOtherBean两处都要填才有效，建议仔细阅读注释。
> > > > 
> > > > 
> > > > 我都填了，v2版本运行的很好，升级了v3后把隔离的“ @”调换为了@，像农场，工厂都可以，但是种豆得豆log中显示获取到了对应数量的互助码，但是互助对象不对
> > > 
> > > 
> > > 你可以把你这两个变量贴出来看看，另外，其实如果你助力完成你提供的账号以后机会还有的话，会给我助力。
> > 
> > 
> > ##################################定义种豆得豆每个人自己的互助码（选填）＃ ################################
> > ## 种豆得豆每个Cookie自己的互助码，可以在运行一次种豆得豆脚本（jd_plantBean）后从日志中查看
> > ## 约定：MyBean后面的编号为数字的是提供了Cookie的账号所对应的互助码，编号与Cookie编号一一对应，如MyBean1，MyBean2
> > ## 约定：MyBean之后的编号为大写字母的是未提供Cookie的帐户所对应的互助码（例如你和其他人交换助力时或者多容器之间相互助力时），如MyBeanA，MyBeanB
> > ## 这里的码只是为了下面“定义种豆得豆要为某些人助力”服务的
> > MyPlantBean1 = “mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea” 
> > MyPlantBean2 = “mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa” 
> > MyPlantBean3 = “olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq” 
> > MyPlantBean4 = “4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa” 
> > MyPlantBean5 = “olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy” 
> > MyPlantBean6 = “e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy” 
> > MyBeanA = “” 
> > MyBeanB = “”
> > #################################定义种豆得豆要为某些人助力（选填）## ###############################
> > ## 1.每个Cookie要为谁助力，填入对应的MyBean系列变量名即可，用@分隔每个变量名
> > ## 2.类别：ForOtherBean1 =“ $ {MyBean2} @ $ {MyBean6} @ $ {MyBeanB}”，表示是Cookie1的帐户将为Cookie2，Cookie6的帐户以及没有提供Cookie只提供了互助码的B用户提供助力
> > ## 3.Cookie定义了多少个，ForOtherBean系列变量就多少个有效（从编号1开始计）
> > ## 4.可以不赋值，这种情况下，将自动随机给他人助力
> > ForOtherPlantBean1 = mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa @ olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq @ 4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa @ olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy @ e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy 
> > ForOtherPlantBean2 = mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea @ olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq @ 4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa @ olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy @ e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy 
> > ForOtherPlantBean3 = mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa @ mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea @ 4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa @ olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy @ e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy
> > ForOtherPlantBean4 = mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa @ mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea @ olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq @ olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy @ e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy 
> > ForOtherPlantBean5 = mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea @ mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa @ olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq @ 4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa @ e7lhibzb3zek3l3o2vhlbsypib2ehxq77hj2nmy 
> > ForOtherPlantBean6 = mlrdw3aw26j3x2zuwhi3odxua3swbtymofqiaea @ mlrdw3aw26j3xnptk4yriadyd3liii2ho6s5isa @ olmijoxgmjutyh2p3xuebrkufaflg4ntilmwvmq @ 4npkonnsy7xi3beb32uzjoe2y4upuapmpeq3zxa @ olmijoxgmjutznyibjw7srtkkfmw37v5h7pzhiy
> 
> 填得不对，建议仔细阅读注释。

哦哦，看明白了，知道了。但是其他的农场、工厂我也是这么填的，运行没什么问题，种豆得豆就不行了，那我都改成直接获取变量吧，不放原始互助码了，万分感谢大佬及时回复！！

**Comment by EvineDeng** [comment]
@yangyangxing 不知道你注意到最顶部的注释没有，所有变量值必须有双引号。

**Comment by yangyangxing** [comment]
> @yangyangxing 不知道你注意到最顶部的注释没有，所有变量值必须有双引号。

哈哈哈，抱歉，没注意，我是直接粘的v2的配置，这边也加上

**Comment by shange1993** [comment]
@EvineDeng 能不能增加https://qmsg.zendee.cn/ 里的QQ通知啊 https://cp.xuthus.cc/里的没办法用，QQ加不上

**Comment by EvineDeng** [comment]
> @EvineDeng 能不能增加https://qmsg.zendee.cn/ 里的QQ通知啊 https://cp.xuthus.cc/ 里的没办法用，QQ加不上  
> 希望大佬能加下

你可以pr到lxk0301仓库中。

**Comment by yangyangxing** [comment]
@EvineDeng 大佬要不要把jd_crazy_joy_coin加到自动任务里啊

**Comment by hacken156026692** [comment]
最近红包雨live redrain 经常不成功，如下


=====远程红包雨信息=====
下一场红包雨开始时间：Fri Dec 25 2020 23:00:00 GMT+0800 (Central Standard Time)
下一场红包雨结束时间：Fri Dec 25 2020 23:05:00 GMT+0800 (Central Standard Time)
远程红包雨配置获取错误，从本地读取配置


本地红包雨配置获取成功

******开始【京东账号1】*********

异常：{"msg":"活动太火爆，请稍后再试~","code":"0","subCode":"1"}

==============📣系统通知📣==============
直播红包雨
【京东账号1】
【24点直播红包雨】暂无红包雨

**Comment by EvineDeng** [comment]
> 最近红包雨live redrain 经常不成功，如下
> 
> 
> =====远程红包雨信息=====
> 下一场红包雨开始时间：Fri Dec 25 2020 23:00:00 GMT+0800 (Central Standard Time)
> 下一场红包雨结束时间：Fri Dec 25 2020 23:05:00 GMT+0800 (Central Standard Time)
> 远程红包雨配置获取错误，从本地读取配置
> 
> 
> 本地红包雨配置获取成功
> 
> ******开始【京东账号1】*********
> 
> 异常：{"msg":"活动太火爆，请稍后再试~","code":"0","subCode":"1"}
> 
> ==============📣系统通知📣==============
> 直播红包雨
> 【京东账号1】
> 【24点直播红包雨】暂无红包雨

你自己不会更新js脚本body不要怪脚本不好拿。
