### ISSUE TITLE
自动删除手动添加的脚本

### ISSUE THREAD

**Issue by 1Shaun** [EvineDeng/jd-base#141]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：
在crontab.list里手动增加了jd_crazy_joy_coin脚本，但是过一会提示我删除失效脚本通知，把jd_crazy_joy_coin这个脚本给删除了，以后这个脚本还会运行吗？如果想手动添加这个脚本应该怎么操作不自动删除呢？

### (2) 详细日志
A：
删除失效脚本通知
jd-base脚本成功删除失效的定时任务：

jd_crazy_joy_coin

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
这个脚本不在lxk大佬仓库docker/crontab_list.sh中，当AutoDelCron=true时，被判定为无效任务。

并且这个任务要挂机执行的，cron没意义。

**Comment by 1Shaun** [comment]
> 这个脚本以jd_开头，不在lxk大佬仓库docker/crontab_list.sh中，当AutoDelCron=true时，被判定为无效任务。
> 
> 脚本会将以jd_开头的任务判定为京东任务。
> 
> 并且这个任务要挂机执行的，cron没意义。

知道了，这个脚本执行一次就不会停止了吧，我看现在还在输出log日志

**Comment by EvineDeng** [comment]
> > 这个脚本以jd_开头，不在lxk大佬仓库docker/crontab_list.sh中，当AutoDelCron=true时，被判定为无效任务。
> > 
> > 脚本会将以jd_开头的任务判定为京东任务。
> > 
> > 并且这个任务要挂机执行的，cron没意义。
> 
> 知道了，这个脚本执行一次就不会停止了吧，我看现在还在输出log日志

对，所以我说加cron没意义。

**Comment by 1Shaun** [comment]
> > > 这个脚本以jd_开头，不在lxk大佬仓库docker/crontab_list.sh中，当AutoDelCron=true时，被判定为无效任务。
> > > 脚本会将以jd_开头的任务判定为京东任务。
> > > 并且这个任务要挂机执行的，cron没意义。
> > 
> > 
> > 知道了，这个脚本执行一次就不会停止了吧，我看现在还在输出log日志
> 
> 对，所以我说加cron没意义。

知道了，谢谢大佬

**Comment by FanchangWang** [comment]
这个脚本如果要执行的话，可以在  diy.sh 中启动一次就可以吧

**Comment by EvineDeng** [comment]
> 这个脚本如果要执行的话，可以在  diy.sh 中启动一次就可以吧

可以。
