### ISSUE TITLE
请先获取京东账号一cookie

### ISSUE THREAD

**Issue by flyxinhua** [EvineDeng/jd-base#142]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：物理机  v3 , 从V3 开始，定时任务一直报这个错。

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：定时任务读取不到 cookie ,手动执行没有问题。
B:  删除XX日前的日志也不生效。设定是2天前。目前还停留着3天前的日志。

### (2) 详细日志
A：
天天提鹅
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/
B:
🔔东东农场, 开始!
开始获取配置文件

共0个京东账号

您提供了2个账号的农场助力码
==============📣系统通知📣==============
东东农场
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/

### (1) Node.js版本

A：v14.15.2

### (2) npm版本

A：6.14.9

### (3)npm install的日志

A：audited 205 packages in 3.142s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by EvineDeng** [comment]
你要不保存好config.sh后重头部署一下？你这问题不好定位。

**Comment by flyxinhua** [comment]
![image](https://user-images.githubusercontent.com/9856660/103052403-0b4e5b80-45d4-11eb-87b2-9e859866a071.png)
手动执行的时候就会提示上面这张图。
会不会是权限引起的 ？
如果没法解决。是不是可以提供一个命令手动执行完全部脚本 ？

**Comment by EvineDeng** [comment]
> ![image](https://user-images.githubusercontent.com/9856660/103052403-0b4e5b80-45d4-11eb-87b2-9e859866a071.png)
> 手动执行的时候就会提示上面这张图。
> 会不会是权限引起的 ？
> 如果没法解决。是不是可以提供一个命令手动执行完全部脚本 ？

你必然得同意。
