### ISSUE TITLE
jd_crazy_joy_coin 任务没有添加到自动任务的问题

### ISSUE THREAD

**Issue by wanghaolyj** [EvineDeng/jd-base#145]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：刚手动更新了git_pull.sh 发现在computer.list.sample 中没有 jd_crazy_joy_coin的定时任务
    crontab -l 中也没有发现此任务

**Comment by FanchangWang** [comment]
这个已经提交过类似的 issue 了，这个任务不是周期性执行的，是执行后就不会关闭，会一直执行。

如果你想执行这个，有两种方法

方法一：手动执行  `bash jd jd_crazy_joy_coin now > /dev/null &` 这个会创建后台任务一直跑

方法二：将 `bash jd jd_crazy_joy_coin now > /dev/null &`  放在 `diy.sh` 文件中，并在 `config.sh` 中配置 `EnableExtraShell="true"` ，这样没次执行 `git_pull.sh` 后都会自动创建对应任务

**Comment by ihuaer** [comment]
补充一下 bash jd.sh jd_crazy_joy now > /dev/null &

**Comment by ChadDongDongChen** [comment]
> 这个已经提交过类似的 issue 了，这个任务不是周期性执行的，是执行后就不会关闭，会一直执行。
> 
> 如果你想执行这个，有两种方法
> 
> 方法一：手动执行  `bash jd jd_crazy_joy_coin now > /dev/null &` 这个会创建后台任务一直跑
> 
> 方法二：将 `bash jd jd_crazy_joy_coin now > /dev/null &`  放在 `diy.sh` 文件中，并在 `config.sh` 中配置 `EnableExtraShell="true"` ，这样没次执行 `git_pull.sh` 后都会自动创建对应任务

大佬，这个用方法一跑起来之后怎么查看呀

**Comment by ChadDongDongChen** [comment]
> EnableExtraShell

执行这个命令后，不会一直跑，过一个小时左右进程就没了
