### ISSUE TITLE
[Termux]export_sharecodes.sh抓取不到本地日志

### ISSUE THREAD

**Issue by zhnlanf** [EvineDeng/jd-base#147]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- x 没有类似的issue 

Q：是否阅读了常见问题
- x 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- x 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- x Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：export_sharecodes.sh抓取不到本地日志,日志都是空的

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/58921007/103136732-e7873480-46fd-11eb-8149-cb4a07a612c1.png)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
先运行一次git_pull.sh更新下脚本，刚刚最新的一次pr就是修复这个问题的，更新脚本后再运行export_sharecodes.sh

**Comment by zhnlanf** [comment]
![image](https://user-images.githubusercontent.com/58921007/103136796-8b70e000-46fe-11eb-9900-1b95964ceca9.png)
还是不行

**Comment by EvineDeng** [comment]
你看看你本地的export_sharecodes.sh的内容是不是和github上的一样，我已经在termux上测试过了，完全能用了。

**Comment by b911ss** [comment]
终于有人提这个问题了，我用N1openwrt带的docker部署的这个，然后Watchtower 我也安装了，并没有export_sharecodes.sh这个文件自动下载下来，手动docker exec -it jd bash git_pull几次也没下载export_sharecodes.sh下来，我手动下载放到容器内，然后手动运行docker exec -it jd bash export_sharecodes获取助力码，提示bash: export_sharecodes: No such file or directory，老大救我这个小白

**Comment by EvineDeng** [comment]
> 终于有人提这个问题了，我用N1openwrt带的docker部署的这个，然后Watchtower 我也安装了，并没有export_sharecodes.sh这个文件自动下载下来，手动docker exec -it jd bash git_pull几次也没下载export_sharecodes.sh下来，我手动下载放到容器内，然后手动运行docker exec -it jd bash export_sharecodes获取助力码，提示bash: export_sharecodes: No such file or directory，老大救我这个小白

小白就去学docker，减少提问。这个脚本已经在docker容器中了，你只要按添加cron就好。

**Comment by b911ss** [comment]
> > 终于有人提这个问题了，我用N1openwrt带的docker部署的这个，然后守望台我也安装了，并没有export_sharecodes.sh这个文件自动下载下来，手动docker exec -it jd bash git_pull有时也没下载export_sharecodes。 sh下来，我手动下载放到容器内，然后手动运行docker exec -it jd bash export_sharecodes获取助力码，提示bash：export_sharecodes：没有这样的文件或目录，老大救我这个小白
> 
> 如果您更新了最新版本的容器的话，这个脚本已经在docker容器中了，您只要按添加cron就好。
> 
> 另外，你们都不看置顶issue的么？

确实是自己的问题，重新部署了一遍，解决了，谢谢老大

**Comment by zhnlanf** [comment]
> 你看看你本地的export_sharecodes.sh的内容是不是和github上的一样，我已经在termux上测试过了，完全能用了。

我把

> 你看看你本地的export_sharecodes.sh的内容是不是和github上的一样，我已经在termux上测试过了，完全能用了。

![image](https://user-images.githubusercontent.com/58921007/103147661-7e053580-4792-11eb-95e4-52aac64bd4d1.png)
我把这里P、E换了个位置，结果出互助码了
![image](https://user-images.githubusercontent.com/58921007/103147690-b99fff80-4792-11eb-90a1-cf885367d7ac.png)

**Comment by zhnlanf** [comment]
> 你看看你本地的export_sharecodes.sh的内容是不是和github上的一样，我已经在termux上测试过了，完全能用了。

![image](https://user-images.githubusercontent.com/58921007/103147786-801bc400-4793-11eb-98e8-a274ab0b17c5.png)
大佬，我把你编辑的“grep”命令""P"E"判别换了位置，结果可以出互助码
![image](https://user-images.githubusercontent.com/58921007/103147820-c07b4200-4793-11eb-871f-c3aeefccc93e.png)

**Comment by EvineDeng** [comment]
> > 你看看你本地的export_sharecodes.sh的内容是不是和github上的一样，我已经在termux上测试过了，完全能用了。
> 
> ![image](https://user-images.githubusercontent.com/58921007/103147786-801bc400-4793-11eb-98e8-a274ab0b17c5.png)
> 大佬，我把你编辑的“grep”命令""P"E"判别换了位置，结果可以出互助码
> ![image](https://user-images.githubusercontent.com/58921007/103147820-c07b4200-4793-11eb-871f-c3aeefccc93e.png)
> 

termux应该用-P啊

**Comment by zhnlanf** [comment]
> > > 你看看你本地的export_sharecodes.sh的内容是不是和github上的一样，我已经在termux上测试过了，完全能用了。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/58921007/103147786-801bc400-4793-11eb-98e8-a274ab0b17c5.png)
> > 大佬，我把你编辑的“grep”命令""P"E"判别换了位置，结果可以出互助码
> > ![image](https://user-images.githubusercontent.com/58921007/103147820-c07b4200-4793-11eb-871f-c3aeefccc93e.png)
> 
> termux应该用-P啊，-E识别不了

确实是-P，我把后面改成-P可以出码，是这里判别系统出问题，还是我的termux有问题

**Comment by EvineDeng** [comment]
我脚本是then后面是E，else后面是P，你调换顺序应该出不来吧。

**Comment by zhnlanf** [comment]
> 我脚本是then后面是E，else后面是P，你调换顺序应该出不来吧。

我按照上面图片里的顺序，可以出，把${opt}改成P也可以出
难道是我装了ssh的原因嘛

**Comment by EvineDeng** [comment]
这就不知道原因了。。

**Comment by zhnlanf** [comment]
> 这就不知道原因了。。

跑程序的的Termux里面没有ANDROID_RUNTIME_ROOT变量，另一部手机里面有，好奇怪
export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
加上这个变量就可以了

**Comment by EvineDeng** [comment]
> > 这就不知道原因了。。
> 
> 跑程序的的Termux里面没有ANDROID_RUNTIME_ROOT变量，另一部手机里面有，好奇怪
> export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
> 加上这个变量就可以了

你输入env，把结果给我。

**Comment by zhnlanf** [comment]
> > > 这就不知道原因了。。
> > 
> > 
> > 跑程序的的Termux里面没有ANDROID_RUNTIME_ROOT变量，另一部手机里面有，好奇怪
> > export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
> > 加上这个变量就可以了
> 
> 你输入env，把结果给我。
![image](https://user-images.githubusercontent.com/58921007/103149683-a434d080-47a6-11eb-91fa-125109867f89.png)
![image](https://user-images.githubusercontent.com/58921007/103149685-ab5bde80-47a6-11eb-838b-eb465aed1872.png)
![image](https://user-images.githubusercontent.com/58921007/103149688-ba429100-47a6-11eb-8c1b-97f99bc1a141.png)

**Comment by zhnlanf** [comment]
export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
用了这个命令，就多了一个变量
![Uploading image.png…]()

**Comment by zhnlanf** [comment]
export ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
添加变量，才会有
![image](https://user-images.githubusercontent.com/58921007/103149723-2624f980-47a7-11eb-9e13-8d71a9b8f3dd.png)

**Comment by EvineDeng** [comment]
那我判断是不是termux，改成ANDROID_RUNTIME_ROOT、ANDROID_ROOT这两个变量中，只要有一个不为空，则判断为termux吧。以前只靠一个ANDROID_RUNTIME_ROOT判断不能解决你这个问题。

**Comment by zhnlanf** [comment]
好的，谢谢了

**Comment by EvineDeng** [comment]
现在你先更新脚本，更新后再运行export_sharecodes.sh看看

**Comment by zhnlanf** [comment]
> 现在你先更新脚本，更新后再运行export_sharecodes.sh看看

完美了，谢谢大佬
