### ISSUE TITLE
部分任务无法正常退出，僵死在脚本结束处

### ISSUE THREAD

**Issue by askiter** [EvineDeng/jd-base#149]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：CentOS 8

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：定时任务会有部分任务无法正常退出，僵死在那里，根据日志看，这些任务也是执行完毕了的

### (2) 详细日志
A：
[root@xxoo JDScripts]# ps -ef | grep jd | grep -v grep | grep -v jd_crazy_joy_coin
root      225912  225911  0 Dec26 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_jdfactory
root      225985  225912  0 Dec26 ?        00:00:00 node jd_jdfactory.js
root      225986  225912  0 Dec26 ?        00:00:00 tee /disk2/JDScripts/log/jd_jdfactory/2020-12-26-23-36-01.log
root      227537  227536  0 00:11 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_rankingList
root      227606  227537  0 00:13 ?        00:00:00 node jd_rankingList.js
root      227607  227537  0 00:13 ?        00:00:00 tee /disk2/JDScripts/log/jd_rankingList/2020-12-27-00-13-51.log
root      229642  229636  0 01:15 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_lotteryMachine
root      229789  229642  0 01:16 ?        00:00:00 node jd_lotteryMachine.js
root      229790  229642  0 01:16 ?        00:00:00 tee /disk2/JDScripts/log/jd_lotteryMachine/2020-12-27-01-16-41.log
root      230374  230373  0 01:36 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_jdfactory
root      230443  230374  0 01:38 ?        00:00:00 node jd_jdfactory.js
root      230444  230374  0 01:38 ?        00:00:00 tee /disk2/JDScripts/log/jd_jdfactory/2020-12-27-01-38-11.log
root      231976  231975  0 02:36 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_jdfactory
root      232045  231976  0 02:38 ?        00:00:00 node jd_jdfactory.js
root      232046  231976  0 02:38 ?        00:00:00 tee /disk2/JDScripts/log/jd_jdfactory/2020-12-27-02-38-13.log
root      242453  242446  0 08:35 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_plantBean
root      242671  242670  0 08:36 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_jdfactory
root      242741  242453  0 08:37 ?        00:00:00 node jd_plantBean.js
root      242742  242453  0 08:37 ?        00:00:00 tee /disk2/JDScripts/log/jd_plantBean/2020-12-27-08-37-12.log
root      242754  242671  0 08:39 ?        00:00:00 node jd_jdfactory.js
root      242755  242671  0 08:39 ?        00:00:00 tee /disk2/JDScripts/log/jd_jdfactory/2020-12-27-08-39-47.log
root      244730  244723  0 09:35 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_plantBean
root      245017  245016  0 09:36 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_jdfactory
root      245086  245017  0 09:36 ?        00:00:00 node jd_jdfactory.js
root      245087  245017  0 09:36 ?        00:00:00 tee /disk2/JDScripts/log/jd_jdfactory/2020-12-27-09-36-13.log
root      245115  244730  0 09:39 ?        00:00:00 node jd_plantBean.js
root      245116  244730  0 09:39 ?        00:00:00 tee /disk2/JDScripts/log/jd_plantBean/2020-12-27-09-39-29.log
root      245970  245969  0 10:18 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_joy_run
root      246193  245970  0 10:21 ?        00:00:00 node jd_joy_run.js
root      246194  245970  0 10:21 ?        00:00:00 tee /disk2/JDScripts/log/jd_joy_run/2020-12-27-10-21-22.log
root      246476  246469  0 10:35 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_plantBean
root      246694  246693  0 10:36 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_jdfactory
root      246763  246476  0 10:36 ?        00:00:00 node jd_plantBean.js
root      246764  246476  0 10:36 ?        00:00:00 tee /disk2/JDScripts/log/jd_plantBean/2020-12-27-10-36-26.log
root      246776  246694  0 10:37 ?        00:00:00 node jd_jdfactory.js
root      246777  246694  0 10:37 ?        00:00:00 tee /disk2/JDScripts/log/jd_jdfactory/2020-12-27-10-37-29.log
root      248550  248549  0 11:36 ?        00:00:00 bash /disk2/JDScripts/jd.sh jd_jdfactory
root      248660  248550  0 11:39 ?        00:00:00 node jd_jdfactory.js
root      248661  248550  0 11:39 ?        00:00:00 tee /disk2/JDScripts/log/jd_jdfactory/2020-12-27-11-39-15.log
[root@xxoo JDScripts]# tail -20 log/jd_plantBean/2020-12-27-10-36-26.log
[逛逛会场]  1/1   1
[正品好药]  1/1   1
[健康好礼]  1/1   1
[浏览店铺]  4/4   1
[关注频道]  3/3   1
[挑选商品]  6/6   1
[每日签到]  1/1   1
[金融双签]  1/1   1
[免费水果]  1/1   1

【上期时间】12月14日-12月20日
【上期成长值】511
【上期兑换京豆】546个
【本期时间】12月21日-12月27日
【本期成长值】481
【助力您的好友】共5人

🔔京东种豆得豆, 结束! 🕛 90.151 秒

### (1) Node.js版本

A：v14.15.3

### (2) npm版本

A：v6.14.9
### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
与本shell无关，是你自己网络不好，导致无法访问国外的api接口服务器导致的。
