### ISSUE TITLE
京小超兑换京豆成功通知推送时京东账号显示为null

### ISSUE THREAD

**Issue by Htle000333** [EvineDeng/jd-base#152]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：环境：一个docker容器填写两个cookie，使用钉钉推送通知。
bug：京小超兑换京豆成功通知推送时京东账号显示为null，出现次数三天共六次
### (2) 详细日志
A：无错误日志

### (1) Node.js版本

A：docker v3版

### (2) npm版本

A：docker v3版

### (3)npm install的日志

A：

**Comment by Htle000333** [comment]
之前是用 jd-scripts-docker这个同样的环境推送是正常显示京东昵称的，换成现在这个jd-base之后同样的账号同样的钉钉群就出现推送时两个账号昵称皆为null，但目前我还不确定是容器的bug还是js脚本的bug

**Comment by EvineDeng** [comment]
js的，建议js那边提。
