### ISSUE TITLE
使用docker1部署运行后的日志里面没有显示自己的互助码

### ISSUE THREAD

**Issue by InfiniteYinux** [EvineDeng/jd-base#153]
RT，使用docker-compose pull更新脚本重启后的脚本日志里面没有自己本人的互助码，请问自己的互助码该如何获取

**Comment by EvineDeng** [comment]
你用docker1跑我docker2这里来提问？是来搞笑的？

**Comment by InfiniteYinux** [comment]
跑错场地了，溜了溜了
