### ISSUE TITLE
京东每日签到bug

### ISSUE THREAD

**Issue by abcdol** [EvineDeng/jd-base#154]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：签到脚本运行一次会签十几次，相关签到日志会打印十几遍，不知道是脚本本身的bug还是jd.sh的bug，麻烦大佬看一下

### (2) 详细日志
A：日志太长，贴在https://yiri.lanzous.com/iiZXxjuddej

### (1) Node.js版本

A：v12.18.3

### (2) npm版本

A：6.14.6

### (3)npm install的日志

A：

**Comment by abcdol** [comment]
版本是Android-v3,使用安卓终端部署，不好意思这个没填。。

**Comment by EvineDeng** [comment]
不清楚原因，这个看起来像是Nobyda大佬原始脚本哪里有问题，也可能是lxk0301哪里调用错了。。。。

**Comment by abcdol** [comment]
我用github action跑了一遍，日志是正常的，大佬帮忙看看吧，如果能定位修复的话就修复一下，主要请求次数多了怕黑号，麻烦了，谢谢😂

**Comment by EvineDeng** [comment]
你怕是不明白shell的原理，只要能出日志，就说明shell本身没有什么问题。。。。。问题只能是别的原因。

**Comment by abcdol** [comment]
好嘞 了解了😂
