### ISSUE TITLE
crontab.list文件修改问题

### ISSUE THREAD

**Issue by chenkid999** [EvineDeng/jd-base#156]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：如果我将默认目录/data/data/com.termux/files/home/storage/shared/jd替换为/data/data/com.termux/files/home/jd1，config文件夹下crontab.list定时任务也已经修改路径，如果下次脚本自动增加或者减少任务时，脚本是否会自动在config里的crontab.list文件增减定时任务并且匹配我修改过后的目录，还是需要我自己去sample文件夹手动复制一份termux.list.sample进行修改

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
脚本有这么傻吗？连自己在哪个目录都检测不出来还好意思自动增加定时任务？

**Comment by chenkid999** [comment]
> 脚本有这么傻吗？连自己在哪个目录都检测不出来还好意思自动增加定时任务？

是我疏忽大意了
