### ISSUE TITLE
新增的挂机任务一个行一个不行

### ISSUE THREAD

**Issue by sofs2005** [EvineDeng/jd-base#157]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [ x] Docker

### (1) 具体问题
A：我开了两个Docker实例，然后发现手工进docker执行挂机命令后都是好的，但是用crontab配置后，只有一个是正常的，另一个死活都没挂上，手工执行的话终端关闭好像挂机进程也就被关了，研究了半天没搞定

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by sofs2005** [comment]
我又观察了下，那个不行的应该也在跑，但不像另一个那样不停的在买狗，奇怪奇怪

**Comment by chenkid999** [comment]
其实可以通过bash jd.sh crazy_joy_coin now来手动执行挂机脚本，并且比较方便观察输出信息

**Comment by kissfast** [comment]
> bash jd.sh crazy_joy_coin now

这个方法不错，可以放在cron里面自动执行吗？

**Comment by sofs2005** [comment]
> > bash jd.sh crazy_joy_coin now
> 
> 这个方法不错，可以放在cron里面自动执行吗？

我就放在cronlist里面了，现在看下来是级别低的话会乱买狗，各个级别的狗都会买进来，级别高了以后会只买高级别的狗

**Comment by b911ss** [comment]
我输入docker exec -it jd bash jd hangup，查看进程，没有，等了一会也没有日志，还是手动执行吧

**Comment by b911ss** [comment]
docker exec -it jd bash jd hangup这个命令应该是执行定时关闭进程的作用，crontab之前没有定时启动疯狂joy，现在有了，上个结束进程后10分钟会启动疯狂joy，所以你要立马执行挂机脚本还得用docker exec jd bash jd jd_crazy_joy_coin now这个命令

**Comment by b911ss** [comment]
> docker exec -it jd bash jd hangup这个命令应该是执行定时关闭进程的作用，crontab之前没有定时启动疯狂joy，现在有了，上个结束进程后10分钟会启动疯狂joy，所以你要立马执行挂机脚本还得用docker exec jd bash jd jd_crazy_joy_coin now这个命令

应该是这样。。。

**Comment by tianya908** [comment]
apt install -y screen
screen -S
bash jd.sh crazy_joy_coin now
就可以一直挂在后台执行了
