### ISSUE TITLE
如何每次执行pull后自动执行挂机脚本

### ISSUE THREAD

**Issue by WoChen5770** [EvineDeng/jd-base#158]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x ] Docker

### (1) 具体问题
A：EnableExtraShell="true"的情况下，添加diy脚本diy.sh，内容为
#!/bin/bash
bash jd hangup > /dev/null &
在pull后，挂机脚本没有自动执行。
而进入容器后执行 . /jd/config/diy.sh 挂机脚本就执行了

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
实测有效，你不信你看你的jd_crazy_joy_coin日志。

**Comment by WoChen5770** [comment]
我就是执行docker exec -it jd bash git_pull
然而没有看到打印日志出来

**Comment by EvineDeng** [comment]
> 我就是执行docker exec -it jd bash git_pull
> 然而没有看到打印日志出来

你也可以看看你的小游戏中的金币会不会自动增加好了。

**Comment by WoChen5770** [comment]
> > 我就是执行docker exec -it jd bash git_pull
> > 然而没有看到打印日志出来
> 
> 你也可以看看你的小游戏中的金币会不会自动增加好了。

如果要测试，我步骤是不是先要把容器重启，然后执行git_pull，然后看有没有日志或者金币有没有增加？

**Comment by EvineDeng** [comment]
> > > 我就是执行docker exec -it jd bash git_pull
> > > 然而没有看到打印日志出来
> > 
> > 你也可以看看你的小游戏中的金币会不会自动增加好了。
> 
> 如果要测试，我步骤是不是先要把容器重启，然后执行git_pull，然后看有没有日志或者金币有没有增加？

不用重启

**Comment by WoChen5770** [comment]
如果我已经在执行挂机脚本，在运行bash jd hangup命令会先把旧的给关闭，然后执行新的？

**Comment by EvineDeng** [comment]
> 如果我已经在执行挂机脚本，在运行bash jd hangup命令会先把旧的给关闭，然后执行新的？

对

**Comment by WoChen5770** [comment]
> > 如果我已经在执行挂机脚本，在运行bash jd hangup命令会先把旧的给关闭，然后执行新的？
> 
> 对

好的，我等会试试。

**Comment by WoChen5770** [comment]
![image](https://user-images.githubusercontent.com/26268544/103390492-b2407380-4b4f-11eb-8534-bb1eed5b57de.png)
好像是没有执行新的， 旧的也没停止，还在运行，日志也是旧的挂机再一直打印。
如果重启容器再执行pull，就没有新的日志

**Comment by WoChen5770** [comment]
刚刚又有新的发现。把容器重启，日志全删再pull，会生成新的日志。但是日志内容是空的，看金币好像也没增加
![image](https://user-images.githubusercontent.com/26268544/103391609-4cef8100-4b55-11eb-874d-4c25deb4d30b.png)

**Comment by WoChen5770** [comment]
![image](https://user-images.githubusercontent.com/26268544/103392060-01d66d80-4b57-11eb-8bad-75d9538c5454.png)
隔了一会好像在挂机了。这个时间好像都是每个小时的55分，并不是pull后就马上执行挂机。
这个时间还推送了新增薅羊毛脚本通知

jd-base脚本成功添加新的定时任务：

jd_health
jd_jdh
jd_live_redrain
jd_ms_redrain
jr_sign

**Comment by sofs2005** [comment]
我做了个傻瓜式的设置，cron里面每小时跑一下挂机脚本。这样万一docker更新后最多一小时也能自己跑起来了

**Comment by WoChen5770** [comment]
这个issues关了，最近更新启动容器就执行挂机脚本

**Comment by EvineDeng** [comment]
> 这个issues关了，最近更新启动容器就执行挂机脚本

只是更新了脚本，晚上再更新容器
