### ISSUE TITLE
挂机任务无法启动

### ISSUE THREAD

**Issue by HIKARuRu1** [EvineDeng/jd-base#161]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：termux

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：bash git_pull.sh之后再bash jd.sh hangup提示nohup: redirecting stderr to stdout

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
你就不能翻译下这什么含义？

明明已经开始了。
