### ISSUE TITLE
[建议]请问能集成 whyour/hundun 这个脚本库吗？里面有些 lxk0301/jd_scripts 不存在的脚本

### ISSUE THREAD

**Issue by FanchangWang** [EvineDeng/jd-base#162]
请问能集成 whyour/hundun 这个脚本库吗？里面有些 lxk0301/jd_scripts 不存在的脚本，比如 京喜农场、财富岛 等

**Comment by EvineDeng** [comment]
添加额外脚本已经很容易了呀，为啥还要集成？

**Comment by FanchangWang** [comment]
主要是想要自动同步啥的，我现在是手动下载了 js 文件丢进目录的

**Comment by EvineDeng** [comment]
> 主要是想要自动同步啥的，我现在是手动下载了 js 文件丢进目录的

自动同步，也只能在执行git_pull.sh时额外wget下吧，意义不大，你可以加到diy.sh中。

**Comment by sofs2005** [comment]
> 主要是想要自动同步啥的，我现在是手动下载了 js 文件丢进目录的

那个怎么用的？小白没看懂。。
