### ISSUE TITLE
脚本自动运行，日志内容为空，脚本被自动运行几次就多几个空日志，手动运行正常

### ISSUE THREAD

**Issue by linlin6688** [EvineDeng/jd-base#163]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x  ] 没有类似的issue 

Q：是否阅读了常见问题
- [x  ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：centos8.0 

## 3. 按照以下哪个教程做的

- [ x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：自动运行无效，必须手动运行一个个脚本，手动运行脚本正常。日志会创建一个个文件夹，但是里面自动运行的项目是空日志。
      已把jd.sh的目录放入全局PATH了，现在在任意目录bash jd.sh 都会出现帮助信息

### (2) 详细日志
A：会创建文件夹，里面也有文件，但是都是空文件

### (1) Node.js版本

A：v14.15.3

### (2) npm版本

A：6.14.9

### (3)npm install的日志

A：audited 205 packages in 3.621s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by EvineDeng** [comment]
让你编辑crontab.list看仔细点，就是不愿意看。

**Comment by hacken156026692** [comment]
是不是log文件夹权限不够？
设置一下，权限改成777就行了！

**Comment by EvineDeng** [comment]
> 是不是log文件夹权限不够？
> 设置一下，权限改成777就行了！

不是，他都有日志的空文件了，很明显是centos的PATH的通病，没仔细阅读crontab.list的注释，没改PATH导致的。

**Comment by zhujoy** [comment]
> 是不是log文件夹权限不够？
> 设置一下，权限改成777就行了！

请教下，安卓机ternux执行jd_bean_sign，结果提示
检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件。是怎么解决的？

**Comment by hacken156026692** [comment]
没事啊，不用纠结这个Bounus，自动还是签到有豆的啊

**Comment by hacken156026692** [comment]
是不是放假了服务器不稳定，不时的运行git pull ，会出错

shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...

--------------------------------------------------------------

git_pull.sh: line 267: [: -eq: unary operator expected
js脚本更新失败，请检查原因或再次运行git_pull.sh...

git_pull.sh: line 278: [: -eq: unary operator expected
git_pull.sh: line 309: [: -eq: unary operator expected
git_pull.sh: line 316: [: -eq: unary operator expected
git_pull.sh: line 324: [: -eq: unary operator expected
git_pull.sh: line 346: [: -eq: unary operator expected

**Comment by bingyang519** [comment]
我的也是这样，只有joy的日志再不断增加，别的定时日志一个都没有。
（path已换本地的，没有问题）

**Comment by EvineDeng** [comment]
> 我的也是这样，只有joy的日志再不断增加，别的定时日志一个都没有。
> （path已换本地的，没有问题）

光改PATH没用，你还得把你的node npm git等等的路径加到PATH最前面，是读不懂crontab.list注释最前面两句话还是小学没毕业？

**Comment by EvineDeng** [comment]
> > > 我的也是这样，只有joy的日志再不断增加，别的定时日志一个都没有。
> > > （path已换本地的，没有问题）
> > 
> > 
> > 光改PATH没用，你还得把你的node npm git等等的路径加到PATH最前面，是读不懂crontab.list注释最前面两句话还是小学没毕业？
> 
> **大佬息怒...**
> 的确是这样改的...
> ![](https://camo.githubusercontent.com/6d45f2276ff627ba945f021e53b9d9a574dd9d9049c48f2fd260a89988072487/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032312f30312f386130616533396364613039653162322e706e67)

MacOS？要理解`node所在路径`的含义。。。比如node位于`/usr/local/bin`，那么所在路径是指`/usr/local/bin`，而不是`/usr/local/bin/node`，另外，MacOS的话你这种方式解决不了我就不知道是什么原因了。

**Comment by bingyang519** [comment]
> > > > 我的也是这样，只有joy的日志再不断增加，别的定时日志一个都没有。
> > > > （path已换本地的，没有问题）
> > > 
> > > 
> > > 光改PATH没用，你还得把你的node npm git等等的路径加到PATH最前面，是读不懂crontab.list注释最前面两句话还是小学没毕业？
> > 
> > 
> > **大佬息怒...**
> > 的确是这样改的...
> > ![](https://camo.githubusercontent.com/6d45f2276ff627ba945f021e53b9d9a574dd9d9049c48f2fd260a89988072487/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032312f30312f386130616533396364613039653162322e706e67)
> 
> MacOS？要理解`node所在路径`的含义。。。比如node位于`/usr/local/bin`，那么所在路径是指`/usr/local/bin`，而不是`/usr/local/bin/node`，改完以后要在config目录下用`crontab crontab.list`命令更新定时任务。另外，MacOS的话如果这种方式解决不了我就不知道是什么原因了。

机子是MacOs。之前我是没加到具体的/node，也用`crontab crontab.list`更新了任务，发现一直不行。刚刚试了试加到/node也重启了命令，发现还是不行。
不管怎么说，还是谢谢大佬。

**Comment by EvineDeng** [comment]
> > > > > 我的也是这样，只有joy的日志再不断增加，别的定时日志一个都没有。
> > > > > （path已换本地的，没有问题）
> > > > 
> > > > 
> > > > 光改PATH没用，你还得把你的node npm git等等的路径加到PATH最前面，是读不懂crontab.list注释最前面两句话还是小学没毕业？
> > > 
> > > 
> > > **大佬息怒...**
> > > 的确是这样改的...
> > > ![](https://camo.githubusercontent.com/6d45f2276ff627ba945f021e53b9d9a574dd9d9049c48f2fd260a89988072487/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032312f30312f386130616533396364613039653162322e706e67)
> > 
> > MacOS？要理解`node所在路径`的含义。。。比如node位于`/usr/local/bin`，那么所在路径是指`/usr/local/bin`，而不是`/usr/local/bin/node`，改完以后要在config目录下用`crontab crontab.list`命令更新定时任务。另外，MacOS的话如果这种方式解决不了我就不知道是什么原因了。
> 
> 机子是MacOs。之前我是没加到具体的/node，也用`crontab crontab.list`更新了任务，发现一直不行。刚刚试了试加到/node也重启了命令，发现还是不行。
> 不管怎么说，还是谢谢大佬。

能产生日志文件但是文件为空，肯定是PATH的问题。你再找找是不是有多个版本的node等等软件包。
