### ISSUE TITLE
多账号并发定时任务无法正常添加

### ISSUE THREAD

**Issue by chenkid999** [EvineDeng/jd-base#164]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：我按照说明里的**每一套脚本的定时任务都写一遍，即你几套账号，就要重复几次。记住，是每套脚本下的crontab.list全部要重复多次，每套脚本下的crontab.list要全部一模一样**这句话操作增加定时任务，会出现每个文件夹定时任务只出现了只增加当前文件夹定时任务的情况，而不是增加所有账号的定时任务
这是我填写的定时内容
[crontab.txt](https://github.com/EvineDeng/jd-base/files/5758993/crontab.txt)

### (2) 详细日志
A：这是两个文件夹下的git日志，159行到163行是脚本自动新增的任务
[jd1.log](https://github.com/EvineDeng/jd-base/files/5758988/jd1.log)
[jd2.log](https://github.com/EvineDeng/jd-base/files/5758989/jd2.log)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
目前的脚本对这个处理是有点麻烦，建议放弃多账号并发（目前多账号并发基本不会有什么多出来的好处），我这就把wiki改了。

**Comment by chenkid999** [comment]
> 目前的脚本对这个处理是有点麻烦，建议放弃多账号并发（目前多账号并发基本不会有什么多出来的好处），我8个账号都是一起跑的，我这就把wiki改了。

是否可以通过在config里填写已有文件夹路径的新变量，然后通过读取配置文件的变量来增减定时任务

**Comment by EvineDeng** [comment]
暂时不想弄物理机的此功能了，实在想要多账号并发，建议使用docker。

**Comment by wanghlstar** [comment]
多任务并发还是可以的吧~~ 我是每天早上搞一次~~ 
for script in $ListScripts
do
if [ "$script" == "jd_crazy_joy_coin" ]
then 
echo "jd_crazy_joy_coin later"
else
jnum=`ps -ef | grep $script | grep -v grep | wc -l `
if [ $jnum -le 0 ]
then
nohup sh ${JD_DIR}/jd.sh $script now >/dev/null 2>&1 &
fi
fi
done

joy_num=`ps -ef | grep jd_crazy_joy_coin | grep -v grep | wc -l `
if [ $joy_num -le 0 ]
then
sh ${JD_DIR}/jd.sh hangup >/dev/null 2>&1 &
fi
