### ISSUE TITLE
阿里云搭建后占用内存变多，

### ISSUE THREAD

**Issue by xunzha** [EvineDeng/jd-base#165]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：centos7

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：搭建完成后，通过宝塔面板查看占用内存从20%逐渐增多到80%，今天凌晨执行脚本时，造成服务器卡死，已是第二次出现这种情况。重启之后内存占用又回到20%，然后又逐渐增多。

### (2) 详细日志
A：

### (1) Node.js版本

A：v15.4.0

### (2) npm版本

A：v7.0.15

### (3)npm install的日志

A：

**Comment by FanchangWang** [comment]
你可以用 top 命令查一下哪个进程占用内存多

**Comment by xunzha** [comment]
> 你可以用 top 命令查一下哪个进程占用内存多


查询发现存在多个node进程，消耗内存均
为2.5%左右
![新建位图图像](https://user-images.githubusercontent.com/65440952/103469665-a3053400-4da2-11eb-97ba-6fa2a85ddf97.jpg)

**Comment by EvineDeng** [comment]
你这可能是进程不释放，centos问题是比较多。

**Comment by ilaotan** [comment]
> 你这可能是进程不释放，centos问题是比较多。
阿里云centos7 也有这毛病，不过感觉就几个脚本执行有问题
![Dingtalk_20210106113827](https://user-images.githubusercontent.com/6210438/103726390-cbe03000-5013-11eb-985e-384f9ebcaf61.jpg)
