### ISSUE TITLE
日志无法自动删除应该是属于bug

### ISSUE THREAD

**Issue by 544325999** [EvineDeng/jd-base#166]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Docker Centos7

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：config.sh设置脚本过期时间为2 log没有被删除
第二个 有些活动提示被风控有什么办法(日本服务器挂7 8个cookie)
### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
自己理解了cron的含义再来问这种弱智问题。

**Comment by 544325999** [comment]
![Uploading image.png…]()

**Comment by 544325999** [comment]
> 自己理解了cron的含义再来问这种弱智问题。

分时日月周   有啥难的          自动删除日志脚本有问题

**Comment by EvineDeng** [comment]
没有问题，你手动运行看看。

**Comment by EvineDeng** [comment]
所以你的cron是哪天启动删除任务呢？

**Comment by 544325999** [comment]
> 所以你的cron是哪天启动删除任务呢？

最起码昨天就改成了 RmLogDaysAgo="1"
之前是2 但是今天日志还在 2020年的 我都rm rf 手动删了

**Comment by EvineDeng** [comment]
那你明白你rm_log这一条cron是何时启动吗？

**Comment by 544325999** [comment]
> 那你明白你rm_log这一条cron是何时启动吗？

57 13 * * 6 bash rm_log >dev/null 2>&1
默认开启 没有注释啊

**Comment by EvineDeng** [comment]
> > 那你明白你rm_log这一条cron是何时启动吗？
> 
> 57 13 * * 6 bash rm_log >dev/null 2>&1
> 默认开启 没有注释啊

对呀，何时启动呢？你不是明白分时日月周的么？

**Comment by EvineDeng** [comment]
我都说了，自己理解了cron的含义再来问这种问题

**Comment by 544325999** [comment]
> > > 那你明白你rm_log这一条cron是何时启动吗？
> > 
> > 
> > 57 13 * * 6 bash rm_log >dev/null 2>&1
> > 默认开启 没有注释啊
> 
> 对呀，何时启动呢？你不是明白分时日月周的么？

周六删啊 淦 丢人了

**Comment by 544325999** [comment]
提示风控了是我国外服务器原因吗，

**Comment by EvineDeng** [comment]
> 提示风控了是我国外服务器原因吗，

账号问题，plus解千愁。

**Comment by 544325999** [comment]
57 8 * * * bash rm_log >dev/null 2>&1
RmLogDaysAgo="1"
还是不会删日志

**Comment by EvineDeng** [comment]
> 57 8 * * * bash rm_log >dev/null 2>&1
> RmLogDaysAgo="1"
> 还是不会删日志



crond日志呢？这个任务运行过没有？手动运行有没有效？

你这么一句话想让我怎么排故？用点脑子行不行。

**Comment by 544325999** [comment]
> > 57 8 * * * bash rm_log >dev/null 2>&1
> > RmLogDaysAgo="1"
> > 还是不会删日志
> 
> 什么平台？crond日志呢？这个任务运行过没有？手动运行有没有效？
> 
> 你这么一句话想让我怎么排故？用点脑子行不行。

你说的都对 就你有脑子

**Comment by 544325999** [comment]
老板把这个bug修好了 牛逼啊
