### ISSUE TITLE
每次自动或手动执行git_pull.sh脚本之后会自动添加一条重复的定时任务

### ISSUE THREAD

**Issue by MatthewDevelop** [EvineDeng/jd-base#167]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：centos 7.9

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：每次手动或者自动执行git_pull.sh脚本时候就会多出一个定时任务！
`0 0,18 * * * cd /scripts && node jd_bean_sign.js >> /scripts/logs/jd_bean_sign.log 2>&1`
![image](https://user-images.githubusercontent.com/23044942/103451094-b1981080-4cfa-11eb-8bf6-e6c2257851b4.png)

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
这一条有问题，你要手动添加，不要指望自动添加。如果你按照教程做，这里应该没有这个问题才对。

**Comment by EvineDeng** [comment]
不过我也把这个问题修复了，不管你有没有初始化crontab.list，都不再存在这个问题了。
