### ISSUE TITLE
新部署的docker无法自动更新临时脚本的自动任务设置

### ISSUE THREAD

**Issue by chenyitian2004** [EvineDeng/jd-base#170]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：centos7.3

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：新部署的docker无法自动更新临时脚本的自动任务设置，如jd_jdh的自动任务设置，但是刚添加的自动检测到新增的脚本可以正确部署自动任务，如jd_health（最后一行），使用`docker exec -it jd node diff.js`无法更新crontab.list

### (2) 详细日志
A：
`#更新lxk0301大佬的js脚本和EvineDeng的shell脚本`
55 5-23 * * * bash git_pull >> ${JD_DIR}/log/git_pull.log 2>&1

`# 删除 RmLogDaysAgo 指定天数以前的旧日志，不记录日志`
57 13 * * 6 bash rm_log >dev/null 2>&1

`# 每日导出所有互助码清单，注意东东小窝一天一变，本cron要在东东小窝运行过后才能运行，日志在log/export_sharecodes下`
48 5 * * * bash export_sharecodes

`# 运行挂机脚本，终止旧的挂机进程，启动新的进程`
33 13 * * * bash jd hangup

`# 运行lxk0301大佬的js脚本，仅作初始化用，AutoAddCron=true时，将自动添加短期任务，请保留任务名称中的前缀"jd_"，去掉后缀".js"`
`# 如果有些任务你不想运行，注释掉就好了，不要删除`
5 9 * * * bash jd jd_bean_change
28 5 * * * bash jd jd_bean_home
4 0,9 * * * bash jd jd_bean_sign
0,30 0 * * * bash jd jd_blueCoin
0 0 * * * bash jd jd_car
2 0 * * * bash jd jd_club_lottery
43 13 * * * bash jd jd_crazy_joy
36 9 * * * bash jd jd_ds  #限学生认证用户，如果你是，请自己解除注释
54 2-23/3 * * * bash jd jd_daily_egg
20 * * * * bash jd jd_dreamFactory
29 7,12,18 * * * bash jd jd_fruit
36 * * * * bash jd jd_jdfactory
14 11 * * * bash jd jd_jdzz
6 0,8,9,13,18,22 * * * bash jd jd_joy
*/20 0-22 * * * bash jd jd_joy_feedPets
0 0,8,12,16 * * * bash jd jd_joy_reward
18 10,13 * * * bash jd jd_joy_run
0 0,6 * * * bash jd jd_joy_steal
32 7 * * * bash jd jd_kd
13-23/5 13 * * * bash jd jd_live
15 1 * * * bash jd jd_lotteryMachine
40 */4 * * * bash jd jd_moneyTree
20 0,20 * * * bash jd jd_necklace
10 7,12,18 * * * bash jd jd_pet
25 * * * * bash jd jd_pigPet
35 7-22 * * * bash jd jd_plantBean
11 0 * * * bash jd jd_rankingList
1 1 * * * bash jd jd_redPacket
0 0 * * * bash jd jd_shop
16 0 * * * bash jd jd_small_home
35 */3 * * * bash jd jd_speed
9 1-23/5 * * * bash jd jd_superMarket
25 9 * * * bash jd jd_syj
44 5 * * 5 bash jd jd_unbind
45 23 * * * bash jd jd_unsubscribe
10 0 1-31 12 * bash jd jd_health

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
那你指出有哪个临时任务没有被自动添加？

**Comment by chenyitian2004** [comment]
> 那你指出有哪个临时任务没有被自动添加？

jd_jdh

**Comment by EvineDeng** [comment]
看完wiki再来问docker exec -it jd node diff.js为什么不能处理crontab.list

**Comment by EvineDeng** [comment]
> > 那你指出有哪个临时任务没有被自动添加？
> 
> jd_jdh

首次运行git_pull.sh不会自动添加定时任务

**Comment by chenyitian2004** [comment]
> > > 那你指出有哪个临时任务没有被自动添加？
> > 
> > 
> > jd_jdh
> 
> 首次运行git_pull.sh不会自动添加定时任务

那要运行什么指令添加呢

**Comment by EvineDeng** [comment]
刚才看错了，其实没有jdh任务了

**Comment by chenyitian2004** [comment]
> 刚才看错了，其实没有jdh任务了

京东官方活动写的是1.05结束

**Comment by chenyitian2004** [comment]
> 刚才看错了，其实没有jdh任务了

反而脚本昨晚新增的jd_health在jd_health.js里写的是2020.12.31结束。。。

**Comment by EvineDeng** [comment]
> > 刚才看错了，其实没有jdh任务了
> 
> 京东官方活动写的是1.05结束

那我建议你仔细读完config.sh的注释再来问
