### ISSUE TITLE
 Error: Cannot find module 'got' Require 

### ISSUE THREAD

**Issue by SuMaiKaDe** [EvineDeng/jd-base#171]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：
群晖系统，docker平台 最新版本
## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：
1、运行其他js文件，提示找不到got模块，看其他问题里边，找到了docker目录内是有node_moudle文件夹，里边有got文件，运行npm install后found 0 vulnerabilities，运行git_pull 后提示更新完成。
但运行js文件仍旧提示找不到模块。
2、种豆得豆总体是api请求失败 有办法解决吗

### (2) 详细日志
A：
❌ 企鹅读书, 失败! 原因: Error: Cannot find module 'got'
Require stack:
- /jd/config/qqreadnode.js!

### (1) Node.js版本

A：
14.15.3
### (2) npm版本

A：
6.14.9
### (3)npm install的日志

A：
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/tunnel failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
audited 205 packages in 10.98s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │      New patch version of npm available! 6.14.9 → 6.14.10       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.10   │
   │                Run npm install -g npm to update!                │
   │                                                                 │

**Comment by EvineDeng** [comment]
既然不懂js逻辑，建议放弃额外脚本。

**Comment by SuMaiKaDe** [comment]
> 既然不懂js逻辑，建议放弃额外脚本。
> 
> api请求失败就是失败，换个时间换个网络换个设备说不定就解决了。

谢谢
