### ISSUE TITLE
为什么不把/jd/scripts也映射出来？

### ISSUE THREAD

**Issue by lustime** [EvineDeng/jd-base#174]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：centos 7.9

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：如果你额外添加的脚本要用到lxk0301大佬仓库中的sendNotify.js来发送通知，或者要用到jdCookie.js来处理Cookie，建议你直接放在容器内的/jd/scripts文件夹下，按以下命令复制进容器（重新部署容器后要再次运行）
----------------------------------------------------------------------------------------------------------------------------------
把/jd/scripts这个映射出来也可以吧 不映射出来的话京东发现-看一看自己抓的包放到哪儿呀 也要docker cp嘛，docker小白问一下～

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
不为什么，会的人自己映射就好，不会的话我也不想解释。

**Comment by lustime** [comment]
> 不为什么，会的人自己映射就好，不会的话我也不想解释。

映射出来的话，新加的脚本直接放到映射文件夹里还需要重启容器嘛，还有京东发现-看一看自己抓的包

**Comment by EvineDeng** [comment]
这种问题，你自己试一试不就知道了。

**Comment by EvineDeng** [comment]
今天的更新满足你映射`/jd/scripts`出来的愿望了，按照最新的wiki使用最新的镜像即可。

**Comment by lustime** [comment]
> 今天的更新满足你映射`/jd/scripts`出来的愿望了，按照最新的wiki使用最新的镜像即可。

大佬威武～

**Comment by lustime** [comment]
> 今天的更新满足你映射`/jd/scripts`出来的愿望了，按照最新的wiki使用最新的镜像即可。

再请教个问题，用wathtower自动更新镜像，容器会做什么操作？会像第一次docker run一样拉lxk教程库嘛 这样的话就会报错，因为映射出来的script文件夹里已经有.git文件，代码库会拉不下来

**Comment by lustime** [comment]
> 今天的更新满足你映射`/jd/scripts`出来的愿望了，按照最新的wiki使用最新的镜像即可。

再请教个问题，用wathtower自动更新镜像，容器会做什么操作？会像第一次docker run一样拉lxk脚本库嘛 这样的话就会报错，因为映射出来的script文件夹里已经有.git目录，代码库会拉不下来。还是说不会做这个操作，我是在第一次部署时候代码没拉下来，把容器删了，第二次run时候拉lxk代码库就报错了。所以想到用watchtower更新镜像时候会不会有同样问题

**Comment by EvineDeng** [comment]
> > 今天的更新满足你映射`/jd/scripts`出来的愿望了，按照最新的wiki使用最新的镜像即可。
> 
> 再请教个问题，用wathtower自动更新镜像，容器会做什么操作？会像第一次docker run一样拉lxk脚本库嘛 这样的话就会报错，因为映射出来的script文件夹里已经有.git目录，代码库会拉不下来。还是说不会做这个操作，我是在第一次部署时候代码没拉下来，把容器删了，第二次run时候拉lxk代码库就报错了。所以想到用watchtower更新镜像时候会不会有同样问题

那是你瞎改js导致的，与watchtower压根没关系。

**Comment by Htle000333** [comment]
> > > 今天的更新满足你映射`/jd/scripts`出来的愿望了，按照最新的wiki使用最新的镜像即可。
> > 
> > 
> > 再请教个问题，用wathtower自动更新镜像，容器会做什么操作？会像第一次docker run一样拉lxk脚本库嘛 这样的话就会报错，因为映射出来的script文件夹里已经有.git目录，代码库会拉不下来。还是说不会做这个操作，我是在第一次部署时候代码没拉下来，把容器删了，第二次run时候拉lxk代码库就报错了。所以想到用watchtower更新镜像时候会不会有同样问题
> 
> 那是你瞎改js导致的，与有没有.git目录没关系，用昨天最新的镜像可以给你重置。

我发现用gitee镜像无法映射/jd/scripts，是不是我用旧版本的问题？

**Comment by EvineDeng** [comment]
> > > > 今天的更新满足你映射`/jd/scripts`出来的愿望了，按照最新的wiki使用最新的镜像即可。
> > > 
> > > 
> > > 再请教个问题，用wathtower自动更新镜像，容器会做什么操作？会像第一次docker run一样拉lxk脚本库嘛 这样的话就会报错，因为映射出来的script文件夹里已经有.git目录，代码库会拉不下来。还是说不会做这个操作，我是在第一次部署时候代码没拉下来，把容器删了，第二次run时候拉lxk代码库就报错了。所以想到用watchtower更新镜像时候会不会有同样问题
> > 
> > 那是你瞎改js导致的，与有没有.git目录没关系，用昨天最新的镜像可以给你重置。
> 
> 我发现用gitee镜像无法映射/jd/scripts，是不是我用旧版本的问题？

不然呢？

**Comment by Htle000333** [comment]
> > > > > 今天的更新满足你映射`/jd/scripts`出来的愿望了，按照最新的wiki使用最新的镜像即可。
> > > > 
> > > > 
> > > > 再请教个问题，用wathtower自动更新镜像，容器会做什么操作？会像第一次docker run一样拉lxk脚本库嘛 这样的话就会报错，因为映射出来的script文件夹里已经有.git目录，代码库会拉不下来。还是说不会做这个操作，我是在第一次部署时候代码没拉下来，把容器删了，第二次run时候拉lxk代码库就报错了。所以想到用watchtower更新镜像时候会不会有同样问题
> > > 
> > > 
> > > 那是你瞎改js导致的，与有没有.git目录没关系，用昨天最新的镜像可以给你重置。
> > 
> > 
> > 我发现用gitee镜像无法映射/jd/scripts，是不是我用旧版本的问题？
> 
> 不然呢？这种简单的问题自己试试不就行了...不要问

好的大哥，另外我发现之前钉钉推送显示为null也是使用了旧的上游库导致的问题
