### ISSUE TITLE
关于docker多容器并发不执行

### ISSUE THREAD

**Issue by SuMaiKaDe** [EvineDeng/jd-base#175]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：
群晖 docker
## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：
docker多账号并发，签到等部分脚本运行不正常。提示以下信息后，就不运行了。
### (2) 详细日志
A：
您的cookie选择的是用&隔开

====================共有6个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/1/5 上午12:04:07=====================

{"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1609776252010,"socket":1609776252010,"lookup":1609776252112,"error":1609776252130,"phases":{"wait":0,"dns":102,"total":120}}}
检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件

### (1) Node.js版本

A：
14.15
### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
与我脚本无关。

**Comment by SuMaiKaDe** [comment]
> 与我脚本无关，基本上是网络问题。

这是其中一个，就是容器多开，执行到一半，日志就没了，也就不执行了，跟容器多开有关系吗？
![Uploading IMG_20210105_200530.jpg…]()

**Comment by SuMaiKaDe** [comment]
> 与我脚本无关，基本上是网络问题。

这是其中一个，就是容器多开，执行到一半，日志就没了，也就不执行了，跟容器多开有关系吗？
![IMG_20210105_200530](https://user-images.githubusercontent.com/5207528/103644636-a7437400-4f91-11eb-8214-5fd083d5b949.jpg)

**Comment by EvineDeng** [comment]
> > 与我脚本无关，基本上是网络问题。
> 
> 这是其中一个，就是容器多开，执行到一半，日志就没了，也就不执行了，跟容器多开有关系吗？
> ![IMG_20210105_200530](https://user-images.githubusercontent.com/5207528/103644636-a7437400-4f91-11eb-8214-5fd083d5b949.jpg)

可能是因为容器被watchtower自动更新了吧，你可以看看watchtower的日志。

**Comment by SuMaiKaDe** [comment]
> > > 与我脚本无关，基本上是网络问题。
> > 
> > 
> > 这是其中一个，就是容器多开，执行到一半，日志就没了，也就不执行了，跟容器多开有关系吗？
> > ![IMG_20210105_200530](https://user-images.githubusercontent.com/5207528/103644636-a7437400-4f91-11eb-8214-5fd083d5b949.jpg)
> 
> 可能是因为刚好在那个时候，容器被watchtower自动更新了吧，你可以看看watchtower的日志。

看了下wtachower日志，他是上午更新的。应该没影响到
也搞不懂是不是容器多并发引起的

**Comment by SuMaiKaDe** [comment]
> > > 与我脚本无关，基本上是网络问题。
> > 
> > 
> > 这是其中一个，就是容器多开，执行到一半，日志就没了，也就不执行了，跟容器多开有关系吗？
> > ![IMG_20210105_200530](https://user-images.githubusercontent.com/5207528/103644636-a7437400-4f91-11eb-8214-5fd083d5b949.jpg)
> 
> 可能是因为刚好在那个时候，容器被watchtower自动更新了吧，你可以看看watchtower的日志。

我今天看了一下，多数情况下，未执行完的后边都同时有其他任务执行，是不是因为执行其他js的时候，将上一个js打断了？

**Comment by EvineDeng** [comment]
> > > > 与我脚本无关，基本上是网络问题。
> > > 
> > > 
> > > 这是其中一个，就是容器多开，执行到一半，日志就没了，也就不执行了，跟容器多开有关系吗？
> > > ![IMG_20210105_200530](https://user-images.githubusercontent.com/5207528/103644636-a7437400-4f91-11eb-8214-5fd083d5b949.jpg)
> > 
> > 可能是因为刚好在那个时候，容器被watchtower自动更新了吧，你可以看看watchtower的日志。
> 
> 我今天看了一下，多数情况下，未执行完的后边都同时有其他任务执行，是不是因为执行其他js的时候，将上一个js打断了？

不会，各容器之间完全无影响，你应该考虑是不是给容器设置了资源限制。

**Comment by SuMaiKaDe** [comment]
> > > > > 与我脚本无关，基本上是网络问题。
> > > > 
> > > > 
> > > > 这是其中一个，就是容器多开，执行到一半，日志就没了，也就不执行了，跟容器多开有关系吗？
> > > > ![IMG_20210105_200530](https://user-images.githubusercontent.com/5207528/103644636-a7437400-4f91-11eb-8214-5fd083d5b949.jpg)
> > > 
> > > 
> > > 可能是因为刚好在那个时候，容器被watchtower自动更新了吧，你可以看看watchtower的日志。
> > 
> > 
> > 我今天看了一下，多数情况下，未执行完的后边都同时有其他任务执行，是不是因为执行其他js的时候，将上一个js打断了？
> 
> 不会，各容器之间完全无影响，一个容器内的各个进程之间影响也不大，不过你应该考虑是不是给容器设置了资源限制。

没有的，我用户的群晖的docker，没做任何的资源限制

**Comment by EvineDeng** [comment]
群晖啊，不好说。

**Comment by SuMaiKaDe** [comment]
> 群晖啊，不好说。

群晖的docker有限制吗？还是说群晖的这个兼容性不好？

**Comment by EvineDeng** [comment]
> > 群晖啊，不好说。
> 
> 群晖的docker有限制吗？还是说群晖的这个兼容性不好？

不了解，不知道群晖会不会干些啥。
