### ISSUE TITLE
写一个qq阅读的抓包教程记录下，赠与有缘人

### ISSUE THREAD

**Issue by ilaotan** [EvineDeng/jd-base#176]
ios可以忽略哈，直接圈x就能抓吧。
首先，阅读大佬的代码 https://github.com/lxk0301/jd_scripts/blob/master/backUp/qqread.js
根据前面那几十行的提示，知道要通过抓包，获取3个变量。
写道这里，我才想到，这个教程注定是给少数人用的，本身抓包这件事就够折腾的，各位自行解决吧。（安卓7.x以后不能抓https的包了，要root后装中间人证书。）我本人是root后使用charles+证书，这里不做探索。手机app版本的抓包我没试过。。这里我只讲抓包后要拿的数据。
根据提示 手机qq 打开网址 https://m.q.qq.com/a/s/d3eacc70120b9a37e46bad408c0c4c2a
开启抓包软件，找到一本书，阅读几秒（小于10秒）退出。
上抓包软件中扒拉请求url
找到url为https://mqqapi.reader.qq.com/log/v4/mqq/track的请求。把请求内容 {"common":{"appid":1450024393,"areaid":5, 开头 "bookStatus":0,"bookPay":0,"ui_pos":0}]}结尾的json保存下来备用。
找到url https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid ，把整行复制下来，包含跟在后面的那一坨参数。
还是这条记录，拷贝出header中的部分数据，手动改成json形式。
这3个变量 改完后的效果 (敏感字段已打码成10086)

`export QQ_READ_HEADER_VAL='{"common":{"appid":10086,"areaid":5,"qq_ver":"8.2.8","os_ver":"Android 10","mp_ver":"0.41.0","mpos_ver":"1.12.1","brand":"Redmi","model":"Redmi Note 8 Pro","screenWidth":393,"screenHeight":835,"windowWidth":393,"windowHeight":781,"openid":"10086","guid":10086,"session":"10086","scene":2014,"source":-1,"hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"sign_window_close_I","click2":"sign_window_button_C","route":"pages/book-shelf/index","refer":-1,"options":{},"dis":1609813057401,"ext6":29,"eventID":"bookShelf_myshelf_myBook_C","type":"click","bid":10086,"bookStatus":0,"bookPay":0,"ui_pos":0}]}'
`
`export QQ_READ_TIME_URL_VAL="https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=10086&refer=-1&bid=10086&readTime=5571&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A5571%2C%22pay_status%22%3A0%7D%7D%5D&sp=-1"
`
`export QQ_READ_TIME_HEADER_VAL='{"Cookie":"ywguid=10086;ywkey=0;platform=android;channel=mqqmina;mpVersion=0.41.0;qq_ver=8.2.8;os_ver=Android 10;mpos_ver=1.12.1;platform=android;openid=xxx","Accept":"*/*","Referer":"https://appservice.qq.com/1110657249/0.41.0/page-frame.html","Connection":"close","User-Agent":"Mozilla/5.0 (Linux; Android 10; Redmi Note 8 Pro Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045438 Mobile Safari/537.36 QQ/MiniApp","mpversion":"0.41.0","Host":"mqqapi.reader.qq.com","ywsession":"10086","Accept-Language":"zh-cn","Content-Length":"0","Content-Type":"application/json"}'`

把以上这3个字段，放到config.sh的末尾即可。
然后运行 bash /home/myid/jd/jd.sh qqread now 就能跑。
添加自定义定时任务

`0,12,24,36,48 * * * * bash /home/myid/jd/jd.sh qqread now`

完活

**Comment by EvineDeng** [comment]
你这个cron可以简写这`*/12 * * * *`，不过qqread最好的应该是`*/10 * * * *`

**Comment by ilaotan** [comment]
> 你这个cron可以简写这`*/12 * * * *`，不过qqread最好的应该是`*/10 * * * *`
好滴大佬

**Comment by ilaotan** [comment]
好滴大佬

**Comment by lustime** [comment]
> ios可以忽略哈，直接圈x就能抓吧。
> 首先，阅读大佬的代码 https://github.com/lxk0301/jd_scripts/blob/master/backUp/qqread.js
> 根据前面那几十行的提示，知道要通过抓包，获取3个变量。
> 写道这里，我才想到，这个教程注定是给少数人用的，本身抓包这件事就够折腾的，各位自行解决吧。（安卓7.x以后不能抓https的包了，要root后装中间人证书。）我本人是root后使用charles+证书，这里不做探索。手机app版本的抓包我没试过。。这里我只讲抓包后要拿的数据。
> 根据提示 手机qq 打开网址 https://m.q.qq.com/a/s/d3eacc70120b9a37e46bad408c0c4c2a
> 开启抓包软件，找到一本书，阅读几秒（小于10秒）退出。
> 上抓包软件中扒拉请求url
> 找到url为[https://mqqapi.reader.qq.com/log/v4/mqq/track的请求。把请求内容](https://mqqapi.reader.qq.com/log/v4/mqq/track%E7%9A%84%E8%AF%B7%E6%B1%82%E3%80%82%E6%8A%8A%E8%AF%B7%E6%B1%82%E5%86%85%E5%AE%B9) {"common":{"appid":1450024393,"areaid":5, 开头 "bookStatus":0,"bookPay":0,"ui_pos":0}]}结尾的json保存下来备用。
> 找到url https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid ，把整行复制下来，包含跟在后面的那一坨参数。
> 还是这条记录，拷贝出header中的部分数据，手动改成json形式。
> 这3个变量 改完后的效果 (敏感字段已打码成10086)
> 
> `export QQ_READ_HEADER_VAL='{"common":{"appid":10086,"areaid":5,"qq_ver":"8.2.8","os_ver":"Android 10","mp_ver":"0.41.0","mpos_ver":"1.12.1","brand":"Redmi","model":"Redmi Note 8 Pro","screenWidth":393,"screenHeight":835,"windowWidth":393,"windowHeight":781,"openid":"10086","guid":10086,"session":"10086","scene":2014,"source":-1,"hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"sign_window_close_I","click2":"sign_window_button_C","route":"pages/book-shelf/index","refer":-1,"options":{},"dis":1609813057401,"ext6":29,"eventID":"bookShelf_myshelf_myBook_C","type":"click","bid":10086,"bookStatus":0,"bookPay":0,"ui_pos":0}]}' `
> `export QQ_READ_TIME_URL_VAL="https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=10086&refer=-1&bid=10086&readTime=5571&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A5571%2C%22pay_status%22%3A0%7D%7D%5D&sp=-1" `
> `export QQ_READ_TIME_HEADER_VAL='{"Cookie":"ywguid=10086;ywkey=0;platform=android;channel=mqqmina;mpVersion=0.41.0;qq_ver=8.2.8;os_ver=Android 10;mpos_ver=1.12.1;platform=android;openid=xxx","Accept":"*/*","Referer":"https://appservice.qq.com/1110657249/0.41.0/page-frame.html","Connection":"close","User-Agent":"Mozilla/5.0 (Linux; Android 10; Redmi Note 8 Pro Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045438 Mobile Safari/537.36 QQ/MiniApp","mpversion":"0.41.0","Host":"mqqapi.reader.qq.com","ywsession":"10086","Accept-Language":"zh-cn","Content-Length":"0","Content-Type":"application/json"}'`
> 
> 把以上这3个字段，放到config.sh的末尾即可。
> 然后运行 bash /home/myid/jd/jd.sh qqread now 就能跑。
> 添加自定义定时任务
> 
> `0,12,24,36,48 * * * * bash /home/myid/jd/jd.sh qqread now`
> 
> 完活
 @ilaotan感谢大佬，
用httpcatch抓到了上面的请求，顺便问一下 大佬是怎么知道抓上面这几个请求的？qqread里没有描述。。盼复

**Comment by ilaotan** [comment]
@lustime 大佬的js文件里有这么两行
`#企鹅读书获取更新body
https:\/\/mqqapi\.reader\.qq\.com\/log\/v4\/mqq\/track url script-request-body https://raw.githubusercontent.com/lxk0301/jd_scripts/master/backUp/qqread.js
#企鹅读书获取时长cookie
https:\/\/mqqapi\.reader\.qq\.com\/mqq\/addReadTimeWithBid? url script-request-header https://raw.githubusercontent.com/lxk0301/jd_scripts/master/backUp/qqread.js`
这就是给圈x用的规则表达式，根据这个，就找到这俩请求了。剩下的就是乱试呗，我是没想到header要用json形式，试了几次报错才知道。

**Comment by ilaotan** [comment]
第二天 金币获取都成1了。。。不知道咋回事 难道要重新获取cookie

**Comment by lustime** [comment]
> 第二天 金币获取都成1了。。。不知道咋回事 难道要重新获取cookie

确实 过了零点就变成1了

**Comment by ilaotan** [comment]
> > 第二天 金币获取都成1了。。。不知道咋回事 难道要重新获取cookie
> 
> 确实 过了零点就变成1了

tg里有人说重新看本书 重新获取下参数。

**Comment by lustime** [comment]
> > > 第二天 金币获取都成1了。。。不知道咋回事 难道要重新获取cookie
> > 
> > 
> > 确实 过了零点就变成1了
> 
> tg里有人说重新看本书 重新获取下参数。

@ilaotan 那每天都要这样搞有点累呀～～～大佬研究出来好办法踢我一下

**Comment by huangzi959** [comment]
这个金币有什么用

**Comment by ilaotan** [comment]
阅读已经晾了 大面积封号了 大家有缘再见

**Comment by lustime** [comment]
> 阅读已经晾了 大面积封号了 大家有缘再见

@ilaotan 没凉啊 我的还跑的好好的

**Comment by ilaotan** [comment]
@lustime 好多老号提现提不了，我这俩号才开了两天，没事，一共提了3块钱。不过也不敢开了，避避风头
