### ISSUE TITLE
请大神帮我看看debian下这是怎么了....

### ISSUE THREAD

**Issue by ktycky** [EvineDeng/jd-base#18]
git_pull.sh: 334: git_pull.sh: function: not found
更新JS脚本，原地址：https://github.com/lxk0301/scripts

Fetching origin
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Already up to date.
git_pull.sh: 340: git_pull.sh: Syntax error: "}" unexpected

**Comment by EvineDeng** [comment]
你用最新脚本再重新试试。

**Comment by Noo13-man** [comment]
git_pull.sh: 343: Syntax error: "}" unexpected

最新脚本试运行另一个地方报错.....

**Comment by EvineDeng** [comment]
你是不是343行多了大括号啊。你仔细找一下大括号是不是成对的。

**Comment by Noo13-man** [comment]
![屏幕截图 2020-11-07 150646](https://user-images.githubusercontent.com/65083358/98434496-3e638b00-210b-11eb-99ea-5c892b50a445.png)
![屏幕截图 2020-11-07 150705](https://user-images.githubusercontent.com/65083358/98434498-3f94b800-210b-11eb-9fbe-30c1c954544a.png)
并没有在VS中打开也没有错误提醒。
在 `  sh git_pull.sh   `时会报错

**Comment by EvineDeng** [comment]
google了一下，[这里](https://stackoverflow.com/questions/45096755/fatal-ambiguous-argument-origin-unknown-revision-or-path-not-in-the-working)似乎有解答。

```
It sounds like your origin does not have a HEAD, in my case this is because my remote is a bare repository that has never had a HEAD set.

Running git branch -r will show you if origin/HEAD is set, and if so, which branch it points at (e.g. origin/HEAD -> origin/<branchname>).
```

**Comment by Noo13-man** [comment]
![屏幕截图 2020-11-07 165357](https://user-images.githubusercontent.com/65083358/98436913-dd8f7f00-2119-11eb-9fdc-38f2cc3eecdf.png)
物理机尝试了一下。
把 git_pull.sh 中第480和485末尾的  `;;`  删除。
运行 `bash git_pull.sh` 命令没有报错。

**Comment by EvineDeng** [comment]
不好意思，那刚刚确实是我改出了bug。。。

**Comment by EvineDeng** [comment]
> ![屏幕截图 2020-11-07 165357](https://user-images.githubusercontent.com/65083358/98436913-dd8f7f00-2119-11eb-9fdc-38f2cc3eecdf.png)
> 物理机尝试了一下。
> 把 git_pull.sh 中第480和485末尾的 `;;` 删除。
> 运行 `bash git_pull.sh` 命令没有报错。
> ![屏幕截图 2020-11-07 165511](https://user-images.githubusercontent.com/65083358/98437114-c8672000-211a-11eb-962b-58b61e02a1ec.png)

再次重新修改了一下你出错的这里Change_coinToBeans这个函数，解决了内存溢出的问题，你再测试一下有没有问题。

**Comment by Noo13-man** [comment]
> > ![屏幕截图 2020-11-07 165357](https://user-images.githubusercontent.com/65083358/98436913-dd8f7f00-2119-11eb-9fdc-38f2cc3eecdf.png)
> > 物理机尝试了一下。
> > 把 git_pull.sh 中第480和485末尾的 `;;` 删除。
> > 运行 `bash git_pull.sh` 命令没有报错。
> > ![屏幕截图 2020-11-07 165511](https://user-images.githubusercontent.com/65083358/98437114-c8672000-211a-11eb-962b-58b61e02a1ec.png)
> 
> 再次重新修改了一下你出错的这里Change_coinToBeans这个函数，解决了内存溢出的问题，你再测试一下有没有问题。

运行没有报错，感谢开发者的努力。
等晚上收豆子了，hhh。
