### ISSUE TITLE
删除旧日志无效

### ISSUE THREAD

**Issue by binge8** [EvineDeng/jd-base#183]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A： X64 L大佬的OpenWrt R20.12.12 里安装了dockerman

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x ] Docker

### (1) 具体问题
A：删除旧日志无效，定时这样设置的《57 13 * * * bash rm_log >dev/null 2>&1》，config里设置2天。2天以前的日志并没有删除，手动运行《docker exec -it jd bash rm_log》可以正常删除

### (2) 详细日志
A：无

### (1) Node.js版本

A：V12.18.4

### (2) npm版本

A：V6.14.6

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
剩余最早的日志是哪天的

**Comment by binge8** [comment]
> 先确认：用的是我的docker镜像？我的镜像没有12.18.4的nodejs。

失误，我看成宿主机的版本了，确定是你的镜像，node:v14.5.4  npm:v6.14.10.从我第一次创建容器那天起12月25日的日志一直在，直到昨天手动运行删除日志才删了

**Comment by EvineDeng** [comment]
> > 先确认：用的是我的docker镜像？我的镜像没有12.18.4的nodejs。
> 
> 失误，我看成宿主机的版本了，确定是你的镜像，node:v14.5.4  npm:v6.14.10.从我第一次创建容器那天起12月25日的日志一直在，直到昨天手动运行删除日志才删了

你把>/dev/null 2>&1删除试试看看

**Comment by binge8** [comment]
> > > 先确认：用的是我的docker镜像？我的镜像没有12.18.4的nodejs。
> > 
> > 
> > 失误，我看成宿主机的版本了，确定是你的镜像，node:v14.5.4  npm:v6.14.10.从我第一次创建容器那天起12月25日的日志一直在，直到昨天手动运行删除日志才删了
> 
> 你部署当时的cron应该是每周六执行，你要确认下你的crontab.list。
> 我是这两天才把sample中的cron改成每天执行。

我第一次部署完（12月25日）之后就把cron改成前面那样每天执行了

**Comment by EvineDeng** [comment]
> > > > 先确认：用的是我的docker镜像？我的镜像没有12.18.4的nodejs。
> > > 
> > > 
> > > 失误，我看成宿主机的版本了，确定是你的镜像，node:v14.5.4  npm:v6.14.10.从我第一次创建容器那天起12月25日的日志一直在，直到昨天手动运行删除日志才删了
> > 
> > 
> > 你部署当时的cron应该是每周六执行，你要确认下你的crontab.list。
> > 我是这两天才把sample中的cron改成每天执行。
> 
> 我第一次部署完（12月25日）之后就把cron改成前面那样每天执行了

容器中输入`crontab -l`看看这条cron是不是改后的，如果是，把`>/dev/null 2>&1`改成 >> ${JD_DIR}/log/rm_log.log`，然后过一天看看这个日志。

**Comment by EvineDeng** [comment]
预计2个小时后这个错误应该全部所有人都会修复了

**Comment by lustime** [comment]
watchtower貌似不自动更新镜像了
