### ISSUE TITLE
请提供panel的开关，cpu占用过高

### ISSUE THREAD

**Issue by Dellear** [EvineDeng/jd-base#189]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker   evinedeng/jd:latest

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：今天的docker镜像加入了web panel功能，此功能占用了较高的cpu，导致cpu长时间被占用，机器增温较高。
此功能使用较少，希望提供一个是否开启此功能的开关。
目前开了3个容器，用盒子跑的伤不起啊，太多功能反而增加负担。

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/22325851/103912299-12cc4380-5142-11eb-9a48-ca218262f6f8.png)
![image](https://user-images.githubusercontent.com/22325851/103912478-5030d100-5142-11eb-814f-80222f389453.png)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
好，过两天加，你这两天关注一下更新。

**Comment by EvineDeng** [comment]
已增加控制开关。

**Comment by xie0027** [comment]
大佬server.js运行不起来
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'got'
Require stack:
- /jd/panel/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/jd/panel/server.js:12:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/jd/panel/server.js' ]
}

**Comment by FanchangWang** [comment]
> 大佬server.js运行不起来
> internal/modules/cjs/loader.js:883
> throw err;
> ^
> 
> Error: Cannot find module 'got'
> Require stack:
> 
> * /jd/panel/server.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>   at Module.require (internal/modules/cjs/loader.js:952:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at Object. (/jd/panel/server.js:12:11)
>   at Module._compile (internal/modules/cjs/loader.js:1063:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>   at Module.load (internal/modules/cjs/loader.js:928:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/jd/panel/server.js' ]
>   }

你手动运行的话，需要 cd panel  然后 npm install
