### ISSUE TITLE
大佬能加个更新通知的开关吗

### ISSUE THREAD

**Issue by huangzi959** [EvineDeng/jd-base#193]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：更新git_up会发送两次通知，目前用bark执行通知，晚上想翻看记录发现很多git_up的记录。看代码是update.js里面执行的，但注释掉后，update一下就覆盖了。请问大佬可以在配置文件里面给个开关吗？我想只接收jd任务的推送。

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
发两次应该是个bug，我看看。

**Comment by huangzi959** [comment]
> 发两次应该是个bug，程序设定只发一次，你把截图以及内容发我看看。

是删除脚本发一次，添加脚本发一次

**Comment by EvineDeng** [comment]
哦，暂时不想加，这个是为了提醒任务变化的。

**Comment by huangzi959** [comment]
> 哦，暂时不想加，这个是为了提醒任务变化的。也就最近可能通知多一点，其他时候不会这么频繁的。

OK，好的

**Comment by hecarli555** [comment]
大佬您好，本人用的nas的docker运行的脚本，想问一下设置里面的RandomDelay随机延时，如果不想延时，RandomDelay=“”这里是填0还是什么都不填呢？感谢回答
