### ISSUE TITLE
请问运行后docker日志出现user root: parse error at 37是怎么回事啊

### ISSUE THREAD

**Issue by mengdie101** [EvineDeng/jd-base#194]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [X] 没有类似的issue 

Q：是否阅读了常见问题
- [X] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [X] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker v3

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [X] Docker

### (1) 具体问题
A：
群晖docker运行的，cookie填写过了，删除重建也不行
### (2) 详细日志
A：
Welcome to Node.js   v14.15.4.
Type ".help" for more information.
crond[24]: user root: parse error at 37
crond[24]: USER root pid 140 cmd bash git_pull >> ${JD_DIR}/log/git_pull.log 2>&1

### (1) Node.js版本

A：v12.16.3

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
我也不清楚。。。

**Comment by mengdie101** [comment]
> 我也不清楚。。。

发现哪里的问题了，docker.list.sample里这一行的定时
7 37 * * * bash jd jd_car

**Comment by AsuraDancing** [comment]
对的，问题就在这一行

**Comment by EvineDeng** [comment]
这一行有猫腻？

**Comment by EvineDeng** [comment]
@AsuraDancing @mengdie101 好吧，确实是，我写反了，应该是37 7 * * *

**Comment by mengdie101** [comment]
> @AsuraDancing @mengdie101 好吧，确实是，我写反了，应该是37 7 * * *
> 
> 老用户无影响，你们应该是新用户吧？

是的
