### ISSUE TITLE
软路由使用network host模式无法访问5678

### ISSUE THREAD

**Issue by r0liang** [EvineDeng/jd-base#196]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：软路由 5.4.77-flippy-49+o

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：软路由使用network host模式无法访问5678

### (2) 详细日志
A：日志并未报错

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /jd/panel/server.js in fork_mode (1 instance)
[PM2] Done.
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ server    │ default     │ N/A     │ fork    │ 46       │ 0s     │ 0    │ online    │ 0%       │ 28.7mb   │ root     │ disabled │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
控制面板启动成功...

**Comment by EvineDeng** [comment]
请从网络、防火墙、端口转发方面找问题。

**Comment by chaoyj** [comment]
同样的问题，好像是脚本自动更新之后就打不开网站了。

**Comment by EvineDeng** [comment]
> 同样的问题，好像是脚本自动更新之后就打不开网站了。

更新镜像。

**Comment by solar24** [comment]
![image](https://user-images.githubusercontent.com/30916655/104144308-b39a5780-53fd-11eb-990b-d12c53368641.png)
我也是 503

**Comment by r0liang** [comment]
> 请从网络、防火墙、端口转发方面找问题。

N1中有其他docker，也是`--net host`模式去安装运行的，均可直接通过IP:PORT访问。唯独大佬的访问了会显示`Connection refused`，转发和防火墙也尝试配置了，无果

**Comment by r0liang** [comment]
其余两个docker开放的端口均可通过`netstat -ntlp | grep 5000`能看到，但是大佬的端口并未在监听列表

**Comment by EvineDeng** [comment]
你先更新镜像，使用最新镜像。
