### ISSUE TITLE
export_sharecodes 无法导出惊喜农场互助码

### ISSUE THREAD

**Issue by avsba001** [EvineDeng/jd-base#198]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：bash export_sharecodes 命令无法导出最新的jxnc 互助码

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by yangyangxing** [comment]
那是因为没有运行过对应脚本，这个互助码导出是基于你的脚本有日志，不然连log都没有肯定是没有互助码的，你可以手动运行一遍脚本然后再运行导出就行了

**Comment by lonee6** [comment]
填了也不认的，等脚本更新吧。

**Comment by yangyangxing** [comment]
> 填了也不认的，等脚本更新吧。

你要不填了互助码之后手动更新一下脚本：
docker exec -it jd bash git_pull

**Comment by lonee6** [comment]
> > 填了也不认的，等脚本更新吧。
> 
> 你要不填了互助码之后手动更新一下脚本：
> docker exec -it jd bash git_pull

已经更新到最新了，我用的linux版本，没用docker的

**Comment by FanchangWang** [comment]
这个功能还没添加呢，肯定导不出来啊。。。

**Comment by FanchangWang** [comment]
现在可以用  `bash jd.sh jd_get_share_code now` 命令查看，回头等 `export_sharecodes` 脚本更新了就好了

**Comment by jaysherlock** [comment]
> 现在可以用 `bash jd.sh jd_get_share_code now` 命令查看，回头等 `export_sharecodes` 脚本更新了就好了

请教惊喜农场的token是不是要在手机上才能获取啊

**Comment by FanchangWang** [comment]
> > 现在可以用 `bash jd.sh jd_get_share_code now` 命令查看，回头等 `export_sharecodes` 脚本更新了就好了
> 
> 请教惊喜农场的token是不是要在手机上才能获取啊

是的，需要用代理拦截请求的 url，如果不会搞的话还是建议种非 APP 专享的种子

**Comment by wintry** [comment]
更新了token，但是没有生效，使用的还是之前写错的token

**Comment by avsba001** [comment]
> 现在可以用 `bash jd.sh jd_get_share_code now` 命令查看，回头等 `export_sharecodes` 脚本更新了就好了

等更新了我再关闭这个issue吧

**Comment by EvineDeng** [comment]
> > 现在可以用 `bash jd.sh jd_get_share_code now` 命令查看，回头等 `export_sharecodes` 脚本更新了就好了
> 
> 等更新了我再关闭这个issue吧

export_sharecodes.sh已经可以导出京喜农场互助码，另外，上游仓库中jd_get_share_codes.js也可以导出。
