### ISSUE TITLE
关于同步lxk0301大佬源码问题

### ISSUE THREAD

**Issue by landcruser** [EvineDeng/jd-base#2]
用在群晖docker了，有一个问题请教下，crontab.list中第一条是同步源码，源码中个别修改的内容又不在git_pull.sh可以设置的变量中，这种情况下是覆盖更新了吗？可否单独设置？类似于github中  pull  merge模式？另外，我没有修改时区，crontab.list中设定的就是北京时间了吧？

**Comment by EvineDeng** [comment]
1.第一个问题不太明白，如果源码改动不影响我脚本中的内容，就应该没有影响。我猜你是大概想说js源码中可以控制取关商品和店铺数量而我脚本中没有设置的地方吧？因为除了这个功能我没加，其他对应的功能全都有，我想得的这个功能可以一天靠多运行几次取关任务就可以实现了，所以没有加。
2.如果容器创建时没有添加`TZ=UTC`的环境变量，默认就是北京时间。

**Comment by landcruser** [comment]
感谢，已经看到了在北京时间执行，搞定了星推，以前github action延迟  总是没豆，本地docker精确解决执行太给力了。第一个是比如说我在星推中修改xtg.js助力码为自己的助力码，要给自己的帐号助力而不是内置帐号助力，在git.pull没有这个设置参数，我修改后执行后就被最新源码覆盖了。另外有考虑加入其他的一些脚本比如野比的，放在这个docker跑吗？

**Comment by EvineDeng** [comment]
你自己直接改js会被覆盖，除非暂时取消git_pull.sh的定时任务。

**Comment by landcruser** [comment]
> 你自己直接改js会被覆盖，除非暂时取消git_pull.sh的定时任务。因为merge在脚本中很难做到自动化。
> 野比是Nobyda大佬吗？如果是的话，我建议直接使用野比大佬的东西去跑。不过jd签到脚本lxk0301大佬其实就是在Nobyda大佬脚本上套了层壳，本质还是Nobyda大佬的脚本。

谢谢，我暂时把那个gitpull的删除了  手动更新 再手动改。第二个Nobyda大的脚本想用黑裙docker在本地跑，不行我再去虚拟机跑一个debian吧。感谢热心回复。

**Comment by EvineDeng** [comment]
> > 你自己直接改js会被覆盖，除非暂时取消git_pull.sh的定时任务。因为merge在脚本中很难做到自动化。
> > 野比是Nobyda大佬吗？如果是的话，我建议直接使用野比大佬的东西去跑。不过jd签到脚本lxk0301大佬其实就是在Nobyda大佬脚本上套了层壳，本质还是Nobyda大佬的脚本。
> 
> 谢谢，我暂时把那个gitpull的删除了 手动更新 再手动改。第二个Nobyda大的脚本想用黑裙docker在本地跑，不行我再去虚拟机跑一个debian吧。感谢热心回复。
> 还有一个问题就是钉钉推送您使用了吗？我这边钉钉推送不了，两个参数都设置了，安全模式只选了加签，token用全部或者=之后的都不行。原来钉钉用的token加关键字模式

钉钉是由js脚本发送的，可能要去js那边反馈下。

**Comment by landcruser** [comment]
> > > 你自己直接改js会被覆盖，除非暂时取消git_pull.sh的定时任务。因为merge在脚本中很难做到自动化。
> > > 野比是Nobyda大佬吗？如果是的话，我建议直接使用野比大佬的东西去跑。不过jd签到脚本lxk0301大佬其实就是在Nobyda大佬脚本上套了层壳，本质还是Nobyda大佬的脚本。
> > 
> > 
> > 谢谢，我暂时把那个gitpull的删除了 手动更新 再手动改。第二个Nobyda大的脚本想用黑裙docker在本地跑，不行我再去虚拟机跑一个debian吧。感谢热心回复。
> > 还有一个问题就是钉钉推送您使用了吗？我这边钉钉推送不了，两个参数都设置了，安全模式只选了加签，token用全部或者=之后的都不行。原来钉钉用的token加关键字模式
> 
> 钉钉是由js脚本发送的，可能要去js那边反馈下。

好的
