### ISSUE TITLE
大佬您好，在第一次运行git_pull.sh时就出现了问题 2020/11/8

### ISSUE THREAD

**Issue by lan-tianxiang** [EvineDeng/jd-base#20]
环境VM下的Ubantu 20

![image](https://user-images.githubusercontent.com/42911023/98460776-3fb3b700-21e2-11eb-83ee-034729bf7a96.png)

能帮看一下如何解决吗，谢谢！！！！！

**Comment by lan-tianxiang** [comment]
我是安装物理机安装的流程来的，即
![image](https://user-images.githubusercontent.com/42911023/98460907-4c84da80-21e3-11eb-97f9-d5529fa2d3e3.png)
然后
![image](https://user-images.githubusercontent.com/42911023/98460910-5575ac00-21e3-11eb-8c66-0622b65d5278.png)
![image](https://user-images.githubusercontent.com/42911023/98460915-61fa0480-21e3-11eb-944b-542848471856.png)
修改完信息，补充cookie之后，就在这一步停了
![image](https://user-images.githubusercontent.com/42911023/98460933-7b9b4c00-21e3-11eb-85c5-84532d53d4eb.png)

**Comment by EvineDeng** [comment]
有个issue与你情况类似，他用最新脚本似乎没问题了：https://github.com/EvineDeng/jd-base/issues/18

git这个错误，我也搞不明白。。。

**Comment by lan-tianxiang** [comment]
> 有个issue与你情况类似，他用最新脚本似乎没问题了：#18
> 
> git这个错误，我也搞不明白。。。

我也是最新脚本呢，为什么人与人之间的体质差这么多（哭笑）

**Comment by lan-tianxiang** [comment]
我跟着改改看

**Comment by EvineDeng** [comment]
> 我跟着改改看

他出错的那里我已经重新改过了，应该没问题才对呀。

**Comment by EvineDeng** [comment]
> 我是安装物理机安装的流程来的，即
> ![image](https://user-images.githubusercontent.com/42911023/98460907-4c84da80-21e3-11eb-97f9-d5529fa2d3e3.png)
> 然后
> ![image](https://user-images.githubusercontent.com/42911023/98460910-5575ac00-21e3-11eb-8c66-0622b65d5278.png)
> ![image](https://user-images.githubusercontent.com/42911023/98460915-61fa0480-21e3-11eb-944b-542848471856.png)
> 修改完信息，补充cookie之后，就在这一步停了
> ![image](https://user-images.githubusercontent.com/42911023/98460933-7b9b4c00-21e3-11eb-85c5-84532d53d4eb.png)

我知道你的问题了，你有没有注意到最后一张图片中最后`sh git_pull.sh`后面的注释？？？

**Comment by lan-tianxiang** [comment]
> > 我是安装物理机安装的流程来的，即
> > ![image](https://user-images.githubusercontent.com/42911023/98460907-4c84da80-21e3-11eb-97f9-d5529fa2d3e3.png)
> > 然后
> > ![image](https://user-images.githubusercontent.com/42911023/98460910-5575ac00-21e3-11eb-8c66-0622b65d5278.png)
> > ![image](https://user-images.githubusercontent.com/42911023/98460915-61fa0480-21e3-11eb-944b-542848471856.png)
> > 修改完信息，补充cookie之后，就在这一步停了
> > ![image](https://user-images.githubusercontent.com/42911023/98460933-7b9b4c00-21e3-11eb-85c5-84532d53d4eb.png)
> 
> 我知道你的问题了，你有没有注意到最后一张图片中最后`sh git_pull.sh`后面的注释？？？

我我我我。。。。。。。。试试

**Comment by lan-tianxiang** [comment]
> > 我是安装物理机安装的流程来的，即
> > ![image](https://user-images.githubusercontent.com/42911023/98460907-4c84da80-21e3-11eb-97f9-d5529fa2d3e3.png)
> > 然后
> > ![image](https://user-images.githubusercontent.com/42911023/98460910-5575ac00-21e3-11eb-8c66-0622b65d5278.png)
> > ![image](https://user-images.githubusercontent.com/42911023/98460915-61fa0480-21e3-11eb-944b-542848471856.png)
> > 修改完信息，补充cookie之后，就在这一步停了
> > ![image](https://user-images.githubusercontent.com/42911023/98460933-7b9b4c00-21e3-11eb-85c5-84532d53d4eb.png)
> 
> 我知道你的问题了，你有没有注意到最后一张图片中最后`sh git_pull.sh`后面的注释？？？

噢，不，还真是这样。抱歉了，呜呜呜
