### ISSUE TITLE
修改了jxnc的token，但未生效

### ISSUE THREAD

**Issue by wintry** [EvineDeng/jd-base#200]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker 

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：jxnc中，修改了token，未生效，仍然使用修改前填写的
即填写了token A，却在使用token B

### (2) 详细日志
A： 【京东账号1（xxxx）的京喜农场好友互助码】 1a4b24762e634fd97080dbe74aa38767
【京东账号1（xxxx）的京喜农场种子active】 jdnc_1_mizao210108_2
开始第1个任务：开启每日免费领水滴提醒
开启每日免费领水滴提醒[做任务]：ret:1032 retmsg:"err operate env"
任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子

### (1) Node.js版本

A：v10.16.3

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
js的问题，等上游修。

**Comment by wintry** [comment]
> 你把你Token填写内容发来看看，可以替换一些信息，以防泄露隐私。

TokenJxnc1='{"farm_jstoken":"cf108xxxxxxxx56a24f6d3d30a618","timestamp":"1610131061664","phoneid":"cxxxxx553b41682282774a3e7bd6361c4"}'
而在日志中看到使用的是jdnc_1_mizao210108_2，这是我第一次没搞清楚的时候填的，后面搞清楚修改成上面，再次运行脚本使用的还是修改前的

**Comment by Hyper-Beast** [comment]
请问怎么获取Token，我在那个js脚本开头的注释里没看到获取方法

**Comment by wintry** [comment]
> 请问怎么获取Token，我在那个js脚本开头的注释里没看到获取方法

ios 使用stream抓包，在app中jxnc做任务，在抓包中找form/dotask的请求，在请求中能找到需要的token
安卓类似

**Comment by Hyper-Beast** [comment]
> > 请问怎么获取Token，我在那个js脚本开头的注释里没看到获取方法
> 
> ios 使用stream抓包，在app中jxnc做任务，在抓包中找form/dotask的请求，在请求中能找到需要的token
> 安卓类似

好的，谢谢

**Comment by FanchangWang** [comment]
检查了下代码，token 无效的问题，是我写错变量了，我修改下代码一会提交 pr 修复

**Comment by FanchangWang** [comment]
token 无效的代码已提交 pr 到上游代码，等 merge 就好了

**Comment by Netflixxp** [comment]
一样，不知道怎么获取token ，求教程

**Comment by FanchangWang** [comment]
token 错误代码已经修复并合并，请执行 bash git_pull.sh 更新代码

**Comment by wintry** [comment]
已经好了
