### ISSUE TITLE
重启容器后，控制面板无法打开

### ISSUE THREAD

**Issue by ad-calcium** [EvineDeng/jd-base#201]
关于你要提交的问题
Q：是否搜索了issue（包括已关闭的issue）

 没有类似的issue
Q：是否阅读了常见问题

 已阅读常见问题，未找到相关说明
Q：是否仔细阅读了教程

 已仔细阅读教程
2. 使用什么平台，精确到版本
A：docker

3. 按照以下哪个教程做的
 Linux
 Android
 MacOS
 Docker
4. 详细叙述
(1) 具体问题
A：重启容器后，发现控制面板无法访问

(2) 详细日志
A： 通过docker log查看日志，未发现异常
![image](https://user-images.githubusercontent.com/33044636/104159663-b7909e80-542a-11eb-8103-1d29a7ad2215.png)

docker ps 端口正常映射
![image](https://user-images.githubusercontent.com/33044636/104159870-148c5480-542b-11eb-95a7-654e3534a6f9.png)

无法访问尝试使用curl进行访问，无法正常访问。
![image](https://user-images.githubusercontent.com/33044636/104159909-25d56100-542b-11eb-986e-8d0683787a20.png)

5.软件版本和npm install
(1) Node.js版本
A：v10.16.3

(2) npm版本
A：

(3)npm install的日志
A：

**Comment by solar24** [comment]
我的是503，E大有空可以解答一下吗？

**Comment by EvineDeng** [comment]
> 我的是503，E大有空可以解答一下吗？
> 

镜像时间？

**Comment by EvineDeng** [comment]
镜像时间？

**Comment by ad-calcium** [comment]
![image](https://user-images.githubusercontent.com/33044636/104162070-e6a90f00-542e-11eb-993c-1f960af30797.png)
可以手动启动web吗？

**Comment by solar24** [comment]
> > 我的是503，E大有空可以解答一下吗？
> 
> 镜像时间？

![image](https://user-images.githubusercontent.com/30916655/104162126-fcb6cf80-542e-11eb-99a7-a0e1da19c03f.png)
2天前

**Comment by ad-calcium** [comment]
![image](https://user-images.githubusercontent.com/33044636/104166670-1a3b6780-5436-11eb-93ba-24b95a8afc5d.png)
4天前

**Comment by EvineDeng** [comment]
@solar24 @ad-calcium 是镜像image的创建时间，不是容器container的创建时间。镜像的最新创建时间见下图：
![image](https://user-images.githubusercontent.com/30263136/104171206-3f7fa400-543d-11eb-8e81-7355d211435f.png)
不是最新镜像的请更新到此镜像。

**Comment by ad-calcium** [comment]
更新之后未发现该问题，感谢回复。

**Comment by solar24** [comment]
> @solar24 @ad-calcium 是镜像image的创建时间，不是容器container的创建时间。镜像的最新创建时间见下图：
> ![image](https://user-images.githubusercontent.com/30263136/104171206-3f7fa400-543d-11eb-8e81-7355d211435f.png)
> 不是最新镜像的请更新到此镜像。

![image](https://user-images.githubusercontent.com/30916655/104254028-e4879480-54b0-11eb-8ad0-9916fad1a0f3.png)
我这个就是镜像image拉取时间呀，都是containrrr/watchtower自动更新的

**Comment by EvineDeng** [comment]
> > @solar24 @ad-calcium 是镜像image的创建时间，不是容器container的创建时间。镜像的最新创建时间见下图：
> > ![image](https://user-images.githubusercontent.com/30263136/104171206-3f7fa400-543d-11eb-8e81-7355d211435f.png)
> > 不是最新镜像的请更新到此镜像。
> 
> ![image](https://user-images.githubusercontent.com/30916655/104254028-e4879480-54b0-11eb-8ad0-9916fad1a0f3.png)
> 我这个就是镜像image拉取时间呀，都是containrrr/watchtower自动更新的

如果镜像是最新，启动日志会以“容器启动成功...”结尾，如果是这个，那么就从网络、端口转发、防火墙方面找问题。如果是路由器中，出去了可能会更复杂些。

**Comment by solar24** [comment]
> > > @solar24 @ad-calcium 是镜像image的创建时间，不是容器container的创建时间。镜像的最新创建时间见下图：
> > > ![image](https://user-images.githubusercontent.com/30263136/104171206-3f7fa400-543d-11eb-8e81-7355d211435f.png)
> > > 不是最新镜像的请更新到此镜像。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/30916655/104254028-e4879480-54b0-11eb-8ad0-9916fad1a0f3.png)
> > 我这个就是镜像image拉取时间呀，都是containrrr/watchtower自动更新的
> 
> 如果镜像是最新，启动日志会以“容器启动成功...”结尾，如果是这个，那么就从网络、端口转发、防火墙方面找问题。如果是路由器中，可能会更复杂些。

我是安装在vps中的，网络应该是没问题，端口也是按照教程配置，能访问登录页面防火墙也是没问题，这个功能出来的时候就没用成功，一直找不到原因，不过这次和上次的报错不是同一个，这次是503，应该是服务器有问题，但是又找不到，有点苦恼

**Comment by EvineDeng** [comment]
> > > > @solar24 @ad-calcium 是镜像image的创建时间，不是容器container的创建时间。镜像的最新创建时间见下图：
> > > > ![image](https://user-images.githubusercontent.com/30263136/104171206-3f7fa400-543d-11eb-8e81-7355d211435f.png)
> > > > 不是最新镜像的请更新到此镜像。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/30916655/104254028-e4879480-54b0-11eb-8ad0-9916fad1a0f3.png)
> > > 我这个就是镜像image拉取时间呀，都是containrrr/watchtower自动更新的
> > 
> > 如果镜像是最新，启动日志会以“容器启动成功...”结尾，如果是这个，那么就从网络、端口转发、防火墙方面找问题。如果是路由器中，可能会更复杂些。
> 
> 我是安装在vps中的，网络应该是没问题，端口也是按照教程配置，能访问登录页面防火墙也是没问题，这个功能出来的时候就没用成功，一直找不到原因，不过这次和上次的报错不是同一个，这次是503，应该是服务器有问题，但是又找不到，有点苦恼

许多vps在服务商网页控制面板中还有一层防火墙设置。

**Comment by solar24** [comment]
> > > > > @solar24 @ad-calcium 是镜像image的创建时间，不是容器container的创建时间。镜像的最新创建时间见下图：
> > > > > ![image](https://user-images.githubusercontent.com/30263136/104171206-3f7fa400-543d-11eb-8e81-7355d211435f.png)
> > > > > 不是最新镜像的请更新到此镜像。
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/30916655/104254028-e4879480-54b0-11eb-8ad0-9916fad1a0f3.png)
> > > > 我这个就是镜像image拉取时间呀，都是containrrr/watchtower自动更新的
> > > 
> > > 
> > > 如果镜像是最新，启动日志会以“容器启动成功...”结尾，如果是这个，那么就从网络、端口转发、防火墙方面找问题。如果是路由器中，可能会更复杂些。
> > 
> > 
> > 我是安装在vps中的，网络应该是没问题，端口也是按照教程配置，能访问登录页面防火墙也是没问题，这个功能出来的时候就没用成功，一直找不到原因，不过这次和上次的报错不是同一个，这次是503，应该是服务器有问题，但是又找不到，有点苦恼
> 
> 许多vps在服务商网页控制面板中还有一层防火墙设置。

我用的是阿里云，我在控制台把这个端口开放了，服务器里面的防火墙好像是默认关闭的
