### ISSUE TITLE
无法使用控制面板

### ISSUE THREAD

**Issue by HIKARuRu1** [EvineDeng/jd-base#205]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：termux

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：无法node server.js，能使用pm2 start server.js，但是无论怎么都无法访问5678端口。

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/73590674/104185715-4c59c300-5450-11eb-83c8-b89baf24fefd.png)

### (1) Node.js版本

A：12.18.3

### (2) npm版本

A：6.14.6

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
按教程安装好依赖：https://github.com/EvineDeng/jd-base/wiki/Panel

手机用啥pm2，直接node server.js。

**Comment by EvineDeng** [comment]
按教程安装好依赖：https://github.com/EvineDeng/jd-base/wiki/Panel

手机用啥pm2，直接node server.js。

**Comment by HIKARuRu1** [comment]
可是没法node啊。。。执行之后报错了

**Comment by EvineDeng** [comment]
> 可是没法node啊。。。执行之后报错了

依赖装好了没有？错误是啥？

**Comment by HIKARuRu1** [comment]
> > 可是没法node啊。。。执行之后报错了
> 
> 依赖装好了没有？错误是啥？

都装好了的，除了这个功能其他都是正常运行的。这功能刚更新的那两天还用过，这两天congfig.sh要更新发现不能用了。没显示错误，就只是前面打了个×。刚把pkg都upgrade了，也不行。
![Screenshot_2021-01-11-23-14-23-961_com termux](https://user-images.githubusercontent.com/73590674/104200362-85e7f980-5463-11eb-8055-62db93359409.jpg)

**Comment by HIKARuRu1** [comment]
> > 可是没法node啊。。。执行之后报错了
> 
> 依赖装好了没有？错误是啥？

抱歉依赖刚刚看错了，安装依赖的时候提醒没有权限。。
![Screenshot_2021-01-12-00-11-27-363_com termux](https://user-images.githubusercontent.com/73590674/104208391-8d130580-546b-11eb-9bdb-910549771ab1.jpg)
![Screenshot_2021-01-12-00-16-54-637_com termux](https://user-images.githubusercontent.com/73590674/104208446-913f2300-546b-11eb-882a-d32e40c7ead5.jpg)

**Comment by EvineDeng** [comment]
你用npm install --no-bin-link试试

**Comment by HIKARuRu1** [comment]
> 你用npm install --no-bin-links 试试

成功了，谢谢大佬。另外在装的时候给了警告，会有什么影响吗？
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN panel No description
npm WARN panel No repository field.
npm WARN panel No license field.
