### ISSUE TITLE
助力码问题

### ISSUE THREAD

**Issue by qiao112** [EvineDeng/jd-base#206]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：群晖6.2.3

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：我想知道如果只填写定义活动每个人自己的互助码,而定义活动要为哪些人助力中不赋值,这种情况下，将自动随机给定义活动每个人自己的互助码中填写的助力码助力吗.
### (2) 详细日志
A：
![7RP )Y01W0APYO6D7O{L@PS](https://user-images.githubusercontent.com/45731546/104282391-e2b8d380-54a6-11eb-9501-75eccb25038d.png)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
会

**Comment by qiao112** [comment]
> 他人是指其他请陌生人，请理解`这里的码只是为了下面“定义东东农场要为哪些人助力”服务的`这句话。读不懂也没关系，照抄改改也可以。

如果不赋值的话会不会随机给自己填的助力码助力

**Comment by qiao112** [comment]
![IELNL%09CB@3$S$P}97}M M](https://user-images.githubusercontent.com/45731546/104298661-2964f880-54bc-11eb-9f9c-cb9ce722f0ec.png)

**Comment by EvineDeng** [comment]
> > 他人是指其他请陌生人，请理解`这里的码只是为了下面“定义东东农场要为哪些人助力”服务的`这句话。读不懂也没关系，照抄改改也可以。
> 
> 如果不赋值的话会不会随机给自己填的助力码助力

不会

**Comment by qiao112** [comment]
> > > 他人是指其他请陌生人，请理解`这里的码只是为了下面“定义东东农场要为哪些人助力”服务的`这句话。读不懂也没关系，照抄改改也可以。
> > 
> > 
> > 如果不赋值的话会不会随机给自己填的助力码助力
> 
> 不会

如果排在前面的助力码助力人数满了会自动给下面的助力码助力吗

**Comment by EvineDeng** [comment]
> > > > 他人是指其他请陌生人，请理解`这里的码只是为了下面“定义东东农场要为哪些人助力”服务的`这句话。读不懂也没关系，照抄改改也可以。
> > > 
> > > 
> > > 如果不赋值的话会不会随机给自己填的助力码助力
> > 
> > 
> > 不会
> 
> 如果排在前面的助力码助力人数满了会自动给下面的助力码助力吗

会
