### ISSUE TITLE
/config/bak文件夹下crontab.list开头的文件实际内容是config.sh的内容

### ISSUE THREAD

**Issue by chenyitian2004** [EvineDeng/jd-base#207]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：centos7.3 docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：/config/bak目录下所有crontab.list开头的备份文件实际内容都是config.sh的内容，怀疑是自动备份出错

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by chenyitian2004** [comment]
顺便问一下wiki的常见问题中forother系列第二个后面的注释是不是应该改成2给1助力

**Comment by EvineDeng** [comment]
> 顺便问一下wiki的常见问题中forother系列第二个后面的注释是不是应该改成2给1助力

已修改。

**Comment by EvineDeng** [comment]
@FanchangWang @jerrykuku 麻烦确认一下这是个bug？

**Comment by jerrykuku** [comment]
嗯 应该是Bug 我修复一下

**Comment by EvineDeng** [comment]
#208 大佬已修复，本issue关闭
