### ISSUE TITLE
脚本通知重复推送

### ISSUE THREAD

**Issue by MatthewDevelop** [EvineDeng/jd-base#209]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：CentOS Linux release 7.9.2009 (Core)

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：有多个定时任务推送执行结果的时候会重复推送，使用push plus 和serverchan 都有相同的问题，出现这个问题的定时任务包括：京东农场，京豆变动等，如下图：
![image](https://user-images.githubusercontent.com/23044942/104397583-115aab00-5588-11eb-859e-82b2c808ab74.png)

### (2) 详细日志
A：消息推送的日志如下：
```log
您未提供server酱的SCKEY，取消微信推送消息通知

push+发送一对多通知消息完成。

您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知

您未提供telegram机器人推送所需的TG_BOT_TOKEN和TG_USER_ID，取消telegram推送消息通知

您未提供钉钉机器人推送所需的DD_BOT_TOKEN或者DD_BOT_SECRET，取消钉钉推送消息通知

您未提供企业微信机器人推送所需的QYWX_KEY，取消企业微信推送消息通知

您未提供企业微信应用消息推送所需的QYWX_AM，取消企业微信应用消息推送消息通知

您未提供iGot的推送IGOT_PUSH_KEY，取消iGot推送消息通知

您未提供酷推的SKEY，取消QQ推送消息通知

```

### (1) Node.js版本

A：v15.5.1

### (2) npm版本

A：7.3.0

### (3)npm install的日志

A：
![image](https://user-images.githubusercontent.com/23044942/104398150-2d128100-5589-11eb-8325-a1e78f1ad788.png)

**Comment by EvineDeng** [comment]
这与我脚本有啥关系呢？你哪里设置出问题了吧。

**Comment by MatthewDevelop** [comment]
哦哦哦，找到问题了，系统的root和普通用户都有一份定时任务！
