### ISSUE TITLE
使用nvm安装的nodejs和npm导致PATH路径不一致无法运行

### ISSUE THREAD

**Issue by RtYkk** [EvineDeng/jd-base#21]
难道只能我一个一个把shell里面的PATH改改吗？请问还有什么其他解决办法，谢谢。
`____npm install
/home/jd/shell/git_pull_function.sh: line 614: npm: command not found`

牵涉到了多个shell

我的PATH，修改后应该是可以正常运行的：`/root/.nvm/versions/node/v14.9.0/bin:/usr/local/bin/abox:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/.nvm/versions/node/v14.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by EvineDeng** [comment]
你的PATH怎么这么奇特，针对更新代码的你复制后的git_pull，你如果只改git_pull.sh有用么？

**Comment by EvineDeng** [comment]
其实还有个办法，你把你的这些命令全部在/usr/local/bin下建立软连接，应该可行。

**Comment by RtYkk** [comment]
多谢，用软链接解决了。但我用[nvm](https://github.com/nvm-sh/nvm)真不是为了追新，nvm可以更方便的切换不同的版本，方便处理一些conflict。
