### ISSUE TITLE
京喜农场, 失败! 原因: SyntaxError: Unexpected token j in JSON at position 0!

### ISSUE THREAD

**Issue by lingyle** [EvineDeng/jd-base#210]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：
群晖 DS918+ 6.23up3
## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：
从2020/1/12开始，jxnc运行出错，在此之前OK

### (2) 详细日志
A：
您的京喜农场 token 选择的是用&隔开

您的京喜农场助力码选择的是用&隔开

共1个京东账号

❌ 京喜农场, 失败! 原因: SyntaxError: Unexpected token j in JSON at position 0!

SyntaxError: Unexpected token j in JSON at position 0
    at JSON.parse (<anonymous>)
    at /jd/scripts/jd_jxnc.js:136:56
    at Array.forEach (<anonymous>)
    at /jd/scripts/jd_jxnc.js:135:38
    at new Promise (<anonymous>)
    at requireConfig (/jd/scripts/jd_jxnc.js:111:12)
    at /jd/scripts/jd_jxnc.js:67:11
    at Object.<anonymous> (/jd/scripts/jd_jxnc.js:100:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

### (1) Node.js版本

A：
v14.15.4
### (2) npm版本

A：
6.14.10
### (3)npm install的日志

A：
root@jd:/jd/scripts $ npm install
audited 205 packages in 6.636s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
---------------------------------------
root@jd:/jd/scripts $ npm fund
lxk0301@1.0.0
├─┬ https://github.com/sindresorhus/got?sponsor=1
│ └── got@11.8.0
├─┬ https://github.com/sponsors/feross
│ └── buffer@5.7.1, ieee754@1.2.1
├─┬ https://www.patreon.com/feross
│ └── buffer@5.7.1, ieee754@1.2.1
├─┬ https://feross.org/support
│ └── buffer@5.7.1, ieee754@1.2.1
├─┬ https://github.com/sindresorhus/is?sponsor=1
│ └── @sindresorhus/is@4.0.0
├─┬ https://github.com/sponsors/sindresorhus
│ └── decompress-response@6.0.0, get-stream@5.2.0, mimic-response@3.1.0, quick-lru@5.1.1
├─┬ https://github.com/sponsors/RubenVerborgh
│ └── follow-redirects@1.13.0
├─┬ https://github.com/sponsors/ljharb
│ └── qs@6.9.4
└─┬ https://github.com/sponsors/epoberezkin
  └── ajv@6.12.6

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │      New patch version of npm available! 6.14.10 → 6.14.11      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.11   │
   │                Run npm install -g npm to update!                │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

**Comment by FanchangWang** [comment]
你配置的 token 格式错了

**Comment by FanchangWang** [comment]
检查你 config.sh 中配置的 token 格式

**Comment by lingyle** [comment]
谢谢大佬们！
