### ISSUE TITLE
助力码问题

### ISSUE THREAD

**Issue by qiao112** [EvineDeng/jd-base#211]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [X] 没有类似的issue 

Q：是否阅读了常见问题
- [X] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [X] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：群晖6.2.3

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [X] Docker

### (1) 具体问题
A：如果26个英语字母用填完之后可以用A1.A2.A3..........之类的代替吗

**Comment by EvineDeng** [comment]
可以，只要编号不重复即可，这么多号你自己最好注释下哪个码对应哪个号。

**Comment by qiao112** [comment]
> 可以，但不能有点`.`，这么多号你自己最好注释下哪个码对应哪个号。

好的谢谢有有点多

**Comment by qiao112** [comment]
> 可以，但不能有点`.`，这么多号你自己最好注释下哪个码对应哪个号。

好的谢谢人有点多
