### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by virkingz** [EvineDeng/jd-base#213]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：armbian下docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [ x] Docker

### (1) 具体问题
A：运行一段时间后内存过高，docker restart jd后正常，怀疑内存泄漏，或者部分线程未关闭

### (2) 详细日志
A：

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
就是部分js脚本无法访问api导致进程不释放，这是上游的问题，但据说今天刚刚上游的代码解决了。你后续可以再看看，。

**Comment by manBoooooooooooooom** [comment]
> 就是部分js脚本无法访问api导致进程不释放，这是上游的问题，但据说今天刚刚上游的代码解决了。你后续可以再看看，。

想询问一下 该如何停止所有的任务？

**Comment by EvineDeng** [comment]
> > 就是部分js脚本无法访问api导致进程不释放，这是上游的问题，但据说今天刚刚上游的代码解决了。你后续可以再看看，。
> 
> 想询问一下 该如何停止所有的任务？

重启容器不就好了

**Comment by lustime** [comment]
> > > 就是部分js脚本无法访问api导致进程不释放，这是上游的问题，但据说今天刚刚上游的代码解决了。你后续可以再看看，。
> > 
> > 
> > 想询问一下 该如何停止所有的任务？
> 
> 重启容器不就好了

0301大佬又被fen了？

**Comment by goargelj** [comment]
> > > > 就是部分js脚本无法访问api导致进程不释放，这是上游的问题，但据说今天刚刚上游的代码解决了。你后续可以再看看，。
> > > 
> > > 
> > > 想询问一下 该如何停止所有的任务？
> > 
> > 
> > 重启容器不就好了
> 
> 0301大佬又被fen了？

现在访问大佬的页面已经404了~

**Comment by wanghlstar** [comment]
gitee 还有~~~~ 把 git_pull.sh 提交一版新的~~~~
