### ISSUE TITLE
首次执行git_pull脚本出现异常

### ISSUE THREAD

**Issue by manBoooooooooooooom** [EvineDeng/jd-base#214]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：CentOs 7

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：在个人另外一台Linux重新搭建一套时，初次执行git_pllu.sh脚本时 出现错误。
排查后发现是脚本的第一个（if [ -f /proc/1/cgroup ]）判断出现问题，导致（if [ -z "${isDocker}" ]）判断出现问题，后续脚本参数报错。

### (2) 详细日志
A：

grep: /.git/config: No such file or directory

--------------------------------------------------------------

系统时间：2021-01-13 17:19:20

SHELL脚本目录：

JS脚本目录：/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
grep: /sample/config.sh.sample: No such file or directory

shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...

git_pull.sh: line 365: [: -eq: unary operator expected
js脚本更新失败，请检查原因或再次运行git_pull.sh...

### (1) Node.js版本

A：v12.6.0

### (2) npm版本

A：6.9.0

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
Docker环境，必须用我的Docker，Docker中的linux是不能用的。

**Comment by manBoooooooooooooom** [comment]
> Docker环境，必须用我的Docker，Docker安装的Linux系统是不能用的，也不打算兼容。

好的 明白了，那我去宿主机捣鼓吧。谢谢大佬回答
