### ISSUE TITLE
东东工厂每日任务没有做

### ISSUE THREAD

**Issue by Misaka09982** [EvineDeng/jd-base#215]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：群晖 6.2.3

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x ] Docker

### (1) 具体问题
A：翻了今天的记录发现今天的每日任务没有做，只有助力完成了，看了下昨天是有记录的

### (2) 详细日志
A：开始获取东东工厂配置文件

您的互助码选择的是用&隔开

共5个京东账号

您提供了5个账号的东东工厂助力码

******开始【京东账号1】御坂智代*********

开始
第1个京东账号将要助力的好友["T0205KkcIWBRqTKoV36m5712CjVWnYaS5kRrbA","T0205KkcP21GqiGDSk2p8p5YCjVWnYaS5kRrbA","T0205KkcIH9GoCGsXlKo86lMCjVWnYaS5kRrbAT0225KkcRhse9FfedhqgkaYOcACjVWnYaS5kRrbA",""]
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
成功收集500电量，当前蓄电池总电量：201809

已选商品：蔡司屏幕清洁湿巾30片装
当前已投入电量/所需电量：95981/880000
已选商品剩余量：580
当前总电量：297790
当前完成度：34%

BoxJs或环境变量暂未提供心仪商品
如需兑换心仪商品，请提供心仪商品名称，否则满足条件后会为您兑换当前所选商品：蔡司屏幕清洁湿巾30片装

所选商品蔡司屏幕清洁湿巾30片装目前数量：580，且当前总电量为：297790，【不满足】兑换此商品所需总电量：880000
故不一次性投入电力，一直放到蓄电池累计

京东账号1御坂智代
京东账号1 御坂智代
已选商品：蔡司屏幕清洁湿巾30片装
当前已投入电量/所需电量：95981/880000
已选商品剩余量：580
当前总电量：297790
当前完成度：34%

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
所以我能做什么呢？

**Comment by Misaka09982** [comment]
> 所以需要我做什么呢？

我就是提出问题，等大佬们修复下

**Comment by EvineDeng** [comment]
> > 所以需要我做什么呢？
> 
> 我就是提出问题，等大佬们修复下

你还不明白，这个问题与我shell脚本有啥关系？你找错地方了。你填issue的时候，那么多提示都没有看到。
