### ISSUE TITLE
https://github.com/lxk0301/jd_scripts,出现404

### ISSUE THREAD

**Issue by 529553174** [EvineDeng/jd-base#216]
这是大佬的账号被删了么

**Comment by sltalex** [comment]
看来是的，早上7点钟的时候就打不开了，整个帐户都没了，现在就剩下这里，不知道还能坚持多久。

**Comment by etzzy** [comment]
希望老大不止一个账号，关键zb者太多，网上很多地方都贴刷豆子的帖子。

**Comment by EvineDeng** [comment]
使用wiki中gitee的方式

**Comment by encoo** [comment]
> 使用wiki中gitee的方式

当前程序能自动从gitee获取更新不呢

**Comment by lunakunada** [comment]
那个互助的 讨论 还有么？
