### ISSUE TITLE
在线编辑工具，无法扫码登录

### ISSUE THREAD

**Issue by leave668** [EvineDeng/jd-base#217]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：linux ubuntu 20.04

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：控制面板对比文件修改的，扫码获取CK工具，扫码后手机提示“页面错误-服务异常，请返回重试”
微信扫码后二维码的网址是https://plogin.m.jd.com/cgi-bin/m/tmauth?appid=300&client_type=m&token=

### (2) 详细日志
A：可以正常对比配置文件，修改、保存配置文件，扫码的话 无法使用。

### (1) Node.js版本

A：v10.19.0

### (2) npm版本

A：6.14.4

### (3)npm install的日志

A：
~/jd/scripts$ npm install
npm WARN saveError EACCES: permission denied, open '/home/myid/jd/scripts/package-lock.json.1060024860'
audited 206 packages in 5.545s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by FanchangWang** [comment]
npm install 路径权限有问题

**Comment by NoEggEgg** [comment]
在线面板需要手动开启，无法随容器启动，怎么处理才能容器重启时在线面板也启动

**Comment by EvineDeng** [comment]
用京东app扫描

**Comment by EvineDeng** [comment]
> 在线面板需要手动开启，无法随容器启动，怎么处理才能容器重启时在线面板也启动

不设置ENABLE_WEB_PANEL=false

**Comment by leave668** [comment]
> 用京东app扫描
京东APP扫码提示："页面错误-服务异常，请返回重试”

**Comment by EvineDeng** [comment]
> > 用京东app扫描
> 京东APP扫码提示："页面错误-服务异常，请返回重试”
> 

那就不明原因了。我们都正常的。

**Comment by EvineDeng** [comment]
> 在线面板需要手动开启，无法随容器启动，怎么处理才能容器重启时在线面板也启动

#57

**Comment by xiaohuaming** [comment]
源项目作者删库了，这磕咋搞

**Comment by 907904228** [comment]
请问是因为啥啊，我也出现这个问题了
