### ISSUE TITLE
关于JS脚本更新失败

### ISSUE THREAD

**Issue by ccboxjole** [EvineDeng/jd-base#218]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：mac os 11.0.1
      node.js  14.15.4
## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：运行 git_pull.sh，shell文件更新成功，JS脚本更新失败

### (2) 详细日志
A：
remote: Repository not found.
fatal: repository 'https://github.com/lxk0301/jd_scripts/' not found
error: Could not fetch origin
HEAD is now at 686686d update

js脚本更新失败，请检查原因或再次运行git_pull.sh...

请问：
1、这是和今天lxk0301大佬的仓库关闭有关系吗？还是因为本人操作导致的问题？
2、有方法解决吗？

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by zxerqw** [comment]
发之前自己看一眼就知道了

**Comment by EvineDeng** [comment]
删了不用就是了

**Comment by ccboxjole** [comment]
> 删了不用就是了

昨天刚装好，今天尝试手动更新了一下，出现更新失败，脚本手动运行还是没问题的，搜索一圈发现只有一个issue有同样的问题，但不是一个系统，个人比较小白，仅能看明白wiki里面和issue的内容，见谅

**Comment by Status-Cai** [comment]
运行git_pull.sh 要输入用户名和密码，现在不能运行 bash git_pull.sh

**Comment by ccboxjole** [comment]
> 运行git_pull.sh 要输入用户名和密码，现在不能运行 bash git_pull.sh

感谢，已经输入了用户名和密码，issues贴出来的是返回值

**Comment by Misaka09982** [comment]
> > 运行git_pull.sh 要输入用户名和密码，现在不能运行 bash git_pull.sh
> 
> 感谢，已经输入了用户名和密码，issues贴出来的是返回值

github仓库已经删除了，现在换到gitee仓库那边去了，你重新建立新的，用gitee版本

**Comment by ccboxjole** [comment]
> > > 运行git_pull.sh 要输入用户名和密码，现在不能运行 bash git_pull.sh
> > 
> > 
> > 感谢，已经输入了用户名和密码，issues贴出来的是返回值
> 
> github仓库已经删除了，现在换到gitee仓库那边去了，你重新建立新的，用gitee版本

好的，正准备这样做
