### ISSUE TITLE
大佬你好，本身已在op里面安装好docker

### ISSUE THREAD

**Issue by minv5** [EvineDeng/jd-base#22]
但是如何实现并发呢？

**Comment by EvineDeng** [comment]
运行多个容器，每个容器分别配置。

**Comment by minv5** [comment]
> 运行多个容器，每个容器分别配置。

我是这样做的，但是运行了后，第二个账号CK也配置好了，但是运行显示需要获取CK

**Comment by EvineDeng** [comment]
仔细看readme和git_pull.sh的注释，有两个必填项，除是cookie之外还有用户数量。
