### ISSUE TITLE
克隆本仓库那里出现-ash: git: not found

### ISSUE THREAD

**Issue by 3136083906** [EvineDeng/jd-base#221]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：openwrt

## 3. 按照以下哪个教程做的

- [x ] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：克隆本仓库步骤出现-ash: git: not found

### (2) 详细日志
A：
-ash: git: not found

### (1) Node.js版本

A：
v12.18.4
### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
仔细读wiki。
