### ISSUE TITLE
解决404问题，替换github remote 方法

### ISSUE THREAD

**Issue by GoToBoy** [EvineDeng/jd-base#223]
//在scripts下,执行git命令

git remote remove origin

git remote add origin https://gitee.com/lxk0301/jd_scripts

git branch --set-upstream-to=origin/master master

**Comment by wanghlstar** [comment]
漂亮~~~~紫薯布丁

**Comment by tanst** [comment]
error: the requested upstream branch 'origin/master' does not exist

**Comment by SuperBambooo** [comment]
Username for 'https://gitee.com': lxk0301                                       
Password for 'https://lxk0301@gitee.com':                                       
remote: lxk0301: Incorrect username or password (access token)                  
fatal: Authentication failed for 'https://gitee.com/lxk0301/jd_scripts/'
这让我输用户名密码怎么办？我是群辉docker

**Comment by GTale** [comment]
> error: the requested upstream branch 'origin/master' does not exist

git pull 更新一下，然后再切换分支

**Comment by chen8148** [comment]
我是群辉中的docker，今天第一次安装仍然卡在这里了，我应该怎么操作？
