### ISSUE TITLE
lxk0301的js地址404了，无法成功运行

### ISSUE THREAD

**Issue by chen8148** [EvineDeng/jd-base#225]
使用群晖的docker安装，容器装好之后看日志停在更新JS脚本这里了“更新JS脚本，原地址https://github.com/lxk0301/jd_scripts”。
访问了一下，发现是地址404了。两个关于404的回复没看明白，可以详细说明一下要怎么操作吗？

**Comment by EvineDeng** [comment]
#224

**Comment by chen8148** [comment]
我是全新安装的，仍然会去github下载
![image](https://user-images.githubusercontent.com/68680455/104733405-9ce75e00-5779-11eb-8994-e7e96a4d860e.png)

**Comment by EvineDeng** [comment]
仔细阅读wiki
