### ISSUE TITLE
手动 git pull 更新脚本要求输入账号和密码

### ISSUE THREAD

**Issue by kissyouhunter** [EvineDeng/jd-base#226]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：openwrt N1 内核5.4.83 docker ce 19.03.12-2

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：手动 git pull 更新脚本要求输入github的账号和密码

### (2) 详细日志
A：root@N1:~# docker exec -it jd bash git_pull

--------------------------------------------------------------

系统时间：2021-01-15 14:23:19

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://github.com/EvineDeng/jd-base

Fetching origin
HEAD is now at 621a899 update

shell脚本更新完成...

--------------------------------------------------------------

更新JS脚本，原地址：https://github.com/lxk0301/jd_scripts

Fetching origin
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/lxk0301/jd_scripts/'
error: Could not fetch origin
HEAD is now at 5fa8605 Merge pull request #650 from DoveBoy/patch-2

js脚本更新失败，请检查原因或再次运行git_pull.sh...

### (1) Node.js版本

A：14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：root@N1:/jd/scripts $ npm install
audited 206 packages in 9.692s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by EvineDeng** [comment]
#224

**Comment by anke1938** [comment]
因为 源代码  js_scripts 在github  已经找不到了.

**Comment by goxofy** [comment]
我刚刚部署了最新版，还是卡在
```
更新JS脚本，原地址：https://github.com/lxk0301/jd_scripts

Fetching origin
```
这里，看了下docker hub里的镜像，最新的也是2天前的

**Comment by liwenjie119** [comment]
lxk0301大佬直接被屏蔽，https://github.com/lxk0301 都没了
