### ISSUE TITLE
[PM2][ERROR] Process or Namespace jd_crazy_joy_coin.js not found

### ISSUE THREAD

**Issue by WoChen5770** [EvineDeng/jd-base#228]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker gitee 最新

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x ] Docker

### (1) 具体问题
A：查看启动日志 出现 [PM2][ERROR] Process or Namespace jd_crazy_joy_coin.js not found

### (2) 详细日志
A：
========================1. 更新源代码========================

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
HEAD is now at 22ad3dd 如果本机上安装了pm2，则挂机程序以pm2启动，否则以nohup启动。

更新JS脚本，原地址：https://gitee.com/lxk0301/jd_scripts

Fetching origin
HEAD is now at 88a7dab fix

========================2. 检测配置文件========================

检测到config配置目录下存在crontab.list，自动导入定时任务...

crond[25]: crond (busybox 1.31.1) started, log level 8
成功添加定时任务...

========================3. 启动挂机程序========================

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
Use --update-env to update environment variables
[PM2][ERROR] Process or Namespace jd_crazy_joy_coin.js not found
[PM2] Starting /jd/scripts/jd_crazy_joy_coin.js in fork_mode (1 instance)
[PM2] Done.
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ jd_crazy_joy_coin    │ default     │ 1.0.0   │ fork    │ 143      │ 0s     │ 0    │ online    │ 0%       │ 29.6mb   │ root     │ disabled │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
挂机程序启动成功...

========================4. 启动控制面板========================

[PM2] Starting /jd/panel/server.js in fork_mode (1 instance)
[PM2] Done.
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ jd_crazy_joy_coin    │ default     │ 1.0.0   │ fork    │ 143      │ 2s     │ 0    │ online    │ 86.7%    │ 50.4mb   │ root     │ disabled │
│ 1   │ server               │ default     │ N/A     │ fork    │ 171      │ 0s     │ 0    │ online    │ 0%       │ 19.4mb   │ root     │ disabled │
└─────┴──────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
控制面板启动成功...

如未修改用户名密码，则初始用户名为：admin，初始密码为：adminadmin

请访问 http://<ip>:5678 登陆并修改配置...

容器启动成功...

Welcome to Node.js v14.15.4.
Type ".help" for more information.

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by WoChen5770** [comment]
疯狗没有挂机

**Comment by kissyouhunter** [comment]
容器更新后也不自动开启了
docker exec -it jd bash jd hangup
显示disable

**Comment by lustime** [comment]
确实 更新后疯狗好像没以前好用了，日志都不打印了

**Comment by EvineDeng** [comment]
@lustime @WoChen5770 @kissyouhunter 不用管error，正常开启的。日志太大，不再记录，直接查看`docker exec -it jd pm2 logs`。

**Comment by kissyouhunter** [comment]
@EvineDeng 看到了 谢谢。更新日志里没有写不再记录日志了，还以为出错了呢。

**Comment by WoChen5770** [comment]
> @lustime @WoChen5770 @kissyouhunter 不用管error，正常开启的。日志太大，不再记录，直接查看`docker exec -it jd pm2 logs`。
> 
> 如要查看有没有运行，也可以输入`docker exec -it jd ps`看看有没有进程。

是我错怪了
