### ISSUE TITLE
手动运行全部脚本功能

### ISSUE THREAD

**Issue by Luxuslaerm** [EvineDeng/jd-base#229]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：N1 openwrt

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：第一次部署好docker之后，不想等定时任务，想手动全部运行一次，wiki里只有运行单条脚本的命令，希望增加一条运行全部脚本的功能

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by SuperManito** [comment]
@Luxuslaerm 我项目里有

touch /home/myid/jd/run-all.sh
bash jd.sh | grep _ >> /home/myid/jd/run-all.sh
sed -i '1d' /home/myid/jd/run-all.sh
sed -i 's/^/bash jd.sh &/g' /home/myid/jd/run-all.sh
sed -i 's/$/& now/g' /home/myid/jd/run-all.sh
sed -i '1i\#!/bin/bash' /home/myid/jd/run-all.sh

**Comment by EvineDeng** [comment]
不提供。你不想麻烦，你就来麻烦我？

**Comment by Luxuslaerm** [comment]
> @Luxuslaerm 我项目里有 #185 下边是代码
> 
> touch /home/myid/jd/run-all.sh
> bash jd.sh | grep _ >> /home/myid/jd/run-all.sh
> sed -i '1d' /home/myid/jd/run-all.sh
> sed -i 's/^/bash jd.sh &/g' /home/myid/jd/run-all.sh
> sed -i 's/$/& now/g' /home/myid/jd/run-all.sh
> sed -i '1i#!/bin/bash' /home/myid/jd/run-all.sh

贴一下我Google研究出来的使用方法，和我一样不会写脚本的小白可以参考一下：

1、首先进入docker，如果你的名字是jd没改的话照抄就行了：`docker exec -it jd /bin/bash` 
2、然后运行大佬的脚本，一行行敲进去就行了，我简单调整了一下位置：
touch run-all.sh
bash jd.sh | grep _ >> run-all.sh
sed -i '1d' run-all.sh
sed -i 's/^/bash jd.sh &/g' run-all.sh
sed -i 's/$/& now/g' run-all.sh
sed -i '1i#!/bin/bash' run-all.sh
3、最后运行脚本大功告成：`sh run-all.sh`

**Comment by xiaobai1988812** [comment]
怎么取消这个邮件通知？各位大佬，我不想一直提示了。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Luxuslaerm&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月16日(星期六) 中午11:52
收件人:&nbsp;&quot;EvineDeng/jd-base&quot;<jd-base@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [EvineDeng/jd-base] 手动运行全部脚本功能 (#229)

**Comment by SuperManito** [comment]
> > @Luxuslaerm

这个命令是进入容器的docker基础命令。。。这个命令的含义是进入容器的终端  我不知道你用的docker在什么环境下用的是什么版本的linux   命令格式是这个  docker exec -it 容器名/容器ID 命令  我的脚本代码只是个思路 但愿你能看懂 还有脚本文件得放在/home/myid/jd目录下才能用

**Comment by Luxuslaerm** [comment]
> > > @Luxuslaerm
> 
> 这个命令是进入容器的docker基础命令。。。这个命令的含义是进入容器的终端 我不知道你用的docker在什么环境下用的是什么版本的linux 命令格式是这个 docker exec -it 容器名/容器ID 命令 我的脚本代码只是个思路 但愿你能看懂 还有脚本文件得放在/home/myid/jd目录下才能用

基本看不懂。。。但是跑起来了达到了我想要的目的。。。感谢~

**Comment by mjyhj** [comment]
> > @Luxuslaerm 我项目里有 #185 下边是代码
> > touch /home/myid/jd/run-all.sh
> > bash jd.sh | grep _ >> /home/myid/jd/run-all.sh
> > sed -i '1d' /home/myid/jd/run-all.sh
> > sed -i 's/^/bash jd.sh &/g' /home/myid/jd/run-all.sh
> > sed -i 's/$/& now/g' /home/myid/jd/run-all.sh
> > sed -i '1i#!/bin/bash' /home/myid/jd/run-all.sh
> 
> 贴一下我Google研究出来的使用方法，和我一样不会写脚本的小白可以参考一下：
> 
> 1、首先进入docker，如果你的名字是jd没改的话照抄就行了：`docker exec -it jd /bin/bash`
> 2、然后运行大佬的脚本，一行行敲进去就行了，我简单调整了一下位置：
> touch run-all.sh
> bash jd.sh | grep _ >> run-all.sh
> sed -i '1d' run-all.sh
> sed -i 's/^/bash jd.sh &/g' run-all.sh
> sed -i 's/$/& now/g' run-all.sh
> sed -i '1i#!/bin/bash' run-all.sh
> 3、最后运行脚本大功告成：`sh run-all.sh`
> 
> 哪里写的不对或者可以优化的地方，大佬帮忙指出


测试无效，直接一直闪所有脚本出来，但是一个都没运行

**Comment by SuperManito** [comment]
> > > @Luxuslaerm 我项目里有 #185 下边是代码
> > > touch /home/myid/jd/run-all.sh
> > > bash jd.sh | grep _ >> /home/myid/jd/run-all.sh
> > > sed -i '1d' /home/myid/jd/run-all.sh
> > > sed -i 's/^/bash jd.sh &/g' /home/myid/jd/run-all.sh
> > > sed -i 's/$/& now/g' /home/myid/jd/run-all.sh
> > > sed -i '1i#!/bin/bash' /home/myid/jd/run-all.sh
> > 
> > 
> > 贴一下我Google研究出来的使用方法，和我一样不会写脚本的小白可以参考一下：
> > 1、首先进入docker，如果你的名字是jd没改的话照抄就行了：`docker exec -it jd /bin/bash`
> > 2、然后运行大佬的脚本，一行行敲进去就行了，我简单调整了一下位置：
> > touch run-all.sh
> > bash jd.sh | grep _ >> run-all.sh
> > sed -i '1d' run-all.sh
> > sed -i 's/^/bash jd.sh &/g' run-all.sh
> > sed -i 's/$/& now/g' run-all.sh
> > sed -i '1i#!/bin/bash' run-all.sh
> > 3、最后运行脚本大功告成：`sh run-all.sh`
> > 哪里写的不对或者可以优化的地方，大佬帮忙指出
> 
> 测试无效，直接一直闪所有脚本出来，但是一个都没运行

很不幸，今天晚上作者刚刚更改了输出信息，这个命令失效了

**Comment by SuperManito** [comment]
> > > @Luxuslaerm 我项目里有 #185 下边是代码
> > > touch /home/myid/jd/run-all.sh
> > > bash jd.sh | grep _ >> /home/myid/jd/run-all.sh
> > > sed -i '1d' /home/myid/jd/run-all.sh
> > > sed -i 's/^/bash jd.sh &/g' /home/myid/jd/run-all.sh
> > > sed -i 's/$/& now/g' /home/myid/jd/run-all.sh
> > > sed -i '1i#!/bin/bash' /home/myid/jd/run-all.sh
> > 
> > 
> > 贴一下我Google研究出来的使用方法，和我一样不会写脚本的小白可以参考一下：
> > 1、首先进入docker，如果你的名字是jd没改的话照抄就行了：`docker exec -it jd /bin/bash`
> > 2、然后运行大佬的脚本，一行行敲进去就行了，我简单调整了一下位置：
> > touch run-all.sh
> > bash jd.sh | grep _ >> run-all.sh
> > sed -i '1d' run-all.sh
> > sed -i 's/^/bash jd.sh &/g' run-all.sh
> > sed -i 's/$/& now/g' run-all.sh
> > sed -i '1i#!/bin/bash' run-all.sh
> > 3、最后运行脚本大功告成：`sh run-all.sh`
> > 哪里写的不对或者可以优化的地方，大佬帮忙指出
> 
> 测试无效，直接一直闪所有脚本出来，但是一个都没运行

这是最新的
touch run-all.sh
bash jd.sh | grep -o 'jd_[a-z].*' > run-all.sh
bash jd.sh | grep -o 'jx_[a-z].*' >> run-all.sh
sed -i 's/^/bash jd.sh &/g' run-all.sh
sed -i 's/$/& now/g' run-all.sh

**Comment by kittyzero520** [comment]
bash jd.sh | grep -o 'jd_[a-z].' > run-all.sh
-------------------------------------------找亮点
bash jd.sh | grep -o 'jd_[a-z].' > >run-all.sh

**Comment by SuperManito** [comment]
> bash jd.sh | grep -o 'jd_[a-z].' > run-all.sh
> -------------------------------------------找亮点
> bash jd.sh | grep -o 'jd_[a-z].' > >run-all.sh

找什么亮点？
