### ISSUE TITLE
大佬你好，初次运行git_pull.sh无法运行

### ISSUE THREAD

**Issue by loverandsky** [EvineDeng/jd-base#23]
~/shell # ./git_pull.sh
/bin/sh: ./git_pull.sh: Permission denied
初次运行卡在这里了
我是OMV5启的docker不知道大佬能否给看看

**Comment by loverandsky** [comment]
~/shell # ls -l git_pull.sh
-rwxrwxrwx 1 root users 17486 Nov  9 22:11 git_pull.sh
已经更改完权限了

**Comment by EvineDeng** [comment]
你试试sh git_pull.sh

不过目前lxk0301主库已被封，暂时用不了

**Comment by doghappy** [comment]
可以把仓储地址指向 Gitee

**Comment by doghappy** [comment]
https://github.com/EvineDeng/jd-base/issues/24

https://gitee.com/lxk0301/scripts
