### ISSUE TITLE
hangup脚本 log位置错误

### ISSUE THREAD

**Issue by 2607627233** [EvineDeng/jd-base#230]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：安卓 Termux

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A： hangup脚本位置创建错误，没有在相应文件内创建，直接创建在了log目录里。 
![Screenshot_20210116-095352](https://user-images.githubusercontent.com/43110396/104794137-b2dc3980-57e0-11eb-9381-97e446f586f1.png)
![Screenshot_20210116-095425](https://user-images.githubusercontent.com/43110396/104794157-cab3bd80-57e0-11eb-9e6b-dc5bb661051f.png)

### (2) 详细日志
A：

### (1) Node.js版本

A：v12.18.3

### (2) npm版本

A：6.14.60

### (3)npm install的日志

A：npm WARN saveError ENOENT: no such file or directory, open '/storage/emulated/0/jd/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/storage/emulated/0/jd/package.json'
npm WARN jd No description
npm WARN jd No repository field.
npm WARN jd No README data
npm WARN jd No license field.

up to date in 2.909s
found 0 vulnerabilities

**Comment by EvineDeng** [comment]
已修复，你更新代码后再重启挂机程序看看？

**Comment by 2607627233** [comment]
> 已修复，你更新代码后再重启挂机程序看看？

没问题了
