### ISSUE TITLE
lxk0301搬家了，搞不定了？

### ISSUE THREAD

**Issue by shenzt68** [EvineDeng/jd-base#231]
lxk0301搬家了，搞不定了。
git clone https://gitee.com/lxk0301/jd_scripts后，配置好 docker-compose.yml
然后运行：
docker-compose up -d
docker-compose logs，显示：

##############################################################################

Container start , Pull the latest code...

容器启动，git 拉取最新代码...

永远就停在这了，为什么？怎样搞定呢？

**Comment by EvineDeng** [comment]
这不是我的docker

**Comment by xiaobai1988812** [comment]
怎么取消这个邮件订阅，一直弹……------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;EvineDeng&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月16日(星期六) 中午11:39
收件人:&nbsp;&quot;EvineDeng/jd-base&quot;<jd-base@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [EvineDeng/jd-base] lxk0301搬家了，搞不定了？ (#231)

**Comment by gnowmil** [comment]
> 怎么取消这个邮件订阅，一直弹……------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;EvineDeng&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月16日(星期六) 中午11:39 收件人:&nbsp;&quot;EvineDeng/jd-base&quot;<jd-base@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [EvineDeng/jd-base] lxk0301搬家了，搞不定了？ (#231)

在右上角watch按钮里设置，不会的话取消watch即可。
