### ISSUE TITLE
config.sh注释笔误

### ISSUE THREAD

**Issue by chenyitian2004** [EvineDeng/jd-base#235]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：config.sh关于疯狂的joy自动购买的等级最后是不是应该为“解除注释”？

### (2) 详细日志
A：
```
################################## 疯狂的JOY（选填） ##################################
## 疯狂的JOY循环助力，"true" 表示循环助力，"false" 表示不循环助力，默认 "false"
export JDJOY_HELPSELF="true"

## 疯狂的JOY京豆兑换，目前最小值为500/1000京豆，默认为 "0" 不开启京豆兑换
export JDJOY_APPLYJDBEAN="2000"

## 疯狂的JOY自动购买什么等级的JOY，如需要使用请自行**解释注释**
export BUY_JOY_LEVEL="28"
```

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
是笔误，下次升版时更新吧。
