### ISSUE TITLE
 jd_bean_sign自动任务产生的log异常

### ISSUE THREAD

**Issue by solodarker** [EvineDeng/jd-base#237]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Docker版本 | 19.03.12

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [ x] Docker

### (1) 具体问题
A： jd_bean_sign自动任务时，产生的log为0kb，签到情况实际为部分签到过，而且并无推送消息。
手动运行 jd_bean_sign now产生的log为正常的。签到情况实际为全部签到过，推送消息正常。

### (2) 详细日志
A：日志为0kb无法提供。相同的openwrt，相同的docker版本，不同的部署方法，在原作者github未404时候，部署github时候的推送一切正常。github404之后，更新docker的gitee部署方法，开始异常。容器完全重新部署，重新配置也无作用

### (1) Node.js版本

A：v12.16.1

### (2) npm版本

A：-ash: npm: not found 

### (3)npm install的日志

A：无

**Comment by solodarker** [comment]
再补充一下。除了jd_bean_sign日志异常，其他脚本产出的日志均为正常的日志，推送消息也正常！！

**Comment by EvineDeng** [comment]
更新镜像到昨天的版本试试？
