### ISSUE TITLE
 bash export_sharecodes.sh 获取互助码信息异常

### ISSUE THREAD

**Issue by TheSaltwaterRoom** [EvineDeng/jd-base#239]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A： bash export_sharecodes.sh 获取互助码信息异常

### (2) 详细日志
A：
签到领现金：
codes=$(perl
-0777
-pe
"s|\*+\n+||g"
${log}
|
grep
-${Opt}
"："
|
perl
-pe
"{s|\*+开始||g;
s|：|：|g}")

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：up to date in 0.877s

11 packages are looking for funding
  run `npm fund` for details

**Comment by EvineDeng** [comment]
perl装好了？

**Comment by TheSaltwaterRoom** [comment]
perl装好了，刚才又执行了一遍，好了
