### ISSUE TITLE
添加crontab 报错

### ISSUE THREAD

**Issue by viabytsai** [EvineDeng/jd-base#242]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：乌班图18

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：按照教程添加定时任务的时候报错，上百度查了一下说是定时的格式有错误 看来一圈找不到错误

### (2) 详细日志
A："config/crontab.list":2: bad minute
       errors in crontab file, can't install

### (1) Node.js版本

A：14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
程序说有错就是有错。

**Comment by RikudouPatrickstar** [comment]
crontab.list 怎么写的，贴出来大家看看
