### ISSUE TITLE
东东农场内置号码助力满了，不能给随机号助力

### ISSUE THREAD

**Issue by hzzhy1987** [EvineDeng/jd-base#244]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：东东农场内置号码助力满了，不能给随机号助力

### (2) 详细日志
A：开始【京东账号1】XXXXXXXX

第1个京东账号将要助力的好友["e6e04602d5e343258873af1651b603ec","52801b06ce2a462f95e1d59d7e856ef4","5bc73a365ff74a559bdee785ea97fcc5"]

【京东账号1（XXXXXXXX）的东东农场好友互助码】60e8f6ac4c884564a89f1b2dceb78b88

【已成功兑换水果】4次

开始助力好友
格式化后的助力码::["e6e04602d5e343258873af1651b603ec","52801b06ce2a462f95e1d59d7e856ef4","5bc73a365ff74a559bdee785ea97fcc5"]

开始助力京东账号1 - XXXXXXXX的好友: e6e04602d5e343258873af1651b603ec
【助力好友结果】: 好友【Evine】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号1 - XXXXXXXX的好友: 52801b06ce2a462f95e1d59d7e856ef4
【助力好友结果】: 好友【做一颗潇洒的蛋蛋】已满五人助力
【今日助力次数还剩】3次

开始助力京东账号1 - XXXXXXXX的好友: 5bc73a365ff74a559bdee785ea97fcc5
【助力好友结果】: 好友【米大眼老鼠】已满五人助力
【今日助力次数还剩】3次

助力好友结束，即将开始领取额外水滴奖励

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
这应该是js的逻辑。
