### ISSUE TITLE
jd命令没有权限

### ISSUE THREAD

**Issue by liwenjie119** [EvineDeng/jd-base#245]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker最新版

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：进入到docker 直接执行jd命令，提示Permission denied。需要给777权限。看了Dockerfile没有给权限。
看了wiki，所有命令需要以bash开头，实际上既然已经连接到 /usr/local/bin/jd，给了权限直接执行jd+具体项目就行，不需要多个bash
### (2) 详细日志
A：
bash: /usr/local/bin/jd: Permission denied

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：非此问题

**Comment by EvineDeng** [comment]
我早就知道了。你更新试代码后再试试？
