### ISSUE TITLE
京喜农场助力失败

### ISSUE THREAD

**Issue by suadam1984** [EvineDeng/jd-base#246]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：openwrt MIPS版

## 3. 按照以下哪个教程做的

- [x ] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：京喜农场助力失败,APP种子已提供了TOKEN

### (2) 详细日志
A：邀请码提交失败 API 返回异常
即将助力 share code：8c162584b45c33dbce14a80be7079f6c
助力结果：ret=1011 retmsg="shareuser not join this active"
即将助力 share code：b27eef51f7493b6594f26750cf2233ca
助力结果：ret=1011 retmsg="shareuser not join this active"
即将助力 share code：04634f65bb0cb154b1c7d44ad653a431
助力结果：ret=1011 retmsg="shareuser not join this active"
即将助力 share code：e8dd4ed6a87055a2b37982066d8910da
助力结果：ret=1011 retmsg="shareuser not join this active"
即将助力 share code：7d645f46ad80cddf7d6d91b4fc39f572
助力结果：ret=1011 retmsg="shareuser not join this active"
即将助力 share code：22bd6fbbabbaa770a45ab2607e7a1e8a
助力结果：ret=1011 retmsg="shareuser not join this active"
即将助力 share code：197c6094e965fdf3d33621b47719e0b1
助力结果：ret=1011 retmsg="shareuser not join this active"
获取随机助力码失败 API 返回异常

### (1) Node.js版本

A：V12.18.4

### (2) npm版本

A：6.14.6

### (3)npm install的日志

A：非此问题

**Comment by FanchangWang** [comment]
- 你应该去上游仓库提 issue ，不应该再这里
- ret=1011  可能对方种植的 active 种子跟你的不一样或 APP 专属种子

**Comment by suadam1984** [comment]
> * 你应该去上游仓库提issue，不应该再这里
> * ret = 1011可能对方种植的active种子跟你的不一样或APP专属种子

好的，你们有这种情况吗？助力需要是同一种种子吗？

**Comment by FanchangWang** [comment]
> > * 你应该去上游仓库提issue，不应该再这里
> > * ret = 1011可能对方种植的active种子跟你的不一样或APP专属种子
> 
> 好的，你们有这种情况吗？助力需要是同一种种子吗？

这个提示几乎是必然的，脚本中有对 1011 的容错次数，一般不需要管他

**Comment by suadam1984** [comment]
> > > * 你应该去上游仓库提issue，不应该再这里
> > > * ret = 1011可能对方种植的active种子跟你的不一样或APP专属种子
> > 
> > 
> > 好的，你们有这种情况吗？助力需要是同一种种子吗？
> 
> 这个提示几乎是必然的，脚本中有对 1011 的容错次数，一般不需要管他

好的，谢谢，那就不管了

**Comment by suadam1984** [comment]
> * 你应该去上游仓库提 issue ，不应该再这里
> * ret=1011  可能对方种植的 active 种子跟你的不一样或 APP 专属种子

看了上游的助力脚本，的确是要同一种子才能助力成功
