### ISSUE TITLE
新增年货节互助码

### ISSUE THREAD

**Issue by Taffyw** [EvineDeng/jd-base#248]
你好，麻烦更新下shareCodes，新增了一个年货节的互助码

**Comment by wxjbb** [comment]
同求，谢谢大佬

**Comment by zlfonline** [comment]
自己把jd.sh和config.sh修改了，追加对应助力码，先这么用着，等作者更新代码。

**Comment by xjw00654** [comment]
> 自己把jd.sh和config.sh修改了，追加对应助力码，先这么用着，等作者更新代码。

@zlfonline 你遇到这个错了么，我改完之后碰着了，像是脚本的问题 ?

```
❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'bizCode' of undefined
    at /jd/scripts/jd_nian.js:471:32
    at got.post.then.message (/jd/scripts/jd_nian.js:634:5694)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by suadam1984** [comment]
> > 自己把jd.sh和config.sh修改了，追加对应助力码，先这么用着，等作者更新代码。
> 
> @zlfonline 你遇到这个错了么，我改完之后碰着了，像是脚本的问题 ?
> 
> ```
> ❗️京东炸年兽🧨, 错误!
> TypeError: Cannot read property 'bizCode' of undefined
>     at /jd/scripts/jd_nian.js:471:32
>     at got.post.then.message (/jd/scripts/jd_nian.js:634:5694)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> ```

没有改也有这个错误

**Comment by hacken156026692** [comment]
我正常的嘛
