### ISSUE TITLE
手动执行就可以获取到cookie可以正常运行，crontab执行所有都获取不到cookie

### ISSUE THREAD

**Issue by jack1256131** [EvineDeng/jd-base#249]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Mac OS 11.0.1 

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：手动执行就可以获取到cookie可以正常运行，crontab执行所有都获取不到cookie

### (2) 详细日志
A：
🔔金融养猪, 开始!

====================共有0个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：1/18/2021, 11:27:07 AM=====================

==============📣系统通知📣==============
金融养猪
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/bean/signIndex.action

🔔金融养猪, 结束! 🕛 0.026 秒

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10
### (3)npm install的日志

A：audited 206 packages in 1.872s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │      New patch version of npm available! 6.14.10 → 6.14.11      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.11   │
   │                Run npm install -g npm to update!                │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

**Comment by lustime** [comment]
git_pull这个任务可以让用户自己配置嘛 每次修改完,跑一次就自动覆盖。。以前的1小时更新一次蛮好的。。

**Comment by jack1256131** [comment]
> git_pull这个任务可以让用户自己配置嘛每次修改完，跑一次就自动覆盖。。以前的1小时更新一次蛮好的。。

就是每次配置完都要运行一次git_pull就可以了是吗？

**Comment by EvineDeng** [comment]
> > git_pull这个任务可以让用户自己配置嘛每次修改完，跑一次就自动覆盖。。以前的1小时更新一次蛮好的。。
> 
> 就是每次配置完都要运行一次git_pull就可以了是吗？

不是。

另外 ，你这个问题很难判断是哪里的问题。

**Comment by jack1256131** [comment]
> > > git_pull这个任务可以让用户自己的配置嘛每次修改完，跑一次就自动覆盖。。以前的1小时更新一次蛮好的。。
> > 
> > 
> > 就是每次配置完都要运行一次git_pull就可以了是吗？
> 
> 不是。
> 
> 另外，你这个问题很难判断是哪里的问题。

挂机程序那个脚本有什么作用？

**Comment by zilong-zZ** [comment]
我也遇到这个问题
Mac os 10.15.6
(1) Node.js版本
A：v12.10.0

(2) npm版本
A：6.14.5

(3)npm install的日志
audited 206 packages in 2.341s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by EvineDeng** [comment]
有按crontab.list中的注释操作吗

**Comment by zilong-zZ** [comment]
我想我知道原因了

**Comment by jack1256131** [comment]
> which node
好的，谢谢，我试一下
我的node 路径（/usr/local/bin//node）多了个/会有什么问题吗？

**Comment by jack1256131** [comment]
> 我想我知道原因了
> 
> ```
> ############ 第2步 ############
> ## 依次输入which node、which npm、which git、which perl，检查node、npm、git、perl的路径，如路径不在刚刚修改的PATH中，则将路径添加在PATH最前面，并以冒号分隔
> ```
> 
> 之前我将路径添加在最后面了，把路径修改到前面，crontab执行能正常获取到cookie了！
> @ jack1256131 @EvineDeng

好的，谢谢，我试一下
我的node路径（/ usr / local / bin // node）多了个/会有什么问题吗？
@zilong-zZ @EvineDeng

**Comment by huangzi959** [comment]
我也是，自动执行cookie获取不了，路径也添加了。手动执行没问题。

**Comment by EvineDeng** [comment]
@huangzi959 @zilong-zZ @lustime 不懂PATH原理的，都自己百度学习PATH去，空日志、手动执行没问题，自动执行有问题，都是PATH的问题，不想解释。

**Comment by lustime** [comment]
> @huangzi959 @zilong-zZ @lustime 不懂PATH原理的，都自己百度学习PATH去，空日志、手动执行没问题，自动执行有问题，都是PATH的问题，不想解释。

我没问题～～～我也懂PATH原理～
