### ISSUE TITLE
炸年兽脚本日志错误

### ISSUE THREAD

**Issue by grey27** [EvineDeng/jd-base#254]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：阿里云服务器Ubuntu 18.04.3 LTS镜像

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：新增炸年兽活动日志报错

### (2) 详细日志
A：
******开始【京东账号1】grey27*********

开始
第1个京东账号将要助力的好友["cgxZWifbeu-Wpm2AD0bol5Cu","cgxZ-tAo8DJqM5xu3ogeOY7OXkOQ2Lw_ympGPITqNcceAad8Y1ph2UOXS-LOq3PUCqmgYjpt-td3CYw18qw","cgxZdTXtIrzev12aC1eu5yr9cCz6N7HkgPrFkYPPzBDaaWjtjA3fokuFPMA","cgxZLWaFIb7S4gvPZ1jlo3Ru3_zhiy3nnTsS4mQaaZc"]
当前爆竹55497🧨，下一关需要237000🧨
可收取的爆竹大于0，去收取爆竹
收取成功，获得901爆竹🧨
当前已开启的地图：小镇车站 
去做OLAY店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /home/myid/jd/scripts/jd_nian.js:566:46
    at got.post.then.message (/home/myid/jd/scripts/jd_nian.js:953:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
去做宝洁店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /home/myid/jd/scripts/jd_nian.js:566:46
    at got.post.then.message (/home/myid/jd/scripts/jd_nian.js:953:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
去做蒙牛店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at /home/myid/jd/scripts/jd_nian.js:566:46
    at got.post.then.message (/home/myid/jd/scripts/jd_nian.js:953:5694)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
随机取20个码放到您固定的互助码后面(不影响已有固定互助)
去做欧莱雅店铺任务

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
提错地方了

**Comment by jonanqe** [comment]
我docker也是一样问题，替换原脚本文件后就没问题了
