### ISSUE TITLE
Linux炸年兽更新完后有报错

### ISSUE THREAD

**Issue by chxmtl2** [EvineDeng/jd-base#255]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：虚拟机centos8

## 3. 按照以下哪个教程做的

- [x ] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：上午自动执行pull之后是可以正常的运行，下午手动又执行了一遍git_pull，并修改了config添加了互助码，原来的jd_sh也添加了更新的内容（删除了也没用），

### (2) 详细日志
A：
🔔京东炸年兽🧨, 开始!
您的cookie选择的是用&隔开

====================共有3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：1/18/2021, 5:40:29 PM=====================

开始获取京东炸年兽🧨配置文件

共3个京东账号

您提供了3个账号的京东炸年兽🧨助力码

******开始【京东账号1】1234*********

开始
随机取20个码放到您固定的互助码后面(不影响已有固定互助)
第1个京东账号将要助力的好友["cgxZdTXtILvd6wrIDgT_7pN7U5dvYK4v9VMck2ZO42scwP_vFHvX78G6O7M","cgxZWifbeu-Wpm2AD0bol5Cu","cgxZ-tAo8DJqM5xu3ogeOY7OXkOQ2Lw_ympGPITqNcceAad8Y1ph2UOXS-LOq3PUCqmgYjpt-td3CYw18qw","cgxZdTXtIrzev12aC1eu5yr9cCz6N7HkgPrFkYPPzBDaaWjtjA3fokuFPMA","cgxZLWaFIb7S4gvPZ1jlo3Ru3_zhiy3nnTsS4mQaaZc","cgxZag6FIb7d4gyYXVavvC2nn7OZb7KZ-xXHwJbx7khb4hz1WYOBChM","cgxZdTXtIOjf6wqcCAz67wfVdPCzan1OSgEpaQanrG8SvNW9c4AtmHyNjEQ","cgxZLmOKILPf4gzOFQCo50mI7-lGMqh5ANFRrVjIJnV_b8Y5YerkVdsjYDA","cgxZbD_cIrjcpkKqZ1TUq6cOpPw","cgxZdTXtILjT6g_PAFH_7DUIT70-1F2Ogs-fZ_Axa2MeMkzoel2uuIGrXfg","cgxZdTXtIumJ7l_AWlP_uxEYfuohOJbugUTL6TUyY1mtwkkPm71CD7njpGQ","cgxZdTXtI7_cuVvOWwyq7nkcIvJfSWpMAPcQWIWvd6PCyVk7VNiT9bm907A","cgxZdTXtIrLb6lrPCw2oujgukXrePS8yVYFpfcJvrSSwHAYhxL54hFNKtYU","AAJgAa2TADCsUtmIWz4mYSIA5SqRCKSvxwvLHCKLUB1T4OHooUxtHI9LJeEykSa2oWjS_TKAHZE"," cgxZZiTaYeuAs1-XCUnljNsg1EWWeOyf2VoOXXsE","cgxZdTXtIO7b7V3LXles5nP2gg1n8DXvuB-pcOuYRW9TWMKBNzWulHtHtew","cgxZZTLIY-CCpkKqAX6t6oLHsOQ","cgxZLGmCIL_f4gzKZ1jlo5mFbJ2njbq37DHaJ4SFyh4","cgxZdTXtIO-Jvw_PDgarvmRVpvvzQbAuiAlo08dWp4xBpqFRSQYKihLoiWQ","cgxZczSHIL_e4gnKREnK6wvJYLabqWd2CMNC","cgxZdTXtUcOGv0ySXV70s-STAvvWE0jZpm7wSekWsLTsH6jF2Ycp6D0","cgxZdTXtUsOevVOMVWHdlCEirrtxlSBJiT4P-YEx9XDFP7UIA1zMK-8","cgxZdTXtIL2IuFybAAaquhmia6q7p3uuCxlOPwVH5AXoPULCeG2c5B0cjRI","cgxZdTXtIu_bu1uYCVGr5wIUBYtzfxVBBvAHRO7rxkpEEbYVBFBdvzprOxg","cgxZdTXtIezcvwnLDAeh6FyjkRo-uVTrZ3CRV5eRYrHoA7raWdkU02mJva4"]

当前爆竹21808🧨，下一关需要327000🧨
可收取的爆竹大于0，去收取爆竹
收取成功，获得314爆竹🧨
当前已开启的地图：小镇车站 
去做OLAY店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at $.post (/home/ipi/jd/scripts/jd_nian.js:566:46)
    at got.post.then.t (/home/ipi/jd/scripts/jd_nian.js:953:5694)
    at process._tickCallback (internal/process/next_tick.js:68:7)
去做宝洁店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at $.post (/home/ipi/jd/scripts/jd_nian.js:566:46)
    at got.post.then.t (/home/ipi/jd/scripts/jd_nian.js:953:5694)
    at process._tickCallback (internal/process/next_tick.js:68:7)
去做蒙牛店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at $.post (/home/ipi/jd/scripts/jd_nian.js:566:46)
    at got.post.then.t (/home/ipi/jd/scripts/jd_nian.js:953:5694)
    at process._tickCallback (internal/process/next_tick.js:68:7)
去做欧莱雅店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at $.post (/home/ipi/jd/scripts/jd_nian.js:566:46)
    at got.post.then.t (/home/ipi/jd/scripts/jd_nian.js:953:5694)
    at process._tickCallback (internal/process/next_tick.js:68:7)
去做伊利店铺任务

❗️京东炸年兽🧨, 错误!
TypeError: Cannot read property 'taskVos' of undefined
    at $.post (/home/ipi/jd/scripts/jd_nian.js:566:46)
    at got.post.then.t (/home/ipi/jd/scripts/jd_nian.js:953:5694)
    at process._tickCallback (internal/process/next_tick.js:68:7)

❌ 京东炸年兽🧨, 失败! 原因: TypeError: $.taskVos is not iterable!

🔔京东炸年兽🧨, 结束! 🕛 13.652 秒

### (1) Node.js版本

A：v10.21.0

### (2) npm版本

A：6.14.4

### (3)npm install的日志

A：audited 206 packages in 5.503s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by chxmtl2** [comment]
--------------------------------------------------------------

系统时间：2021-01-18 17:07:03

SHELL脚本目录：/home/ipi/jd

JS脚本目录：/home/ipi/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
From https://gitee.com/evine/jd-base
   d74e0c5..6129b88  v3         -> origin/v3
   d74e0c5..6129b88  dev        -> origin/dev
HEAD is now at 6129b88 兼容Docker中运行的Linux，去除isDocker判断。

shell脚本更新完成...

--------------------------------------------------------------

更新JS脚本，原地址：https://gitee.com/lxk0301/jd_scripts

Fetching origin
From https://gitee.com/lxk0301/jd_scripts
   de77746..e3815aa  master     -> origin/master
HEAD is now at e3815aa Merge pull request #46 from iouAkira/patch-1

js脚本更新完成...

检测到配置文件config.sh.sample有更新

更新日期: 2021-01-18
当前版本: 3.14.0
新的版本: 3.15.0
更新内容: 增加全民炸年兽活动助力环境变量。

如需使用新功能按该文件前几行注释操作，否则请无视本消息。


🔔通知, 开始!
您未提供push+推送所需的PUSH_PLUS_TOKEN，取消push+推送消息通知

server酱发送通知消息成功

您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知

您未提供telegram机器人推送所需的TG_BOT_TOKEN和TG_USER_ID，取消telegram推送消息通知

您未提供钉钉机器人推送所需的DD_BOT_TOKEN或者DD_BOT_SECRET，取消钉钉推送消息通知

您未提供企业微信机器人推送所需的QYWX_KEY，取消企业微信推送消息通知

您未提供企业微信应用消息推送所需的QYWX_AM，取消企业微信应用消息推送消息通知

您未提供iGot的推送IGOT_PUSH_KEY，取消iGot推送消息通知

您未提供酷推的SKEY，取消QQ推送消息通知


🔔通知, 结束! 🕛 2.634 秒


--------------------------------------------------------------

系统时间：2021-01-18 17:33:50

SHELL脚本目录：/home/ipi/jd

JS脚本目录：/home/ipi/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
HEAD is now at 6129b88 兼容Docker中运行的Linux，去除isDocker判断。

shell脚本更新完成...

--------------------------------------------------------------

更新JS脚本，原地址：https://gitee.com/lxk0301/jd_scripts

Fetching origin
HEAD is now at e3815aa Merge pull request #46 from iouAkira/patch-1

js脚本更新完成..

**Comment by vForce825** [comment]
+1 我也有同样的报错，同Linux

**Comment by tlz328522853** [comment]
怎么获取互助码

**Comment by EvineDeng** [comment]
#254
