### ISSUE TITLE
gitee更新出错

### ISSUE THREAD

**Issue by yswcdmm** [EvineDeng/jd-base#259]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker

## 3. 按照以下哪个教程做的

- [x] Linux
- [x] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：gitee 自动更新出现错误，但是手动执行git_pull.sh 可以更新

### (2) 详细日志
A：
系统时间：2021-01-19 15:55:00

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403
fatal: the remote end hung up unexpectedly
error: Could not fetch origin
HEAD is now at 6129b88 兼容Docker中运行的Linux，去除isDocker判断。

shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...

/usr/local/bin/git_pull: line 371: [: -eq: unary operator expected
js脚本更新失败，请检查原因或再次运行git_pull.sh...

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
每次还是偶尔 ？

**Comment by yswcdmm** [comment]
> 每次还是偶尔？

从今天9点55分开始 每一次高兴都出现403错误。但是手动更新但是没有问题

**Comment by EvineDeng** [comment]
试试重启大法

**Comment by suadam1984** [comment]
看日志最近几次自动js脚本更新都失败了

**Comment by EvineDeng** [comment]
> 看日志最近几次自动js脚本更新都失败了

如果是docker重启下

**Comment by suadam1984** [comment]
> > 看日志最近几次自动js脚本更新都失败了
> 
> 如果是docker重启下

路由器OPENWRT MIPS版，每天都会重启，下午的更新都失败了，手动可以

**Comment by EvineDeng** [comment]
> > > 看日志最近几次自动js脚本更新都失败了
> > 
> > 
> > 如果是docker重启下
> 
> 路由器OPENWRT MIPS版，每天都会重启，下午的更新都失败了，手动可以

那就很奇怪了，只要手动能运行，说明脚本是没问题的。其他具体什么原因，你们再观察下吧。

**Comment by lin-xh** [comment]
> > > > 看日志最近几次自动js脚本更新都失败了
> > > 
> > > 
> > > 如果是docker重启下
> > 
> > 
> > 路由器OPENWRT MIPS版，每天都会重启，下午的更新都失败了，手动可以
> 
> 那就很奇怪了，只要手动能运行，说明脚本是没问题的。其他具体什么原因，你们再观察下吧。

日志里还有这个提示：Repository more than 5 connections
所以，可能是同一时间（5-23，每小时的第55分钟）有大量的请求，导致出错了。
改回原来的随机时间？

**Comment by EvineDeng** [comment]
> > > > > 看日志最近几次自动js脚本更新都失败了
> > > > 
> > > > 
> > > > 如果是docker重启下
> > > 
> > > 
> > > 路由器OPENWRT MIPS版，每天都会重启，下午的更新都失败了，手动可以
> > 
> > 
> > 那就很奇怪了，只要手动能运行，说明脚本是没问题的。其他具体什么原因，你们再观察下吧。
> 
> 日志里还有这个提示：Repository more than 5 connections
> 可能是同一时间（5-23，每小时的第55分钟）有大量的请求，导致出错了。
> 
> 现在手动更新之后，crontab.list文件中是这样的
> 55 5-23 * * * bash git_pull >> ${JD_DIR}/log/git_pull.log 2>&1
> 
> 所以，换回原来的随机时间？

我也怀疑是同一时间大量请求同时向gitee发起请求导致的。

又有一个 #263

**Comment by EvineDeng** [comment]
@yswcdmm @lin-xh @suadam1984 @GoToBoy 

解决办法见 #292
