### ISSUE TITLE
脚本仓库重建了，我们需要自己改还是等老板你这边更新就可以了？

### ISSUE THREAD

**Issue by sofs2005** [EvineDeng/jd-base#26]
是不是等老板你的脚本更新后再拉一遍就行了？

**Comment by EvineDeng** [comment]
1. 删除原来的scripts文件夹，其他文件夹可以全部保留（无论物理机还是docker均如此）；
2. 重新按readme配置。

**Comment by ibelieve3212** [comment]
提示js脚本获取不正常，请手动克隆。。
