### ISSUE TITLE
git_pull.sh 106行的perl指令 中替换操作可能有点问题。

### ISSUE THREAD

**Issue by dpawsbear** [EvineDeng/jd-base#260]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Centos | Linux localhost.localdomain 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## 3. 按照以下哪个教程做的

- [ x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：git_pull.sh 中106行的perl代码替换 let invite_pins = [""] 以及 let run_pins = [""] 部分时会把头部替换掉，变成纯字符串。
像下面这样子：
```bash
//此处填入你需要助力好友的京东用户名
//下面给出好友邀请助力的示例填写规则
K047913674_p,Evine,做一颗潇洒的蛋蛋,Evine007,jd_7bb2be8dbd65c,jd_6fae2af082798,jd_664ecc3b78945,277548856_m,米大眼老鼠,jd_6cd93e613b0e5,被折叠的记忆33,jd_704a2e5e28a66,jd_45a6b5953b15b,zooooo58,jd_66f5cecc1efcd,jd_41345a6f96aa5"];
//下面给出好友赛跑助力的示例填写规则
K047913674_p,Evine,做一颗潇洒的蛋蛋,Evine007,jd_7bb2be8dbd65c,jd_6fae2af082798,jd_664ecc3b78945,277548856_m,米大眼老鼠,被折叠的记忆33,jd_6cd93e613b0e5,jd_66f5cecc1efcd,jd_sIhNpDXJehOr,jd_41345a6f96aa5,jd_704a2e5e28a66,zooooo58"];
```
这里替换掉的文件是 jd_joy_run.js 

### (2) 详细日志
A：这部分我已经分析过一次了，没有日志。

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：和npm应该关系不大。

**Comment by EvineDeng** [comment]
你cookie1的pin是以写数字开头的吗

**Comment by dpawsbear** [comment]
> 你cookie1的pin是以写数字开头的吗？看看这个#113

确实是数字开头的，刚才还没搜索到，抱歉，我也看了一圈perl发现我解决不了上来发issue。。。。
