### ISSUE TITLE
git 自动更新脚本失败

### ISSUE THREAD

**Issue by Yvan0329** [EvineDeng/jd-base#263]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：
Docker
## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：自动更新脚本失败

### (2) 详细日志
A：
系统时间：2021-01-19 15:55:00

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
remote: [31mRepository more than 5 connections.[0m
fatal: unable to access 'https://gitee.com/evine/jd-base/': The requested URL returned error: 403
error: Could not fetch origin
HEAD is now at 6129b88 兼容Docker中运行的Linux，去除isDocker判断。

shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...

/usr/local/bin/git_pull: line 371: [: -eq: unary operator expected
js脚本更新失败，请检查原因或再次运行git_pull.sh...

--------------------------------------------------------------

系统时间：2021-01-19 16:55:00

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
remote: [31mRepository more than 5 connections.[0m
fatal: unable to access 'https://gitee.com/evine/jd-base/': The requested URL returned error: 403
error: Could not fetch origin
HEAD is now at 6129b88 兼容Docker中运行的Linux，去除isDocker判断。

shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...

/usr/local/bin/git_pull: line 371: [: -eq: unary operator expected
js脚本更新失败，请检查原因或再次运行git_pull.sh...

--------------------------------------------------------------

系统时间：2021-01-19 17:55:00

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
From https://gitee.com/evine/jd-base
   6129b88..e2e0170  v3         -> origin/v3
   6129b88..e2e0170  dev        -> origin/dev
HEAD is now at e2e0170 Optimized code

shell脚本更新完成...

--------------------------------------------------------------

更新JS脚本，原地址：https://gitee.com/lxk0301/jd_scripts

Fetching origin
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403
fatal: the remote end hung up unexpectedly
error: Could not fetch origin
HEAD is now at bf7d822 Merge pull request #59 from DoveBoy/patch-2

js脚本更新失败，请检查原因或再次运行git_pull.sh...

--------------------------------------------------------------

系统时间：2021-01-19 18:55:00

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
HEAD is now at e2e0170 Optimized code

shell脚本更新完成...

--------------------------------------------------------------

更新JS脚本，原地址：https://gitee.com/lxk0301/jd_scripts

Fetching origin
remote: [31mRepository more than 5 connections.[0m
fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': The requested URL returned error: 403
error: Could not fetch origin
HEAD is now at bf7d822 Merge pull request #59 from DoveBoy/patch-2

js脚本更新失败，请检查原因或再次运行git_pull.sh...

手动更新没有问题，自动更新出现以上错误

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
我怀疑是gitee的问题。

**Comment by Yvan0329** [comment]
@EvineDeng 我是docker同时启动了六个容器，六个容器同一时间点拉取gitee代码，会不会是因为这个问题，如果开多个的话，在每个整点50-59分之间更新会不会能解决这个问题呢？

**Comment by Yvan0329** [comment]
@EvineDeng 因为手动更新都可以，但是手动更新是进去容器一个一个更新的，我觉得问题可能在这。我之前是开一个，好像没出现过这个问题。

**Comment by Yvan0329** [comment]
@EvineDeng 6个容器同时更新的话，有成功的，但是可能4个或者5个都是上面的错误。

**Comment by Yvan0329** [comment]
@EvineDeng 我觉得分钟加个随机数可能是可以解决这个问题的

**Comment by EvineDeng** [comment]
不仅是你，是所有用户都在那个时候更新，所以我建议你把每个docker的cron设置为和大部队不一样，或者切换github镜像。

**Comment by shusheng110** [comment]
vi 进到 git_pull.sh   371行  -eq  换成 =  然后  bash git_pull.sh 运行一次就好了

**Comment by lustime** [comment]
同更新失败

**Comment by Yvan0329** [comment]
把更新时间55分改成不一样的分钟数可以解决。

**Comment by HowToLoveChina** [comment]
--------------------------------------------------------------

更新shell脚本，原地址：https://github.com/EvineDeng/jd-base

正在获取 origin
HEAD 现在位于 b2b580b Fix

shell脚本更新完成...

--------------------------------------------------------------

更新LXK9301脚本，原地址：https://github.com/LXK9301/jd_scripts

正在获取 origin
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/lxk0301/jd_scripts/'
error: 不能获取 origin
HEAD 现在位于 cd33b4f Update jd_dreamFactory.js

更新shylocks脚本，原地址：https://github.com/shylocks/Loon

正在获取 origin
HEAD 现在位于 639483d 开卡活动

js脚本更新失败，请检查原因或再次运行git_pull.sh...


手动执行提示需要用户名和密码，这是什么情况

**Comment by oOyH** [comment]
> 更新shell脚本，原地址：https://github.com/EvineDeng/jd-base
> 
> 正在获取 origin
> HEAD 现在位于 [b2b580b](https://github.com/EvineDeng/jd-base/commit/b2b580baf5ca20529cf5fe82be98c0ead2eb3ea6) Fix
> 
> shell脚本更新完成...
> 
> 更新LXK9301脚本，原地址：https://github.com/LXK9301/jd_scripts
> 
> 正在获取 origin
> Username for 'https://github.com':
> Password for 'https://github.com':
> remote: Repository not found.
> fatal: Authentication failed for 'https://github.com/lxk0301/jd_scripts/'
> error: 不能获取 origin
> HEAD 现在位于 cd33b4f Update jd_dreamFactory.js
> 
> 更新shylocks脚本，原地址：https://github.com/shylocks/Loon
> 
> 正在获取 origin
> HEAD 现在位于 639483d 开卡活动
> 
> js脚本更新失败，请检查原因或再次运行git_pull.sh...
> 
> 手动执行提示需要用户名和密码，这是什么情况

我的也是同样问题，先git pull 更新一下，然后在scripts下,执行git命令

git remote remove origin

git remote add origin https://gitee.com/lxk0301/jd_scripts

git branch --set-upstream-to=origin/master master 即可

**Comment by HowToLoveChina** [comment]
> > 更新shell脚本，原地址：https://github.com/EvineDeng/jd-base
> > 正在获取 origin
> > HEAD 现在位于 [b2b580b](https://github.com/EvineDeng/jd-base/commit/b2b580baf5ca20529cf5fe82be98c0ead2eb3ea6) Fix
> > shell脚本更新完成...
> > 更新LXK9301脚本，原地址：https://github.com/LXK9301/jd_scripts
> > 正在获取 origin
> > Username for 'https://github.com':
> > Password for 'https://github.com':
> > remote: Repository not found.
> > fatal: Authentication failed for 'https://github.com/lxk0301/jd_scripts/'
> > error: 不能获取 origin
> > HEAD 现在位于 cd33b4f Update jd_dreamFactory.js
> > 更新shylocks脚本，原地址：https://github.com/shylocks/Loon
> > 正在获取 origin
> > HEAD 现在位于 639483d 开卡活动
> > js脚本更新失败，请检查原因或再次运行git_pull.sh...
> > 手动执行提示需要用户名和密码，这是什么情况
> 
> 我的也是同样问题，先git pull 更新一下，然后在scripts下,执行git命令
> 
> git remote remove origin
> 
> git remote add origin https://gitee.com/lxk0301/jd_scripts
> 
> git branch --set-upstream-to=origin/master master 即可

 我直接把scripts目录删除，然后重新做了git_pull.sh 也就好了

**Comment by ljhnchina** [comment]
系统时间：2021-01-23 07:55:00

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
HEAD is now at 3e5b0f0 现在本脚本可以一键导出所有互助码了（包括临时活动）

shell脚本更新完成...

--------------------------------------------------------------

更新LXK9301脚本，原地址：https://gitee.com/lxk0301/jd_scripts

Fetching origin
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403
fatal: the remote end hung up unexpectedly
error: Could not fetch origin
HEAD is now at 7ba584d Merge pull request #209 from DoveBoy/patch-2

更新shylocks脚本，原地址：https://github.com/shylocks/Loon

Fetching origin
HEAD is now at 867ee8c joy总动员

js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by EvineDeng** [comment]
@HowToLoveChina @ljhnchina @lustime @Yvan0329 

解决办法见：#292
