### ISSUE TITLE
大佬可否接入Loon的脚本？

### ISSUE THREAD

**Issue by qqqm7** [EvineDeng/jd-base#266]
https://github.com/shylocks/Loon，有很多不错的脚本，不知是否可以加入自动更新的计划，更新比较频繁，每次都要挨个换
如有冒犯请勿怪，谢大佬

**Comment by EvineDeng** [comment]
全是一次性活动，我不想加加删删的，你需要你可以借助diy.sh来更新这些脚本。

**Comment by qqqm7** [comment]
我也想自己弄。。奈何能力不够，diy.sh怎么写能把脚本和定时同步啊

**Comment by qqqm7** [comment]
而且它还都是jd开头的。。会被清理掉

**Comment by EvineDeng** [comment]
#243

**Comment by EvineDeng** [comment]
已经添加了

**Comment by DomKing** [comment]
> #243

改进版本，不用每次改js列表变量，会自动拉所有任务脚本
`#!/usr/bin/env bash

cd $ScriptsDir   # 在 git_pull.sh 中已经定义 ScriptsDir 此变量，diy.sh 由 git_pull.sh 调用，因此可以直接使用此变量
scriptsUrl="https://raw.githubusercontent.com/shylocks/Loon/main/surge/shylocks_Task.sgmodule.sgmodule"
echo -e "更新 shylocks_Task.sgmodule ...\n"
wget -q --no-check-certificate $scriptsUrl -O shylocks_Task.sgmodule.new

# 更新Task列表
if [ $? -eq 0 ]; then
  mv -f shylocks_Task.sgmodule.new shylocks_Task.sgmodule
  echo -e "更新 shylocks_Task.sgmodule 完成...\n"
else
  [ -f shylocks_Task.sgmodule.new ] && rm -f shylocks_Task.sgmodule.new
  echo -e "更新 shylocks_Task.sgmodule 失败，使用上一次正常的版本...\n"
fi

cat shylocks_Task.sgmodule | while read LINE
do
  jsSplit="script-path="
  nameSplite="main/"
  result=$(echo $LINE | grep "script-path=.*shylocks")
  if [[ "$result" != "" ]]; then
    jsUrl=${LINE##*$jsSplit}
    jsName=${jsUrl##*$nameSplite}
    # 下载my_scripts_list中的每个js文件，重命名增加前缀"shylocks_"，增加后缀".new"
    echo -e "更新 $jsName ...\n"
    wget -q --no-check-certificate $jsUrl -O shylocks_$jsName.new

    # 如果上一步下载没问题，才去掉后缀".new"，如果上一步下载有问题，就保留之前正常下载的版本
    if [ $? -eq 0 ]; then
      mv -f shylocks_$jsName.new shylocks_$jsName
      echo -e "更新 $jsName 完成...\n"
    else
      [ -f shylocks_$jsName.new ] && rm -f shylocks_$jsName.new
      echo -e "更新 $jsName 失败，使用上一次正常的版本...\n"
    fi
  fi
done`

**Comment by DomKing** [comment]
> #243

改进版本，不用每次改js列表变量，会自动拉所有任务脚本

`
#!/usr/bin/env bash

cd $ScriptsDir   # 在 git_pull.sh 中已经定义 ScriptsDir 此变量，diy.sh 由 git_pull.sh 调用，因此可以直接使用此变量
scriptsUrl="https://raw.githubusercontent.com/shylocks/Loon/main/surge/shylocks_Task.sgmodule.sgmodule"
echo -e "更新 shylocks_Task.sgmodule ...\n"
wget -q --no-check-certificate $scriptsUrl -O shylocks_Task.sgmodule.new

# 更新Task列表
if [ $? -eq 0 ]; then
  mv -f shylocks_Task.sgmodule.new shylocks_Task.sgmodule
  echo -e "更新 shylocks_Task.sgmodule 完成...\n"
else
  [ -f shylocks_Task.sgmodule.new ] && rm -f shylocks_Task.sgmodule.new
  echo -e "更新 shylocks_Task.sgmodule 失败，使用上一次正常的版本...\n"
fi

cat shylocks_Task.sgmodule | while read LINE
do
  jsSplit="script-path="
  nameSplite="main/"
  result=$(echo $LINE | grep "script-path=.*shylocks")
  if [[ "$result" != "" ]]; then
    jsUrl=${LINE##*$jsSplit}
    jsName=${jsUrl##*$nameSplite}
    # 下载my_scripts_list中的每个js文件，重命名增加前缀"shylocks_"，增加后缀".new"
    echo -e "更新 $jsName ...\n"
    wget -q --no-check-certificate $jsUrl -O shylocks_$jsName.new

    # 如果上一步下载没问题，才去掉后缀".new"，如果上一步下载有问题，就保留之前正常下载的版本
    if [ $? -eq 0 ]; then
      mv -f shylocks_$jsName.new shylocks_$jsName
      echo -e "更新 $jsName 完成...\n"
    else
      [ -f shylocks_$jsName.new ] && rm -f shylocks_$jsName.new
      echo -e "更新 $jsName 失败，使用上一次正常的版本...\n"
    fi
  fi
done

`

**Comment by dreamdc** [comment]
已经更新用上了新增脚本，感谢大佬

**Comment by hacken156026692** [comment]
已经更新用上了新增脚本，感谢大佬！最喜欢的还是红包雨，爽！~

**Comment by qqqm7** [comment]
谢谢大佬

**Comment by Matear890** [comment]
大佬 更新了2个脚本，linux部署的有2个目录 scripts  和 scripts2 ，目前手动脚本好像无法执行。脚本卡主了不跑。比如这个：bash jd.sh jd_bean_sign  now
