### ISSUE TITLE
惊喜工厂任务无法完成

### ISSUE THREAD

**Issue by jiegangwu** [EvineDeng/jd-base#268]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [X] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [X] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：
树莓派
## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：
惊喜工厂无法正常完成任务
### (2) 详细日志
A：

部分日志如下：

DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去玩炸年兽分10亿任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！
DoTask异常：{"data":{},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":20011}
领取去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！任务奖励失败，任务已领奖
去做任务：去集喜气1元秒年礼,去9.9抢年货好礼,全场1元去秒杀！

### (1) Node.js版本

A：
最新版本
### (2) npm版本

A：
最新版本
### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
与本脚本无关。
