### ISSUE TITLE
新增的shylocks大佬的脚本clone失败了，手动也不行

### ISSUE THREAD

**Issue by requireCool** [EvineDeng/jd-base#270]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x ] Docker

### (1) 具体问题
A：git_pull克隆shylocks大佬的脚本时提示fatal: unable to access 'https://github.com/shylocks/Loon/': SSL: no alternative certificate subject name matches target host name 'github.com'
手动更新也不行

### (2) 详细日志
A：系统时间：2021-01-20 13:55:00

SHELL脚本目录：/jd

JS脚本目录：/jd/scripts

--------------------------------------------------------------

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin
HEAD is now at da8055e Update

shell脚本更新完成...

--------------------------------------------------------------

更新LXK9301脚本，原地址：https://gitee.com/lxk0301/jd_scripts

Fetching origin
remote: [31mRepository more than 5 connections.[0m
fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': The requested URL returned error: 403
error: Could not fetch origin
HEAD is now at b047b10 Merge remote-tracking branch 'origin/master'

克隆shylocks脚本，原地址：https://github.com/shylocks/Loon

Cloning into '/jd/scripts2'...
fatal: unable to access 'https://github.com/shylocks/Loon/': SSL: no alternative certificate subject name matches target host name 'github.com'

/usr/local/bin/git_pull: line 393: cd: /jd/scripts2: No such file or directory
cp: cannot stat '/jd/scripts2/jd_bean_change.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_bean_home.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_bean_sign.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_blueCoin.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_bookshop.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_car.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_car_exchange.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_cash.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_club_lottery.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_crazy_joy.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_crazy_joy_coin.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_daily_egg.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_dreamFactory.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_family.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_fruit.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_get_share_code.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_jdfactory.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_jdzz.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_joy.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_joy_feedPets.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_joy_help.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_joy_reward.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_joy_run.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_joy_steal.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_jxnc.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_kd.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_live.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_lotteryMachine.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_moneyTree.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_necklace.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_nh.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_nian.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_nianCollect.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_pet.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_petTreasureBox.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_pigPet.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_plantBean.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_rankingList.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_redPacket.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_shop.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_small_home.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_speed.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_superMarket.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_syj.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_unbind.js': No such file or directory
cp: cannot stat '/jd/scripts2/jd_unsubscribe.js': No such file or directory
js脚本更新失败，请检查原因或再次运行git_pull.sh...

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by FanchangWang** [comment]
被墙了

**Comment by requireCool** [comment]
> 被墙了

我只能在Docker的主机上挂代理，但是也不行

**Comment by FanchangWang** [comment]
shy 的库好像没做 gitee 的镜像同步，可以自己去 gitee 上创建个库，从 github 上拉取，然后把 scripts2 目录 clone gitee 的代码

**Comment by EvineDeng** [comment]
自己想办法改善网络条件，报错不影响lxk的脚本。

**Comment by Matear890** [comment]
大佬我是可以更新脚本，2个库的脚本都下载下来了，但是现在手动执行脚本脚本就卡主了，无法执行；
linux环境部署的脚本；
bash jd.sh jd_bean_sign  now
