### ISSUE TITLE
获取邀请码报错

### ISSUE THREAD

**Issue by 544325999** [EvineDeng/jd-base#271]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：获取某个用户邀请码时报错后面不再执行
之前的都正常 jd_get_share_code
### (2) 详细日志
A：
======账号4开始======
【账号4（See李sir）东东工厂】T028vfh2loOPId1G9aR7Qlq0odBLdsibCjVWnYaS5kRrbA
【账号4（See李sir）京喜农场助力码】7796fa95239bf7692b7c0953db76c015
【账号4（See李sir）京喜农场】未选择种子，请先去京喜农场选择种子

❌ 获取互助码, 失败! 原因: TypeError: Cannot read property 'jwordShareInfo' of undefined!

🔔获取互助码, 结束! 🕛 8.813 秒

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
这是js的问题，你提错地方了。
