### ISSUE TITLE
建议增加删除pm2日志cron

### ISSUE THREAD

**Issue by meselson** [EvineDeng/jd-base#272]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Ubuntu 20.04.1

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：建议增加删除pm2日志的定时任务
```
# 重启挂机脚本：
32 13 * * * pm2 flush
33 13 * * * bash /home/ubuntu/jd/jd.sh hangup
```

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
安装了pm2才使用pm2，不是每个用户都装了的。好像也不是很好加啊。

**Comment by EvineDeng** [comment]
也可以，你要自己pr进来吗

**Comment by meselson** [comment]
> 也可以，你要自己pr进来吗

已提交PR

**Comment by EvineDeng** [comment]
已merge，关闭咯。
