### ISSUE TITLE
最新镜像报错，无法运行首次配置

### ISSUE THREAD

**Issue by jiangcm** [EvineDeng/jd-base#28]
1-10 12:45:36-- https://raw.githubusercontent.com/EvineDeng/jd-base/main/first_run.sh
g raw.githubusercontent.com... 0.0.0.0, 0.0.0.0
ng to raw.githubusercontent.com|0.0.0.0|:443... failed: Connection refused.

ng to raw.githubusercontent.com|0.0.0.0|:443... failed: Connection refused.

) Failed to connect to raw.githubusercontent.com port 443: Connection refused

ax error: unexpected "||"

**Comment by EvineDeng** [comment]
好吧，我忘记容器内的bash功能不全了，马上修改一下。
