### ISSUE TITLE
docker 多容器可以支持共同变量吗

### ISSUE THREAD

**Issue by HeatonZ** [EvineDeng/jd-base#280]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Centos

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：我看docker-compose的config是每个不同的，如果需要共同变量应该如何处理

**Comment by EvineDeng** [comment]
所有变量相同，为啥要多容器？

不过你想法是可行的，多个容器用一套变量。

**Comment by HeatonZ** [comment]
> 所有变量相同，为啥要多容器？
> 
> 不过你想法是可行的，多个容器用一套变量。

就是想分组，每个组有不同的配置也有相同的配置，比如弄分组通知
我现在都挂载一个相同的文件，然后再每个config上面source

**Comment by EvineDeng** [comment]
可以
