### ISSUE TITLE
酷推推送异常: undefined

### ISSUE THREAD

**Issue by fyzzy1943** [EvineDeng/jd-base#281]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：ubuntu 20.04 docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：通知中填写了酷推的 sec 和 mode，mode使用空字符串或send，都会提示：酷推推送异常: undefined

### (2) 详细日志
A：酷推推送异常: undefined

### (1) Node.js版本

A：docker 中的 node

### (2) npm版本

A：docker 中的 npm

### (3)npm install的日志

A：这个docker版本的不知道在哪里额。

**Comment by EvineDeng** [comment]
这一般是你填错了，另：你提错地方了。

**Comment by Hthing** [comment]
我看了看响应，发现是被和谐了。  jd和京东也都是敏感词， 应该还有很多
{"code":503,"message":"检测到敏感词","data":"京豆"}

**Comment by fyzzy1943** [comment]
> 我看了看响应，发现是被和谐了。 jd和京东也都是敏感词， 应该还有很多
> {"code":503,"message":"检测到敏感词","data":"京豆"}

原来如此，我没找到这个日志。
