### ISSUE TITLE
希望能够支持不同账户的通知推送不同账户

### ISSUE THREAD

**Issue by someash** [EvineDeng/jd-base#284]
比如我一个docker容器挂了两个号，我希望两个号的通知分别通过对应的serverchan的key推送到对应的微信

**Comment by FanchangWang** [comment]
1、这种功能实现的比较费劲，这需要所有脚本单独适配
2、这个功能明显就是给那些卖慢充京豆的人用的啊

**Comment by someash** [comment]
> 1、这种功能实现的比较费劲，这需要所有脚本单独适配
> 2、这个功能明显就是给那些卖慢充京豆的人用的啊

其他的都还好，主要是有些实物领取通知，别人的号领取推送给我，我每次都告知一遍别人不是很僵硬？

**Comment by hacken156026692** [comment]
哈哈哈，我也有这想法

**Comment by FanchangWang** [comment]
> > 1、这种功能实现的比较费劲，这需要所有脚本单独适配
> > 2、这个功能明显就是给那些卖慢充京豆的人用的啊
> 
> 其他的都还好，主要是有些实物领取通知，别人的号领取推送给我，我每次都告知一遍别人不是很僵硬？

我使用的 pushplus 跟 钉钉，实物让他们自己看通知就行

**Comment by CallDockerMaybe** [comment]
> 比如我一个docker容器挂了两个号，我希望两个号的通知分别通过对应的serverchan的key推送到对应的微信

你为什么不在docker里建立多个由同一镜像生成的容器，每个容器添加不同微信推送，互助码又不干涉，相当于应用分身！

**Comment by HeatonZ** [comment]
使用docker-compose实现
