### ISSUE TITLE
用x86机器得docker跑  机器老是自动重启

### ISSUE THREAD

**Issue by sy0927** [EvineDeng/jd-base#286]

**Comment by sy0927** [comment]
请问是怎么回事

**Comment by hacken156026692** [comment]
请问下，昨天在termux里，config里设置了UA，但执行 git_pull.sh后，提示出错。然后把设置的UA删除了，再执行，还是出错。

js脚本更新完成...

/data/data/com.termux/files/home/jd/config/config.sh: line 556: syntax error near unexpected token `iPhone'
/data/data/com.termux/files/home/jd/config/config.sh: line 556: `## 示例：export JD_WECHAT_USER_AGENT="Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15A148 MicroMessenger/7.0.20(0x17001320) NetType/WIFI Language/zh_CN"'

不知怎么回事。貌似定时任务没受影响。
