### ISSUE TITLE
多个docker的年兽任务状态判断有问题

### ISSUE THREAD

**Issue by sofs2005** [EvineDeng/jd-base#287]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：我跑了两个docker，上面各一个账号，现在发现跑新增加的三个年兽任务的时候，只有先跑的那个是成功的，后跑的总是说已经完成了，其实并没有，涉及脚本为：jd jd_nian_ar，jd_nian_sign，jd jd_nian_wechat

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
发错地方

**Comment by sofs2005** [comment]
不好意思，搞错了，一个docker在昨天更新了，另一个没有，所以一个已经在半夜跑过了-_-'
