### ISSUE TITLE
shell文件夹下有三个.sh.sh的文件

### ISSUE THREAD

**Issue by baby-sun** [EvineDeng/jd-base#29]
在crontab.list中却不是对应的
![image](https://user-images.githubusercontent.com/74224618/98632656-e28f4100-235a-11eb-99cc-dc0236a1eb6b.png)

**Comment by EvineDeng** [comment]
啊，我临时改的，改错了，你下载最新镜像重新启动一下容器即可，原来多出的文件删掉就好。
