### ISSUE TITLE
怎么停止某一个脚本一段时间不运行

### ISSUE THREAD

**Issue by underlaw** [EvineDeng/jd-base#290]
## 1.关于你要提交的问题
幸福家庭号2021，点开就显示太火爆了
Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：3。19

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [ x] Docker

### (1) 具体问题
A：幸福家庭号2021，点开就显示太火爆了

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by FanchangWang** [comment]
改 crontab.list
