### ISSUE TITLE
运行docker后 并没有后台运行crazy_joy_coin

### ISSUE THREAD

**Issue by ctr54188** [EvineDeng/jd-base#291]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：运行docker后并没有后台运行疯狂joy脚本

### (2) 详细日志
A：重新手动运行后台命令后还是没有log，但是pm2状态里显示脚本online，app里也没有购买合成动作
单独运行js脚本，脚本可以工作
![image](https://user-images.githubusercontent.com/26321252/105524830-2c14e880-5d1b-11eb-9516-05ab614d7019.png)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
请提供容器创建日志，docker log -f jd
