### ISSUE TITLE
控制面板的新功能“日志查询”打不开

### ISSUE THREAD

**Issue by popeshaka** [EvineDeng/jd-base#295]
如题，提示Cannot GET /log

**Comment by FanchangWang** [comment]
重启面板的pm2进程，或者直接重启docker 容器

pm2 restart server

或

docker restart jd

**Comment by popeshaka** [comment]
> 重启面板的pm2进程，或者直接重启docker 容器
> 
> pm2 restart server
> 
> 或
> 
> docker restart jd

谢谢可以了
