### ISSUE TITLE
jd_crazy_joy_coin未自动运行，手动执行挂机后也未执行挂机任务

### ISSUE THREAD

**Issue by Clown666** [EvineDeng/jd-base#299]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：安卓Termux

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：jd_crazy_joy_coin未自动运行，手动执行挂机后也未执行挂机任务。无相关日志。手动执行jd_crazy_joy_coin.js脚本可以执行。

### (2) 详细日志
A：

### (1) Node.js版本

A：v12.18.3

### (2) npm版本

A：6.14.6

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
安卓不会自动启动。

**Comment by cjfbfb** [comment]
> 启

我的openwrt也不会自动运行

**Comment by EvineDeng** [comment]
> > 启
> 
> 我的openwrt也不会自动运行

教程哪里告诉你会自动启动了？

**Comment by Clown666** [comment]
> > > 启
> > 
> > 
> > 我的openwrt也不会自动运行
> 
> 教程哪里告诉你会自动启动了？
> 
> 并且如果有pm2，会以pm2启动，不记录log，只能在pm2中查看日志。

哥，我手动执行开启挂机的程序之后也没有生成log。bash jd.sh hangup这个

**Comment by EvineDeng** [comment]
> > > > 启
> > > 
> > > 
> > > 我的openwrt也不会自动运行
> > 
> > 
> > 教程哪里告诉你会自动启动了？
> > 并且如果有pm2，会以pm2启动，不记录log，只能在pm2中查看日志。
> 
> 哥，我手动执行开启挂机的程序之后也没有生成log。bash jd.sh hangup这个

如果有pm2，会以pm2启动，不记录log，只能在pm2中查看日志。

自己去看wiki
