### ISSUE TITLE
我填写了三个cookie 替换不成功，只填写一个会把jdCookie替换掉 ，老哥知道怎么回事吗？

### ISSUE THREAD

**Issue by balabachao** [EvineDeng/jd-base#3]

**Comment by landcruser** [comment]
不知道你的使用环境，我是群晖docker一次成功

**Comment by EvineDeng** [comment]
请问是使用我的办法还是另外的办法呢？只要`UserSum`定义为`3`，应该没有问题的。

**Comment by balabachao** [comment]
是定义为3了，我看了一下 控制台报错正则匹配的时候 把我的cookie 解析不了，另外一个可以解析的，我看了下另外2个cookie确实结构和那个正常的不一样，但是各自又是都可以使用的，单独填进去也替换不了， 直接写到jdcookie.js可以正常使用，但是一运行git_pull.sh 就会覆盖掉 ，系统是centos7

**Comment by EvineDeng** [comment]
> 是定义为3了，我看了一下 控制台报错正则匹配的时候 把我的cookie 解析不了，另外一个可以解析的，我看了下另外2个cookie确实结构和那个正常的不一样，但是各自又是都可以使用的，单独填进去也替换不了， 直接写到jdcookie.js可以正常使用，但是一运行git_pull.sh 就会覆盖掉 ，系统是centos7

你看看是不是多什么特殊字符？

**Comment by balabachao** [comment]
我把cookie 贴到这了 你 帮我看看吧 谢谢

mobilev=html5; __jda=122270672.16023044621641893066111.1602304462.1602778527.1603615207.4; mba_muid=16023044621641893066111; shshshfp=3b1ef6c830182997fcde811237bc22fb; shshshfpa=39f245b1-c5e7-4d7b-b7ab-7674a9467f3b-1602304474; shshshfpb=usNWS6eM39JEV3ZYjT5euBg%3D%3D; 3AB9D23F7A4B3C9B=6PJWDE6POJ56L72FCLZN2J6JJRCB3EFS3NA5OVQPETCLCPRI64MAZVET7UGH7RBPXT6KV4SNUTAYB7VVW5C7DAAAMM; __jdb=122270672.4.16023044621641893066111|4.1603615207; __jdv=122270672%7Cdirect%7C-%7Cnone%7C-%7C1603615207455; mba_sid=16036152074579521901079825418.4; __jdc=122270672; shshshsID=0db7dfa6e1de16e599a833ad1a4763d0_1_1603615215686; RT="z=1&dm=jd.com&si=0k8t8pjtrs3m&ss=kgov3ej8&sl=2&tt=0&obo=2&nu=d41d8cd98f00b204e9800998ecf8427e&cl=y9d&ld=z33&r=cd59e30434c072e9ba947d36055a17f3&hd=z39"; TrackerID=ye9OWvVkrJdXHEiCFd6dvepcohPPGBa8k_DDvwwAefsYqhfzg5ljoM_-AdSbjPA165ORBDxtEdI5f6kaZ0j5XTkqzEPenbS0lu5CGO6_-mHuIGWW9wOWqr_J2vDFlmj9; pt_key=AAJflTobADD1pyHgpToyU-3y8sjxSViVsd5Ue-z_9TnRv7eq5DA5fXRUdgFWrTfwmwRtH3RuN8Y; pt_pin=jd_53e4e40ddfa9a; pt_token=p8k6qthw; pwdt_id=jd_53e4e40ddfa9a; sfstoken=tk01m96541be0a8sMXgxKzN4MkxH8I+id02w1LpPGaEUyBYP0rEpYdA5APbPG4pNHGFtd9QlbNrB4RaCuB9oShpqUQeq; __jd_ref_cls=Mnpm_ComponentApplied; jcap_dvzw_fp=289c654183f880bde2a475352a5984c1$888792344300; whwswswws=; guid=f497e07c8e995029119a73784b06316691238882a7aa778eac1d2a9d01b6873d; lstoken=wx03ti6n; lang=chs; lsid=4otl2frb2x0wpv7ufoc8y6bcejg27wxb; s_key=AAJflTobADBadf-ROW3jj4A0rIOcZs5Co4y39pNwO89X2xUtcREjK9vpQHyOV_Zt1K0g-b0f528; s_pin=jd_53e4e40ddfa9a

**Comment by EvineDeng** [comment]
> 是定义为3了，我看了一下 控制台报错正则匹配的时候 把我的cookie 解析不了，另外一个可以解析的，我看了下另外2个cookie确实结构和那个正常的不一样，但是各自又是都可以使用的，单独填进去也替换不了， 直接写到jdcookie.js可以正常使用，但是一运行git_pull.sh 就会覆盖掉 ，系统是centos7

Cookie可是很隐私的东西，不要随便贴出来，我已经给你删除了，填在脚本中的形式是：pt_key=XXXX;pt_pin=jd_XXXX; 
我也看了你的信息，这一段中没有什么特殊字符，应该没有问题才对，你仔细检查一下哪里少了什么东西。

**Comment by balabachao** [comment]
你可以放到你那帮我测试一下吗 会有报错的呀

**Comment by EvineDeng** [comment]
试过了，没有问题。我都加上了我就先留着你这个Cookie。
```
东东农场 - 账号 - jd_53e4e40ddfa9a

【水果名称】3斤雪花梨
【京东账号】jd_53e4e40ddfa9a
【今日剩余助力👬】4次
【额外奖励】领取失败,原因：助力好友未达5个
【今日共浇水】1次
【剩余 水滴】143g💧
【水果🍉进度】0.67%，已浇水1次,还需149次
【开花进度】再浇水19次开花
【预测】135天之后(2021-03-09日)可兑换水果🍉
```

**Comment by balabachao** [comment]
我这里是这样的啊。。。
![image](https://user-images.githubusercontent.com/38938679/97108990-d6c13f00-170b-11eb-8303-ea4153aa0d23.png)

**Comment by balabachao** [comment]
双引号在Cookie1="XXXXXXX" 替换完 在jdcookies.js 是一个空的字串 ’ ‘
Cookie1=’XXXXX‘ 替换会报图上那个错
也就是说我双引号包起来的cookie 替换完后 那个数组 是
 let CookieJDs = [
'',
’‘
]

我也摸不透了

**Comment by EvineDeng** [comment]
> 双引号在Cookie1="XXXXXXX" 替换完 在jdcookies.js 是一个空的字串 ’ ‘
> Cookie1=’XXXXX‘ 替换会报图上那个错
> 也就是说我双引号包起来的cookie 替换完后 那个数组 是
> let CookieJDs = [
> '',
> ’‘
> ]
> 
> 我也摸不透了

你有没有注意到你的引号不太对。

**Comment by balabachao** [comment]
我那俩个不能正常替换的cookie 都是不带引号 直接替换到sh脚本的呀。。迷了

**Comment by EvineDeng** [comment]
> 我那俩个不能正常替换的cookie 都是不带引号 直接替换到sh脚本的呀。。迷了

cookie要带半角双引号呀。

**Comment by balabachao** [comment]
都试过了，不行替换不了，我只能手动填进去 把git_pull,sh 定时去了，隔断时间拉一下，手动替换cookies了，

**Comment by EvineDeng** [comment]
> 都试过了，不行替换不了，我只能手动填进去 把git_pull,sh 定时去了，隔断时间拉一下，手动替换cookies了，

算了，反正我已经把你发的那个cookie放我这边在跑了。就这样吧，你也别折腾了。
记得下次不要随意把cookie发出去了。

**Comment by balabachao** [comment]
啊 我搞好了，谢谢老哥 我是 复制了整段cookie 的不是只放2个字段的，之前那个正常的账号是很长一串的，
现在只放了pt_pin =xxx ;pt_key =xxx  我别的字段也搞进去了，所以会失败，下次不会随便放cookie了
