### ISSUE TITLE
大佬，我用您项目在本地改的，看看这样行吗

### ISSUE THREAD

**Issue by lan-tianxiang** [EvineDeng/jd-base#30]
https://github.com/lan-tianxiang/EvineDeng-jd-base

**Comment by EvineDeng** [comment]
你可以直接用我改好的按https://github.com/EvineDeng/jd-base/issues/26重新配置一下即可了，我这边代码基本改好了。可以所原来的git_pull.sh备份一下，重建以后对照着旧的这个改一下就好。

**Comment by lan-tianxiang** [comment]
> 你可以直接用我改好的按#26 重新配置一下即可了，我这边代码基本改好了。可以把原来的git_pull.sh备份一下，重建以后对照着旧的这个改一下就好。
> 
> 不仅仅是替换一下lxk大佬库的链接那么简单，他因为github action已不能使用，相关代码已删除，而我原来的方式与此有关，已经无法使用。


嗯嗯
