### ISSUE TITLE
京东赚赚： 从日志中未找到任何互助码...

### ISSUE THREAD

**Issue by wudongdefeng** [EvineDeng/jd-base#300]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：shell

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：JDZZ总是提示好友已满5人助力，然后就不显示自己的主力码了

### (2) 详细日志
A：京东赚赚： 从日志中未找到任何互助码...

### (1) Node.js版本

A：12.18.2

### (2) npm版本

A：6.14.6

### (3)npm install的日志

A：

**Comment by zhx47** [comment]
仔细看日志，应该是已经被助力满了，不现实助力码了

**Comment by wudongdefeng** [comment]
![Uploading Screenshot_20210124-234313.jpg…]()

**Comment by zhx47** [comment]
日志显示满5次获取不到助力了，我没看代码，电脑关了，你可以看看代码，试试手动请求一次接口看看返回值

**Comment by EvineDeng** [comment]
程序说没找到就是日志中确实没有呗，还能咋的，不信你可以自己去找。
