### ISSUE TITLE
config.sh未更新

### ISSUE THREAD

**Issue by jerrykkkkk** [EvineDeng/jd-base#303]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：群晖docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：使用git_pull后，没有报错，export_sharecodes能获取到“个护爱消除”、“闪购盲盒”和“工业品爱消除”等新增的活动。 查看在线编辑工具的config.sh 开头版本还是3.15.1 更新日期是2021-1-20，内容中并没有上述新增几个活动的配置参数。

### (2) 详细日志
A：
root@DS418PLAY:~# docker exec -it jd bash git_pull
系统时间：2021-01-25 11:27:00
SHELL脚本目录：/jd
JS脚本目录：/jd/scripts
更新shell脚本，原地址：https://github.com/EvineDeng/jd-base
Fetching origin
HEAD is now at faa816f Fix
shell脚本更新完成...
更新LXK9301脚本，原地址：https://github.com/LXK9301/jd_scripts
Fetching origin
HEAD is now at d5f72a6 更新环境变量
更新shylocks脚本，原地址：https://github.com/shylocks/Loon
Fetching origin
HEAD is now at 3a2e7ff debug
js脚本更新完成...

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
config.sh由你本人对照config.sh.sample进行更新，脚本无法帮你更新。

**Comment by jerrykkkkk** [comment]
> config.sh由你本人对照config.sh.sample进行更新，脚本无法帮你更新。

懂了，谢谢大佬
