### ISSUE TITLE
多容器方式是否有控制台？

### ISSUE THREAD

**Issue by robin0409** [EvineDeng/jd-base#304]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Ubtunu 9.3.0

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：
使用docker-compose 方式部署多个容器，是不是没有各容器的控制台？
### (2) 详细日志
A：
docker ps 能看到不同容器在不同端口运行，进入 http://ip:5679 http://ip:5680 控制台都无法打开 

### (1) Node.js版本

A：v10.19.0

### (2) npm版本

A：6.14.4

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
各是各的控制台。

**Comment by robin0409** [comment]
噢噢，有了，我配置的端口号改成一样了，谢谢解答
