### ISSUE TITLE
JD赚赚 提取不了互助码，并且运行脚本有报错

### ISSUE THREAD

**Issue by mjyhj** [EvineDeng/jd-base#305]
![11](https://user-images.githubusercontent.com/22577418/105664382-7c549c00-5f0f-11eb-8f3e-06462c955e06.png)

已经运行过很多次了，每次都这样

**Comment by EvineDeng** [comment]
脚本是从日志中找互助码，日志中没有当然就找不到了。报错请向上游反馈。

**Comment by 2375399351** [comment]
我是无法获取到互助码，一直提示满5人邀请，获取不到互助码

**Comment by EvineDeng** [comment]
> 我是无法获取到互助码，一直提示满5人邀请，获取不到互助码

字面意思，满5人助力脚本就看不见助力码。

**Comment by 2375399351** [comment]
> > 我是无法获取到互助码，一直提示满5人邀请，获取不到互助码
> 
> 字面意思，满5人助力脚本就看不见助力码。

那么问题来了。怎么才能看见，用京东赚赚的脚本看不见，用那个统一获取助力码的脚本也没有。。。。。

**Comment by EvineDeng** [comment]
> > > 我是无法获取到互助码，一直提示满5人邀请，获取不到互助码
> > 
> > 
> > 字面意思，满5人助力脚本就看不见助力码。
> 
> 那么问题来了。怎么才能看见，用京东赚赚的脚本看不见，用那个统一获取助力码的脚本也没有。。。。。

不要让别人助力你，运行脚本就能看见了。
