### ISSUE TITLE
pt_pin=jd_xxxxxxxxxxxx;的账号Cookie报错

### ISSUE THREAD

**Issue by GcMin** [EvineDeng/jd-base#307]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：
pt_pin=jd_xxxxxxxxxxxx;的账号会出现签到错误
其余非这种格式的账号正常运行
昨天还能正常签到运行，今天更新后失败，

### (2) 详细日志
A：
"Invalid character in header content [\"cookie\"]"
京豆签到 API请求失败，请检查网路重试
*****************开始京东账号3 jd_601a09548d971京豆签到*******************

⚠️⚠️⚠️⚠️目前Bark APP推送通知消息对推送内容长度有限制，如推送通知中包含此推送方式脚本会默认转换成简洁内容推送 ⚠️⚠️⚠️⚠️

开始替换变量
替换变量完毕

开始执行脚本签到，请稍等
👇👇👇👇👇👇👇👇👇👇👇LOG记录👇👇👇👇👇👇👇👇👇👇👇

‼️京东转盘-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
后面都是一样的错误

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
开始京东账号3 jd_601a09548d971京豆签到**

这不都正常显示了吗？与shell没啥关系。
