### ISSUE TITLE
黑号问题怎么解决 

### ISSUE THREAD

**Issue by yhwl8888** [EvineDeng/jd-base#310]
开始【京东账号3】wdvKYxbmPFpiCq

由于您第3个京东账号未提供shareCode,将采纳本脚本自带的助力码
第3个京东账号将要助力的好友["{\"smp\":\"22bd6fbbabbaa770a45ab2607e7a1e8a\",\"active\":\"jdnc_1_cucumber210123_2\",\"joinnum\":2}","{\"smp\":\"197c6094e965fdf3d33621b47719e0b1\",\"active\":\"jdnc_1_penggan210123_2\",\"joinnum\":3}","{\"smp\":\"22bd6fbbabbaa770a45ab2607e7a1e8a\",\"active\":\"jdnc_1_cucumber210123_2\",\"joinnum\":3}","{\"smp\":\"197c6094e965fdf3d33621b47719e0b1\",\"active\":\"jdnc_1_penggan210123_2\",\"joinnum\":4}"]
获取用户信息 & 任务列表
获取任务列表  总共17个任务！
【京东账号3（wdvKYxbmPFpiCq）的京喜农场好友互助码】{"smp":"892f85253be2a436f026819bb0c4748c","active":"jdnc_1_heimi210123_2","joinnum":1}
开始第1个任务：每日签到
每日签到[做任务]：ret:0 retmsg:"成功"
结束第1个任务：每日签到
开始第2个任务：开启明日免费领水滴提醒
开启明日免费领水滴提醒[做任务]：ret:0 retmsg:"成功"
结束第2个任务：开启明日免费领水滴提醒
开始第3个任务：App签到额外领水滴
App签到额外领水滴[做任务]：ret:1031 retmsg:"err sign env"
结束第3个任务：App签到额外领水滴
开始第4个任务：去惊喜提现100元
去惊喜提现100元[做任务]：ret:0 retmsg:"成功"
结束第4个任务：去惊喜提现100元
开始第5个任务：去炸年兽分10亿
去炸年兽分10亿[做任务]：ret:0 retmsg:"成功"
结束第5个任务：去炸年兽分10亿
开始第6个任务：源头年味3.9元起
源头年味3.9元起[做任务]：ret:0 retmsg:"成功"
结束第6个任务：源头年味3.9元起
开始第7个任务：养猪猪赚红包
养猪猪赚红包[做任务]：ret:0 retmsg:"成功"
结束第7个任务：养猪猪赚红包
开始第8个任务：5.9元抢3斤耙耙柑
5.9元抢3斤耙耙柑[做任务]：ret:0 retmsg:"成功"
结束第8个任务：5.9元抢3斤耙耙柑
开始第9个任务：吐司面包500g只要7.9元
吐司面包500g只要7.9元[做任务]：ret:0 retmsg:"成功"
结束第9个任务：吐司面包500g只要7.9元
开始第10个任务：全场一元，去秒杀！
全场一元，去秒杀！[做任务]：ret:0 retmsg:"成功"
结束第10个任务：全场一元，去秒杀！
开始第11个任务：抢金果兑神券
抢金果兑神券[做任务]：ret:0 retmsg:"成功"
结束第11个任务：抢金果兑神券
开始第12个任务：逛产地直发会场抢好货
逛产地直发会场抢好货[做任务]：ret:0 retmsg:"成功"
结束第12个任务：逛产地直发会场抢好货
开始第13个任务：爆款好物,全网超低价
爆款好物,全网超低价[做任务]：ret:0 retmsg:"成功"
结束第13个任务：爆款好物,全网超低价
开始第14个任务：上岛0元领好物
上岛0元领好物[做任务]：ret:0 retmsg:"成功"
结束第14个任务：上岛0元领好物
开始第15个任务：去工厂0元领好物
去工厂0元领好物[做任务]：ret:0 retmsg:"成功"
结束第15个任务：去工厂0元领好物
开始第16个任务：看京喜直播 互动领20元红包
看京喜直播 互动领20元红包[做任务]：ret:0 retmsg:"成功"
结束第16个任务：看京喜直播 互动领20元红包
准备做答题任务：每日答题
每日答题[做任务]：ret:1029 retmsg:"no active config,sActive:jdnc_1_heimi210123_1"
获取任务列表  总共2个任务！
邀请码提交：undefined
即将助力 share {"smp":"22bd6fbbabbaa770a45ab2607e7a1e8a","active":"jdnc_1_cucumber210123_2","joinnum":"2"}
助力结果：ret=147 retmsg="filter"

  !!!!!!!!   当前账号黑号了  !!!!!!!!

**Comment by hacken156026692** [comment]
开通个plus或买个100多元以上的东西， 应该可以解决。我已花钱破了。。。。。。
