### ISSUE TITLE
panel sharecode/自定义脚本/日志查询 3个页面无法打开

### ISSUE THREAD

**Issue by avsba001** [EvineDeng/jd-base#312]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [X] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：群晖 docker v3

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：Cannot GET /shareCode
Cannot GET /diy
Cannot GET /log

### (2) 详细日志
A：其他功能正常，docker内功能正常，目录映射正常

### (1) Node.js版本

A：14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
重启容器。

**Comment by avsba001** [comment]
已解决
