### ISSUE TITLE
arm64 openwrt docker bridge网络无法更新脚本源码

### ISSUE THREAD

**Issue by yangnd** [EvineDeng/jd-base#319]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：arm64 openwrt

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：docker 用bridge网络，无论用自建的bridge还是默认bridge，都无法更新源码，容器Exited (1)
                  用host网络，没有问题
可能还是宿主机或docker配置的问题，求教

### (2) 详细日志
A：
docker logs -f xxx
========================1. 更新源代码========================

更新shell脚本，原地址：https://github.com/EvineDeng/jd-base

Fetching origin
fatal: unable to access 'https://github.com/EvineDeng/jd-base/': Failed to connect to github.com port 443: Connection refused
error: Could not fetch origin

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
如果使用docker，这里不解答。

**Comment by yangnd** [comment]
自己找到原因了，是宿主机openwrt docker配置的原因。
配置文件/etc/config/dockerd

    config docker
         option wan_mode '1'

为了安全默认wan_mode为0，改成1，重启即可。

修改前后可以对比一下规则

    iptables -t nat -S

docker bridge类型的规则都会加入进去
