### ISSUE TITLE
mac 系统替换Cookie 不成功

### ISSUE THREAD

**Issue by zhangxu2814** [EvineDeng/jd-base#33]
修改git_pull.sh里面的Cookie 然后运行，替换不成功
另外群主能否拉个群？

**Comment by EvineDeng** [comment]
麻烦仔细读读readme以及git_pull的注释。

**Comment by zhangxu2814** [comment]
![1605003810870](https://user-images.githubusercontent.com/8907295/98661879-0154fe00-2382-11eb-80b7-dd4b38603858.jpg)
MAC OS 10.15.7 (19H2) 
已经按要求修改 必填的两项 数量1 和Cookie1

**Comment by EvineDeng** [comment]
好吧，其实错误已经提示你了，mac下sed不好使
