### ISSUE TITLE
星推官活动结束了，需要手动删除脚本吗？

### ISSUE THREAD

**Issue by tanst** [EvineDeng/jd-base#37]
星推官活动结束了，需要手动删除脚本吗？
cron 里面也要手动删除吗？还有 js sh 脚本，全部手动吗？

**Comment by EvineDeng** [comment]
lxk0301大佬主库中调整crontab后我这个脚本会自动删除，如果你急的话可以先在那一行前面加#号注释掉，然后使用 `crontab /root/crontab.list`更新定时任务。这种情况也适用于jd_818, jd_collectProduceScore。
