### ISSUE TITLE
为什么更新js脚本需要登录github账号了，是仓库的权限设置还是啥出了问题？

### ISSUE THREAD

**Issue by soapffz** [EvineDeng/jd-base#39]
如图所示，今天才发现仓库搬迁了，重新删除了docker镜像，重新下载的镜像，按照readme操作到这步出现的问题

![image](https://user-images.githubusercontent.com/43143519/98897798-2d3dc400-24e7-11eb-9bff-ccb9f3320823.png)

**Comment by EvineDeng** [comment]
请看更新日志中2020-11-11的更新说明。

**Comment by soapffz** [comment]
原来的脚本在哪里呢？
docker run -dit -v /jd_auto:/root --name jd --restart unless-stopped evinedeng/jd-base:latest
比如这样执行之后，在vps上ls -l找不到文件夹
![image](https://user-images.githubusercontent.com/43143519/98900726-55c8bc80-24ed-11eb-908e-94f600ae896a.png)

**Comment by EvineDeng** [comment]
如果你之前运行的也是这个命令：docker run -dit -v /jd_auto:/root --name jd --restart unless-stopped evinedeng/jd-base:latest

那么请去宿主机上的/jd_auto中删除旧文件夹。建议删除前备份一下你原来的git_pull.sh
```
cd /jd_auto
rm -rf shell scripts
```

**Comment by soapffz** [comment]
哦哦， 找到文件夹了，非常感谢！
