### ISSUE TITLE
standard_init_linux.go：211：exec用户进程导致“ exec格式错误”

### ISSUE THREAD

**Issue by xiaoyao1995** [EvineDeng/jd-base#4]
退出代码 为0
--

**Comment by xiaoyao1995** [comment]
2020-10-25T02：38：19.980083246Z standard_init_linux.go：211：exec用户进程导致“ exec格式错误”

2020-10-25T02：38：33.881118168Z standard_init_linux.go：211：exec用户进程导致“ exec格式错误”

2020-10-25T02：39：00.568468661Z standard_init_linux.go：211：exec用户进程导致“ exec格式错误”

**Comment by xiaoyao1995** [comment]
InspectTreeText
Object
AppArmorProfile
Args [ ]
Config { AttachStderr: false, AttachStdin: false, AttachStdout: false, Cmd: null, Domainname: , Entrypoint: docker-entrypoint.sh, Env: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin,NODE_VERSION=12.19.0,YARN_VERSION=1.22.5,HOME=/root,LANGUAGE=en_US.UTF-8,LANG=en_US.UTF-8,LC_ALL=C, Hostname: 921fd6d7d450, Image: evinedeng/jd-base:latest, Labels: [object Object], OnBuild: null, OpenStdin: true, StdinOnce: false, Tty: true, User: , Volumes: [object Object], WorkingDir: /root }
Created 2020-10-25T02:33:48.594636622Z
Driver btrfs
ExecIDs
GraphDriver { Data: null, Name: btrfs }
HostConfig { AutoRemove: false, Binds: /docker/jd:/root, BlkioDeviceReadBps: null, BlkioDeviceReadIOps: null, BlkioDeviceWriteBps: null, BlkioDeviceWriteIOps: null, BlkioWeight: 0, BlkioWeightDevice: , CapAdd: null, CapDrop: null, Capabilities: null, Cgroup: , CgroupParent: , ConsoleSize: 0,0, ContainerIDFile: , CpuCount: 0, CpuPercent: 0, CpuPeriod: 0, CpuQuota: 0, CpuRealtimePeriod: 0, CpuRealtimeRuntime: 0, CpuShares: 0, CpusetCpus: , CpusetMems: , DeviceCgroupRules: null, DeviceRequests: null, Devices: , Dns: , DnsOptions: , DnsSearch: , ExtraHosts: null, GroupAdd: null, IOMaximumBandwidth: 0, IOMaximumIOps: 0, IpcMode: private, Isolation: , KernelMemory: 0, KernelMemoryTCP: 0, Links: null, LogConfig: [object Object], MaskedPaths: /proc/asound,/proc/acpi,/proc/kcore,/proc/keys,/proc/latency_stats,/proc/timer_list,/proc/timer_stats,/proc/sched_debug,/proc/scsi,/sys/firmware, Memory: 0, MemoryReservation: 0, MemorySwap: 0, MemorySwappiness: null, NanoCpus: 0, NetworkMode: default, OomKillDisable: false, OomScoreAdj: 0, PidMode: , PidsLimit: null, PortBindings: [object Object], Privileged: false, PublishAllPorts: false, ReadonlyPaths: /proc/bus,/proc/fs,/proc/irq,/proc/sys,/proc/sysrq-trigger, ReadonlyRootfs: false, RestartPolicy: [object Object], Runtime: runc, SecurityOpt: null, ShmSize: 67108864, UTSMode: , Ulimits: null, UsernsMode: , VolumeDriver: , VolumesFrom: null }
HostnamePath /mnt/mmcblk1p3/docker/containers/921fd6d7d450079808879f4316c03fbd09e21343bf7a866f4b07ca77f0140909/hostname
HostsPath /mnt/mmcblk1p3/docker/containers/921fd6d7d450079808879f4316c03fbd09e21343bf7a866f4b07ca77f0140909/hosts
Id 921fd6d7d450079808879f4316c03fbd09e21343bf7a866f4b07ca77f0140909
Image sha256:1f631a1e57bdeb1a49ac77ed50bb0a1b4797181c923bbbb4dd59b2ae3d74c045
LogPath /mnt/mmcblk1p3/docker/containers/921fd6d7d450079808879f4316c03fbd09e21343bf7a866f4b07ca77f0140909/921fd6d7d450079808879f4316c03fbd09e21343bf7a866f4b07ca77f0140909-json.log
MountLabel
Mounts [ [object Object] ]
Name /jd
NetworkSettings { Bridge: , EndpointID: , Gateway: , GlobalIPv6Address: , GlobalIPv6PrefixLen: 0, HairpinMode: false, IPAddress: , IPPrefixLen: 0, IPv6Gateway: , LinkLocalIPv6Address: , LinkLocalIPv6PrefixLen: 0, MacAddress: , Networks: [object Object], Ports: [object Object], SandboxID: a55db66c94f21ac8ef156d308f16462ea92869d2feca660a597c0c15cdadc6e2, SandboxKey: /var/run/docker/netns/a55db66c94f2, SecondaryIPAddresses: null, SecondaryIPv6Addresses: null }
Path docker-entrypoint.sh
Platform linux
ProcessLabel
ResolvConfPath /mnt/mmcblk1p3/docker/containers/921fd6d7d450079808879f4316c03fbd09e21343bf7a866f4b07ca77f0140909/resolv.conf
RestartCount 16
State { Dead: false, Error: , ExitCode: 1, FinishedAt: 2020-10-25T02:40:55.82

**Comment by xiaoyao1995** [comment]
使用环境为N1,openwrt，内置的docker-ce

**Comment by EvineDeng** [comment]
N1是arm的吧，用不了我的docker镜像。

**Comment by xiaoyao1995** [comment]
armv8

**Comment by EvineDeng** [comment]
> armv8

armv8也用不了
