### ISSUE TITLE
请问群晖下怎么安装食用？

### ISSUE THREAD

**Issue by iiiiqt** [EvineDeng/jd-base#40]
请问群晖下怎么安装食用？
已从群晖docker--注册表搜索evinedeng/jd-base并下载成功，大小150M。
后面就不会了。

**Comment by EvineDeng** [comment]
使用ssh工具登陆群晖，按顺序输入readme中的命令行。

如不会，建议使用lxk0301大佬主库中docker办法一。

**Comment by lllrrr2** [comment]
能不能搞个像lxk0301大佬那样的一个json文件直接导入，在群晖下ssh登录去搞，一直搞不成。

**Comment by EvineDeng** [comment]
> 能不能搞个像lxk0301大佬那样的一个json文件直接导入，在群晖下ssh登录去搞，一直搞不成。

lxk0301大佬中docker办法一已经做好了，直接用那个吧。

**Comment by iiiiqt** [comment]
lxk0301大佬 的我有用过，不太好，卡进程。一天不重启内存占用几G。有些脚本一直卡在进程中。

EvineDeng <notifications@github.com> 于2020年11月13日周五 下午11:07写道：

**Comment by EvineDeng** [comment]
那没办法了，我没用过群晖，不太了解。你要么完全按照我这种命令行的方式抛弃网页界面，要么只能用docker办法一。
