### ISSUE TITLE
大大，能写一个多线程运行的脚本吗

### ISSUE THREAD

**Issue by lan-tianxiang** [EvineDeng/jd-base#41]
由于这些脚本是一个一个账号运行的，耗时长。
所以我在之前做新推官任务的时候，是拷贝了三份这个目录，并在不同目录中配置不同的Cookie，然后再配置crontab.list

小声的问一下，这个功能可以嘀嘀嘀嘛（哭笑），谢谢大大

**Comment by EvineDeng** [comment]
你只能像你已经做的方式这么做。
