### ISSUE TITLE
 Failed connect to raw.githubusercontent.com:443; 拒绝连接

### ISSUE THREAD

**Issue by cattingnum** [EvineDeng/jd-base#43]
bash -c "$(curl -fsSL https://raw.githubusercontent.com/EvineDeng/jd-base/main/first_run.sh)"

curl: (7) Failed connect to raw.githubusercontent.com:443; 拒绝连接

**Comment by EvineDeng** [comment]
使用代理

**Comment by cattingnum** [comment]
嗯嗯可以了
