### ISSUE TITLE
删除日志脚本运行出错

### ISSUE THREAD

**Issue by Hw0fz6kW** [EvineDeng/jd-base#49]
系统是 Openwrt lean 代码编译

![2020-11-15_18-06-19](https://user-images.githubusercontent.com/7458643/99182055-8880e800-276d-11eb-85e6-8927fd5be716.png)
![2020-11-15_18-08-47](https://user-images.githubusercontent.com/7458643/99182079-af3f1e80-276d-11eb-9f70-16a8156ed324.png)

**Comment by EvineDeng** [comment]
什么错

**Comment by EvineDeng** [comment]
你不用那个cre
