### ISSUE TITLE
每次启动都有个github的请求异常日志

### ISSUE THREAD

**Issue by ljh740** [EvineDeng/jd-base#50]
--2020-11-16 08:59:48-- https://raw.githubusercontent.com/EvineDeng/jd-base/main/first_run.sh

Resolving raw.githubusercontent.com... 151.101.72.133, ::

Connecting to raw.githubusercontent.com|151.101.72.133|:443... connected.

ERROR: no certificate subject alternative name matches

requested host name 'raw.githubusercontent.com'.

To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.

Welcome to Node.js v12.19.0.

Type ".help" for more information.

**Comment by EvineDeng** [comment]
在没有科学上网环境时，是这样子的，我等会还是把这个first_sun.sh集成在docker镜像中吧，这样至少docker不会报错了。

**Comment by ljh740** [comment]
> 在没有科学上网环境时，是这样子的，我等会还是把这个first_sun.sh集成在docker镜像中吧，这样至少docker不会报错了。

有科学上网 在docker curl https://google.com ,curl https://github.com 都没问题

**Comment by EvineDeng** [comment]
那有点奇怪了。。。不管怎样，我集成在镜像里面应该就没问题了。

**Comment by EvineDeng** [comment]
好了，把first_run.sh直接集成在docker镜像里面了，现在应该不会再报这种错了。
