### ISSUE TITLE
容器里是utc时间

### ISSUE THREAD

**Issue by kisdaojf** [EvineDeng/jd-base#51]
脚本执行时间和北京时间差了8小时

**Comment by EvineDeng** [comment]
你不加参数肯定是北京时间，你自己加的参数。

**Comment by kisdaojf** [comment]
什么也没加呀，按教程一步步来的。我重装试试吧

**Comment by EvineDeng** [comment]
容器内使用date可看时间

**Comment by qiuhaiwei2020** [comment]
用armbian部署的，log日志里全是空白的，0kb

**Comment by EvineDeng** [comment]
> 用armbian部署的，log日志里全是空白的，0kb

你没成功，按readme从头检查

**Comment by qiuhaiwei2020** [comment]
从头做到脚，做了两遍，不知道哪里出错了，哈啊哈

**Comment by qiuhaiwei2020** [comment]
再问下互助码是这样格式吗：貌似跟其他方式有点不一样ForOtherPlantBean1=ebxm5lgxoknqcey4h37vidxas6ed6oqmbohb6ii"\@"o7eiltak46s2wrlcjn73knl5v3do2uj6i5kqq4q

**Comment by EvineDeng** [comment]
>  再问下互助码是这样格式吗：貌似跟其他方式有点不一样ForOtherPlantBean1=ebxm5lgxoknqcey4h37vidxas6ed6oqmbohb6ii"\@"o7eiltak46s2wrlcjn73knl5v3do2uj6i5kqq4q

你仔细读注释，码是填在My系统中，ForOther只要填My的变量名就行，里面举了例子的。

**Comment by qiuhaiwei2020** [comment]
> > 再问下互助码是这样格式吗：貌似跟其他方式有点不一样ForOtherPlantBean1=ebxm5lgxoknqcey4h37vidxas6ed6oqmbohb6ii"@"o7eiltak46s2wrlcjn73knl5v3do2uj6i5kqq4q
> 
> 你仔细读注释，码是填在My系列中，ForOther只要填My系列的变量名就行，里面举了例子的。

清楚了

**Comment by kisdaojf** [comment]
> 容器内使用date可看时间

重新部署还是差8小时，需要把docker卸载重装吗？

**Comment by EvineDeng** [comment]
> > 容器内使用date可看时间
> 
> 重新部署还是差8小时，需要把docker卸载重装吗？

你这不对劲啊，我从第一个版本的镜像开始，所有的版本都一直是默认北京时间，除非自己加TZ=UTC的环境变量。你把你原来的镜像和容器全删除重新部署看看？

**Comment by kisdaojf** [comment]
> > > 容器内使用date可看时间
> > 
> > 
> > 重新部署还是差8小时，需要把docker卸载重装吗？
> 
> 你这不对劲啊，我从第一个版本的镜像开始，所有的版本都一直是默认北京时间，除非自己加TZ=UTC的环境变量。你把你原来的镜像和容器全删除重新部署看看？

我用你那三个命令把容器删了 文件夹也删了 换了个路径重新装的没有tz=utc这个变量 现在是要把docker这个程序也重装的意思是吗？

**Comment by EvineDeng** [comment]
> > > > 容器内使用date可看时间
> > > 
> > > 
> > > 重新部署还是差8小时，需要把docker卸载重装吗？
> > 
> > 
> > 你这不对劲啊，我从第一个版本的镜像开始，所有的版本都一直是默认北京时间，除非自己加TZ=UTC的环境变量。你把你原来的镜像和容器全删除重新部署看看？
> 
> 我用你那三个命令把容器删了 文件夹也删了 换了个路径重新装的没有tz=utc这个变量 现在是要把docker这个程序也重装的意思是吗？

容器删了，镜像也要删除，参考首页更新日志2020-11-15这一天的说明可删除。不用重新安装docker。

**Comment by kisdaojf** [comment]
> > > > > 容器内使用date可看时间
> > > > 
> > > > 
> > > > 重新部署还是差8小时，需要把docker卸载重装吗？
> > > 
> > > 
> > > 你这不对劲啊，我从第一个版本的镜像开始，所有的版本都一直是默认北京时间，除非自己加TZ=UTC的环境变量。你把你原来的镜像和容器全删除重新部署看看？
> > 
> > 
> > 我用你那三个命令把容器删了 文件夹也删了 换了个路径重新装的没有tz=utc这个变量 现在是要把docker这个程序也重装的意思是吗？
> 
> 容器删了，镜像也要删除，参考首页更新日志2020-11-15这一天的说明可删除。不用重新安装docker。

docker stop jd                # 停止名为jd的容器
docker rm jd                  # 删除名为jd的容器
docker rmi evinedeng/jd-base  # 删除名为evinedeng/jd-base的镜像
就是这三个命令 我搞了两次了 完全按照教程来的。就是安装docker用的别的教程 因为那个好像源好像有点问题 装不上

**Comment by EvineDeng** [comment]
> docker stop jd # 停止名为jd的容器
> docker rm jd # 删除名为jd的容器
> docker rmi evinedeng/jd-base # 删除名为evinedeng/jd-base的镜像
> 就是这三个命令 我搞了两次了 完全按照教程来的。就是安装docker用的别的教程 因为那个好像源好像有点问题 装不上

对，就这样，另外，检查容器中是不是设置了UTC，可以在容器中输入`echo $TZ`，如果设置了，将显示`UTC`。

**Comment by kisdaojf** [comment]
> > docker stop jd # 停止名为jd的容器
> > docker rm jd # 删除名为jd的容器
> > docker rmi evinedeng/jd-base # 删除名为evinedeng/jd-base的镜像
> > 就是这三个命令 我搞了两次了 完全按照教程来的。就是安装docker用的别的教程 因为那个好像源好像有点问题 装不上
> 
> 对，就这样，另外，检查容器中是不是设置了UTC，可以在容器中输入`echo $TZ`，如果设置了，将显示`UTC`。

什么都没显示

**Comment by EvineDeng** [comment]
> 什么都没显示

那么就是北京时间，**在容器中** 使用`date`可查看时间。

**Comment by kisdaojf** [comment]
> > 什么都没显示
> 
> 那么就是北京时间，**在容器中** 使用`date`可查看时间。

显示：Ture Nov 17 13:46:53 UTC 2020

**Comment by EvineDeng** [comment]
> > > 什么都没显示
> > 
> > 
> > 那么就是北京时间，**在容器中** 使用`date`可查看时间。
> 
> 显示：Ture Nov 17 13:46:53 UTC 2020

搞不清楚你这个毛病。。。。无可奈何。。。。你可能只能改crontab了。。。

**Comment by EvineDeng** [comment]
还有个办法，你试下看看可行不可行

部署容器时增加一个环境变量，`-e TZ=Asia/Shanghai`，这样再试试。

**Comment by qazmcl1230** [comment]
> 还有个办法，你试下看看可行不可行
> 
> 部署容器时增加一个环境变量，`-e TZ=Asia/Shanghai`，这样再试试。

用这个方法echo $TZ显示上海 date 2020前面的utc没了 但还是差8小时

**Comment by EvineDeng** [comment]
> > 还有个办法，你试下看看可行不可行
> > 部署容器时增加一个环境变量，`-e TZ=Asia/Shanghai`，这样再试试。
> 
> 用这个方法echo $TZ显示上海 date 2020前面的utc没了 但还是差8小时

那真的搞不清楚你这个是啥问题了。。
