### ISSUE TITLE
computer教程114行命令无法理解

### ISSUE THREAD

**Issue by bobotoy** [EvineDeng/jd-base#52]
computer教程114行命令cd root/shell无法理解。
接下来运行bash jd_bean_sign.sh报错，错误代码如下：
TypeError: (intermediate value)(...).catch(...).finally is not a function
    at Object.<anonymous> (/home/bobotoy/jd/scripts/jd_bean_sign.js:52:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by EvineDeng** [comment]
请检查第一次运行git_pull.sh的日志

**Comment by bobotoy** [comment]
> 写错了，应该是`cd /home/myid/jd/shell`

大佬，错误代码帮着看看呗，完全没js基础

**Comment by EvineDeng** [comment]
> > 写错了，应该是`cd /home/myid/jd/shell`
> 
> 大佬，错误代码帮着看看呗，完全没js基础

Computer.md已更新，你可以直接使用按教程cd到scripts文件夹下运行`node jd_bean_sign.js`看看报错不报错。

如果报错，请再运行一次git_pull.sh，仔细看输出日志并按日志的提示操作。

**Comment by EvineDeng** [comment]
或者在scripts文件夹运行`npm install || npm install --registry=https://registry.npm.taobao.org`，请注意看成功不成功，不成功就运行多次。

**Comment by bobotoy** [comment]
> 或者在scripts文件夹运行`npm install || npm install --registry=https://registry.npm.taobao.org`，请注意看成功不成功，不成功就运行多次。

放弃了，git_pull.sh 运行过程不报错，明天换N1armbian试试

**Comment by EvineDeng** [comment]
> > 或者在scripts文件夹运行`npm install || npm install --registry=https://registry.npm.taobao.org`，请注意看成功不成功，不成功就运行多次。
> 
> 放弃了，git_pull.sh 运行过程不报错，明天换N1armbian试试

那你就在scripts文件夹运行`npm install || npm install --registry=https://registry.npm.taobao.org`几次看看吧。

**Comment by bobotoy** [comment]
> > > 或者在scripts文件夹运行`npm install || npm install --registry=https://registry.npm.taobao.org`，请注意看成功不成功，不成功就运行多次。
> > 
> > 
> > 放弃了，git_pull.sh 运行过程不报错，明天换N1armbian试试
> 
> 那你就在scripts文件夹运行`npm install || npm install --registry=https://registry.npm.taobao.org`几次看看吧。

试过了，也许其他依赖问题，感谢，明天换系统再试

**Comment by bobotoy** [comment]
确定是npm和nodejs版本问题，N1armbian已经完美运行，有同样问题的小伙伴可以参照考以下解决方案，重新安装npm和nodejs
https://github.com/nodejs/help/issues/1877

**Comment by EvineDeng** [comment]
> 确定是npm和nodejs版本问题，N1armbian已经完美运行，有同样问题的小伙伴可以参照考以下解决方案，重新安装npm和nodejs
> https://github.com/nodejs/help/issues/1877

好的，我也更新到readme中。
