### ISSUE TITLE
执行 bash -c "$(curl -fsSL https://github.com/EvineDeng/jd-base/blob/main/first_run.sh)"

### ISSUE THREAD

**Issue by jakietwo** [EvineDeng/jd-base#54]
报错 
`bash: -c: line 6: syntax error near unexpected token `newline'
bash: -c: line 6: `<!DOCTYPE html>'`

**Comment by EvineDeng** [comment]
你就没有获取到真正的文件，手动吧。

**Comment by jakietwo** [comment]
你的意思是把文件复制下来 执行吗？ 主要是connection refused， 即使我科学上网也不行

**Comment by EvineDeng** [comment]
对。刷新一下wiki，我更新了那个教程。

**Comment by jakietwo** [comment]
好的 非常感谢
