### ISSUE TITLE
关于多账号并发，脚本有变动时crontab重置为单个账号文件夹底下的crontab.list

### ISSUE THREAD

**Issue by lan-tianxiang** [EvineDeng/jd-base#58]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：按照教程配置多账号并发没问题，但是如果脚本出现更新，crontab会默认重置为单个账号文件夹底下的crontab.list (自己是配置了多个文件夹的一同运行)

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
教程中已经说明，多账号并发时，你的crontab.list中每一个任务都应该有多条，而不是只放这个文件夹下的任务。

**Comment by lan-tianxiang** [comment]
> 教程中已经说明，多账号并发时，你的crontab.list中每一个任务都应该有多条，而不是只放这个文件夹下的任务。
> 
> 没有仔细阅读教程哦，所以你不勾选“已仔细阅读教程”？

不好意思，没习惯，啊哈哈

多条任务在 自动更新或者删减任务的时候 是否有效呢

**Comment by lan-tianxiang** [comment]
> 教程中已经说明，多账号并发时，你的crontab.list中每一个任务都应该有多条，而不是只放这个文件夹下的任务。
> 
> 没有仔细阅读教程哦，所以你不勾选“已仔细阅读教程”？

下次一定改

**Comment by EvineDeng** [comment]
> > 教程中已经说明，多账号并发时，你的crontab.list中每一个任务都应该有多条，而不是只放这个文件夹下的任务。
> > 
> > 没有仔细阅读教程哦，所以你不勾选“已仔细阅读教程”？
> 
> 不好意思，没习惯，啊哈哈
> 
> 多条任务在 自动更新或者删减任务的时候 是否有效呢

同样有效。

**Comment by lan-tianxiang** [comment]
> > > 教程中已经说明，多账号并发时，你的crontab.list中每一个任务都应该有多条，而不是只放这个文件夹下的任务。
> > > 没有仔细阅读教程哦，所以你不勾选“已仔细阅读教程”？
> > 
> > 
> > 不好意思，没习惯，啊哈哈
> > 多条任务在 自动更新或者删减任务的时候 是否有效呢
> 
> 同样有效。

好，谢谢！！！！！！！！！！！！！！！！！！！！！！

**Comment by EvineDeng** [comment]
另外，你可以把crontab.list建立硬连接，这样就不用改多次了。

**Comment by lan-tianxiang** [comment]
> 另外，你可以把crontab.list建立硬连接，这样就不用改多次了。

嗯嗯
