### ISSUE TITLE
定时运行程序成功 但不执行脚本

### ISSUE THREAD

**Issue by s1sunny** [EvineDeng/jd-base#59]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：android 7.1.2

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：自动定时任务设置成功，可是不会执行其中脚本，无法在log里看到脚本的运行log。但是可以：cat ~/date.log  看到每分钟的执行情况。在京东APP上也看到没执行，目前苦逼手动一个一个脚本执行中，请问哪里出了问题？

### (2) 详细日志
A：无

### (1) Node.js版本

A：V12.18.3

### (2) npm版本

A：6.14.6

### (3)npm install的日志

A：11 packages are looking for funding
run 'npm fund' for details
found 0 vulnerabilities

**Comment by EvineDeng** [comment]
1. 手机在不用的时候，处于低功耗状态，程序运行受限；
2. crond程序启动了没有？
3. `crontab -l`可显示定时任务清单，清单是什么？

**Comment by s1sunny** [comment]
感谢大佬的回复，我把教程重新操作了一遍，成功了；之前可能步骤有做错，加上我对定时时间的格式理解有误，以为到点没执行。等了一天发现可以了。自己是个小白，对linux这块啥都不懂，都是看教程捣鼓，感谢出这么傻瓜式的教程，让我也整起来了。谢谢！谢谢！谢谢！
2：截图图片上传，crontab -l的内容
![image](https://user-images.githubusercontent.com/51485377/99781454-d96c5400-2b52-11eb-924c-37713b3b2758.png)
3，是crond -iPp 启动的，第二次运行有提示那段报错。
