### ISSUE TITLE
能不能搞个arm64版本

### ISSUE THREAD

**Issue by le0liu** [EvineDeng/jd-base#6]
这两天再搞星推官,发现用不了,能不能搞个arm64版本,谢谢

**Comment by EvineDeng** [comment]
老实说，我不会，我是新手。

**Comment by QCEnjoyLL** [comment]
这不是有dockerfile么，直接构建一个完事儿,我跑完测试了一下，能用
https://hub.docker.com/r/orangeqiu/jd_base

**Comment by noreph** [comment]
> 如果没有arm64设备，也能做镜像？

https://teddysun.com/581.html

**Comment by EvineDeng** [comment]
2020年11月11日晚21：55，已使用Github Action构建多平台容器，包括：
`linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6`

dockerhub请访问：https://hub.docker.com/r/evinedeng/jd-base/tags
