### ISSUE TITLE
随机互助那个create_share_code.sh怎么没有了？

### ISSUE THREAD

**Issue by yellowbins** [EvineDeng/jd-base#60]
能再上传一次吗？

**Comment by EvineDeng** [comment]
不提供了，人越来越多，搞得我被助力都满不了。倒也不是说就一定是我脚本导致的，毕竟大家都知道怎么上车。只是既然都这样了，人这么多，那我就主动减少一点点我脚本对上车人数的影响吧。

**Comment by dchaofei** [comment]
@EvineDeng 大佬现在好像不能上车了， api/v2/jd/farm/create     not found 了
