### ISSUE TITLE
如何更新我本地的脚本库

### ISSUE THREAD

**Issue by liaobadadi** [EvineDeng/jd-base#61]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：armbian

## 3. 按照以下哪个教程做的

- [x ] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：问下，我看到lxk0301/jd_scripts ，其中一些脚本更新了（再或者说新增了一些*.js脚本）,如何更新我本地的脚本库？

### (2) 详细日志
A：不需要

### (1) Node.js版本

A：不需要

### (2) npm版本

A：不需要

### (3)npm install的日志

A：不需要

**Comment by EvineDeng** [comment]
把linux的教程完整读一遍，你会找到答案的。
