### ISSUE TITLE
发现L大佬更新了2个比较有用的脚本。麻烦更新一下

### ISSUE THREAD

**Issue by jinyusme** [EvineDeng/jd-base#62]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：x86 docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x ] Docker

### (1) 具体问题
A：麻烦更新下jd_dreamFactory.js (惊喜工厂)和jd_necklace.js (点点券，可以兑换无门槛红包)

**Comment by EvineDeng** [comment]
你根本没懂我这脚本的精髓，你看看你的定时任务清单？如果没有，三个小时后再看看？
