### ISSUE TITLE
termux更新额外脚本出错

### ISSUE THREAD

**Issue by meselson** [EvineDeng/jd-base#64]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：termux 0.102

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：bash git_pull.sh 无法更新额外脚本，但直接wget都在脚本可以下载

### (2) 详细日志
A：/tmp/jd_paopao.js: No such file or directory

### (1) Node.js版本

A：v14.14.0

### (2) npm版本

A：6.14.8

### (3)npm install的日志

A：可正常npm i

**Comment by EvineDeng** [comment]
额，忘记要兼容手机了。。。手机压根没有/tmp目录。。。。

**Comment by EvineDeng** [comment]
好了，现在你连续运行两次git_pull.sh，看看第二次的结果如何？

**Comment by meselson** [comment]
可以正常更新了
