### ISSUE TITLE
镜像更新后arm平台的docker就起不来了

### ISSUE THREAD

**Issue by sofs2005** [EvineDeng/jd-base#66]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：ArmV8的Docker 19.03.12

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x ] Docker

### (1) 具体问题
A：今天一点多升级镜像后docker就不能启动了，不断在restart，和之前不支持arm平台的时候一样情况。前面应该是watchtower自动更新的，然后我手工更新了一次镜像也还是起不来

### (2) 详细日志
A：NA

### (1) Node.js版本

A：NA

### (2) npm版本

A：NA

### (3)npm install的日志

A：NA

**Comment by EvineDeng** [comment]
已修复，现在试试

**Comment by sofs2005** [comment]
可以了，老大速度真快
