### ISSUE TITLE
看到GITHUB脚本更新了，如何升级本地的脚本？

### ISSUE THREAD

**Issue by liaobadadi** [EvineDeng/jd-base#68]
## 1.关于你要提交的问题
看到GITHUB脚本更新了，如何升级本地的脚本？
Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：armbian

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：现在运行正常，但是不知道如何升级自己的本地脚本。

### (2) 详细日志
A：完全按照这个教程做的 https://github.com/EvineDeng/jd-base/wiki/Linux ，但是没搞懂，如何升级本地的脚本？

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
你确定有仔细阅读教程？你再把[Linux](https://github.com/EvineDeng/jd-base/wiki/Linux)的安装教程仔仔细细读一遍？

**Comment by meselson** [comment]
> 你确定有仔细阅读教程？你再把[Linux](https://github.com/EvineDeng/jd-base/wiki/Linux)的安装教程仔仔细细读一遍？
> 
> 然后再把`git_pull.sh`或者`git_pull.sh.sample`文件中的注释仔仔细细读一遍？

估计是不明白git的作用吧。
P.S. 建议将git地址写成国内加速的地址，https://hub.fastgit.org/lxk0301/jd_scripts，新脚本下载改成https://raw.fastgit.org/......
这个在国内就可以无障碍同步和下载了

**Comment by EvineDeng** [comment]
> > 你确定有仔细阅读教程？你再把[Linux](https://github.com/EvineDeng/jd-base/wiki/Linux)的安装教程仔仔细细读一遍？
> > 然后再把`git_pull.sh`或者`git_pull.sh.sample`文件中的注释仔仔细细读一遍？
> 
> 估计是不明白git的作用吧。
> P.S. 建议将git地址写成国内加速的地址，[https://hub.fastgit.org/lxk0301/jd_scripts，新脚本下载改成https://raw.fastgit.org/](https://hub.fastgit.org/lxk0301/jd_scripts%EF%BC%8C%E6%96%B0%E8%84%9A%E6%9C%AC%E4%B8%8B%E8%BD%BD%E6%94%B9%E6%88%90https://raw.fastgit.org/)......
> 这个在国内就可以无障碍同步和下载了

国内加速那个，不是实时的吧。

前者这个lxk0301的仓库加速链接，可不能随便替换，我一替换，所有人都要重头配置，所以这个还是算了。

后面这个可以，我来试一下，反正是wget而不是git，切换也没关系。

**Comment by EvineDeng** [comment]
@meselson 额外两上脚本的下载链接已经改了，欢迎测试。

**Comment by meselson** [comment]
> @meselson 额外两个脚本的下载链接已经改了，欢迎测试。

fastgit.org相当于就是一个代理，不存在缓存，是实时的

**Comment by EvineDeng** [comment]
> > @meselson 额外两个脚本的下载链接已经改了，欢迎测试。
> 
> fastgit.org相当于就是一个代理，不存在缓存，是实时的

会有安全性的问题吗，有什么介绍我来看看？

**Comment by meselson** [comment]
> > > @meselson 额外两个脚本的下载链接已经改了，欢迎测试。
> > 
> > 
> > fastgit.org相当于就是一个代理，不存在缓存，是实时的
> 
> 会有安全性的问题吗，有什么介绍我来看看？
> 
> 试了一下，好像没觉得有变快啊。。。

是个开源项目，github上可以搜到，国内网络的话git很不流畅啊，我这基本几k一秒，用fastgit就能几百k

**Comment by EvineDeng** [comment]
> > > > @meselson 额外两个脚本的下载链接已经改了，欢迎测试。
> > > 
> > > 
> > > fastgit.org相当于就是一个代理，不存在缓存，是实时的
> > 
> > 会有安全性的问题吗，有什么介绍我来看看？
> > 
> > 试了一下，好像没觉得有变快啊。。。
> 
> 是个开源项目，github上可以搜到，国内网络的话git很不流畅啊，我这基本几k一秒，用fastgit就能几百k

行吧，那我加个控制开关吧，让大家自己选择要不要用。

**Comment by EvineDeng** [comment]
> > > > @meselson 额外两个脚本的下载链接已经改了，欢迎测试。
> > > 
> > > 
> > > fastgit.org相当于就是一个代理，不存在缓存，是实时的
> > 
> > 会有安全性的问题吗，有什么介绍我来看看？
> > 
> > 试了一下，好像没觉得有变快啊。。。
> 
> 是个开源项目，github上可以搜到，国内网络的话git很不流畅啊，我这基本几k一秒，用fastgit就能几百k

对于lxk0301大佬的仓库，改链接没有用，因为对老用户来说，已经clone下来的项目文件，在其git配置文件，已经写死来源链接了，要是我用脚本强制给lxk0301仓库增加一个remote远程git链接的话，可能会出错。另一方面，对于已经clone下来的脚本，后续只会git pull，这个更新量不大，基本每次只有几K或者几十K，所以，即使再慢也不会花费很长时间。

**Comment by meselson** [comment]
> > > > > @meselson 额外两个脚本的下载链接已经改了，欢迎测试。
> > > > 
> > > > 
> > > > fastgit.org相当于就是一个代理，不存在缓存，是实时的
> > > 
> > > 
> > > 会有安全性的问题吗，有什么介绍我来看看？
> > > 试了一下，好像没觉得有变快啊。。。
> > 
> > 
> > 是个开源项目，github上可以搜到，国内网络的话git很不流畅啊，我这基本几k一秒，用fastgit就能几百k
> 
> 对于lxk0301大佬的仓库，改链接没有用，因为对老用户来说，已经clone下来的项目文件，在其git配置文件，已经写死来源链接了，要是我用脚本强制给lxk0301仓库增加一个remote远程git链接的话，可能会出错。另一方面，对于已经clone下来的脚本，后续只会git pull，这个更新量不大，基本每次只有几K或者几十K，所以，即使再慢也不会花费很长时间。

国内暂时没污染git clone的地址，不用加速也可以，raw的地址污染了，改了就好。

**Comment by meselson** [comment]
不开新issues了，文档中写的“经测试，在没有ROOT时，本脚本只能在内置存储中运行，在外置存储中无法正常运行。” 
这一条是因为外置存储无法正常npm i ，经测试，first_run.sh运行完成后，自行在外置存储scripts目录中运行npm install --no-bin-links ， 可正常安装依赖包，脚本在外置存储就可以正常运行了。或者您的first_run.sh 在判断运行环境为termux时，npm命令直接增加 --no-bin-links参数即可。

**Comment by EvineDeng** [comment]
> 不开新issues了，文档中写的“经测试，在没有ROOT时，本脚本只能在内置存储中运行，在外置存储中无法正常运行。” 
> 这一条是因为外置存储无法正常npm i ，经测试，first_run.sh运行完成后，自行在外置存储scripts目录中运行npm install --no-bin-links ， 可正常安装依赖包，脚本在外置存储就可以正常运行了。或者您的first_run.sh 在判断运行环境为termux时，npm命令直接增加 --no-bin-links参数即可。

行，我加上，看样子又需要多几行代码了。

**Comment by meselson** [comment]
> > 不开新issues了，文档中写的“经测试，在没有ROOT时，本脚本只能在内置存储中运行，在外置存储中无法正常运行。”
> > 这一条是因为外置存储无法正常npm i ，经测试，first_run.sh运行完成后，自行在外置存储scripts目录中运行npm install --no-bin-links ， 可正常安装依赖包，脚本在外置存储就可以正常运行了。或者您的first_run.sh 在判断运行环境为termux时，npm命令直接增加 --no-bin-links参数即可。
> 
> 行，我加上，看样子又需要多几行代码了。不过不是first_run.sh来运行npm install的，而是git_pull.sh

写错了。。。。

**Comment by meselson** [comment]
wiki中还有个问题，git config --global pull.rebase true 会导致termux无法正常git pull，我是先git config --global pull.rebase true，再git config --global pull.rebase false ，git正常，一大段提示也没有了。

**Comment by EvineDeng** [comment]
> wiki中还有个问题，git config --global pull.rebase true 会导致termux无法正常git pull，我是先git config --global pull.rebase true，再git config --global pull.rebase false ，git正常，一大段提示也没有了。
> 

行，要不你帮忙更新下wiki？目前所有人都可以编辑。

**Comment by meselson** [comment]
> > wiki中还有个问题，git config --global pull.rebase true 会导致termux无法正常git pull，我是先git config --global pull.rebase true，再git config --global pull.rebase false ，git正常，一大段提示也没有了。
> 
> 行，要不你帮忙更新下wiki？目前所有人都可以编辑。

已更新。感谢您的脚本！

**Comment by EvineDeng** [comment]
> > > wiki中还有个问题，git config --global pull.rebase true 会导致termux无法正常git pull，我是先git config --global pull.rebase true，再git config --global pull.rebase false ，git正常，一大段提示也没有了。
> > 
> > 行，要不你帮忙更新下wiki？目前所有人都可以编辑。
> 
> 已更新。感谢您的脚本！

代码已更新，安卓可以在外置存储使用了，另外wiki中我也直接改成了在外置存储使用脚本了。

**Comment by hacken156026692** [comment]
能否在安卓的说明里，再说下怎么修改编辑cookie之类吧？谢谢。

**Comment by EvineDeng** [comment]
> 能否在安卓的说明里，再说下怎么修改编辑cookie之类吧？谢谢。

请仔细阅读教程，你是把修改配置章节下面这部分内容吃了吗？

```
cd ~/storage/shared/jd/shell
cp git_pull.sh.sample git_pull.sh  # 复制git_pull.sh.sample为git_pull.sh
nano git_pull.sh   # Ctrl + O 保存，Ctrl + X 退出
```

参数清单，如何修改请见git_pull.sh中的注释。

**Comment by EvineDeng** [comment]
> > > wiki中还有个问题，git config --global pull.rebase true 会导致termux无法正常git pull，我是先git config --global pull.rebase true，再git config --global pull.rebase false ，git正常，一大段提示也没有了。
> > 
> > 行，要不你帮忙更新下wiki？目前所有人都可以编辑。
> 
> 已更新。感谢您的脚本！

发现不root无法取得外置存储上文件的可执行权限，手动运行可以，定时任务运行不了。看样子这种方法还是不行。

**Comment by hacken156026692** [comment]
~/jd/shell   main  cp git_pull.sh.sample git_pull.sh
cp: cannot create regular file 'git_pull.sh': Permission denied
 

我上视频网站先看看常规操作吧，从你这截图里确实没看懂怎么设置cookie。
另外，我目前要运行，一直显示许可被拒绝，我root权限也设置了，不知是哪里还有问题。谢谢。

**Comment by EvineDeng** [comment]
> ~/jd/shell   main  cp git_pull.sh.sample git_pull.sh
> cp: cannot create regular file 'git_pull.sh': Permission denied
>  
> 
> 我上视频网站先看看常规操作吧，从你这截图里确实没看懂怎么设置cookie。
> 另外，我目前要运行，一直显示许可被拒绝，我root权限也设置了，不知是哪里还有问题。谢谢。

你是在这里压根没有权限，所以复制都没复制成功。如果设置cookie在git_pull.sh.sample文件的注释中。

**Comment by hacken156026692** [comment]
~  pkg install tsu -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
tsu is already the newest version (8.5.1-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
 ~  /data/data/com.termux/files/home/jd/shell/
 ~/jd/shell   main  cp git_pull.sh.sample git_pull.sh
cp: cannot create regular file 'git_pull.sh': Permission denied
 
我装了tsu，root了呀，权限不知哪里设，不好意思，小白一个，看你教程，依样画葫芦似的操作，可能某个步骤错了。。。

**Comment by hacken156026692** [comment]
另外，我根据你的说明，终于知道了，sample文件，用MT管理器打开，里面注释写的清清楚楚。不好意思，一直以为这个后缀名sample是个备份文件。

**Comment by EvineDeng** [comment]
> 另外，我根据你的说明，终于知道了，sample文件，用MT管理器打开，里面注释写的清清楚楚。不好意思，一直以为这个后缀名sample是个备份文件。

看你代码中有乱码，应该是这原因导致的，正常来讲，不会有乱码。你大概是多打了些看不见的字符。

**Comment by hacken156026692** [comment]
好的，我重新全部清除数据了终端termux，再按照教程一步步做下来，有一点眉目了，谢谢指导我这个小白
