### ISSUE TITLE
金果摇钱树更新了 “摇钱树是否卖出金果” 的参数，更新后的 git_pull.sh.sample 中无此项目

### ISSUE THREAD

**Issue by servicehost** [EvineDeng/jd-base#72]
Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程

## 2. 使用什么平台，精确到版本
A：
N3700 x86 软路由
固件版本 | OpenWrt  R20.2.15 / LuCI Master (git-20.045.63360-69eac90)
内核版本 | 4.19.101
Node v12.19.0

## 3. 按照以下哪个教程做的
- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题

脚本更新：https://github.com/lxk0301/jd_scripts/blob/master/jd_moneyTree.js

MONEY_TREE_SELL_FRUIT | 摇钱树是否卖出金果 | 非必须 | 控制摇钱树脚本是否自动卖出金果兑换成金币，true卖出，false不卖出，默认true

但是git_pull.sh更新后也无此参数可修改，希望能添加此功能。

**Comment by EvineDeng** [comment]
好，晚点加上。

**Comment by servicehost** [comment]
> 
> 
> 好，晚点加上。

答复好快，麻烦了。

有个问题请教下您，我看到lxk0301中一般的JS源码中定义控制某些代码是否执行是写成：

`let jdNotify = true;//用来是否关闭弹窗通知，true表示关闭，false表示开启。
let superMarketUpgrade = true;//自动升级,顺序:解锁升级商品、升级货架,true表示自动升级,false表示关闭自动升级
`
但是这次的金果摇钱树，他的代码是这么写的：

  if (process.env.MONEY_TREE_SELL_FRUIT && process.env.MONEY_TREE_SELL_FRUIT === 'false') 

我搜索了 jd_moneyTree.js 也没找到 MONEY_TREE_SELL_FRUIT 的定义。
而您的 git_pull_function.sh 的代码基本就是去修改 JS 文件中涉及 true 或 false 的部份。那像金果摇钱树这样的要如何修改呢？MONEY_TREE_SELL_FRUIT 这个参数lxk0301是在哪定义的？

本人小白，只能看懂部份代码，特向您请教，谢谢。

**Comment by EvineDeng** [comment]
没有定义，从环境变量取值，你看我改就好了。

**Comment by servicehost** [comment]
> 
> 
> 没有定义，从环境变量取值，你看我改就好了。

好的

**Comment by EvineDeng** [comment]
已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不自己卖金果功能是否正常。

**Comment by hacken156026692** [comment]
> 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。

不好意思，我手机安卓，装了termux，然后执行了first.sh，最后脚本执行成功了。不过好像没地方可以设置cookie，请问下哪里设置cookie，谢谢

**Comment by hacken156026692** [comment]
> 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。

我在MT管理器运行，最后是脚本执行成功。
我在twrmux里运行，显示这个

~/jd  bash first_run.sh
bash: first_run.sh: Permission denied

是哪里没对吗？谢谢

**Comment by meselson** [comment]
> > 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。
> 
> 我在MT管理器运行，最后是脚本执行成功。
> 我在twrmux里运行，显示这个
> 
> ~/jd  bash first_run.sh
> bash: first_run.sh: Permission denied
> 
> 是哪里没对吗？谢谢

MT里改过的文件，要在Termux里重新给予权限

**Comment by servicehost** [comment]
> 
> 
> 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。

你好，实测依然会卖掉金果。

**已更新 git_pull.sh 并设定如下：**

################################## 定义摇钱树是否自动将金果卖出变成金币（选填） ##################################
## 默认为true，自动将金果卖出，变成金币，如想要不希望自动卖出，请修改为 false
MoneyTreeAutoSell="false"

**执行 bash git_pull.sh 后显示的日志，从头到尾没有出现 ：“设置摇钱树是否自动将金果卖出变成金币为”的字样，如下面所示：**

_更新JS脚本，原地址：https://github.com/lxk0301/jd_scripts

Fetching origin
HEAD is now at 24f23bf update
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.

js脚本更新完成，开始替换信息，并检测定时任务变化情况...

jdCookie.js: 替换Cookies...

sendNotify.js: 替换ServerChan推送通知SCKEY...

jd_bean_sign.js：设置每日签到每个接口延迟时间为 250 ms...

jdFruitShareCodes.js: 替换东东农场互助码...

jdPetShareCodes.js: 替换东东萌宠互助码...

jdPlantBeanShareCodes.js: 替换种豆得豆互助码...

jd_blueCoin.js: 设置东东超市蓝币兑换 20 个京豆...

jd_joy.js: 设置宠汪汪喂食克数为：80g...

jd_joy_feedPets.js: 设置宠汪汪喂食克数为：80g...

jd_joy_reward.js：设置宠汪汪兑换京豆数量为 20...

jd_joy_steal.js：设置宠汪汪成功偷取好友积分与狗粮是否静默运行为 true...

jd_joy.js：设置宠汪汪是否自动报名宠物赛跑为 false...

jd_dreamFactory.js：设置京喜工厂是否静默运行为 false...

jd_unsubscribe.js：设置商品取关数量为 50...

jd_unsubscribe.js：设置店铺取关数量为 50...

检测到有新的定时任务：

jd_small_home

每日签到的通知形式保持默认为 原始通知...

-------------------------------------------------------------------

更新shell脚本，原地址：https://github.com/EvineDeng/jd-base

Fetching origin
HEAD is now at e930d27 Merge pull request #73 from EvineDeng/dev
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.

shell脚本更新完成..._

我仔细对比过，执行 git_pull.sh 前和执行后 金果摇钱树 jd_moneyTree.js 原来的代码片段，下面这段JS代码无任何变化，并有修改成功：

_if (process.env.MONEY_TREE_SELL_FRUIT && process.env.MONEY_TREE_SELL_FRUIT === 'false')_

**Comment by EvineDeng** [comment]
> > 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。
> 
> 不好意思，我手机安卓，装了termux，然后执行了first.sh，最后脚本执行成功了。不过好像没地方可以设置cookie，请问下哪里设置cookie，谢谢

请自行阅读wiki，会告诉你在哪里改cookie。

**Comment by EvineDeng** [comment]
> > 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。
> 
> ### 你好，实测依然会卖掉金果。
> 
> **已更新 git_pull.sh 并设定如下：**
> 
> 定义摇钱树是否自动将金果卖出变成金币（选填）
> 默认为true，自动将金果卖出，变成金币，如想要不希望自动卖出，请修改为 false
> MoneyTreeAutoSell="false"
> ### **执行 bash git_pull.sh 后显示的日志，从头到尾没有出现 ：“设置摇钱树是否自动将金果卖出变成金币为”的字样，如下面所示：**
> 
> 更新JS脚本，原地址：https://github.com/lxk0301/jd_scripts
> 
> Fetching origin
> HEAD is now at 24f23bf update
> warning: Pulling without specifying how to reconcile divergent branches is
> discouraged. You can squelch this message by running one of the following
> commands sometime before your next pull:
> 
> git config pull.rebase false # merge (the default strategy)
> git config pull.rebase true # rebase
> git config pull.ff only # fast-forward only
> 
> You can replace "git config" with "git config --global" to set a default
> preference for all repositories. You can also pass --rebase, --no-rebase,
> or --ff-only on the command line to override the configured default per
> invocation.
> 
> Already up to date.
> 
> js脚本更新完成，开始替换信息，并检测定时任务变化情况...
> 
> jdCookie.js: 替换Cookies...
> 
> sendNotify.js: 替换ServerChan推送通知SCKEY...
> 
> jd_bean_sign.js：设置每日签到每个接口延迟时间为 250 ms...
> 
> jdFruitShareCodes.js: 替换东东农场互助码...
> 
> jdPetShareCodes.js: 替换东东萌宠互助码...
> 
> jdPlantBeanShareCodes.js: 替换种豆得豆互助码...
> 
> jd_blueCoin.js: 设置东东超市蓝币兑换 20 个京豆...
> 
> jd_joy.js: 设置宠汪汪喂食克数为：80g...
> 
> jd_joy_feedPets.js: 设置宠汪汪喂食克数为：80g...
> 
> jd_joy_reward.js：设置宠汪汪兑换京豆数量为 20...
> 
> jd_joy_steal.js：设置宠汪汪成功偷取好友积分与狗粮是否静默运行为 true...
> 
> jd_joy.js：设置宠汪汪是否自动报名宠物赛跑为 false...
> 
> jd_dreamFactory.js：设置京喜工厂是否静默运行为 false...
> 
> jd_unsubscribe.js：设置商品取关数量为 50...
> 
> jd_unsubscribe.js：设置店铺取关数量为 50...
> 
> 检测到有新的定时任务：
> 
> jd_small_home
> 
> 每日签到的通知形式保持默认为 原始通知...
> 
> 更新shell脚本，原地址：https://github.com/EvineDeng/jd-base
> 
> Fetching origin
> HEAD is now at [e930d27](https://github.com/EvineDeng/jd-base/commit/e930d27014173fb87524db52e366c022fdef9aeb) Merge pull request #73 from EvineDeng/dev
> warning: Pulling without specifying how to reconcile divergent branches is
> discouraged. You can squelch this message by running one of the following
> commands sometime before your next pull:
> 
> git config pull.rebase false # merge (the default strategy)
> git config pull.rebase true # rebase
> git config pull.ff only # fast-forward only
> 
> You can replace "git config" with "git config --global" to set a default
> preference for all repositories. You can also pass --rebase, --no-rebase,
> or --ff-only on the command line to override the configured default per
> invocation.
> 
> Already up to date.
> 
> shell脚本更新完成...
> ### 我仔细对比过，执行 git_pull.sh 前和执行后 金果摇钱树 jd_moneyTree.js 原来的代码片段，下面这段JS代码无任何变化，并没有修改成功：
> 
> _if (process.env.MONEY_TREE_SELL_FRUIT && process.env.MONEY_TREE_SELL_FRUIT === 'false')_

好吧，我光记得写函数了，不记得调用了，现在应该好了，连续运行两次git_pull.sh，看第二次的结果。然后检测下有效没有？

**Comment by servicehost** [comment]
> 
> 
> > > 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。
> > 
> > 
> > ### 你好，实测依然会卖掉金果。
> > **已更新 git_pull.sh 并设定如下：**
> > 定义摇钱树是否自动将金果卖出变成金币（选填）
> > 默认为true，自动将金果卖出，变成金币，如想要不希望自动卖出，请修改为 false
> > MoneyTreeAutoSell="false"
> > ### **执行 bash git_pull.sh 后显示的日志，从头到尾没有出现 ：“设置摇钱树是否自动将金果卖出变成金币为”的字样，如下面所示：**
> > 更新JS脚本，原地址：https://github.com/lxk0301/jd_scripts
> > Fetching origin
> > HEAD is now at 24f23bf update
> > warning: Pulling without specifying how to reconcile divergent branches is
> > discouraged. You can squelch this message by running one of the following
> > commands sometime before your next pull:
> > git config pull.rebase false # merge (the default strategy)
> > git config pull.rebase true # rebase
> > git config pull.ff only # fast-forward only
> > You can replace "git config" with "git config --global" to set a default
> > preference for all repositories. You can also pass --rebase, --no-rebase,
> > or --ff-only on the command line to override the configured default per
> > invocation.
> > Already up to date.
> > js脚本更新完成，开始替换信息，并检测定时任务变化情况...
> > jdCookie.js: 替换Cookies...
> > sendNotify.js: 替换ServerChan推送通知SCKEY...
> > jd_bean_sign.js：设置每日签到每个接口延迟时间为 250 ms...
> > jdFruitShareCodes.js: 替换东东农场互助码...
> > jdPetShareCodes.js: 替换东东萌宠互助码...
> > jdPlantBeanShareCodes.js: 替换种豆得豆互助码...
> > jd_blueCoin.js: 设置东东超市蓝币兑换 20 个京豆...
> > jd_joy.js: 设置宠汪汪喂食克数为：80g...
> > jd_joy_feedPets.js: 设置宠汪汪喂食克数为：80g...
> > jd_joy_reward.js：设置宠汪汪兑换京豆数量为 20...
> > jd_joy_steal.js：设置宠汪汪成功偷取好友积分与狗粮是否静默运行为 true...
> > jd_joy.js：设置宠汪汪是否自动报名宠物赛跑为 false...
> > jd_dreamFactory.js：设置京喜工厂是否静默运行为 false...
> > jd_unsubscribe.js：设置商品取关数量为 50...
> > jd_unsubscribe.js：设置店铺取关数量为 50...
> > 检测到有新的定时任务：
> > jd_small_home
> > 每日签到的通知形式保持默认为 原始通知...
> > 更新shell脚本，原地址：https://github.com/EvineDeng/jd-base
> > Fetching origin
> > HEAD is now at [e930d27](https://github.com/EvineDeng/jd-base/commit/e930d27014173fb87524db52e366c022fdef9aeb) Merge pull request #73 from EvineDeng/dev
> > warning: Pulling without specifying how to reconcile divergent branches is
> > discouraged. You can squelch this message by running one of the following
> > commands sometime before your next pull:
> > git config pull.rebase false # merge (the default strategy)
> > git config pull.rebase true # rebase
> > git config pull.ff only # fast-forward only
> > You can replace "git config" with "git config --global" to set a default
> > preference for all repositories. You can also pass --rebase, --no-rebase,
> > or --ff-only on the command line to override the configured default per
> > invocation.
> > Already up to date.
> > shell脚本更新完成...
> > ### 我仔细对比过，执行 git_pull.sh 前和执行后 金果摇钱树 jd_moneyTree.js 原来的代码片段，下面这段JS代码无任何变化，并没有修改成功：
> > _if (process.env.MONEY_TREE_SELL_FRUIT && process.env.MONEY_TREE_SELL_FRUIT === 'false')_
> 
> 好吧，我光记得写函数了，不记得调用了，现在应该好了，连续运行两次git_pull.sh，看第二次的结果。然后检测下有效没有？

OK，这次不会卖掉了
修改成功，JS源码中的 卖金果 执行代码也消失了
辛苦了

**Comment by servicehost** [comment]
> 
> 
> 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。

你好，还有个小问题。

我发现如果你的 shell 脚本有更新，那么通过 bash git_pull.sh 执行后，会导致所有的 .sh 文件失去可执行权限。我昨天看路由的日志明明有些 .sh 脚本执行了，却没生成 log，任务也没做，后来发现有个账号的目录所有的可执行权限全没了。

**所以 git_pull_function.sh 这里的代码：**

**### 更新shell脚本**
if [ $? -eq 0 ]; then
  cd ${ShellDir}
  echo -e "--------------------------------------------------------------\n"
  Git_PullShell
fi

**是不是缺了段：chmod +x "${ShellDir}/${Cron}.sh" ？**

因为在 “自动增加新的定时任务” 和 “复制额外的js脚本对应的ash脚本并增加定时任务” 中都是有这段代码的。

而我是把 “定义是否自动增加新的本地定时任务（选填）” AutoAddCron="false"  关掉的。这样就导致了无法被执行 chmod +x 的操作。

**Comment by EvineDeng** [comment]
> > 
> > 
> > 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。
> 
> 你好，还有个小问题。
> 
> 我发现如果你的 shell 脚本有更新，那么通过 bash git_pull.sh 执行后，会导致所有的 .sh 文件失去可执行权限。我昨天看路由的日志明明有些 .sh 脚本执行了，却没生成 log，任务也没做，后来发现有个账号的目录所有的可执行权限全没了。
> 
> ### 所以 git_pull_function.sh 这里的代码：
> 
> 更新shell脚本
> if [ $? -eq 0 ]; then
>   cd ${ShellDir}
>   echo -e "--------------------------------------------------------------\n"
>   Git_PullShell
> fi
> 
> ### 是不是缺了段：chmod +x "${ShellDir}/${Cron}.sh" ？
> 
> 因为在 “自动增加新的定时任务” 和 “复制额外的js脚本对应的ash脚本并增加定时任务” 中都是有这段代码的。
> 
> 而我是把 “定义是否自动增加新的本地定时任务（选填）” AutoAddCron="false"  关掉的。这样就导致了无法被执行 chmod +x 的操作。
> 
> 即使有些人打开这个选项，如果没有新的定时任务，只有shell脚本更新，同样也会因为更新导致所有 .sh 失去可执行权限。
> 
> 

是我另外加的代码出了问题，不是你说这里，我等会改下。

**Comment by EvineDeng** [comment]
> > 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。
> 
> 你好，还有个小问题。
> 
> 我发现如果你的 shell 脚本有更新，那么通过 bash git_pull.sh 执行后，会导致所有的 .sh 文件失去可执行权限。我昨天看路由的日志明明有些 .sh 脚本执行了，却没生成 log，任务也没做，后来发现有个账号的目录所有的可执行权限全没了。
> 
> ### 所以 git_pull_function.sh 这里的代码：
> 更新shell脚本
> if [ $? -eq 0 ]; then
> cd ${ShellDir}
> echo -e "--------------------------------------------------------------\n"
> Git_PullShell
> fi
> 
> ### 是不是缺了段：chmod +x "${ShellDir}/${Cron}.sh" ？
> 因为在 “自动增加新的定时任务” 和 “复制额外的js脚本对应的ash脚本并增加定时任务” 中都是有这段代码的。
> 
> 而我是把 “定义是否自动增加新的本地定时任务（选填）” AutoAddCron="false" 关掉的。这样就导致了无法被执行 chmod +x 的操作。
> 
> 即使有些人打开这个选项，如果没有新的定时任务，只有shell脚本更新，同样也会因为更新导致所有 .sh 失去可执行权限。

已修复。

**Comment by servicehost** [comment]
> 
> 
> > > 已添加相关代码，请在重新配置git_pull.sh后，连续运行两次，看看摇钱树不卖金果功能是否正常。
> > 
> > 
> > 你好，还有个小问题。
> > 我发现如果你的 shell 脚本有更新，那么通过 bash git_pull.sh 执行后，会导致所有的 .sh 文件失去可执行权限。我昨天看路由的日志明明有些 .sh 脚本执行了，却没生成 log，任务也没做，后来发现有个账号的目录所有的可执行权限全没了。
> > ### 所以 git_pull_function.sh 这里的代码：
> > 更新shell脚本
> > if [ $? -eq 0 ]; then
> > cd ${ShellDir}
> > echo -e "--------------------------------------------------------------\n"
> > Git_PullShell
> > fi
> > ### 是不是缺了段：chmod +x "${ShellDir}/${Cron}.sh" ？
> > 因为在 “自动增加新的定时任务” 和 “复制额外的js脚本对应的ash脚本并增加定时任务” 中都是有这段代码的。
> > 而我是把 “定义是否自动增加新的本地定时任务（选填）” AutoAddCron="false" 关掉的。这样就导致了无法被执行 chmod +x 的操作。
> > 即使有些人打开这个选项，如果没有新的定时任务，只有shell脚本更新，同样也会因为更新导致所有 .sh 失去可执行权限。
> 
> 已修复。

好的
