### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by bobotoy** [EvineDeng/jd-base#76]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Ubuntu18

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：功能建议：建议添加自动互助上车脚本，直接调用git_pull中设置的互助码访问API，并设置每月1/10/20日2点后执行计划任务

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
不接受此建议，有能力者自己写。

**Comment by bobotoy** [comment]
我自己简单，脚本都不用，直接定时任务访问网址，只是感觉有点low

**Comment by EvineDeng** [comment]
> 我自己简单，脚本都不用，直接定时任务访问网址，只是感觉有点low

能达到目的就行。
