### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by zhuzf88** [EvineDeng/jd-base#78]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Armbian 5.9.0

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：似乎是我的node版本太高还是npm版本太低？

### (2) 详细日志
A：
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=4.17.20 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
added 205 packages from 179 contributors in 31.193s

### (1) Node.js版本

A：v10.21.0

### (2) npm版本

A：5.8.0

### (3)npm install的日志

A：
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
up to date in 9.844s

**Comment by EvineDeng** [comment]
1. 只是警告，能用就行；
2. 如果想消除，按它的提示操作即可。

**Comment by hacken156026692** [comment]
> 1. 只是警告，能用就行；
> 2. 如果想消除，按它的提示操作即可。

请问，我安卓今天试了一下，就在nano里设置了cookie，设置了账号数量为1，其他互助码都没加进去，运行了一下。显示如下，

Fetching origin
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Total 13 (delta 8), reused 8 (delta 8), pack-reused 5
Unpacking objects: 100% (13/13), 2.07 KiB | 100.00 KiB/s, done.
From https://github.com/EvineDeng/jd-base
   cf12fae..86ef005  main       -> origin/main
   d4a7633..6c8da54  dev        -> origin/dev
HEAD is now at 86ef005 Merge pull request #77 from EvineDeng/dev
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.

shell脚本更新完成...


这表示基本上运行没问题了吗？麻烦简单帮我看一下，谢谢。

**Comment by EvineDeng** [comment]
你自己试下能用不能用，能用就行。

**Comment by landcruser** [comment]
我的docker跑的很好，加入了安卓以备用，安卓华为手机安卓7.0已经root，按照安卓教程配置，似乎脚本的.sh放在外置存储无法给予可执行权限，百度无解，tremux也尝试用proot,和tsu，都不行，有遇到过的吗？

**Comment by EvineDeng** [comment]
> 我的docker跑的很好，加入了安卓以备用，安卓华为手机安卓7.0已经root，按照安卓教程配置，似乎脚本的.sh放在外置存储无法给予可执行权限，百度无解，tremux也尝试用proot,和tsu，都不行，有遇到过的吗？

似乎无解，所以我昨天把教程中这个root相关描述也删掉了，我也搞不定。

**Comment by EvineDeng** [comment]
> 这表示基本上运行没问题了吗？麻烦简单帮我看一下，谢谢。

你自己试下能用不能用，能用就行。

**Comment by landcruser** [comment]
> 我的docker跑的很好，加入了安卓以备用，安卓华为手机安卓7.0已经root，按照安卓教程配置，似乎脚本的.sh放在外置存储无法给予可执行权限，百度无解，tremux也尝试用proot,和tsu，都不行，有遇到过的吗？
好的，不过也不影响使用，感谢大佬

**Comment by hacken156026692** [comment]
大佬，问下，有没有一个命令，可以一下子把所有的.js自动签到完成的？我现在一个一个执行，感觉还不高效，比如得复制文件名jd_bean_sign.js，再在终极模拟器里执行。

**Comment by EvineDeng** [comment]
> jd_bean_sign.js

签到只有一个jd_bean_sign.js

**Comment by hacken156026692** [comment]
谢谢大佬！晚安。
