### ISSUE TITLE
博主你好

### ISSUE THREAD

**Issue by xiaoyao1995** [EvineDeng/jd-base#8]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
added 213 packages from 208 contributors and audited 213 packages in 53.074s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

更新shell脚本，原地址：https://github.com/EvineDeng/jd-base

Fetching origin
HEAD is now at ed15a6d 遗漏了蓝币兑换1000京豆的代码。
Already up to date.

**Comment by xiaoyao1995** [comment]
请问openwrt内docker出现这种情况如何使用，我用的上一个问题里别人编译你的包运行的

**Comment by EvineDeng** [comment]
只是警告，不用管。
