### ISSUE TITLE
lxk大佬跑路了 还能用吗？

### ISSUE THREAD

**Issue by wangkangfeng99** [EvineDeng/jd-base#82]
![VOW`C}OEZ${ }5{LR WL@D](https://user-images.githubusercontent.com/68324194/100436040-c4a33980-30d9-11eb-806e-657405e137f3.png)

**Comment by EvineDeng** [comment]
能用，你这错误是哪里没做对

**Comment by wangkangfeng99** [comment]
> 能用，你这错误是哪里没做对

找到问题了 我的node版本太低
