### ISSUE TITLE
在<<定义User-Agent（选填）>> 填入后，运行报错

### ISSUE THREAD

**Issue by lan-tianxiang** [EvineDeng/jd-base#87]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Centos 8.0

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：在<<定义User-Agent（选填）>> 填入后，运行报错

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/42911023/100531150-a6eae700-3235-11eb-8797-d8cd8916d75c.png)

Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.
Unknown regexp modifier "/1" at -e line 1, at end of line
Unknown regexp modifier "/5" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
syntax error at -e line 1, near "000af5363df7"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "/;"
syntax error at -e line 1, near "ANDROID 9"
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/0" at -e line 1, at end of line
Unknown regexp modifier "/1" at -e line 1, at end of line
-e has too many errors.
Bareword found where operator expected at -e line 1, near "000af5363df7"
        (Missing operator before af5363df7?)
Number found where operator expected at -e line 1, near "ANDROID 9"
        (Do you need to predeclare ANDROID?)
Warning: Use of "ref" without parentheses is ambiguous at -e line 1.

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
外欠侧加双引号了没？

**Comment by lan-tianxiang** [comment]
> 两侧加双引号了没？

加了 
![image](https://user-images.githubusercontent.com/42911023/100532713-bdde0900-3236-11eb-9d25-05a08c666552.png)

**Comment by lan-tianxiang** [comment]
UserAgent="jdapp;android;9.2.4;9;-000af5363df7;network/wifi;model/Mi 10 Pro;addressid/1302879558;aid/f09ae3c06b071b35;oaid/038299e47951c4dc;osVer/28;appBuild/85576;psn/-000af5363df7|150;psq/17;uid/-000af5363df7;adk/;ads/;pap/JA2015_311210|9.2.4|ANDROID 9;osv/9;pv/154.18;jdv/0|kong|t_1000170135|tuiguang|notset|1606538736428|1606538736;ref/com.jd.lib.personal.view.fragment.JDPersonalFragment;partner/xiaomi001;apprpd/MyJD_Main;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 9; Mi 10 Pro Build/PKQ1.190118.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/045131 Mobile Safari/537.36"

**Comment by EvineDeng** [comment]
现在应该好了，你先不要定义UserAgent，运行一次git_pull.sh，运行一次以后，再定义UserAgent，然后再运行一次git_pull.sh看看报错不报错。

开始没考虑到UA中会含有`|`这个符号，导致出错。

**Comment by lan-tianxiang** [comment]
> 现在应该好了，你先不要定义UserAgent，运行一次git_pull.sh，运行一次以后，再定义UserAgent，然后再运行一次git_pull.sh看看报错不报错。
> 
> 开始没考虑到UA中会含有`|`这个符号，导致出错。


可以了！！！ 谢谢！！！！
