### ISSUE TITLE
更新后定时运行无效果，日志为空，手动运行正常

### ISSUE THREAD

**Issue by SuAlex1996** [EvineDeng/jd-base#95]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：linux centos7

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：更新后定时运行无效果，日志为空。手动运行正常，日志正常。对于这次更新把export删除有些疑惑。

### (2) 详细日志
A：日志为空。

### (1) Node.js版本

A：v14.15.1

### (2) npm版本

A：6.14.8

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
不申明PATH，直接使用系统默认的PATH。

不申明PATH的时候，你系统的默认PATH是什么？

**Comment by EvineDeng** [comment]
看样子有些平台在定时任务中还必须申明PATH了呀

**Comment by EvineDeng** [comment]
你额外增加一条定时任务如下：
```
* * * * * date; echo $PATH >> ~/test.log
```
在家目录下看看这个文件每分钟能正常写入内容吗，如果能，看看内容是什么？

**Comment by SuAlex1996** [comment]
export NODE_HOME=/usr/local/lib/nodejs/node-v14.15.1-linux-x64
export PATH=$NODE_HOME/bin:$PATH
export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0;
这个是我自己添加的
默认就是PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

test,log输出如下
`XDG_SESSION_ID=1185
SHELL=/bin/sh
USER=root
PATH=/usr/bin:/bin
PWD=/root
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
LOGNAME=root
XDG_RUNTIME_DIR=/run/user/0
_=/usr/bin/env
`

**Comment by SuAlex1996** [comment]
`XDG_SESSION_ID=1185
SHELL=/bin/sh
USER=root
PATH=/usr/bin:/bin
PWD=/root
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
LOGNAME=root
XDG_RUNTIME_DIR=/run/user/0
_=/usr/bin/env
`

**Comment by EvineDeng** [comment]
看样子确实crontab的PATH和系统默认的PATH会不一致。你crontab的PATH是`PATH=/usr/bin:/bin`。
你这样解决吧：
1. 在你自己的crontab.list文件中新增第一行如下：
```shell
PATH=/usr/local/lib/nodejs/node-v14.15.1-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
```
2. 然后使用`crontab /你的路径/crontab.list`更新一下crontab。然后看看定时任务正常不正常？

其实你的PATH就和我在改代码之前写死的`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`不一致，所以这也是我今天把PATH申明删掉的原因，我希望物理机由每个用户自己去按照上述方法在crontab.list中写入自己的PATH。教程那边我稍微调整一下。另外crontab.list.sample我也增加一点注释。

**Comment by SuAlex1996** [comment]
增加之后可以了，有日志了，感谢。

**Comment by kissfast** [comment]
我也是同样的问题，添加了一行path就可以
谢谢大神

**Comment by EvineDeng** [comment]
> 我也是同样的问题，添加了一行path就可以
> 谢谢大神

嗯，以你系统实际的PATH为准，不要照抄。

**Comment by wangkangfeng99** [comment]
![image](https://user-images.githubusercontent.com/68324194/101123171-2d853700-362f-11eb-9d76-977e76cd47ee.png)
我也遇到这个问题了 不一样的地方是 手动运行js文件正常，运行shell无反应，ye也是和他一样的解决方法吗

**Comment by EvineDeng** [comment]
> ![image](https://user-images.githubusercontent.com/68324194/101123171-2d853700-362f-11eb-9d76-977e76cd47ee.png)
> 我也遇到这个问题了 不一样的地方是 手动运行js文件正常，运行shell无反应，ye也是和他一样的解决方法吗

一样

**Comment by wangkangfeng99** [comment]
我不知道我的path要改成什么
能简单说一下吗

**Comment by EvineDeng** [comment]
> 我不知道我的path要改成什么
> 能简单说一下吗

重新去看下linux那篇教程，定时任务部分，我更新了。

**Comment by hacken156026692** [comment]
大佬，反馈一个小问题。我是安卓ternux.执行的js文件。
执行jd_bean_sign，结果提示

$ node jd_bean_sign
{"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1607132838425,"socket":1607132838426,"lookup":1607132838429,"error":1607132838433,"phases":{"wait":1,"dns":3,"total":8}}}
检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件
文件下载完毕
*****************开始京东账号1 XXXXXX京豆签到*******************

两个签到都执行成功，server酱也推送了。但我好奇这个JD_DailyBonus是什么东西，又去执行了一下，发现JD_DailyBonus又可以签到十几个豆，不过只能签到账号1，账号2无签到活动。

请能否看看并配置一下这个JD_DailyBonus的内容？谢谢！！

**Comment by EvineDeng** [comment]
lxk0301仓库中有说明。

**Comment by EvineDeng** [comment]
> 大佬，反馈一个小问题。我是安卓ternux.执行的js文件。
> 执行jd_bean_sign，结果提示
> 
> 检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件
> 文件下载完毕
> *****************开始京东账号1 XXXXXX京豆签到*******************
> 
> 两个签到都执行成功，server酱也推送了。但我好奇这个JD_DailyBonus是什么东西，又去执行了一下，发现JD_DailyBonus又可以签到十几个豆，不过只能签到账号1，账号2无签到活动。
> 
> 请能否看看并配置一下这个JD_DailyBonus的内容？谢谢！！

lxk0301仓库中有说明。

**Comment by RtYkk** [comment]
请问我直接 `crontab -e` 有什么问题吗？刚刚发现了这个问题准备来提个 issue 就看到了 pin……

**Comment by EvineDeng** [comment]
> 请问我直接 `crontab -e` 有什么问题吗？刚刚发现了这个问题准备来提个 issue 就看到了 pin……

脚本自动增删任务是靠crontab.list这个文件，每次增删会后会以这个文件的内存覆盖你原来的定时任务，so...

**Comment by RtYkk** [comment]
> > 请问我直接 `crontab -e` 有什么问题吗？刚刚发现了这个问题准备来提个 issue 就看到了 pin……
> 
> 脚本自动增删任务是靠crontab.list这个文件，每次增删会后会以这个文件的内存覆盖你原来的定时任务，so你不改这个文件的话
> crontab -e的修改相当于没修改。

改了，改了。感谢指导。本来想偷个懒（

**Comment by hacken156026692** [comment]
不好意思，困扰了我两天，想对这个定时再问一下：

我看了android 和linux篇的定时，但还是运行bash git_pull.sh时，没有加载成功定时任务。

~/jd/shell $ which node
/data/data/com.termux/files/usr/bin/node
~/jd/shell $ whereis node
node: /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/share/man/man1/node.1.gz
~/jd/shell $ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

请问下，我的path应该怎么改，进nano crontab.list修改了，改在第一行下面吗？谢谢！！！！！

**Comment by EvineDeng** [comment]
> 不好意思，困扰了我两天，想对这个定时再问一下（我是安卓termux，之前一直一个个手动运行js文件，想试试sh的定时文件，不过失败了）：
> 
> 我看了android 和linux篇的定时，但还是运行bash git_pull.sh时，显示里没有加载成功定时任务。我在linux里试试输入了命令，如下
> 
> ~/jd/shell $ which node
> /data/data/com.termux/files/usr/bin/node
> ~/jd/shell $ whereis node
> node: /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/share/man/man1/node.1.gz
> ~/jd/shell $ echo $PATH
> /data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
> 
> 请问下一下大神，我的path应该怎么改。进nano crontab.list修改了，是在第一行下面回车了复制这个PATH吗？谢谢！！！！！

用你的PATH替换crontab.list中的PATH

**Comment by hacken156026692** [comment]
秒回啊！谢谢大神！PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets吗？
不用bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin这样的形式吗？

**Comment by EvineDeng** [comment]
> 秒回啊！谢谢大神！PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets吗？
> 不用bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin这样的形式吗？

嗯

**Comment by hacken156026692** [comment]
大神，咨询一下，我想每个小时整点自动红包雨，但我应该命令弄错了，我写的是
*/60  * * * * /data/data/com.termux/files/home/jd/shell/jd_live_redrain.sh

运行 crontab crontab.list，提示
"crontab.list":52: bad minute
errors in crontab file, can't install.

我52行这个每小时整点运行红包雨的命令，应该怎么修改，能否指出错误，谢谢！

**Comment by EvineDeng** [comment]
> 大神，咨询一下，我想每个小时整点自动红包雨，但我应该命令弄错了，我写的是
> */60 * * * * /data/data/com.termux/files/home/jd/shell/jd_live_redrain.sh
> 
> 运行 crontab crontab.list，提示
> "crontab.list":52: bad minute
> errors in crontab file, can't install.
> 
> 我52行这个每小时整点运行红包雨的命令，应该怎么修改，能否指出错误，谢谢！

这问题你应该百度crontab写法。
