### ISSUE TITLE
当前获取js脚本的地址好像已经被作者 See you later了，可以改成gitee上的地址进行gitpull

### ISSUE THREAD

**Issue by yuanshaocheng** [EvineDeng/jd-base#96]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：windows docker

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：目前脚本貌似不是最新的了，js的脚本没有获取到一些新的脚本，原因是lxk0301大佬的github关闭了之前的脚本;
  实际上gitee上他还在更新，奉上地址 https://gitee.com/lxk0301/jd_scripts?_from=gitee_search

### (2) 详细日志
A：日志没有，我是看js脚本没有新增，谢谢

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
gitee上没有github更新快，不会切换为gitee的。

**Comment by yuanshaocheng** [comment]
嗷嗷，我直接看github地址，作者好像关闭了还是只留了一个readme.md，所以有此一问，谢谢哈

**Comment by ilaotan** [comment]
master分支，main分支。。。

**Comment by xiaolaba123** [comment]
ScriptsURL=https://github.com/lxk0301/jd_scripts 把这个替换成你的那个吗？
