### ISSUE TITLE
脚本更新问题

### ISSUE THREAD

**Issue by xiaokaig** [EvineDeng/jd-base#97]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [x] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：l大更新了几个新js，git_pull下载下来了，但是sh和计划任务都没有添加，手动添加了sh和计划任务，git_pull又给删了😅

### (2) 详细日志
A：
git_pull日志怎么永远是11.25的

### (1) Node.js版本

A：12.16.1

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
因为要等上游添加，如果你非得手动添加，你暂时将AutoDelCron设置为false。

**Comment by hacken156026692** [comment]
请问一下大神，jd_kd.js等几个新更新的任务，我如下载下来到手机里，在ternux里是否无法运行，还需要配合对应的sh文件才能运行是吗？
