### ISSUE TITLE
rm_bash 执行出错

### ISSUE THREAD

**Issue by GoToBoy** [EvineDeng/jd-base#98]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：OSX big Sur

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [x] MacOS
- [ ] Docker

### (1) 具体问题
A：bash rm_log.sh 出错

### (2) 详细日志
A：
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
rm_log.sh: line 21: 1607347908 - : syntax error: operand expected (error token is " ")

### (1) Node.js版本

A：v12.13.0

### (2) npm版本

A：我是用的是yarn ， yarn -v 1.22.4

### (3)npm install的日志

A：
yarn install v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.

**Comment by EvineDeng** [comment]
看起来是Mac下的`date`命令不能这么用。可是其他sh脚本中也有使用date命令啊，怎么没有报错？

**Comment by GoToBoy** [comment]
> 看起来是Mac下的`date`命令不能这么用。可是其他sh脚本中也有使用`date`命令啊，你看下其他jd_XXX.sh的脚本报错不报错？

不报错呀，我运行了出这个之外的都是正常的

**Comment by GoToBoy** [comment]
`$ date
Tue Dec  8 10:46:58 CST 2020`
date命令可以用，是不是 这行
`LogDate=$(echo ${log} | awk -F "/" '{print $NF}' | cut -c1-10)`
获取到空了？

**Comment by EvineDeng** [comment]
> `$ date
> Tue Dec  8 10:46:58 CST 2020`
> date命令可以用，是不是 这行
> `LogDate=$(echo ${log} | awk -F "/" '{print $NF}' | cut -c1-10)`
> 获取到空了？

你错误已经说是第21行了，不是这一行，第21行有date命令，不过这个用法在mac下不受支持。

**Comment by GoToBoy** [comment]
> > `$ date Tue Dec  8 10:46:58 CST 2020`
> > date命令可以用，是不是 这行
> > `LogDate=$(echo ${log} | awk -F "/" '{print $NF}' | cut -c1-10)`
> > 获取到空了？
> 
> 你错误已经说是第21行了，不是这一行，第21行有date命令，不过这个用法在mac下不受支持。

了解了，谷歌了下没找到mac下的反format方式...

**Comment by EvineDeng** [comment]
我手上没有mac，所以我也没法测试，如果你掌握了怎么用，可以告诉，我可以改代码。

这第21行主要是用来计算两个日期间的差值，用当前日期减去-d后面这个日期，-d后面就是日志文件的日期。

**Comment by EvineDeng** [comment]
已经改好代码了，你用mac试试v2.3.9的rm_log.sh.sample能用不能用？

**Comment by GoToBoy** [comment]
> 已经改好代码了，你用mac试试v2.3.9的rm_log.sh.sample能用不能用？

好，感谢～

**Comment by GoToBoy** [comment]
> 已经改好代码了，你用mac试试v2.3.9的rm_log.sh.sample能用不能用？

可以运行～
